feat: display of relative paths in markdown and improvement in file preview in markdown
SwissDataScienceCenter/renku-ui pull request #1008
Opened 2020-08-13 21:26 UTC by vfried

I created a markdown component that fetches images from relative paths and also fixes relative links in markdown files.

I also improved/restyled the preview of files...

![image](https://user-images.githubusercontent.com/42647877/90188716-3c17bc00-ddbc-11ea-9cbd-de80e4d72628.png)

Closes #667 
Closes #941

2020-08-18 12:52 UTC, vfried commented
Preview available:
https://virginiatest.dev.renku.ch/projects/virginiafriedrich/overviewR

2020-08-19 13:39 UTC, ciyer reviewed
Been testing this, and it is very nice, a major improvement to how it worked before! 

I noticed a couple of discrepancies to how images are handled in GitLab, and I think we should decide what to do about them.

1. In GitLab, relative paths work (e.g., I can do `../images/foo.png` that it will be resolved correctly), but this does not work in RenkuLab
2. In GitLab, images are set to `max-width: 100%`, so they never overflow, but they are shown full size in RenkuLab
3. In GitLab, images that are in LFS are rendered in markdown files, but this does not work in RenkuLab
4. Images are not rendered correctly in issue previews.

To see illustrations of these, compare the following pairs:

**Point 1**
[RenkuLab: something.md](https://virginiatest.dev.renku.ch/projects/cramakri/markdown-images/files/blob/afolder/something.md) and [GitLab: something.md](https://dev.renku.ch/gitlab/cramakri/markdown-images/-/blob/test/afolder/something.md)

**Points 2, 3**
[RenkuLab: README.md](https://virginiatest.dev.renku.ch/projects/cramakri/markdown-images/files/blob/README.md) and [GitLab: README.md](https://dev.renku.ch/gitlab/cramakri/markdown-images/-/blob/test/README.md)

**Point 4**
https://virginiatest.dev.renku.ch/projects/cramakri/markdown-images/collaboration/issues

I think we should make relative paths work in RenkuLab (1). For the max-width (2), I think the way it is handled in GitLab is a bit nicer, but I don't think it is a dealbreaker either. If handling LFS files is easy (3), I think it would be nice to have, but if it is difficult, it can be done later. I think we should show the alt-text for an image in an issue preview (4).

2020-08-19 13:48 UTC, ciyer requested changes
Code looks good! I have two small things to fix: I think I found a leftover debugging comment, and there is a name I do not understand, but otherwise looks great.

2020-08-19 13:48 UTC, ciyer commented on src/model/RenkuModels.test.js
> +// import { Project, projectSchema } from "./RenkuModels";
This was probably for debugging.

2020-08-19 13:48 UTC, ciyer commented on src/utils/Markdown.js
> +function RenkuMarkdownDeep(props) {
Why is this called "RenkuMarkdownDeep" -- what makes it "Deep"?

2020-08-19 13:51 UTC, vfried commented on src/utils/Markdown.js
> +function RenkuMarkdownDeep(props) {
Deep as in deep fetching of stuff, I guess the name is confusing. Maybe I can rename it to RenkuMarkdownWithFiles?

2020-08-20 08:01 UTC, ciyer commented on src/utils/Markdown.js
> +function RenkuMarkdownDeep(props) {
How about `RenkuMarkdownWithPathTranslation`?

2020-09-07 06:42 UTC, ciyer commented
The fixes for the relative paths handle the most common case, which is great! Two change requests:

- `Rename RenkuMarkdownWithFiles` -> `RenkuMarkdownWithPathTranslation` (I think this is a clearer name)
- Could you write a couple of tests for the fixRelativePath function?

2020-09-07 06:43 UTC, ciyer requested changes
The fixes for the relative paths handle the most common case, which is great! Two change requests:

- `Rename RenkuMarkdownWithFiles` -> `RenkuMarkdownWithPathTranslation` (I think this is a clearer name)
- Could you write a couple of tests for the fixRelativePath function?

2020-09-07 11:04 UTC, vfried commented
I addressed the requested changes and fixed a small bug I found with ids for file previews in issues.

2020-09-07 12:12 UTC, ciyer approved these changes
Looks good! If you squash, don't forget to add a reference to the issue #667 and the PR #1008 in the commit message.

2020-09-07 13:08 UTC, merged