refactor: dataset info partially retrieved from the core service
SwissDataScienceCenter/renku-ui pull request #1029
Opened 2020-09-05 19:28 UTC by vfried

Dataset info for projects is partially retrieved from the core service.

Closes #997

2020-09-09 11:57 UTC, lorenzo-cavazzi requested changes
Works well! I've found a couple of minor fixes (see inline comments).
Other 3 things I noticed:
* From Overview --> Datasets, clicking on a dataset brings you to a (probably wrong) link where an error is generated and no further action is possible because the page goes blank (e.g. https://virginia.dev.renku.ch/projects/renku-qa/core-integration-test/overview/datasets)
* When you click on the Datasets tab, the first time it queries the `datasets.list` endpoint but the next times it doesn't. The information there doesn't refresh. I would query it every time the Datasets tab is loaded (it's already the case for Overview --> Datasets)
* The Datasets page alignment is wrong unless the page is small. I'll upload the screenshot for different widths to give an idea

2020-09-09 11:59 UTC, lorenzo-cavazzi commented
* Small size --> ok
  ![Screenshot_20200909_084934](https://user-images.githubusercontent.com/43481553/92595299-6fa71280-f2a4-11ea-9ade-d0c2c88b7f5e.png)

* Medium size --> compressed on the left
  ![Screenshot_20200909_084947](https://user-images.githubusercontent.com/43481553/92595358-864d6980-f2a4-11ea-9172-1f5bc917ca06.png)

* Large size --> ok-ish but right side could avoid wrapping word (as in small size)
  ![Screenshot_20200909_085006](https://user-images.githubusercontent.com/43481553/92595423-9feeb100-f2a4-11ea-85ed-5a79dbf89ea1.png)

2020-09-09 12:01 UTC, ciyer requested changes
Have a some code/naming requests.

2020-09-09 12:03 UTC, ciyer commented on src/api-client/dataset.js
> +  client.listProjectDatasetsFromCore = (git_url) => {
I suggested `fooFromCoreService` above `fooFromCore` is also ok for me, but the naming format should be the same everywhere.

2020-09-09 12:54 UTC, ciyer requested changes
Some additional changes to wording.

2020-09-09 12:54 UTC, ciyer commented on src/dataset/Dataset.present.js
> +          props.dataset.published !== undefined && props.dataset.published.datePublished !== undefined ?
Maybe extract `const dataset = props.dataset` to a local variable to avoid that duplication?

2020-09-09 12:54 UTC, ciyer commented on src/dataset/Dataset.present.js
> +          <strong>This dataset is not in the Knowledge Graph</strong>,
Wording:

`<strong>This dataset is not in the Knowledge Graph</strong>;
this means that some operations on it are not possible.<br /><br />
If the dataset was created recently, and the Knowledge Graph integration for the project is active, the dataset should be added to the Knowledge Graph soon. Otherwise, you need to activate the Knowlede Graph to be able to use the full set of dataset features.
```

2020-09-09 12:54 UTC, ciyer commented on src/project/datasets/new/DatasetNew.present.js
> +          This operation is taking too long and it will continue being processed in the background.<br />
Wording:

```This operation is taking longer than expected; it will continue being processed in the background.<br />
           Please check the datasets list later to make sure that the new dataset is available. <br />
           You can also check the <Link to={props.overviewCommitsUrl}>commits list
           </Link> in the project to see if commits for the new dataset appear there.
```

2020-09-09 15:29 UTC, vfried commented on src/project/Project.js
> +        projectPath={projectPathWithNamespace}
Fixed

2020-09-09 15:30 UTC, vfried commented
Thanks for both of your reviews... All changes were addressed and reviewed, this is ready to be merged whenever renku-python and kg are ready to make a release.

2020-09-10 07:17 UTC, vfried commented
Things have been fixed and deployed to virginia.dev.renku.ch

2020-09-10 13:26 UTC, lorenzo-cavazzi reviewed
Nice!
All good on my side, just a couple of comments to be sure the code is correct when setting the variables in the store (I believe either the `this.set()` or `this.setObject()` is not setting the proper variable, but maybe I misinterpreted -- see inline comments)

2020-09-10 13:26 UTC, lorenzo-cavazzi commented on src/project/Project.state.js
> +        const updatedState = { datasets_kg: { $set: datasets }, transient: { requests: { datasets_kg: false } } };
I think the same `datasets_kg: { $set: datasets }` should be applied also a few lines above (264)

2020-09-10 13:26 UTC, lorenzo-cavazzi commented on src/project/Project.state.js
>          this.setObject(updatedState);
This duplicates the `datasets_kg` values in the redux store, so that I see the same value in both `core.datasets_kg` and `datasets_kg`. Is this intended or should this be `this.setObject( {core: updatedState} );`?
The same applies a few lines above (266)

2020-09-28 11:32 UTC, vfried commented on src/project/Project.state.js
>          this.setObject(updatedState);
I fixed this, i removed the this.set since we had the datasets lists duplicated, only one set is needed now. The other value was used by mistake in the overview of datasets but this is fixed now.

2020-09-28 13:29 UTC, lorenzo-cavazzi approved these changes
:+1:

2020-09-29 12:49 UTC, ciyer requested changes
One question about the code in the latest commit.

2020-09-29 12:49 UTC, ciyer commented on src/dataset/Dataset.container.js
>        dataset.isPartOf = dataset_kg.isPartOf;
So you want to add `dataset.insideKg = true` here?

2020-09-29 13:36 UTC, vfried commented on src/dataset/Dataset.container.js
>        dataset.isPartOf = dataset_kg.isPartOf;
No, I would prefer to leave this empty since in the generic view this is not set (the datasets come from the KG and are not pre-processed)

2020-09-29 14:38 UTC, ciyer commented on src/dataset/Dataset.container.js
>        dataset.isPartOf = dataset_kg.isPartOf;
Could we just put a comment in there. It would be good to explain why there is an asymmetry.

2020-09-29 14:42 UTC, vfried commented on src/dataset/Dataset.container.js
>        dataset.isPartOf = dataset_kg.isPartOf;
Actually, while I was explaining myself better I realized that datasets are always going through this mapDataset function, it doesn't matter if they are inside a project or not.

It makes sense to have this property set properly... I just pushed the change

2020-09-29 14:50 UTC, ciyer approved these changes
🎉  Very nice! It's great to be able to look at datasets and create even on private projects that aren't in the KG.

2020-09-29 14:52 UTC, merged

2020-09-29 16:16 UTC, rokroskar commented
coming late to the party here, but nicely done! One (minor) question: have you thought about using some sort of icon or something to indicate whether the dataset is in the KG? The text seems a bit excessive.

2020-09-29 16:17 UTC, vfried commented
Yes, i thought about this... we have the icon that we are using for the KG inside files but i don't know how well this icon represents a graph