feat: better explain that renku clone is preferred
SwissDataScienceCenter/renku-ui pull request #1058
Opened 2020-10-02 14:43 UTC by ciyer

# Appearance

Here is the new appearance.

![image](https://user-images.githubusercontent.com/1196411/94935855-dc8d8100-04cd-11eb-8dd0-b4ce38d2dd15.png)

Fix #1057

2020-10-02 15:19 UTC, lorenzo-cavazzi submitted a review, later dismissed
Definitely more explanatory than before :+1:

2020-10-07 16:04 UTC, lorenzo-cavazzi requested changes
I have a minor comment on the extra margin introduced by the `<p>` element. Feel free to discard it.

There is another detail to adjust: linting is failing on a long line (src/project/Project.present.js @ 1381).

2020-10-07 16:04 UTC, lorenzo-cavazzi commented on src/project/Project.present.js
> +              <p className="mt-2">
This `<p>` adds extra margin in the bottom, so that the second command `renku githooks install` is very distanced (see image).
I would add also the class `mb-0`

![Screenshot_20201007_175948](https://user-images.githubusercontent.com/43481553/95356404-ea287980-08c6-11eb-8754-4db424dd324a.png)

2020-10-07 20:57 UTC, ciyer commented on src/project/Project.present.js
> +              <p className="mt-2">
Good point about the spacing. I have improved this and pushed.

2020-10-08 06:27 UTC, lorenzo-cavazzi approved these changes
Very neat solution with the show/hide link!

2020-10-08 07:28 UTC, merged