feat: migration improvements
SwissDataScienceCenter/renku-ui pull request #1068
Opened 2020-10-13 12:14 UTC by vfried

2020-11-16 08:30 UTC, ciyer commented
Should we just hide this information if the user is not logged in?

<img width="939" alt="image" src="https://user-images.githubusercontent.com/1196411/99229485-5fed0280-27ee-11eb-983a-3eb0a698e180.png">

2020-11-16 08:39 UTC, vfried commented
Yes, that's a good idea...

2020-11-16 08:46 UTC, vfried commented
@Panaetius it would be good if you review a bit the logic since I'm not 100% sure that it's OK.

2020-11-16 11:42 UTC, ciyer commented
I think C.3 can happen. For example, I could update the template to change the number of CPUs requested. Then the Dockerfile is up-to-date (I didn't change it), and project metadata current as well, but there is a new template version.

2020-11-16 11:58 UTC, ciyer requested changes
Very nice code and helpful instructions for reviewing this complex PR. The issue was a little under spec'd, and you did a great job filling in the missing cases!

Most of my comments deal with messages or what information we show. Where possible I tried to add comments to the place in the code, but here is an overview.

1. We shouldn't show the template version by default if it is a hash.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/1196411/99240824-5323db00-27fd-11eb-8dc6-2befe92ba47e.png">

We should only show it if the user clicks `Show details`.

2. Should this project have a warning badge to indicate that it needs to be upgraded?
<img width="988" alt="image" src="https://user-images.githubusercontent.com/1196411/99241077-a72ebf80-27fd-11eb-8250-c4ea6d07dffa.png">

3. (C2) If there is no template version, we should just say "This project does not use a versioned template."

<img width="927" alt="image" src="https://user-images.githubusercontent.com/1196411/99249080-c59ab800-2809-11eb-91dd-a8c90da886fb.png">


3. If there is a new template, we should show a link to the template repo where the author has (hopefully) explained the changes.

<img width="927" alt="image" src="https://user-images.githubusercontent.com/1196411/99248457-c1ba6600-2808-11eb-9c85-6586fa925ace.png">

2020-11-16 11:58 UTC, ciyer commented on client/src/project/status/ProjectVersionStatus.present.js
> +            You can learn more about the changes in the template repository.
Could `template repository` be a link to the template repository? May need some assistance from renku-python to implement this (we would need a URL to the template repo).

2020-11-16 11:58 UTC, ciyer commented on client/src/project/status/ProjectVersionStatus.present.js
> +        This project&apos;s template can&apos;t be updated because it has no template version,
I think this can be simplified. In this case there is no need to show the null versions. We can just say `This project does not use a versioned template.`

2020-11-16 12:44 UTC, Panaetius reviewed
This looks really good. I think the only thing that is missing is that if check_migration returns `docker_update_possible: false`, you should set `skip_docker_update: true`.

There are two cases where `docker_update_possible: false`: the docker file is already up to date or it does not support updating. In the latter case, trying to update it anyways will give an exception `Couldn't update renku-python version in Dockerfile, as it doesn't contain an 'ARG RENKU_VERSION=...' line.` i.e. 
```
{
                "code": -32100,
                "reason": "Couldn't update renku-python version in Dockerfile, as it doesn't contain an 'ARG RENKU_VERSION=...' line.",
                "template_update_failed":...,
                "dockerfile_update_failed": true,
                "migrations_failed": ...,
            }
```

This is by design, to prevent the metadata migrations from being executed if the renku version in the dockerfile doesn't get updated at the same time, as otherwise, the project would be in a broken state (new metadata but still old renku-python).

2020-11-16 12:57 UTC, ciyer commented
> This looks really good. I think the only thing that is missing is that if check_migration returns `docker_update_possible: false`, you should set `skip_docker_update: true`.
> 
> There are two cases where `docker_update_possible: false`: the docker file is already up to date or it does not support updating. In the latter case, trying to update it anyways will give an exception `Couldn't update renku-python version in Dockerfile, as it doesn't contain an 'ARG RENKU_VERSION=...' line.` i.e.
> 
> ```
> {
>                 "code": -32100,
>                 "reason": "Couldn't update renku-python version in Dockerfile, as it doesn't contain an 'ARG RENKU_VERSION=...' line.",
>                 "template_update_failed":...,
>                 "dockerfile_update_failed": true,
>                 "migrations_failed": ...,
>             }
> ```
> 
> This is by design, to prevent the metadata migrations from being executed if the renku version in the dockerfile doesn't get updated at the same time, as otherwise, the project would be in a broken state (new metadata but still old renku-python).

If the project requires a migration and the docker file does not support updating, then we do not support a 1-click migration. In that case, we instruct the user to launch an interactive environment and manually migrate the project.

We only allow 1-click migrations if the Dockerfile either will be updated or does not need to be updated.

2020-11-16 14:03 UTC, Panaetius submitted a review, later dismissed

2020-11-16 16:01 UTC, vfried commented on client/src/project/status/ProjectVersionStatus.present.js
> +            You can learn more about the changes in the template repository.
@Panaetius could we get a link to the template repository in the response?

2020-11-16 16:02 UTC, vfried commented on client/src/project/status/ProjectVersionStatus.present.js
> +  const currentTemplatesInfo = <p>
@Panaetius could we get this link in the response of migration check?

2020-11-16 16:05 UTC, vfried commented on client/src/project/status/ProjectVersionStatus.present.js
> +        This project&apos;s template can&apos;t be updated because it has no template version,
Done

2020-11-16 16:19 UTC, vfried commented on client/src/project/status/ProjectVersionStatus.present.js
> +            You can learn more about the changes in the template repository.
https://github.com/SwissDataScienceCenter/renku-python/issues/1729 there is a new issue for this in renku-python

2020-11-16 16:22 UTC, vfried commented
- hiding all info for not logged in users --> DONE
- We shouldn't show the template version by default if it is a hash. --> Not sure if it's always a hash or only here that it's a test case (assuming it's always a hash I've decided to hide it)
- missing warning icon --> fixed
- C3.2 test project created
- template repository link --> a new issue has been created in rp to support the request

2020-11-16 16:41 UTC, vfried commented
TESTING IF BACKEND+FRONTEND WORK TOGETHER:

C1 - UP TO DATE - https://virginia.dev.renku.ch/projects/virginiafriedrich/migration-test-c1-tupf-ctvnnull-up-to-date/overview/status

C2 - NO TEMPLATE - https://virginia.dev.renku.ch/projects/virginiafriedrich/Migration-Test-C2-TUPf-CTVnull/overview/status

C3.1 - PRE MIGRATION - https://virginia.dev.renku.ch/projects/virginiafriedrich/migration-test-c3-tup-mr-ps-dup/overview/status
C3.1 - MIRGATED -   https://virginia.dev.renku.ch/projects/virginiafriedrich/migration-test-c3-tup-mr-ps-dup-migrated/overview/status

C3.2 - PRE MIGRATION - https://virginia.dev.renku.ch/projects/virginiafriedrich/migration-test-c3-tup-mnr-ps-dunp/overview/status
C3.2 - MIGRATED - https://virginia.dev.renku.ch/projects/virginiafriedrich/migration-test-c3-tup-mnr-ps-dunp-migrated/overview/status

C4 - UP TO DATE - https://virginia.dev.renku.ch/projects/virginiafriedrich/migration-test-c4-mrf-pst-dupf/overview/status

C5 - MANUAL MIGRATION NOT POSIBLE - https://virginia.dev.renku.ch/projects/virginiafriedrich/migration-test-c5-tup-mr-ps-dunp/overview/status

C6- PRE MIGRATION - https://virginia.dev.renku.ch/projects/virginiafriedrich/migration-test-c6-mr-ps-dup/overview/status
C6 - MIGRATED - https://virginia.dev.renku.ch/projects/virginiafriedrich/migration-test-c6-mr-ps-dup-migrated/overview/status

C7 - PROJECT NOT SUPPORTED - https://virginia.dev.renku.ch/projects/virginiafriedrich/migration-test-c7-mr-dup-psf/overview/status

ALL THE CASES WE TESTED WORK!! 

post-migration error handling in the UI needs to be improved!!!

2020-11-17 11:48 UTC, ciyer requested changes
All my requests for changes were addressed. Thanks! I took a closer look at the wording of the messages and have a few changes there.

2020-11-17 11:48 UTC, ciyer commented on client/src/project/status/ProjectVersionStatus.present.js
> +              Upgrading the Renku Version automatically will also upgrade the template.
Wording: `Upgrading the Renku version will also automatically upgrade the template.`

2020-11-17 11:48 UTC, ciyer commented on client/src/project/status/ProjectVersionStatus.present.js
> +                Upgrading the Renku Version is not {migration_required ? "possible " : "needed "}
Wording: `Upgrading the Renku version is not...`

2020-11-17 11:48 UTC, ciyer commented on client/src/project/status/ProjectVersionStatus.present.js
> +        The current project is not supported, renku migration operations are not possible.&nbsp;
Wording: `This project appears to be using an experimental version of Renku. Migration is not supported.`

2020-11-17 11:48 UTC, ciyer commented on client/src/project/status/ProjectVersionStatus.present.js
> +        The current project is not supported, template migration operations are not possible.&nbsp;
Wording: `This project appears to be using an experimental version of Renku. Template migration is not supported.`

2020-11-17 11:52 UTC, ciyer commented on client/src/project/status/ProjectVersionStatus.present.js
> +            A new version of the <strong>project template</strong> is available.
Could we have a `[show details]` link that would show the current and new template versions?

2020-11-17 11:57 UTC, ciyer commented
@Panaetius From your information above, we understood that in the situation project metadata is out-of-date, Dockerfile is current, we would get a `docker_update_possible: false` response from the server.

To upgrade such a project, do we need to send `skip_docker_update: true`?

2020-11-17 12:10 UTC, Panaetius commented
> @Panaetius From your information above, we understood that in the situation project metadata is out-of-date, Dockerfile is current, we would get a `docker_update_possible: false` response from the server.
> 
> To upgrade such a project, do we need to send `skip_docker_update: true`?

no, if the dockerfile is updatable (It has the `ARG RENKU_VERSION=... line`), updating it even if it's current won't throw an exception. Only trying to update one without that line will give an exception. Though this should only happen if a user manually updates the dockerfile but doesn't run migrations, which would be weird.

Maybe this can be improved at the same time as https://github.com/SwissDataScienceCenter/renku-python/issues/1729, by also returning the current dockerfile version or `null` on the migration check

2020-11-17 13:45 UTC, ciyer commented
> Maybe this can be improved at the same time as [SwissDataScienceCenter/renku-python#1729](https://github.com/SwissDataScienceCenter/renku-python/issues/1729), by also returning the current dockerfile version or `null` on the migration check

I think this is a good idea. That will give us on the UI all information necessary to present the right choices to the user.

2020-11-17 14:01 UTC, vfried commented on client/src/project/status/ProjectVersionStatus.present.js
> +            A new version of the <strong>project template</strong> is available.
Do we like this....
![image](https://user-images.githubusercontent.com/42647877/99399206-a40efe80-28e5-11eb-8638-114a618187eb.png)

![image](https://user-images.githubusercontent.com/42647877/99399260-b4bf7480-28e5-11eb-801b-593c9133b25e.png)

The purple in the link is so that it matches with... 
![image](https://user-images.githubusercontent.com/42647877/99399293-c012a000-28e5-11eb-854b-c9e80db3a6b1.png)

2020-11-17 14:02 UTC, vfried commented on client/src/project/status/ProjectVersionStatus.present.js
> +            A new version of the <strong>project template</strong> is available.
just saw the typo in details... i would change it for info maybe but I'm not sure

2020-11-17 14:04 UTC, vfried commented on client/src/project/status/ProjectVersionStatus.present.js
> +            A new version of the <strong>project template</strong> is available.
Another example of this... 
![image](https://user-images.githubusercontent.com/42647877/99399591-2c8d9f00-28e6-11eb-950b-0ba731f96207.png)

2020-11-17 14:51 UTC, vfried commented
I created an issue for adding the template link and docker version info https://github.com/SwissDataScienceCenter/renku-ui/issues/1132

2020-11-19 14:36 UTC, rokroskar commented
I believe this is unfortunately blocked by https://github.com/SwissDataScienceCenter/renku-python/issues/1743 - right now, because of an error in the service image build, every version suggestion will have `-dirty` attached to it which of course is not a valid version to install from PyPI. It's an easy enough fix though. So clicking update will pretty reliably break every project atm. 

There is another problem I found just now - it looks like if the version in the service is less than the version in the project, this will try to downgrade the version:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/3353586/99674072-d64f6600-2a75-11eb-9a34-a045c4a287fe.png">

I'm not sure what side-effects this can have. I also find that the messaging could be adapted here a bit - here is the project I'm looking at: https://virginia.dev.renku.ch/projects/rokroskar/test-migrate/overview/status

This is the response of the migrate check endpoint:

```json
{"result": {"latest_version": "0.12.1.dev13+dirty", "docker_update_possible": true, "project_version": "0.12.2.dev2+dirty", "template_update_possible": false, "latest_template_version": "aff506859f03d10a7e91a41fdb0d71058d8f8f03", "project_supported": true, "migration_required": false, "current_template_version": "aff506859f03d10a7e91a41fdb0d71058d8f8f03"}}
```

The message says that I need to migrate for the project to keep working, even though the response says that the project is supported and `migration_required: false` - is this intentional because a docker update is possible?

2020-11-19 14:47 UTC, vfried commented
migration_required ---> is for renku version only (this should actually be called renku_migration_required)

project_supported ---> 
![image](https://user-images.githubusercontent.com/42647877/99681077-0d297a00-2a7e-11eb-990a-350b6fbba34e.png) 
So, if the project is for some reason ahead of the version supported by the backend... THERE IS AN EXAMPLE PROJECT FOR THIS ON TOP
![image](https://user-images.githubusercontent.com/42647877/99681240-364a0a80-2a7e-11eb-85a6-48a7db26ce3f.png)

In this case, docker needs to be updated and therefore we display the sign... we could display that the docker needs to be updated but for simplicity, we decided to leave  this like that... it can be changed if you request it

If the version in the service is less than the version in the project then the project shouldn't be supported... i know there is something weird going on with images that end in dev or dirty maybe @Panaetius can explain better....

2020-11-19 14:52 UTC, rokroskar commented
Right, I get the purpose of the `project_supported` which is why I'm asking why it's stated that I _must_ migrate my project? Shouldn't we say that the user "may" update their dockerfile in this case? The project doesn't require a migration.

2020-11-19 14:57 UTC, vfried commented
I'm not sure about this, I think maybe @Panaetius should clarify.

I thought that we didn't want users to have outdated docker images... that this could lead to the project being in a "dirty" state... but maybe I'm wrong.

@ciyer maybe you can help with this...

2020-11-19 16:58 UTC, ciyer commented
> Right, I get the purpose of the `project_supported` which is why I'm asking why it's stated that I _must_ migrate my project? Shouldn't we say that the user "may" update their dockerfile in this case? The project doesn't require a migration.

The case you have is project metadata current, dockerfile can be migrated. I think was overlooked in the design (#1026). When can this happen? Is it possible to get a link to a changelist for the dockerfile? I'm wondering how a user will be able to make a decision as to whether to upgrade or not.

My suggestion is that we leave the behavior as is for the moment, and add this case to the follow-up issue #1132.

2020-11-19 17:01 UTC, rokroskar commented
Right - it can happen because the version of renku-python in the Dockerfile does not necessarily correspond to the version used to create the project - I've created an issue to remedy this in the templates: https://github.com/SwissDataScienceCenter/renku-project-template/issues/98 but it will also require a change in renku-python.

2020-11-19 17:02 UTC, rokroskar commented
Sorry I sent the comment too quickly: so I agree, we can wait on fine-tuning that once this is streamlined a bit with the templates. However, this PR has to wait for https://github.com/SwissDataScienceCenter/renku-python/issues/1743 before it can be merged.

2020-11-19 17:32 UTC, Panaetius commented
> I'm not sure about this, I think maybe @Panaetius should clarify.
> 
> I thought that we didn't want users to have outdated docker images... that this could lead to the project being in a "dirty" state... but maybe I'm wrong.
> 
> @ciyer maybe you can help with this...

We only require to update the dockerfile if we need to do migrations, which happens if we change https://dev.renku.ch/gitlab/virginiafriedrich/datasets-01/-/blob/master/.renku/metadata.yml#L18 SchemaVersion, not if renku-python version changes. It's good if a user updates `renku-python` regardless of that, to make sure they have up-to-date bugfixes in their repo. But unless the bug is with the schema (in which case it'd require a schema migration), the service should have those bugfixes and work just fine even if they have an older, but compatible, version of renku-python. So saying a project is not supported and HAS to be mgirated, in those cases, is a bit strong. 

A counter-example would be the renku cli command redesign, when we changed e.g. `renku update` to require a `--all` flag. That didn't need a Schema change by itself, so it wouldn't matter which version is used, but it would mean the user now has to use the new command syntax if we force them to upgrade, even though this additional mental load wasn't strictly necessary.

Right now with the schema semi-stable, it doesn't matter too much, as most of the time there will be a Schema change still on each release, but as things settle, this hopefully becomes less common. At that point, updating `renku-python` starts going from fixing things to potentially breaking things. I.e. with the renku user api, we might change the api without changing the metadata, so an update could force the user to change their scripts (or otherwise leave their projects in a broken state), making it a bit of a nuisance.

2020-11-25 13:41 UTC, rokroskar commented
Turns out that the migration breaks projects already anyway so there is no need to delay this PR... in any case, the fix to renku-core has been merged so it should all be fine now.

2020-11-30 14:31 UTC, vfried commented
TESTING IF BACKEND+FRONTEND WORK TOGETHER **AGAIN**:

C1 - UP TO DATE - https://virginiatest.dev.renku.ch/projects/virginiafriedrich/migration-test-c1-tupf-ctvnnull-up-to-date/overview/status

C2 - NO TEMPLATE - https://virginiatest.dev.renku.ch/projects/virginiafriedrich/Migration-Test-C2-TUPf-CTVnull/overview/status

C3.1 - PRE MIGRATION - https://virginiatest.dev.renku.ch/projects/virginiafriedrich/migration-test-c3-tup-mr-ps-dup/overview/status
C3.1 - MIGRATED - https://virginiatest.dev.renku.ch/projects/virginiafriedrich/migration-test-c3-tup-mr-ps-dup-migrated-t2/overview/status

C3.2 - PRE MIGRATION - https://virginiatest.dev.renku.ch/projects/virginiafriedrich/migration-test-c3-tup-mnr-ps-dunp/overview/status
C3.2 - MIGRATED - https://virginiatest.dev.renku.ch/projects/virginiafriedrich/migration-test-c3-tup-mnr-ps-dunp-migrated-t2/overview/status

C4 - UP TO DATE - https://virginiatest.dev.renku.ch/projects/virginiafriedrich/migration-test-c4-mrf-pst-dupf/overview/status

C5 - MANUAL MIGRATION NOT POSIBLE - https://virginiatest.dev.renku.ch/projects/virginiafriedrich/migration-test-c5-tup-mr-ps-dunp/overview/status

C6- PRE MIGRATION - https://virginiatest.dev.renku.ch/projects/virginiafriedrich/migration-test-c6-mr-ps-dup/overview/status
C6 - MIGRATED - https://virginiatest.dev.renku.ch/projects/virginiafriedrich/migration-test-c6-mr-ps-dup-migrated-t2/overview/status

C7 - PROJECT NOT SUPPORTED - https://virginiatest.dev.renku.ch/projects/virginiafriedrich/migration-test-c7-mr-dup-psf/overview/status

ALL THE CASES WE TESTED WORK!!

2020-11-30 15:44 UTC, ciyer requested changes
Tested it and it works very well. One request for a change to the wording.

I noticed that after an upgrade, there is a brief flash of the the UI where the upgrade is clickable again. Have you seen this? If it is easy to fix, it would be nice to have that, if not, we can look at it again later.

2020-11-30 15:44 UTC, ciyer commented on client/src/project/status/ProjectVersionStatus.present.js
> +                Upgrading the Renku version is not {migration_required ? "possible " : "needed "}
Wording:

```{migration_required ? "The Renku version cannot be upgraded" : "The Renku version is up-to-date"}. If you wish, you can upgrade the project template.```

2020-12-02 10:59 UTC, vfried commented on client/src/project/status/ProjectVersionStatus.present.js
> +                Upgrading the Renku version is not {migration_required ? "possible " : "needed "}
Fixed.

2020-12-02 16:34 UTC, ciyer approved these changes
Wow, this is quite a PR! I think this is a great interface for a complex set of interactions. 🎉

2020-12-02 17:33 UTC, merged