custom images for interactive environments
SwissDataScienceCenter/renku-ui pull request #1109
Opened 2020-11-04 17:27 UTC by lorenzo-cavazzi

This PR is still a draft

Preview: https://lorenzotest.dev.renku.ch
Currently, it works only for logged user. Please be sure to log in!

A sample project that uses a custom image https://lorenzotest.dev.renku.ch/projects/lorenzo.cavazzi.tech/custom-image/environments/new

fix #1105

2020-11-17 17:38 UTC, lorenzo-cavazzi commented
Now it verifies whether a default image has been used for an interactive environment, giving feedback to the user.

It's not deployed yet, but it can be tested using the image built from this PR https://github.com/SwissDataScienceCenter/renku-notebooks/pull/452
--> `lorenzocavazzitech/renku-notebooks:0.8.3-5e1faef`


![Screenshot_20201117_183412](https://user-images.githubusercontent.com/43481553/99425901-c31c8900-2903-11eb-8787-404bf066054c.png)

2020-11-18 14:53 UTC, lorenzo-cavazzi commented
Preview added here: https://lorenzotest.dev.renku.ch/
* This is a sample of project with a custom image: https://lorenzotest.dev.renku.ch/projects/lorenzo.cavazzi.tech/custom-image
* This is a project with an unavailable image. Switch the `other` branch and ignore the Docker image error to start the environment with the default image: https://lorenzotest.dev.renku.ch/projects/lorenzo.cavazzi.tech/faulty-image/environments/new

2020-11-30 12:14 UTC, ciyer requested changes
This looks very good, and the changes are easy to follow. I would like a different terminology for the "custom" images. I do not think that word is very descriptive. I suggest "pinned." I also think most users do not care which image is being used, so I suggest changing the new  environment form to display the information about the pinned image like this:

![image](https://user-images.githubusercontent.com/1196411/100609152-d2410500-330d-11eb-9a6d-da8df180747c.png)

The "more info/pinned image" link should take the user to documentation about this feature.

@rokroskar what do you think?

2020-11-30 12:14 UTC, ciyer commented on client/src/notebooks/Notebooks.present.js
> +function getStatusObject(status, defaulImage) {
`defaulImage` -> `defaultIamge`

2020-11-30 12:14 UTC, ciyer commented on client/src/notebooks/Notebooks.present.js
> +          contains {language.article}variable{language.plural} that {language.aux} either
👍

2020-12-02 17:02 UTC, lorenzo-cavazzi commented
I addressed the 2 points from the review, but I used slightly different words to avoid the disputed `pinned` word. We can adjust that as we prefer before merging. Let me know if the sentence is clear.

Redeploying to https://lorenzotest.dev.renku.ch is taking longer due to the docker pull rate limit. Running through telepresence works when paired with the latest version of renku-notebook currently on `master`.

This is the result:
![Screenshot_20201202_170254](https://user-images.githubusercontent.com/43481553/100904712-8fc32800-34c7-11eb-9a62-16b2145273d2.png)

2020-12-04 08:57 UTC, ciyer requested changes
With the agreement on terminology in https://github.com/SwissDataScienceCenter/renku/pull/1737, I think we can just use "pinned image."

2020-12-04 08:57 UTC, ciyer commented on client/src/notebooks/Notebooks.present.js
> +            an <ExternalLink role="text" iconSup={true} iconAfter={true} url={url} title="image in the settings" />. A
Now that https://github.com/SwissDataScienceCenter/renku/pull/1737 has been approved, I think we can go with
```
 This project specifies a <ExternalLink role="text" iconSup={true} iconAfter={true} url={url} title="pinned image" />.
```

2020-12-04 08:59 UTC, ciyer commented on client/src/notebooks/Notebooks.present.js
> +      text = "custom";
This should be changed to `text = "pinned";`

2020-12-04 14:13 UTC, lorenzo-cavazzi commented
I changed the texts. I didn't re-deploy the preview. Here is a screenshot showing the relevant part of the "New environment" page.

![Screenshot_20201204_150925](https://user-images.githubusercontent.com/43481553/101173635-17817180-3643-11eb-8635-8f7e4faa6050.png)

2020-12-04 14:35 UTC, ciyer approved these changes
Fantastic! 🎉

2020-12-04 15:06 UTC, merged