Improve title validation on new project creation
SwissDataScienceCenter/renku-ui pull request #1115
Opened 2020-11-05 17:45 UTC by lorenzo-cavazzi

The "New Project" page already contains a number of checks to prevent the user from clicking on "Create Project" when the provided data are wrong. Both the title and the project slug were not tested deeply enough and users were getting confusing errors. We are now closer to (the GitLab slugify function)[https://github.com/gitlabhq/gitlabhq/blob/7942fe679107b5e73e0b359f000946dbbf2feb35/app/assets/javascripts/lib/utils/text_utility.js#L48-L65], and we test unicode chars in the title. Sadly, we still don't allow emoji... yet :smile:

This PR solves the issue on the UI side, and it should be deployed together with SwissDataScienceCenter/renku-python#1691 that replicates similar functionalities in the renku-core backend APIs.

Preview temporarily available here: https://lorenzo.dev.renku.ch/projects/new (will be moved to `lorenzotest` soon)

2020-11-06 11:54 UTC, ciyer requested changes
This is looking good, and the code is great. I have a few requests for changes.

More generally, would it be difficult to just strip accents rather than convert those letters into hyphens? E.g., turn `é` into `e` rather than `-`?

2020-11-06 11:54 UTC, ciyer commented on client/src/project/new/ProjectNew.state.js
> +      errors["title"] = `Similar title (${slugFromTitle(input.title, true)}) ${slugExplanation}`;
Change to 

`Title produces a project identifier (${slugFromTitle(input.title, true)}) that is already taken in the selected namespace. Please select a different title or namespace.`

This message is shown when I just enter the slug as a title, in which case no characters were changed, so I don't think we need to mention the transformation.

2020-11-06 11:54 UTC, ciyer commented on client/src/project/new/ProjectNew.state.js
> +    const slugExplanation = "already in use in current namespace. Non ascii chars were converted or stripped out.";
Change to `already taken in the selected namespace.`

This message is shown when I just enter the slug as a title, in which case no characters were changed, so I don't think we need to mention that part.

2020-11-06 11:54 UTC, ciyer commented on client/src/project/new/ProjectNew.state.js
> +      errors["title"] = "Title must contain at least a standard ascii char or a number.";
`Title must contain at least one letter (without any accents) or a number.`

2020-11-06 11:54 UTC, ciyer commented on client/src/utils/HelperFunctions.js
> +    .split(separator).filter(Boolean).join(separator); // remove separators duplicates
Very clever!

2020-11-06 11:54 UTC, ciyer commented on client/src/utils/Utils.test.js
> +describe("title related functions", () => {
These tests are great, very helpful to understand the behavior.

2020-11-06 11:54 UTC, ciyer commented on client/src/utils/Utils.test.js
> +    expect(verifyTitleValidity("")).toBeTruthy();
Why is this one a valid title?

2020-11-06 12:55 UTC, lorenzo-cavazzi commented on client/src/project/new/ProjectNew.state.js
> +      errors["title"] = `Similar title (${slugFromTitle(input.title, true)}) ${slugExplanation}`;
We substitute all the non `[a-zA-Z]` letters with `-` _and_ we strip the extra `-`. This leads to possibly confusing cases.
E.G: If you have `namespace/test`, there are a number of title combinations that will produce the same slug, like `testü`, `test-ä`, `testé`, `-test-`, ...
I will change the message with what you suggested.

2020-11-06 13:11 UTC, lorenzo-cavazzi commented on client/src/utils/HelperFunctions.js
> +    .split(separator).filter(Boolean).join(separator); // remove separators duplicates
Blatantly copied from here :grin:  https://github.com/gitlabhq/gitlabhq/blob/7942fe679107b5e73e0b359f000946dbbf2feb35/app/assets/javascripts/lib/utils/text_utility.js#L48-L65

2020-11-06 13:16 UTC, lorenzo-cavazzi commented on client/src/utils/Utils.test.js
> +    expect(verifyTitleValidity("")).toBeTruthy();
Good point, the name `verifyTitleValidity` is probably slightly misleading...
It actually checks only that valid chars are used, while other cases are tested separately in the coordinator component to give better feedback to the user (i.e. first letter wrong, title empty, ...).
Should I change the function name to `verifyTitleCharacters`?

2020-11-06 13:35 UTC, lorenzo-cavazzi commented
I also forgot to check for the first letter to be a number or a character. Added now.

> More generally, would it be difficult to just strip accents rather than convert those letters into hyphens? E.g., turn é into e rather than -?

It's not particularly difficult, and we could borrow [from this convenient function](https://github.com/gitlabhq/gitlabhq/blob/7942fe679107b5e73e0b359f000946dbbf2feb35/app/assets/javascripts/lib/utils/text_utility.js#L278-L351), but we tried to stick to the same rules GitLab is applying on its new project page.
The backend has to implement the very same logic (we don't pass the project part of the namespace slug as a separate argument to the backend) and adopting GitLab standard was preferred over deciding for our own flavor -- even if what you suggested was the first solution we considered :smile: 

Preview updated in https://lorenzotest.dev.renku.ch/projects/new

2020-11-06 14:35 UTC, ciyer requested changes
I think the behavior is good with the improvements. It is very minor, but while we are here, we might as well make the improvements -- could you rename the function to `verifyTitleCharacters`?

Regarding the conversion of accents. I don't think the GitLab behavior is the best guide, because in GitLab the slug is user editable. I think our solution is better and easier to use, where the slug is just generated from the title, but it need the conversion from title to slug to be good. 

For example, if I wanted to create a project with the title `Caffè`, it would have the slug `caff`, which seems weird. I think the slug `caffe` would be better. In GitLab, I could fix the slug. In RenkuLab, I would need to create the project as `Caffe` and then rename it to `Caffè`. This seems needlessly complicated.

But, it's a minor thing. I think if you agree it is worth fixing, we should do it. If not, I will approve after the function rename.

2020-11-06 14:35 UTC, ciyer commented on client/src/utils/Utils.test.js
> +    expect(verifyTitleValidity("")).toBeTruthy();
Good idea -- `verifyTitleCharacters` would make it clearer.

2020-11-06 16:31 UTC, lorenzo-cavazzi commented
Well, your argumentation makes sense.
Plus, we have to deviate anyway from the GitLab conversion pattern because it seems to suggest [invalid patterns]( https://github.com/docker/distribution/blob/master/reference/regexp.go#L6-L20), leading to invalid references format for images in the GitLab registry ([example 1](https://dev.renku.ch/gitlab/lorenzo.cavazzi.tech/example-with-_-in-the-middle/-/jobs/119065), [example 2](https://dev.renku.ch/gitlab/lorenzo.cavazzi.tech/test-oww_.wewe1322/-/jobs/119062)).

The changes are:
* Any valid symbol is converted to `-`
* The slugify function tries to convert Unicode accented chars to ascii with the specified rules.

I'll update the preview as soon as the backend counterpart is ready.

2020-11-09 15:06 UTC, lorenzo-cavazzi commented
As discussed offline, the final solution won't include the accented letters conversion.
The function is there, I just invoke `slugFromTitle` without the flag for the conversion.

**Preview updated**: https://lorenzotest.dev.renku.ch/projects/new

P.S: I'll create a follow-up issue for making the fork modal UX similar to the new project creation. At the moment, the feedback to the user is not real-time (the error comes after trying to fork the project) and the wording for errors is slightly different.

2020-11-09 16:16 UTC, ciyer approved these changes
Nice fix. Please remember to make sure the issue and PR numbers are in the commit message.

2020-11-09 16:45 UTC, merged