add client side notifications
SwissDataScienceCenter/renku-ui pull request #1123
Opened 2020-11-13 12:50 UTC by lorenzo-cavazzi

This PR addresses #1055 and adds client-side notifications. The elements introduced in the UI are:
* toast notifications appearing in the top right when a notification is added (not for `info` notifications)
* dropdown menu on the top right for the unread notifications (not for `info` notifications)
* notifications page with a full recap (all notifications, also when already marked as read)

Currently, notifications are produced only when starting interactive environments. In the preview, it's possible to generate fake notifications from the notifications menu. That will be removed before merging the PR

**Preview**: https://lorenzotest.dev.renku.ch

fix #1055

2020-11-13 14:32 UTC, ciyer requested changes
Looking forward to having this feature integrated! The notifications page looks good.

I have one request for a refactoring (extract a function) and some rewordings. I also have a couple of requests for different behavior.

1. Closing a toast should not mark the notification as read.

![image](https://user-images.githubusercontent.com/1196411/99081263-d6a5b800-25c2-11eb-8ff5-df9b2c99cd62.png)

I have been closing the notifications precisely when I do not have time to read them / do not want them in my way. 

2. Could we make some changes to the way the notifications page is shown?

![image](https://user-images.githubusercontent.com/1196411/99082981-271e1500-25c5-11eb-827a-fcbfd4b62248.png)

* Move the "Mark Read" button to the other left side and make it just a check mark, without a box
* Make the links buttons with text to describe what you see if you click on the link. Keep an indication if the link takes you to an external site.

2020-11-13 14:32 UTC, ciyer commented on client/src/notebooks/Notebooks.container.js
> +      const resources = Object.keys(data.resources).map(res => `${res}: ${data.resources[res]}`);
Could this part be extracted into a function? Something like `postNotification(data)`? Having it inline here makes it hard to separate the code that does the work from the code that informs the user about what was done.

2020-11-13 14:32 UTC, ciyer commented on client/src/notifications/Notifications.present.js
> +        <Link to="/notifications"><DropdownItem>Notification page</DropdownItem></Link>
I think this should simply be called `Notifications`.

2020-11-13 14:32 UTC, ciyer commented on client/src/notifications/Notifications.present.js
> +            <h1>New notifications</h1>
I think this section should be called `Unread`.

2020-11-13 15:18 UTC, lorenzo-cavazzi commented on client/src/notebooks/Notebooks.container.js
> +      const resources = Object.keys(data.resources).map(res => `${res}: ${data.resources[res]}`);
I think the whole logic in that function is about crafting the notification (apart from the redirect, that I was tempted to remove), while the logic to start the server is in the `startServer` function in the coordinator.
If you prefer, I can move lines `343-358` to a separate function, but that won't be reusable and `internalStartServer` would only contain `this.coordinator.startServer()`.
Would it work better if I add a couple of comments instead?

2020-11-13 15:41 UTC, ciyer commented on client/src/notebooks/Notebooks.container.js
> +      const resources = Object.keys(data.resources).map(res => `${res}: ${data.resources[res]}`);
Ok. Comments should be enough then.

2020-11-13 17:17 UTC, lorenzo-cavazzi commented on client/src/notebooks/Notebooks.container.js
> +      const resources = Object.keys(data.resources).map(res => `${res}: ${data.resources[res]}`);
Done. If you believe it's still confusing, we can try with the separate function.

2020-11-16 16:29 UTC, lorenzo-cavazzi commented
1. Behavior changed as requested. Closing the toast notifications doesn't silence it. Clicking on the notification URL (if available) still does it.
2. Visualization changed. I chose to keep the icon on the link button for both internal and external links to keep it coherent with the toast and the dropdown notifications. Let me know if this is ok.
3. In-line changes done.

The preview is up-to-date: https://lorenzotest.dev.renku.ch

### Further changes
The link button seems too prominent to me. There are a couple of changes we may want to apply:
- Invert colors (as in the second link in the screen below)
- Shrink the button (as in the first link). Not sure this is necessary if we invert the colors.

Let me know your feedback and feel free to suggest further changes/adjustments.

![Screenshot_20201116_165633](https://user-images.githubusercontent.com/43481553/99280100-48833900-2831-11eb-9044-206b6ea98dfd.png)

2020-11-17 11:25 UTC, ciyer requested changes
We are in the final stretch for this PR! Looking very good, we just need to remove the items from the notification menu that are there for testing.

I have some requests for the wording and timing of the interactive env launch notifications.

2020-11-17 11:25 UTC, ciyer commented on client/src/notebooks/Notebooks.container.js
> +      Reference URL: "${data.url}", ${projectData.join(", ")}, ${resources.join(", ")}.`;
Most of the project data isn't very useful.

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/1196411/99384282-7a4add00-28cf-11eb-9b3d-9b0735e68a9b.png">

Could we just say `An interactive environment for the project [project link] will be available soon.`

(Or, if the change below is made, then `An interactive environment for the project [project link] is available.`)

2020-11-17 11:25 UTC, ciyer commented on client/src/notebooks/Notebooks.container.js
> +      this.notifications.addSuccess(
Could we add the notification at a later point. Instead of when the environment is starting, I would prefer to have it once the environment has started. But if this is complicated, it isn't absolutely necessary.

2020-11-17 13:32 UTC, lorenzo-cavazzi commented on client/src/notebooks/Notebooks.container.js
> +      this.notifications.addSuccess(
That would be a very good improvement. This is a bit difficult now due to how we poll the resources, but as soon as we move the notebook polling logic to the ui-server it should be much easier. I would postpone it to that point.

2020-11-17 13:41 UTC, ciyer commented
Sorry, I overlooked this part.

> ### Further changes
> The link button seems too prominent to me. There are a couple of changes we may want to apply:
> 
> * Invert colors (as in the second link in the screen below)
> * Shrink the button (as in the first link). Not sure this is necessary if we invert the colors.

I think we should leave the colors since these are the colors for primary buttons, but making the button smaller is a good idea.

2020-11-17 14:33 UTC, lorenzo-cavazzi commented on client/src/notebooks/Notebooks.container.js
> +      Reference URL: "${data.url}", ${projectData.join(", ")}, ${resources.join(", ")}.`;
I've changed the text. The short message is similar to what you suggested, but the full name is used instead of the url. In the extra information, all the content is gone except the branch and the commit.

![Screenshot_20201117_151719](https://user-images.githubusercontent.com/43481553/99402672-e2a6b800-28e9-11eb-9200-8c772a3cbb5f.png)

2020-11-17 14:54 UTC, lorenzo-cavazzi commented on client/src/notebooks/Notebooks.container.js
> +      Reference URL: "${data.url}", ${projectData.join(", ")}, ${resources.join(", ")}.`;
I've changed the text. The short message is similar to what you suggested, but the full name is used instead of the url. In the extra information, all the content is gone except the branch and the commit.

![Screenshot_20201117_151719](https://user-images.githubusercontent.com/43481553/99402672-e2a6b800-28e9-11eb-9200-8c772a3cbb5f.png)

2020-11-17 14:54 UTC, lorenzo-cavazzi commented
I've addressed the comments and removed the buttons to generate fake notifications.
https://lorenzotest.dev.renku.ch

2020-11-18 11:54 UTC, ciyer approved these changes
Very cool! I love being able to request a new environment and then go do other things and get notified when it's (almost) ready.🎉

2020-11-18 12:30 UTC, ciyer requested changes

2020-11-18 12:30 UTC, ciyer commented on client/src/notifications/Notifications.present.js
> +        <DropdownItem onClick={() => this.props.handlers.markAllRead()}>Mark all read</DropdownItem>
Actually, just using it again and I have one more request. Could we remove this menu item? It's easy to click by accident, and I don't think it is a big deal to go to the notifications page and mark all read there.

2020-11-18 13:58 UTC, lorenzo-cavazzi commented on client/src/notifications/Notifications.present.js
> +        <DropdownItem onClick={() => this.props.handlers.markAllRead()}>Mark all read</DropdownItem>
I think this will still be useful once more notifications are generated. I can image a page left open in the browser that possibly generates a few errors and it may be tedious for the user to remove each one.
Anyway, I can remove this from the dropdown menu and we can re-introduce it once (and if) we need it.

2020-11-18 14:08 UTC, ciyer approved these changes
🎉

2020-11-18 14:24 UTC, merged