feat: sync tabs on authentication events
SwissDataScienceCenter/renku-ui pull request #1163
Opened 2020-12-04 16:47 UTC by lorenzo-cavazzi

This implements a basic mechanism to synchronize tabs on relevant authentication events.

I prepared 2 previews, one with notifications and one without. I believe taking advantage of the notification system is very useful for this case. Otherwise, the user may be confused when he switches to a page that was refreshed without explanations.

***Preview without notifications***: https://lorenzotest2.dev.renku.ch/
***Preview with notifications***:  https://lorenzotest.dev.renku.ch/

***How to test***: Open at least 2 tabs on the same deployment. Try to login/logout in one of them, then check what happens in the other.

fix #1048

2020-12-04 17:05 UTC, rokroskar commented
This looks really nice! I do like the notifications here, I think they make sense. I think we should discuss the presentation options for the popups and the page, but that should be done elsewhere. 

Two minor comments:

1. clicking on the "X" while the notification is shown doesn't mark it as read. I have to click on the drawer (is that what it's called) and click the "X" there or go to the page and click the check mark. 
2. The wording on the two notifications is slightly different:

> The page was refreshed because you recently logged out on a different tab.

vs

> The page was refreshed because the user has recently logged in on a different tab.

I guess I prefer the "you recently..." vs "the user..." but I don't have a strong opinion there - it just seems like they should be the same.

2020-12-06 14:04 UTC, ciyer commented
> 1. clicking on the "X" while the notification is shown doesn't mark it as read. I have to click on the drawer (is that what it's called) and click the "X" there or go to the page and click the check mark.

It originally worked the other way (x marked the notification as read), but I asked for it to be changed because I found myself closing the notification precisely when I wanted out of my way without reading it, with the intention of reading it later.

2020-12-07 07:50 UTC, lorenzo-cavazzi commented
I believe clearing the notification when clicking on the `X` would be the most natural behavior.
After trying the other way around for a while, it still seems strange that closing it leaves the red dot. The content we provide is concise, acknowledging that something is finished instead of providing information to read carefully.

I have changed the wording as suggested (preview not updated).
It's probably better to also use the same type of notification. I guess a warning is the better solution since it's a consequence of actions done somewhere else (the result in the tab may be negative, like a 404 page if a private project page was open).

2020-12-07 09:34 UTC, ciyer requested changes
This is great. It works very well (better than I thought possible)! 

My only request is for a little comment in the LoginHelper class. The tests are helpful (and also very nice!), but it took me a minute to understand how the code worked, and a class comment just explaining how localStorage and sessionStorage are used would be helpful.

I made a proposal. If my understanding is 100% correct, you can take that, otherwise, fix or describe in your own words.

2020-12-07 09:34 UTC, ciyer commented on client/src/authentication/Authentication.container.js
> +const LoginHelper = {
Could you add a little comment here like:
```
The LoginHelper manages communication of login/logout events between tabs. It uses localStorage to communicate the events between tabs, and uses sessionStorage to remember an event after a refresh within a tab.
```

2020-12-07 10:43 UTC, lorenzo-cavazzi commented on client/src/authentication/Authentication.container.js
> +const LoginHelper = {
I agree the component is convoluted and a description would help. The one you provided is on point.

2020-12-07 10:45 UTC, lorenzo-cavazzi commented
I updated the preview on https://lorenzotest.dev.renku.ch/ with the latest changes.
It includes toast notifications with the modified behavior as agreed offline.

2020-12-07 12:02 UTC, ciyer approved these changes
🎉

2020-12-07 16:16 UTC, lorenzo-cavazzi commented
> I think we should discuss the presentation options for the popups and the page, but that should be done elsewhere.

@rokroskar Should I create an issue for discussing that and keep the notifications disabled in the meanwhile?

2020-12-07 17:20 UTC, rokroskar commented
@lorenzo-cavazzi yes please make an issue but not necessary to disable IMO. Thanks!!

2020-12-08 10:10 UTC, lorenzo-cavazzi commented
Ok, then I'll merge this.
This is the issue for improving notifications #1167

2020-12-08 10:10 UTC, merged