feat: remove dataset from projects
SwissDataScienceCenter/renku-ui pull request #1164
Opened 2020-12-07 10:06 UTC by vfried

There is an issue with button placement since the title and the buttons are at the same height.

Solution 1: putting the buttons on top
![image](https://user-images.githubusercontent.com/42647877/101337031-79c4b700-387b-11eb-9d8d-008e3befbee6.png)

Solution 2: making the buttons icons (We could display the text inside the button on hover)
How it looks like...
![image](https://user-images.githubusercontent.com/42647877/101337426-f35ca500-387b-11eb-8464-b6553517b51c.png)

On hover... (we could also add the normal tooltip on hover)
![image](https://user-images.githubusercontent.com/42647877/101337643-36b71380-387c-11eb-9907-79c36615799c.png)

Closes #1151

2020-12-07 12:12 UTC, ciyer commented
I like Solution 2. I think it looks good and is clear in terms of functionality.

2020-12-08 08:16 UTC, vfried commented
I implemented the solution 2 with the tooltip that we have been using to be consistent. These tooltips don't work 100% well though (I've seen this not working well in other places as well). I can implement the on hover solution that we describe on top if we prefer this solution. We should also create an issue to try to solve the hover problem in general.

2020-12-08 08:54 UTC, vfried commented
I changed the order of the actions to be like...
![image](https://user-images.githubusercontent.com/42647877/101458234-e94bac80-3936-11eb-8e20-6f0f5690ce83.png)

In case the user is outside of a project only the add to project is displayed and it looks like...

2020-12-08 09:39 UTC, vfried commented
@ciyer latest changes for this are in virginiatest

2020-12-08 11:23 UTC, ciyer requested changes
# Buttons

I like the icons, but, I think we want to give delete a less prominent place. Could we make the buttons like this:

<img width="126" alt="image" src="https://user-images.githubusercontent.com/1196411/101477141-1c9a3580-394f-11eb-8777-e9766b22739b.png">

(Edit on the far right, a "more options" button to the left. Clicking on "More options" should bring the two options: add to project and delete).

2020-12-08 11:29 UTC, vfried commented
I don't like this suggestion.
 
In my opinion the add to project button is the most important button in datasets (because we want to promote users to share datasets) so it doesn't make sense for me to hide this button inside a menu. 

Regarding edit and delete I think if we put them in a menu it could happen that the users don't know there is new functionality. 
In case we add more buttons I would use the menu option but not now. I can try changing the color of the buttons if this is preferred. Given the size of the buttons, I wouldn't say that any of them has a "prominent place".

2020-12-08 11:34 UTC, vfried commented
This is how it would look in reality...
![image](https://user-images.githubusercontent.com/42647877/101478951-b6fb7880-3951-11eb-9e7d-90ffb7816282.png)

2020-12-08 11:39 UTC, vfried commented
We can play with colors to make buttons less strong if this is what we want...
![image](https://user-images.githubusercontent.com/42647877/101479385-67697c80-3952-11eb-9040-5d0dca994cc7.png)

2020-12-08 11:46 UTC, ciyer requested changes
Code looks good, and the feature works well (tested a public project with KG and a private project w/o KG).

I have one question/request about the code and a request about the button ordering/display.

2020-12-08 11:46 UTC, ciyer commented on client/src/project/datasets/remove/RemoveDataset.present.js
> +      const errors = Object.keys(error).map(v => {
Is this a pattern that is used in multiple places by the renku-core? If so, we should extract this to a function
```
function displayErrorFromServerErrors(serverErrors) {
    let content;
    let error = props.serverErrors.error;
    if (typeof serverErrors == "string") {
      content = <pre className="text-wrap">{error}</pre>;
    }
    else {
      const errors = Object.keys(error).map(v => {const text = typeof error[v] == "string" ?
            `${v}: ${error[v]}` :
            `Error message: ${JSON.stringify(error[v])}`;
        return (<pre key={v} className="text-wrap">{text}</pre>);
      });
      if (errors.length === 1)
        content = (errors[0]);
      else
        content = error[0];
    }
    return content;
}

2020-12-08 11:54 UTC, vfried commented on client/src/project/datasets/remove/RemoveDataset.present.js
> +      const errors = Object.keys(error).map(v => {
I think the function for the Form generator should be more generic and potentially could be improved since we get error messages for fields in particular and we should display this error messages in the fields where they happen.

Also, some changes where made there (in the form generator) that actually broke/break the error messages in some cases. I discovered this a few days ago and I was planing on investigating this a bit more when making the form generator available everywhere. 

I can extract this in a function now but i think we should revise the way we handle errors from the core service in general.

2020-12-08 12:48 UTC, ciyer commented
> I don't like this suggestion.
> 
> In my opinion the add to project button is the most important button in datasets (because we want to promote users to share datasets) so it doesn't make sense for me to hide this button inside a menu.
> 
> Regarding edit and delete I think if we put them in a menu it could happen that the users don't know there is new functionality.
> In case we add more buttons I would use the menu option but not now. I can try changing the color of the buttons if this is preferred. Given the size of the buttons, I wouldn't say that any of them has a "prominent place".

I think it makes sense to have the add to project button easily accessible, but I do not think delete should be so readily available. Deleting a dataset should be rare.

Can we do it this way, then

<img width="104" alt="image" src="https://user-images.githubusercontent.com/1196411/101485796-0050c580-395c-11eb-9899-6624d79eae4c.png">

On the dataset page. "Delete" should be moved to an action on the edit page:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/1196411/101485838-0f377800-395c-11eb-8a84-fbf88cdaffc0.png">

2020-12-08 12:53 UTC, vfried commented
I think operations should be simple and easy to reach in general. I am not sure that putting the delete inside the modify will be clear for the user. Considering that things are backed up in git and can be reverted and also that there is a confirmation window that asks a user if they are sure they want to delete the dataset I am not sure that we want a delete operation inside the modify.

2020-12-08 13:00 UTC, vfried commented
I am just trying to think about this in a different way... the reason why we want this button "hidden" is because we want to prevent the user from deleting datasets in general or because we want to prevent users from accidentally deleting a dataset?

--> If we want to prevent users from accidentally deleting a dataset we could implement something like the delete project in gitlab that asks you to write the name of the project that you are trying to delete.

--> If we want to prevent users from deleting datasets in general then i can hide the button somewhere.

2020-12-08 13:03 UTC, vfried commented
In case this two things go inside modify dataset i think we should do something like this... 
![image](https://user-images.githubusercontent.com/42647877/101487218-1f505700-395e-11eb-989f-f49ab4a79073.png)

2020-12-08 13:27 UTC, vfried commented
I named this remove but i'm not sure if this should be remove or delete... any suggestions?

2020-12-08 13:44 UTC, vfried commented
4th proposal... if we want to group operations I would group the delete and edit inside a menu... I would leave the add to project button as it is and add a menu with delete and edit.

2020-12-08 15:45 UTC, vfried commented
As we spoke, here are the new changes... i also did a small refactor in error messages since i realized we didn't need all the code that i pushed, the error messages for delete are simpler.

Changes:
- new menu
- fix for errors
- renaming to delete

![image](https://user-images.githubusercontent.com/42647877/101505462-a9a3b580-3974-11eb-8201-61c29012bb93.png)

2020-12-08 15:48 UTC, vfried commented on client/src/project/datasets/remove/RemoveDataset.present.js
> +      const errors = Object.keys(error).map(v => {
I realized most of this code isn't needed so I deleted most of it, it's much simpler now.

2020-12-08 16:56 UTC, ciyer approved these changes
Very nice! I think this solution works very well.

2020-12-08 17:11 UTC, merged