fix: refactor the project list components
SwissDataScienceCenter/renku-ui pull request #1229
Opened 2021-02-04 20:23 UTC by lorenzo-cavazzi

_I'll update the description soon_

/deploy

> * Remove the local redux state and use react functional components instead (#1181)
> * Preserve the search string when changing tab (#1189) and when clicking any
>   button on the page.
> * Prevent illegal actions and automatically redirect when possible
> 
> fix #1189
> fix #1181

2021-02-05 08:55 UTC, lorenzo-cavazzi commented
Sorry for force-pushing a few times in a row, I tried different solutions to prevent `npm` tests from failing in GitHub actions when re-defining the window.location object.
It works fine now.

2021-02-05 13:17 UTC, ciyer requested changes
I think the code improvements here are very nice, and it's great to see the logic using more modern React features.

I have reviewed about 1/2 the PR (it's very big!) and wanted to get these comments up.

I found two bugs in the logic:

- It should be possible to search for all projects by leaving the input empty, but that does not work.

![image](https://user-images.githubusercontent.com/1196411/107038360-af731700-67bc-11eb-8b77-f6a1604398b0.png)

- In the same page as above, it is not possible to return to "Filter by Project" after changing to one of the other options.

2021-02-05 13:17 UTC, ciyer commented on client/src/project/list/ProjectList.container.js
> +  // Initial setup
The logic in this component is a bit hard to follow. I think writing custom hooks would help make it clearer.

2021-02-05 13:17 UTC, ciyer commented on client/src/project/list/ProjectList.present.js
> +    return (<p>We couldn&apos;t find any project matching the search criteria.</p>);
I think 
```
<p>We could not find any matching projects.</p>
```

Would be better.

2021-02-05 13:17 UTC, ciyer commented on client/src/project/list/ProjectList.present.js
> +  const [userInput, setUserInput] = useState(params.query.toString());
Here also, I think custom hooks would help get the state-management logic out of this function to make it easier to understand the logic here.

2021-02-05 13:17 UTC, ciyer commented on client/src/project/list/ProjectList.present.js
> +      content = (<p>Please enter you filtering words in the field above and click on Search to get the result.</p>);
```
      content = (<p>Please enter text in the field above and click on "Search" to see the results.</p>);
```

But I wasn't able to get this message to appear.

2021-02-05 13:36 UTC, lorenzo-cavazzi commented on client/src/project/Project.test.js
> -  it("renders list without crashing for anonymous user", () => {
That is now included in the tests in `ProjectList.test.js `

2021-02-05 13:41 UTC, lorenzo-cavazzi commented on client/src/project/list/ProjectList.present.js
> +      content = (<p>Please enter you filtering words in the field above and click on Search to get the result.</p>);
Theoretically, this text should never appear since entering the page triggers a fetch, therefore it would be `fetching = true`. When that is set to `false` again because the action finished, then `fetched != null`.
Technically, it's still possible that the condition is satisfied for a brief instant. We can either get rid of it and return `null` or leave it there just in case (and fix the text :grin: )

2021-02-05 13:43 UTC, lorenzo-cavazzi commented
>     * It should be possible to search for all projects by leaving the input empty, but that does not work.
It's possible when searching projects, but it's not when looking for users or groups. Is that wrong?

>     * In the same page as above, it is not possible to return to "Filter by Project" after changing to one of the other options.
Oh, that is definitely a bug! I'll fix that soon

2021-02-05 14:55 UTC, ciyer commented
> > ```
> > * It should be possible to search for all projects by leaving the input empty, but that does not work.
> > ```
> 
> It's possible when searching projects, but it's not when looking for users or groups. Is that wrong?

It does not work for me on projects either:

![image](https://user-images.githubusercontent.com/1196411/107049540-86598300-67ca-11eb-9536-f918ebfc50b7.png)


But on dev, I can leave the field empty and get all results also on users or groups.

2021-02-08 22:03 UTC, lorenzo-cavazzi commented
The tests with the up-to-date acceptance tests passed here: https://github.com/SwissDataScienceCenter/renku-ui/runs/1856588114
I've now removed the explicit reference to the `ui1229-fix-acceptance` branch when deploying the test environment. After merging this PR, we should tag a UI version and merge SwissDataScienceCenter/renku#1937 to correctly update the acceptance tests for the other PRs in the UI and the other renku repositories

2021-02-09 08:14 UTC, ciyer approved these changes
Looks good! 🎉

2021-02-09 08:56 UTC, merged