Release 0.11.5
SwissDataScienceCenter/renku-ui pull request #1231
Opened 2021-02-09 09:16 UTC by lorenzo-cavazzi

2021-02-09 15:00 UTC, ciyer requested changes
I think the changelog should only reference the PR and issues, not the commit.

2021-02-09 15:00 UTC, ciyer commented on CHANGELOG.md
> +* preserve any input when clicking on buttons and links on the projects list page, and improve UX for non-logged users (#1229) ([b2ee34b](https://github.com/SwissDataScienceCenter/renku-ui/commit/b2e
This looks good, but I would drop the reference to the commit and just include the references to the PR and issues.

2021-02-09 15:16 UTC, lorenzo-cavazzi commented on CHANGELOG.md
> +* preserve any input when clicking on buttons and links on the projects list page, and improve UX for non-logged users (#1229) ([b2ee34b](https://github.com/SwissDataScienceCenter/renku-ui/commit/b2e
Should I remove only the link to the commit but leave the short SHA to keep it coherent with the changelog from the previous releases?

2021-02-10 08:53 UTC, ciyer submitted a review, later dismissed
👍

2021-02-10 09:29 UTC, ableuler submitted a review, later dismissed

2021-02-10 09:31 UTC, rokroskar commented on CHANGELOG.md
> +* preserve any input when clicking on buttons and links on the projects list page, and improve UX for non-logged users (#1229) b2ee34b, closes [#1229](https://github.com/SwissDataScienceCenter/renku-
the formatting here is a bit weird 

```suggestion
* preserve any input when clicking on buttons and links on the projects list page, and improve UX for non-logged users ([#1229](https://github.com/SwissDataScienceCenter/renku-ui/issues/1229) [#1181](https://github.com/SwissDataScienceCenter/renku-ui/issues/1181) [#1189](https://github.com/SwissDataScienceCenter/renku-ui/issues/1189))
```

2021-02-10 09:32 UTC, rokroskar commented on CHANGELOG.md
> +* preserve any input when clicking on buttons and links on the projects list page, and improve UX for non-logged users (#1229) b2ee34b, closes [#1229](https://github.com/SwissDataScienceCenter/renku-
also, #1229 is a PR not an issue - did you mean to link to a different issue?

2021-02-10 09:33 UTC, lorenzo-cavazzi commented on CHANGELOG.md
> +* preserve any input when clicking on buttons and links on the projects list page, and improve UX for non-logged users (#1229) b2ee34b, closes [#1229](https://github.com/SwissDataScienceCenter/renku-
If we change this, I would change it also for all the other versions -- currently, it's the same format everywhere since we started using `conventional-changelog`

2021-02-10 10:56 UTC, ciyer commented on CHANGELOG.md
> +* preserve any input when clicking on buttons and links on the projects list page, and improve UX for non-logged users (#1229) b2ee34b, closes [#1229](https://github.com/SwissDataScienceCenter/renku-
We include references to the PR and any relevant issues in our changelog.

2021-02-10 12:31 UTC, rokroskar commented on CHANGELOG.md
> +* preserve any input when clicking on buttons and links on the projects list page, and improve UX for non-logged users (#1229) b2ee34b, closes [#1229](https://github.com/SwissDataScienceCenter/renku-
that's fine, but what is written doesn't make sense - it says that #1229 closes #1229 - first, it doesn't make sense because #1229 is a PR so it wouldn't usually be closed by a PR, and second because it's closing itself. If I run `conventional-changelog` I get 

```
* refactor the project list components ([#1229](https://github.com/SwissDataScienceCenter/renku-ui/issues/1229)) ([b2ee34b](https://github.com/SwissDataScienceCenter/renku-ui/commit/b2ee34b)), closes [#1181](https://github.com/SwissDataScienceCenter/renku-ui/issues/1181) [#1189](https://github.com/SwissDataScienceCenter/renku-ui/issues/1189) [#1189](https://github.com/SwissDataScienceCenter/renku-ui/issues/1189) [#1181](https://github.com/SwissDataScienceCenter/renku-ui/issues/1181)
```

2021-02-10 12:34 UTC, rokroskar commented on CHANGELOG.md
> +* preserve any input when clicking on buttons and links on the projects list page, and improve UX for non-logged users (#1229) ([b2ee34b](https://github.com/SwissDataScienceCenter/renku-ui/commit/b2e
why make extra work for yourself? You'll have to do this every single time and the actual rendered text will look the same apart from the fact that you now have a non-clickable sha in the changelog. Just wondering, do whatever you think makes sense 😄

2021-02-10 12:35 UTC, rokroskar approved these changes

2021-02-10 12:49 UTC, ciyer approved these changes

2021-02-10 12:51 UTC, lorenzo-cavazzi commented on CHANGELOG.md
> +* preserve any input when clicking on buttons and links on the projects list page, and improve UX for non-logged users (#1229) b2ee34b, closes [#1229](https://github.com/SwissDataScienceCenter/renku-
Really? If I run `conventional-changelog -p angular` (as suggested here https://github.com/SwissDataScienceCenter/sdsc-dev-docs/tree/master/renku-release#compile-changelog) I get the following output

```
* refactor the project list components ([#1229](https://github.com/SwissDataScienceCenter/renku-ui/issues/1229)) ([b2ee34b](https://github.com/SwissDataScienceCenter/renku-ui/commit/b2ee34bfb11a6a2032fb6761b0bbedf98bf44ad9)), closes [#1181](https://github.com/SwissDataScienceCenter/renku-ui/issues/1181) [#1189](https://github.com/SwissDataScienceCenter/renku-ui/issues/1189) [#1189](https://github.com/SwissDataScienceCenter/renku-ui/issues/1189) [#1181](https://github.com/SwissDataScienceCenter/renku-ui/issues/1181)
```

It's even uglier if I run `conventional-changelog`.
Your suggestion makes sense, I committed it from your comment, but the funny part was coming directly from the output of the command. Adjusting it is a limited effort, but for sure we weren't manually adding the bits about closing the PR :grin:

2021-02-10 12:54 UTC, rokroskar commented on CHANGELOG.md
> +* preserve any input when clicking on buttons and links on the projects list page, and improve UX for non-logged users (#1229) b2ee34b, closes [#1229](https://github.com/SwissDataScienceCenter/renku-
oh I thought maybe it was a typo from when you edited it by hand. Isn't that the same output I got? It doesn't say #1229 closes #1229 :) Anyway, doesn't matter it's fine as is 👍

2021-02-10 12:54 UTC, lorenzo-cavazzi commented on CHANGELOG.md
> +* preserve any input when clicking on buttons and links on the projects list page, and improve UX for non-logged users (#1229) b2ee34b, closes [#1229](https://github.com/SwissDataScienceCenter/renku-
I also get the same content when running the `conventional-changelog -p angular` as suggested here https://github.com/SwissDataScienceCenter/sdsc-dev-docs/tree/master/renku-release#compile-changelog) 

```
* refactor the project list components ([#1229](https://github.com/SwissDataScienceCenter/renku-ui/issues/1229)) ([b2ee34b](https://github.com/SwissDataScienceCenter/renku-ui/commit/b2ee34bfb11a6a2032fb6761b0bbedf98bf44ad9)), closes [#1181](https://github.com/SwissDataScienceCenter/renku-ui/issues/1181) [#1189](https://github.com/SwissDataScienceCenter/renku-ui/issues/1189) [#1189](https://github.com/SwissDataScienceCenter/renku-ui/issues/1189) [#1181](https://github.com/SwissDataScienceCenter/renku-ui/issues/1181)
```

It's slightly uglier if I run `conventional-changelog` command without parameters.
Your suggestion makes sense, I committed it from your comment, but the funny part about closing the PR comes directly from the output of the command. For sure we weren't adding those bits manually :grin:

2021-02-10 12:56 UTC, merged