feat: file upload notification for datasets
SwissDataScienceCenter/renku-ui pull request #1247
Opened 2021-02-17 12:57 UTC by vfried

When all files finished uploading on a dataset add/edit

![image](https://user-images.githubusercontent.com/42647877/108207367-f3084200-7127-11eb-84ba-37e8ce90d9cb.png)

When a file failed

![image](https://user-images.githubusercontent.com/42647877/108207486-18954b80-7128-11eb-8d02-8784b308caee.png)

2021-02-18 07:56 UTC, lorenzo-cavazzi requested changes
All good! Just a note on the text for the successful operation.

For the user, it's not clear he can move away from the page while uploading. I was tempted to suggest adding such a message, but probably that would just clog the UI even more. We could consider this later if we think it's useful.

2021-02-18 07:56 UTC, lorenzo-cavazzi commented on client/src/project/datasets/change/DatasetChange.container.js
> +            `Files for the ${datasetName} in ${props.projectPathWithNamespace} finished uploading.`,
Should we make it more explicit that it's necessary to carry on with the operation?   Maybe something like `Files uploaded, you can finalize the dataset`. I would omit the project name

2021-02-22 13:27 UTC, ciyer commented
I suggest the following:
- If the file is greater than some configurable threshold (default 50 MB), inform the user that they will be notified when the upload finishes.
![image](https://user-images.githubusercontent.com/1196411/108714613-0ba69c80-751a-11eb-9d14-99927ac62799.png)

2021-02-22 14:55 UTC, vfried commented on client/src/project/datasets/change/DatasetChange.container.js
> +            `Files for the ${datasetName} in ${props.projectPathWithNamespace} finished uploading.`,
@ciyer what do you think about this. A more direct message could be ok for notifications but I think it would be out of tone with he rest of the UI messages.

Regarding the project name, I think it should be there because you could be creating two datasets for different projects at the same time.

The message so that the user knows they will receive a notification will be pushed soon.

2021-02-22 15:01 UTC, vfried commented
I just pushed new changes, if the file is bigger than 100MB they will see the message. Otherwise, they won't.

![image](https://user-images.githubusercontent.com/42647877/108724719-f0da2500-7525-11eb-95dd-477446d009f7.png)

2021-02-24 10:25 UTC, ciyer approved these changes
This works very well! I tested uploading files to two different datasets at the same time, and that worked, the notifications were easy to follow. 

Ready to merge.

🎉

2021-02-24 10:25 UTC, ciyer commented on client/run-telepresence.sh
> +UPLOAD_THRESHOLD='{"hard":"104857600"}'
Good idea to reuse the existing format/structure!

2021-02-25 09:44 UTC, lorenzo-cavazzi reviewed
It works well :tada: 
I suggest a minor change to simplify the "upload threshold" structure before merging -- see the comment inline

2021-02-25 09:44 UTC, lorenzo-cavazzi commented on helm-chart/renku-ui/values.yaml
> +  hard: 104857600 # 100MB
We could simplify this structure to:
```
uploadSizeThreshold: 104857600 # 100MB
```
So that we have a string here instead of a JSON, making it more robust in the following steps (e.g. we won't need to invoke the `toJson` function in the "deployment.yaml" file)

2021-02-25 10:34 UTC, lorenzo-cavazzi commented on helm-chart/renku-ui/values.yaml
> +  hard: 104857600 # 100MB
As discussed offline, let's keep this structure and change `hard` to `soft` to make it more meaningful.
We will use `hard` when implementing #1251

2021-02-26 12:39 UTC, lorenzo-cavazzi approved these changes
:+1:

2021-02-26 12:41 UTC, merged