fix: fail gracefully when a dataset is missing
SwissDataScienceCenter/renku-ui pull request #1258
Opened 2021-03-02 16:31 UTC by lorenzo-cavazzi

Adds a 404 page when the dataset doesn't exist or the user doesn't have access (currently, the access control is not yet enforced by the APIs).
It's similar to the 404 project page when the user is trying to access `/datasets/<id>`, while it's a simpler message when trying to access datasets in a project page.

**Hot to test**: try to access non-existing datasets as anonymous or logged user
1. PR: https://renku-ci-ui-1258.dev.renku.ch/datasets/fake-id
    DEV: https://dev.renku.ch/datasets/fake-id

2. PR: https://renku-ci-ui-1258.dev.renku.ch/projects/lorenzo.cavazzi.tech/dataset-test-project-copy/datasets/fake-id
    DEV: https://dev.renku.ch/projects/lorenzo.cavazzi.tech/dataset-test-project-copy/datasets/fake-id

![Screenshot_20210302_173048](https://user-images.githubusercontent.com/43481553/109680738-14801980-7b7d-11eb-9f4f-0d0db8753a52.png)

/deploy
fix #1003

2021-03-04 11:05 UTC, vfried reviewed
Hey, things look good to me... i tested it and it looks like it works...

i just have a small question/resquest

2021-03-04 13:57 UTC, lorenzo-cavazzi commented on client/src/dataset/Dataset.container.js
> +                  setFetchError({ code: 0, message: "error fetching dataset: " + response.data.error.reason });
Right, I guess the "dataset not found" case is covered by the `-32100` error code, so any other error should be about files. I've changed the text to `error fetching dataset files` to make it explicit. This is the new output in case the dataset exists and fetching the files triggers an error.

![Screenshot_20210304_145359](https://user-images.githubusercontent.com/43481553/109974215-9c8b2e00-7cf9-11eb-8133-1e9c5308370e.png)

2021-03-04 14:07 UTC, lorenzo-cavazzi commented on client/src/dataset/Dataset.container.js
> +              setDatasetFiles(response.data);
I guess this is setting the content to the error we are getting in the response. I agree it doesn't make much sense, and it's more clear if we set it to an empty array, even if it has no impact. I've changed it

2021-03-04 15:33 UTC, ciyer requested changes
Looks good, but why do we have different styles of error messages in these two cases:

![image](https://user-images.githubusercontent.com/1196411/109987198-b4b57a00-7d06-11eb-9ab1-6f30e5e28346.png)

vs.

![image](https://user-images.githubusercontent.com/1196411/109987240-bd0db500-7d06-11eb-8263-3a78207cf6f1.png)

Could these two errors not be made to look more similar?

2021-03-04 15:33 UTC, ciyer commented on client/src/dataset/Dataset.present.js
> +            We could not find the dataset. It is possible is has been deleted by its owner or you don&apos;t have
I believe this message is incorrect. If the user can access the page of the project containing the dataset (which must be the case to be here), then they must also have access to the dataset.

2021-03-04 15:33 UTC, ciyer commented on client/src/dataset/Dataset.present.js
> +      (<p className="mb-0">You can try to select again a dataset ferom the list in the previous page.</p>) :
`You can try to select a dataset again from the list in the previous page.`

2021-03-04 15:33 UTC, ciyer commented on client/src/dataset/Dataset.present.js
> +          It is possible that the dataset has been deleted by its owner or you don&apos;t have permission
`...or you do not have permission...` would be better.

2021-03-08 09:57 UTC, lorenzo-cavazzi commented on client/src/dataset/Dataset.container.js
> +  }, [props.insideProject, datasetFiles, props.datasetId,
Good point. I was able to remove a couple of dependencies also in the other `useEffect` hook

2021-03-08 10:01 UTC, lorenzo-cavazzi commented on client/src/dataset/Dataset.present.js
> +            We could not find the dataset. It is possible is has been deleted by its owner or you don&apos;t have
This makes sense since it's on the project page and, even if the user has access only to the dataset but not to the project (not sure if it's possible with the future authorization on datasets), this page won't appear.

2021-03-08 10:12 UTC, lorenzo-cavazzi commented
I agree the two pages could be more similar, but I'm not sure if showing the bigger `404` on a project's sub-page would be good. Also, the message should be simplified because the permissions don't play a role here (currently, if the user can access the project, he can also see the datasets -- no permissions would result in the project 404 page).

Let me know if you have an idea to find common ground to unify the two dataset error pages. I believe it would be easier to unify the 404 on datasets outside the project and the 404 on missing projects. Maybe that would be easier once the search will be global (we could point the user to the search page and automatically compile the search field).

I've addressed the other comments.

2021-03-08 11:29 UTC, ciyer approved these changes
Yes, I wonder if we need to show a "404" error, since that is quite technical and probably not of interest to our users, but that is a larger discussion and the changes here are consistent with our current approach to errors.

It looks good now! 👍

2021-03-08 12:49 UTC, lorenzo-cavazzi commented
> Yes, I wonder if we need to show a "404" error, since that is quite technical and probably not of interest to our users, but that is a larger discussion and the changes here are consistent with our current approach to errors.

I agree we may want to hide some technical details to make the UI more user-friendly. We could still expose a few extra bits with the `show more` collapsable elements we have already used in other elements.
Should we create an issue/epic for this?

2021-03-08 12:51 UTC, merged