feat(design): new top bar
SwissDataScienceCenter/renku-ui pull request #1268
Opened 2021-03-10 17:04 UTC by vfried

Implemented design from https://xd.adobe.com/view/161ea402-fc08-41c1-b52e-1c423af506c9-434d/

![image](https://user-images.githubusercontent.com/42647877/110667604-b5e51c00-81ca-11eb-8e9f-49263d018227.png)

Incognito:
![image](https://user-images.githubusercontent.com/42647877/110667864-f93f8a80-81ca-11eb-9871-08659b27f6a6.png)

Collapsed
![image](https://user-images.githubusercontent.com/42647877/110667912-08263d00-81cb-11eb-8dc7-50d705f332cc.png)

![image](https://user-images.githubusercontent.com/42647877/110667955-14aa9580-81cb-11eb-8003-0613cb96fc4d.png)

ToDo:
Clean up the css
Make a bottom line under the selected item if applies (Projects, Datasets, Environments)

2021-03-10 17:57 UTC, lorenzo-cavazzi commented
Nice to see the new design at work :rocket: 

I've noticed the footer may need to be adjusted. I can't scroll on Chrome (look at the bottom right in the screenshot) and it's not rendered at the bottom in Firefox (on the left).

![Screenshot_20210310_185120](https://user-images.githubusercontent.com/43481553/110674187-f005ec00-81d1-11eb-9424-51ed1166c286.png)

2021-03-11 07:39 UTC, vfried commented
Yes, you are right about the footer.

I've also detected that but I will address the footer in a different PR so that it's easier to reviews.

2021-03-11 08:04 UTC, lorenzo-cavazzi requested changes
The content of the collapsable navbar doesn't look vertically centered (see screenshot).
I would reduce the top and the bottom margin on the renku logo so that the navbar height doesn't grow too much, but I'm also fine with the current solution.

I've seen you changed the `container` class. Should we create a different class instead if we need those CSS rules?
I would stick with the normal container since the current solution misaligns the content of the navbar and the main container on the left and on the right on a few pages.
I believe we haven't been consistent with the class elements for the layout (container --> col --> row) in many pages, and this is why the content is currently misaligned even with the default container (e.g. in the landing page we have 2 nested container).

![Screenshot_20210311_085250](https://user-images.githubusercontent.com/43481553/110753717-32b5db80-8247-11eb-9333-f0c257f1e7be.png)

2021-03-11 15:56 UTC, vfried commented on client/src/styles/bootstrap/_custom_bootstrap.scss
> +.container {
What you say on top is very true, i think we should change the way we are using containers. I'm taking a look at how we can use containers in a way that makes aligning things easier.

2021-03-11 15:58 UTC, vfried commented on client/src/styles/bootstrap/_custom_bootstrap.scss
> +.container {
Also, yes... it's a bad idea to do that with container.

2021-03-12 15:26 UTC, vfried commented
@ciyer @lorenzo-cavazzi I just pushed new changes, I was having lots of problems aligning elements in the bar so i decided to take a look at how bootstrap does the top navigation and did something similar to what they have. It seems to work. It's not 100% perfect but I think it's a big improvement.

We were having problems with the autosuggest and the way it was looking. Even in what we have deployed now there are problems. I also fixed this.

I also decided to delete all the containers and leave only two containers (top bar and body) let's see if this works, otherwise, we can add a few more. I hope we can slowly clean the pages from so many rows/cols/containers and things like that that make it hard to align items properly.

Let me know what you think about it.
It should get deployed soon.

2021-03-12 15:30 UTC, vfried commented
![image](https://user-images.githubusercontent.com/42647877/110961131-c1158480-834f-11eb-9932-1a7d8b001b9b.png)

![image](https://user-images.githubusercontent.com/42647877/110961170-ca065600-834f-11eb-9ad8-0ea2de262bec.png)

![image](https://user-images.githubusercontent.com/42647877/110961217-d4285480-834f-11eb-9b04-eb80a1c54ab2.png)

---> I didn't add color to the top bar search because I had the feeling it was hard to read but I can add it and try a bit more to make it look better.

---> I could add a bit of padding to the right and left if we wanted it, but this gives us less space

---> bootstrap has something that looks nice with icons when the bar is collapsed, i could do it for us as well (see here https://getbootstrap.com/docs/5.0/components/navbar/) or on the image here...
![image](https://user-images.githubusercontent.com/42647877/110961482-25384880-8350-11eb-9da1-6fc397d0eab2.png)

--> the logged out bar will disappear so i didn't put too much effort on that (We could change the way the login button looks, maybe make it green if we wanted to)

2021-03-15 12:50 UTC, rokroskar commented
This is looking great! Nice work, looking forward to having this live! 😄 🎉 
 
A few observations: 

* Looks like there are some issues with padding? 

![image](https://user-images.githubusercontent.com/3353586/111155053-3a9db480-8594-11eb-99f0-bd6fcb25c67c.png)

![image](https://user-images.githubusercontent.com/3353586/111155089-45f0e000-8594-11eb-85ce-01e5a83dada0.png)

* I don't know if that's in scope here but the color of the folder icon in the file browser needs to be updated:

![image](https://user-images.githubusercontent.com/3353586/111155222-789ad880-8594-11eb-868a-847c4c8ecc7c.png)

* Is the dataset view narrower intentionally?

![image](https://user-images.githubusercontent.com/3353586/111155802-3b831600-8595-11eb-8f66-144932a134df.png)

2021-03-15 12:53 UTC, vfried commented
Hey @rokroskar thanks for your observations, these things are out of scope now but I will take them into account.

I am only addressing the top nav bar on this PR, we are splitting the work into smaller chunks so that it's easier to review.

2021-03-15 12:54 UTC, rokroskar commented
Make sense, I was confused by the PR title since it seemed to implement everything already 😆

2021-03-15 13:10 UTC, pameladelgado commented
general question about the new design: are we going to have a dark theme version of it available? from time to time some users ask if we have this option...

2021-03-15 13:48 UTC, vfried commented
I changed the title to navbar i guess it makes more sense. 

We will be grouping all design related commits here https://github.com/SwissDataScienceCenter/renku-ui/pull/1274

@pameladelgado we will not have a dark theme at the moment but i think it's something that would be cool to have in the future.

2021-03-15 15:02 UTC, lorenzo-cavazzi commented
@vfried thanks for looking into this.

The vertical alignment still seems a bit off, not sure if that is on purpose. This is what I get in Firefox.

![Screenshot_20210315_155839](https://user-images.githubusercontent.com/43481553/111174197-89087e80-85a7-11eb-9b63-0e1ea8b57aef.png)

I played a bit with `margin: auto` and I was able to vertically center the components on the right.

![Screenshot_20210315_155705](https://user-images.githubusercontent.com/43481553/111174296-9d4c7b80-85a7-11eb-84a3-f2b79d77a8c5.png)

If this looks better, I can try to apply the changes to this PR

2021-03-15 15:08 UTC, vfried commented
Hey, my intention was to throw the elements on the right to the bottom. I thought it looked better, but I'm not 100% sure about this. Maybe @ciyer can also pitch in and give his opinion.

2021-03-15 15:18 UTC, lorenzo-cavazzi commented
Ah right, in the reference design the rightmost elements are vertically aligned with the logo
![Screenshot_20210315_161520](https://user-images.githubusercontent.com/43481553/111176677-d7b71800-85a9-11eb-8b08-5ebc9abe1358.png)
While the search and the links are oddly aligned (I can't see the intention here since they are not aligned with any other element :thinking: )
![Screenshot_20210315_161544](https://user-images.githubusercontent.com/43481553/111176744-e56c9d80-85a9-11eb-93c7-ad781fb2be44.png)

2021-03-15 17:06 UTC, ciyer commented
I think there was a mistake made in the top nav alignment. Here is a comparison of top nav from the Renku UI XD file and the one from the earlier presentation version. The alignment in the presentation version looks better to my eyes.

![image](https://user-images.githubusercontent.com/1196411/111192170-16080380-85b9-11eb-8301-186e5f6e289d.png)

I think we should do the alignment as it was in the presentation and check with the designer that that was the intention.

2021-03-17 15:08 UTC, vfried commented
Things centered like said on top... ready to be reviewed again

See changes in the text input...
Option 1: padding-top 0rem --> i like this one
![image](https://user-images.githubusercontent.com/42647877/111484948-7d978d80-8736-11eb-83a1-05cda96c1e85.png)

Option 2: padding-top:0.3rem
![image](https://user-images.githubusercontent.com/42647877/111485181-ae77c280-8736-11eb-8b89-503b205c2a2f.png)

2021-03-19 15:18 UTC, ciyer approved these changes
Nice improvement. I like the way this is progressing!

2021-03-19 15:19 UTC, merged