refactor: add dropdown indicator on autosuggest
SwissDataScienceCenter/renku-ui pull request #1277
Opened 2021-03-15 13:18 UTC by lorenzo-cavazzi

That was not planned for this sprint but I was checking something on bootstrap and I accidentally found the `custom-select` class to style an input element as a dropdown.
Sadly, I had to re-implement the same styling because the Autosuggest element has a minor bug preventing adding a class on the main `input` element when untouched.

/deploy
fix #1271

2021-03-15 14:37 UTC, ciyer approved these changes
Great fix!

It looks a little bit different than than what is expected on Safari and Chrome (didn't test FF), but I think this is fine, and I don't think it is worth putting in the effort to fix that.

2021-03-15 14:43 UTC, ciyer requested changes
Actually, I looked a little longer, and I think we should make a minor change if it is possible. Could you move the dropdown indicator (the triangles) over by a few pixels to line up with the other dropdown indicator. See image

![image](https://user-images.githubusercontent.com/1196411/111171385-2ca45f80-85a5-11eb-8b01-b843d81f1cd4.png)


Chrome, Safari, and FF all have their indicator closer to the right edge of the widget.

2021-03-15 14:53 UTC, lorenzo-cavazzi commented
I suggest using the opposite approach: instead of trying to adjust the class on the input, we could actually assign the same class to the other `select` elements and have the same output.
I don't particularly like to modify the default select appearance, but it's just the icon on the right, while the dropdown interaction won't change. That seems the only solution to prevent very different layouts in some browsers (e.g. with Firefox on Linux the dropdown icon is _very_ different).
This would be the layout with the suggested change

![Screenshot_20210315_154939](https://user-images.githubusercontent.com/43481553/111172799-6b86e500-85a6-11eb-850d-219644732ce0.png)

2021-03-15 15:25 UTC, ciyer commented
> I suggest using the opposite approach: instead of trying to adjust the class on the input, we could actually assign the same class to the other `select` elements and have the same output.

I like this solution! Do you have an opinion, @vfried?

2021-03-16 08:20 UTC, ciyer approved these changes
Great solution. I think this looks better than before.

2021-03-16 10:33 UTC, merged