feat(design): redesign of project search bar
SwissDataScienceCenter/renku-ui pull request #1281
Opened 2021-03-17 14:03 UTC by vfried

Before:
![image](https://user-images.githubusercontent.com/42647877/111479760-92bded80-8731-11eb-8594-769c4d7b5d9f.png)

After:
![image](https://user-images.githubusercontent.com/42647877/111479807-9d788280-8731-11eb-8c68-ac369c907cba.png)

Collapsed Before:
![image](https://user-images.githubusercontent.com/42647877/111479999-cb5dc700-8731-11eb-808b-e12f8888f205.png)

Collapsed After:
![image](https://user-images.githubusercontent.com/42647877/111480059-d6b0f280-8731-11eb-99a0-eee84f774e4a.png)

2021-03-18 14:11 UTC, ciyer requested changes
This looks good! I see that you have deviated from the design document in a few places, and I think most make sense, but I wanted clarify a few things illustrated by this image here:

![image](https://user-images.githubusercontent.com/1196411/111639490-99189c00-87fb-11eb-9c60-5748c24def91.png)

* What font weight should we use for "Renku Projects"? Here it is regular/400, the designer specified medium/500, but I think demi-bold/600 also looks good.
* Should we say "Filter by..." or "Search..." I lean to "Search" because it may be less technically correct, but I think it is simpler to understand
* I think we should try to emulate the look of the "Order by: " selection that comes from the designer.

2021-03-19 13:33 UTC, vfried commented on client/src/styles/fonts/_fonts.scss
> +$font-family-base: 'Calcutta-Regular', sans-serif;
Hey, you are right about this, i tried this but for some reason it didn't work, but it works now so i changed this to 

`$font-family-base: 'Calcutta', sans-serif;`

- Filter vs Search should be search
- Renku Projects font weight... in my opinion there is not much difference, i would like to make it the same for all text in that H* so that it's consistent. For now i left things to what bootstrap sets and i like it.
- Order by changed to look like luca designed.

2021-03-19 13:36 UTC, vfried commented on client/src/styles/fonts/_fonts.scss
> +$font-family-base: 'Calcutta-Regular', sans-serif;
I'm not very experienced with fonts, i will leave them like this for now and we could overwrite bootstraps values when we know what we want, maybe you could do it if you know better. Otherwise, i will give it a try.

Something else to consider is that Luca sent us the fonts for Regular and Medium but there are actually versions of the fonts for more weights the problem is we only have them in woff (i think) and we would need to have them also in eot, ttf and svc... this can be done with online converters if we would want to have the font in all the weights, I'm just not sure how bootstrap will use them... i tried to read about this but couldn't find anything in the documentation about it.

2021-03-22 10:06 UTC, ciyer approved these changes
This looks very good. The design is starting to come together! 🚀

2021-03-22 10:35 UTC, merged