feat(design): project search results redesigned
SwissDataScienceCenter/renku-ui pull request #1285
Opened 2021-03-23 14:38 UTC by vfried

Redesign for project search results...

![image](https://user-images.githubusercontent.com/42647877/112163843-b1b6f680-8bed-11eb-89e4-790625b61f49.png)

Pagination...

![image](https://user-images.githubusercontent.com/42647877/112163923-c4313000-8bed-11eb-9884-22b1f94d9401.png)

Design ref: https://xd.adobe.com/view/161ea402-fc08-41c1-b52e-1c423af506c9-434d/screen/75caace6-caf1-4183-9472-0224e227bd44/specs/

- we didn't had a design for the pagination so i adapted the one we have now 

/deploy

2021-03-24 10:27 UTC, ciyer requested changes
This looks great! The code is good. I think we should use spaces for indentation (see comments). Also one request for feature change: the XD file does not specify this, but I think the row that is under the mouse should be made more prominent. 

E.g., Which row is the mouse over here?

![image](https://user-images.githubusercontent.com/1196411/112293847-e0d37380-8c92-11eb-9db3-d67654c6b6d3.png)

If you look carefully, you will see that it is row 1.

2021-03-24 10:27 UTC, ciyer commented on client/src/styles/icons/icons.scss
> +.circle {
Could we use 2 spaces for indentation instead of tabs?

2021-03-24 10:27 UTC, ciyer commented on client/src/styles/components/_renku_search.scss
> +.rk-search-bar{
Could we use 2 spaces for indentation instead of tabs?

2021-03-24 10:27 UTC, ciyer commented on client/src/styles/components/_renku_search.scss
> +	border-top: solid 2px $light;
The difference between the hover and non-hover rows is not easy to see.

E.g., Which row is the mouse over here?

![image](https://user-images.githubusercontent.com/1196411/112293847-e0d37380-8c92-11eb-9db3-d67654c6b6d3.png)

If you look carefully, you will see that it is row 1, but it is very subtle. Could this be made a bit more obvious? Do not have a solution readily available, but maybe something like:

```border: 3px solid #adadad;```

Or maybe use the same color as the dot for the border?

2021-03-24 16:46 UTC, vfried commented on client/src/styles/components/_renku_search.scss
> +	border-top: solid 2px $light;
I hadn't read your suggestion... here is an example with the border with the dot color...

![image](https://user-images.githubusercontent.com/42647877/112349273-de8c0c00-8cc8-11eb-82b9-d1527d99bbb9.png)

2021-03-24 16:56 UTC, vfried commented
I just pushed fixes and restyled all the scss code, we should make an issue to add scss to linting rules.

2021-03-25 08:53 UTC, ciyer commented
I think the solution to highlighting with the gray background on the results list is nice. Let us go with that. In testing, I found two other cases were we need to modify the hover styling.

In user and group searches, the styling of the selected option is the same as the hovered over option. Let us make these a bit more different (maybe changing the background color).

![image](https://user-images.githubusercontent.com/1196411/112445529-83512c80-8d4f-11eb-9ebc-5498df94f361.png)


![image](https://user-images.githubusercontent.com/1196411/112445431-69afe500-8d4f-11eb-87fb-37b0c5d12a72.png)

2021-03-25 09:13 UTC, vfried commented
I will apply this hover color to the hover in search results and users

2021-03-29 11:35 UTC, ciyer approved these changes
Looks good!

2021-03-29 11:51 UTC, merged