feat(design): dataset search redesigned
SwissDataScienceCenter/renku-ui pull request #1287
Opened 2021-03-24 15:23 UTC by vfried

New datasets search page...

![image](https://user-images.githubusercontent.com/42647877/112336268-3c1a5b80-8cbd-11eb-9b8f-fa17851ac1b5.png)

2021-03-30 09:52 UTC, ciyer requested changes
This is coming along! I just found one minor issue and have a suggestion about a comment.

2021-03-30 09:52 UTC, ciyer commented on client/src/dataset/list/DatasetList.present.js
> +            // Can't remember if we had decided to leave just the first 3 crators...
On the Project/dataset page, we handle this using CSS: 
https://github.com/SwissDataScienceCenter/renku-ui/blob/master/client/src/project/Project.css#L40

We don't need to apply the same styling in this PR, but maybe the comment could reflect that.

2021-03-30 09:52 UTC, ciyer commented on client/src/dataset/list/DatasetList.present.js
> +            for, <Button className="pr-0 pl-0 pt-0 pb-0 mb-1" color="link" id="toggler">
The spacing around the button is off here. 

![image](https://user-images.githubusercontent.com/1196411/112970022-11615480-914e-11eb-9753-4125f095ba7c.png)

I think the problem is that Bootstrap 5 changes the naming convention for the spacing classes:

https://getbootstrap.com/docs/5.0/utilities/spacing/

I think the className should be set to `px-0 py-0` if we would want to control l/r and t/b styling separately or just `p0` to set everything to 0.

2021-03-30 11:04 UTC, vfried commented on client/src/dataset/list/DatasetList.present.js
> +            for, <Button className="pr-0 pl-0 pt-0 pb-0 mb-1" color="link" id="toggler">
I fixed the button padding, it's now p-0 (it changed from pr to pe as in pading end and pl to ps as in pading start).

Fixed a  small problem with the description height, now set to 100px max.

The creatos length, it's now limited to 3 person as it is now in the dataset project. This is what we had agreed with rok.

![image](https://user-images.githubusercontent.com/42647877/112978958-3fe42d00-9158-11eb-9310-19a7d25c1ed7.png)

2021-03-31 08:50 UTC, ciyer approved these changes
Great!

2021-03-31 08:52 UTC, merged