Read encoded metadata from the URL when creating new project
SwissDataScienceCenter/renku-ui pull request #1288
Opened 2021-03-25 08:13 UTC by lorenzo-cavazzi

Manage metadata from the query paramaters on the "create project page" to automatically fill in some inputs. Thin included the pieces to generate the URL and to read the data:

* Generate URL: click on the dropdown button "share link" to open a modal with the encoded URL. The user can decide which inputs to include in the metadata (screenshot 1).
* Read metadata: detect and read the metadata from the query parameters. The URL resets back to the basic one, then the data are gradually fetched and restored automatically (screenshot 2). Any error (e.g. unexisting template) or warning (e.g namespace unaccessible) will appear on top (screenshot 3).

For testing purposes, you can easily generate the encoded content of the `data` param by using `btoa` and `JSON.stringify` from the browser console (useful to generate errors or warnings on purpose), then add it after `/projects/new?data=`.
This is an example:
```
btoa(JSON.stringify({title:"test", namespace:"renku-qa", template:"Custom/python-minimal", url:"https://github.com/SwissDataScienceCenter/renku-project-template", ref:"0.1.16", visibility:"private", variables: { description: "description here" }}))
```

> eyJ0aXRsZSI6InRlc3QiLCJuYW1lc3BhY2UiOiJyZW5rdS1xYSIsInRlbXBsYXRlIjoiQ3VzdG9tL3B5dGhvbi1taW5pbWFsIiwidXJsIjoiaHR0cHM6Ly9naXRodWIuY29tL1N3aXNzRGF0YVNjaWVuY2VDZW50ZXIvcmVua3UtcHJvamVjdC10ZW1wbGF0ZSIsInJlZiI6IjAuMS4xNiIsInZpc2liaWxpdHkiOiJwcml2YXRlIiwidmFyaWFibGVzIjp7ImRlc2NyaXB0aW9uIjoiZGVzY3JpcHRpb24gaGVyZSJ9fQ==

The final URL is `/projects/new?data=<encoded_data_here>`

fix #1194

### Screenshots

1)
![Screenshot_20210325_085711](https://user-images.githubusercontent.com/43481553/112440000-125b4600-8d4a-11eb-823e-7d9cbac2c535.png)

2)
![Screenshot_20210325_085801](https://user-images.githubusercontent.com/43481553/112440022-1be4ae00-8d4a-11eb-85ca-4c458cf956ec.png)

3)
![Screenshot_20210325_091103](https://user-images.githubusercontent.com/43481553/112440038-20a96200-8d4a-11eb-93a1-d1ebbabb3c76.png)

2021-03-26 17:29 UTC, ciyer requested changes
Sorry for the delay -- I have been distracted with my computer set up. 

I have not yet had a chance to test the feature, but I was looking at the code and have done a partial review and noticed a few things. Take a look and see if you agree.

2021-03-26 17:29 UTC, ciyer commented on client/src/project/new/ProjectNew.container.js
> +  }
I suggest rewriting it with guarding clauses. I think this will be advantageous if we switch to notifications, since then we will know what the problem is.

```suggestion
    // Unrecognized params: should we notify? Let's start without notifications.
  const errorValue = null;
  if (params  == null) return errorValue;
  if (Object.keys(params).length < 1) return errorValue;
  if (params.data == null) return errorValue;
  const data = JSON.parse(atobUTF8(params.data));
  if (data == null || Object.keys(data).length < 1) return errorValue;
  // validate metadata
  const validKeys = Object.keys(newProjectSchema.createEmpty().automated.data);
  const keys = Object.keys(data);
  for (let key of keys) {
    if (!validKeys.includes(key))
      throw new Error("unexpected project field in the encoded metadata: " + key);
  }
  return data;
```

2021-03-26 17:29 UTC, ciyer commented on client/src/project/new/ProjectNew.present.js
> +  else if (automated.finished) {
`else` is unnecessary here.

I think 
```
if (!automated.finished) return null;
```
would be clearer.

2021-03-26 17:29 UTC, ciyer commented on client/src/project/new/ProjectNew.present.js
> +            the RenkuLab link asking for a new one.
```suggestion
It is possible the metadata are outdated or not valid. Please contact the source of the the RenkuLab link and ask for a new one.
```

2021-03-26 17:29 UTC, ciyer commented on client/src/project/new/ProjectNew.present.js
> +            Some pre-initializzation settings could not be applied.
```suggestion
            Some pre-initialization settings could not be applied.
```

2021-03-26 17:29 UTC, ciyer commented on client/src/project/new/ProjectNew.present.js
> +          Some pre-initializzation settings were applied.
See above comment on "pre-initialization" vs. "initialization".

2021-03-29 06:51 UTC, lorenzo-cavazzi commented on client/src/project/new/ProjectNew.present.js
> +  else if (automated.finished) {
Simplified in a similar way -- I've slightly changed the code preceding this part since it already included `if (!automated.finished)`.

2021-03-29 07:08 UTC, lorenzo-cavazzi commented on client/src/project/new/ProjectNew.container.js
> +  }
The code you suggested is definitely less convoluted.
I ended up committing a small variation of it, using `|| !` to merge the conditions in the first few lines so that it's coherent with line `295`. Let me know if that works

2021-03-29 08:32 UTC, ciyer requested changes
Trying out the feature, and it has been working well so far. I have some suggestions for changes in wording.

2021-03-29 08:32 UTC, ciyer commented on client/src/project/new/ProjectNew.present.js
> +          Some pre-initialization settings could not be applied.
```suggestion
          Some fields could not be pre-filled with the information provided in the RenkuLab project-creation link.
```

2021-03-29 08:32 UTC, ciyer commented on client/src/project/new/ProjectNew.present.js
> +        <br />You can still change any setting before you create the project.
```suggestion
        Some fields were pre-filled. 
        <br />You can still change any values before you create the project.
```

2021-03-29 08:32 UTC, ciyer commented on client/src/project/new/ProjectNew.present.js
> +  const button = showFadeIn ?
Is there a specific use case for including this? The pop-up is there for too short a time to make this useful. Or is this an "escape hatch" if the pre-filling doesn't finish for a long time?

- If this is a useful feature, I think it should be placed on the main "New project" page as part of the info dialog that says "Some fields were pre-filled...".

- If this is a fallback mechanism, I think the wording should be changed to "If pre-filling the new project form is taking too long, you can [use a blank form](link to normal new project form)".

2021-03-29 08:32 UTC, ciyer commented on client/src/project/new/ProjectNew.present.js
> +            <p>You entered a url containing initialization data.</p>
```suggestion
            <p>You entered a url containing information to pre-fill.</p>
```

2021-03-29 08:32 UTC, ciyer commented on client/src/project/new/ProjectNew.present.js
> +              Please wait, we are fetching the required metadata...&nbsp;
```suggestion
              Please wait while we fetch the required metadata...&nbsp;
```

2021-03-29 08:32 UTC, ciyer commented on client/src/project/new/ProjectNew.present.js
> +      <DropdownItem onClick={this.toggle}><FontAwesomeIcon icon={faLink} /> Share link</DropdownItem>
"Share link" is a bit unclear. How about: "Create link"?

2021-03-29 08:32 UTC, ciyer commented on client/src/project/new/ProjectNew.present.js
> +              Clicking on it will pre-fill the inputs automatically.
```suggestion
              Here is your shareable link, containing the current values for a new project.
              Following the link will lead to a <b>New project<b> form with these values pre-filled.
```

2021-03-29 08:32 UTC, ciyer commented on client/src/project/new/ProjectNew.present.js
> +              You can review which settings to include in the link metadata.
```suggestion
              You can control which values should be pre-filled..
```

2021-03-29 08:32 UTC, ciyer commented on client/src/project/new/ProjectNew.present.js
> +        Including the namespace may lead to errors if the user does not have access to it.
```suggestion
        Pre-filling the namespace may lead to errors since other users are not guaranteed to have access to it.
```

2021-03-29 12:52 UTC, lorenzo-cavazzi commented on client/src/project/new/ProjectNew.container.js
> +      this.coordinator.setAutomated(null, e);
This error should occur only when the user copy/pasted a wrong link. I think it's useful to notify the user about that to prevent confusion. I'm ok with removing it if you think it's a better UX, but I would rather not logging the error to the console -- not sure if that is a pattern we want to introduce for user-side debugging.

2021-03-29 13:07 UTC, lorenzo-cavazzi commented on client/src/project/new/ProjectNew.present.js
> +  const button = showFadeIn ?
It's actually the second case, and I don't expect it to happen often. An example could be a very slow response from a remote git repo when a custom template is provided.

I think the wording you suggested is great. Should I change the "show more" text to something like `taking too long?`?
This is the current output, let me know if I can improve it further

![Screenshot_20210329_150208](https://user-images.githubusercontent.com/43481553/112841112-647cce00-90a0-11eb-84b0-1f4e37f2bb15.png)
![Screenshot_20210329_150240](https://user-images.githubusercontent.com/43481553/112841121-66df2800-90a0-11eb-807a-e176edb14756.png)

2021-03-29 13:19 UTC, lorenzo-cavazzi commented
Thank you @ciyer for taking the time to go through the wording, it was a bit incoherent :pray: 

I'm not sure about using the `console.log` message for logging an error. If the error is useful, I would use another way to display it -- either a notification or showing it somehow on the page. Otherwise, I would just drop it. I don't think the user/dev would ever check the console, nor we should encourage this pattern.

2021-03-29 13:24 UTC, ciyer commented on client/src/project/new/ProjectNew.present.js
> +  const button = showFadeIn ?
Looks good as you have solved it. 👍

2021-03-29 13:32 UTC, ciyer commented on client/src/project/new/ProjectNew.container.js
> +      this.coordinator.setAutomated(null, e);
Maybe I do not understand how you get into this code path. 

In general, I think the error handling is good as is. One case that could be improved, though, is if the URL is broken. For example:

https://renku-ci-ui-1288.dev.renku.ch/projects/new?data=eyJ0aXRsZSI6InRlc3QtdGl0bGUiLCJ0ZW1wbGF0ZSI6IlJlbmt1L3B5dGhvbi1taW5pbWFsIiwidmFyaWFibGVzIjp7ImRlc2NyaXB0aW9uIjoidGVzdCBkZXNjcmlwdGlvbiJ9fq%3D%3D

This URL has been corrupted. For most users, ignoring it as happens is the correct behavior, but if I am the developer of the URL, it is confusing because I just get the blank project form with no indication that the data parameter was ignored.

I thought that is what is happening in this code above, but maybe that logic is somewhere else.

2021-03-29 14:17 UTC, lorenzo-cavazzi commented on client/src/project/new/ProjectNew.container.js
> +      this.coordinator.setAutomated(null, e);
Oh, I fear I added a check on `newProject.automated.finished` that prevents early errors from showing up to the user :facepalm:  -- the corrupted link is the most expected one.

The intended output was the following

![Screenshot_20210329_161657](https://user-images.githubusercontent.com/43481553/112850348-343a2d00-90aa-11eb-9de7-09b4873be43a.png)

2021-03-31 07:52 UTC, ciyer submitted a review, later dismissed
Very nice 🎉 ! Ready to merge as far as I am concerned, but we can wait a day to see if any new feedback comes in.

2021-03-31 10:58 UTC, ltalirz commented
Thanks, guys!   ( @rokroskar pointed me here).

> if this PR works well, we should create a corresponding entry in the documentation for this new feature

Indeed it will be important to document how to generate the data payload, since these links will likely be created outside renku (at least in our case). 
It's therefore also helpful if the method for generating the payload remains stable, and if future changes to the parameters in the form (=keys in the dictionary) are backwards-compatible where possible.

2021-03-31 11:26 UTC, rokroskar commented
@ltalirz I just tried now and the deployment seems to be fine - you can find it at https://renku-ci-ui-1288.dev.renku.ch/ - note that the login is a bit convoluted because it authenticates against our dev cluster so you essentially log in twice.

2021-03-31 12:23 UTC, lorenzo-cavazzi commented
@ltalirz Thanks for the pointers! The project creation based on templates should be flexible enough. For sure, we will try to keep backward-compatibility in case of changes.
The main reason for links to become broken could be referencing templates that are not available anymore, or using a mutable reference (e.g. a branch instead of a tag/commit).

Generating the links outside renku seems more challenging to achieve. We serialize and encode an object with all the data for pre-filling fields, assigning the string to a single query parameter that we include in the URL. It's much easier to do that from the UI. Do you perhaps need to automatize the link generation?

2021-04-06 14:05 UTC, ltalirz commented
Sorry for the late follow-up

> Generating the links outside renku seems more challenging to achieve. We serialize and encode an object with all the data for pre-filling fields, assigning the string to a single query parameter that we include in the URL. It's much easier to do that from the UI. Do you perhaps need to automatize the link generation?

Yes - our use case will involve creating these links on the Materials Cloud Archive, where next to an AiiDA export file on a record like [this](https://archive.materialscloud.org/record/2020.153) there would be a "open in renkulab" icon.
That would link directly to the new project page, with metadata concerning the project template, title + some user-defined variables of the template already filled in.

2021-04-06 14:06 UTC, ltalirz commented
If the serialization uses standard libraries and is clearly documented, I don't see a big issue in doing this in the materials cloud archive application (might use python instead of JS).

2021-04-06 14:16 UTC, ltalirz commented
P.S. An alternative could be to `POST` to the URL with a specific JSON payload - that would get rid of the need for (de)serialization.

2021-04-06 15:19 UTC, lorenzo-cavazzi commented
> If the serialization uses standard libraries and is clearly documented, I don't see a big issue in doing this in the materials cloud archive application (might use python instead of JS).

Right, after all we just serialize a dictionary to a JSON string, and we base64 encode it. Once the underlying dictionary structure is known, the process is straightforward in any programming language.

I pushed a PR for updating the documentation here: SwissDataScienceCenter/renku#2060
It contains also a Python example.

In short, here is the process to compute the link:
```
# 1. Create a dictionary with all the required data

  raw_data = {
    "title":"test",
    "url":"https://github.com/SwissDataScienceCenter/renku-project-template",
    "ref":"0.1.17",
    "template":"Custom/python-minimal",
    "variables": {
      "description":"test description"
    }
  }

  # 2. Serialize to a string

  import json
  serialized_data = json.dumps(raw_data)

  # 3. Encode in base64
  import base64
  data = base64.b64encode(str.encode(serialized_data))

  # 4. Use the output to compose the URL
  print(data)

  > b'eyJ0aXRsZSI6ICJ0ZXN0IiwgInVybCI6ICJodHRwczovL2dpdGh1Yi5jb20vU3dpc3NEYX
    RhU2NpZW5jZUNlbnRlci9yZW5rdS1wcm9qZWN0LXRlbXBsYXRlIiwgInJlZiI6ICIwLjEuMT
    ciLCAidGVtcGxhdGUiOiAiQ3VzdG9tL3B5dGhvbi1taW5pbWFsIiwgInZhcmlhYmxlcyI6IH
    siZGVzY3JpcHRpb24iOiAidGVzdCBkZXNjcmlwdGlvbiJ9fQ=='

  # The link will be
  # https://<renkulab_url>/projects/new?data=eyJ0aXRs...biJ9fQ==
```

2021-04-12 11:18 UTC, ciyer approved these changes

2021-04-13 07:58 UTC, merged

2021-05-01 11:48 UTC, ltalirz commented
Just wanted to mention that @vgranata created an internal prototype using this and it seems to be working fine!

Just waiting for https://github.com/SwissDataScienceCenter/contributed-project-templates/pull/4 to be reviewed and merged before we can consider making it public.

2021-05-05 06:39 UTC, ciyer commented
@ltalirz Thanks for the update!