Apply the new design of the home page
SwissDataScienceCenter/renku-ui pull request #1298
Opened 2021-04-01 11:57 UTC by ciyer

2021-04-15 15:21 UTC, lorenzo-cavazzi commented
Wow the new landing page is gorgeous!

I have a couple of notes on the appearance (I still need to go through the code).

One is on the element above the footer: it looks nice on big and small pages, but the alignment of the locations is a bit off on medium size.

![Screenshot_20210415_170815](https://user-images.githubusercontent.com/43481553/114892806-628b6c80-9e0d-11eb-9123-8908fb610315.png)

A suggestion to mitigate this would be to let the first element (renku logo + "We have offices in...") take all the horizontal space (a `col-12` without max-width) and let the 2 locations float below.
I would also let them align on the left with the aforementioned element. Something like this

![Screenshot_20210415_171510](https://user-images.githubusercontent.com/43481553/114893717-46d49600-9e0e-11eb-91d6-79b34b3ede0e.png)

The other thing is the menu on top right. When open, it looks misaligned on the right -- not sure if the idea is to align it on the right or not, but since it's just slightly off, the current vertical alignment looks a bit odd.

![Screenshot_20210415_171639](https://user-images.githubusercontent.com/43481553/114894043-91561280-9e0e-11eb-9898-36af2d4bd669.png)

Maybe it's just me, but it was difficult to identify the Login button on the top right, even though I knew where to look. Maybe using a background (or different colors) would make it stand out more?
I guess waiting for a second opinion on this may be better since it's probably just a personal preference

2021-04-15 16:12 UTC, lorenzo-cavazzi reviewed
The code looks good! Just a couple of minor comments inline.

As mentioned offline, I found a problem with setting the content through telepresence. I'll test with more combinations once that is fixed.

2021-04-15 16:12 UTC, lorenzo-cavazzi commented on client/src/landing/AnonymousHome.js
> + * Copyright 2018 - Swiss Data Science Center (SDSC)
2021

2021-04-16 08:46 UTC, ciyer commented on client/.eslintrc.json
> +          "tsstrasse",
Good suggestion! I actually tried this at first, but I was trying to just disable the spellcheck, which I couldn't get to work. You are right: we can just disable all linting on this line.

2021-04-16 09:43 UTC, ciyer commented
Thanks for the review. I think all of your concerns have been addressed now.

2021-04-16 12:31 UTC, lorenzo-cavazzi requested changes
Great! There is just a minor typo in the telepresence example command I noticed while testing (see inline).

The office locations still look misaligned on smaller browsers. If we are fine with that, feel free to disregard the other inline comments suggesting a slightly different solution.

2021-04-16 12:31 UTC, lorenzo-cavazzi commented on client/run-telepresence.sh
> +# set HOMEPAGE_MAIN_CONTENTMD '# Yoyodyne'\n'Welcome to the Yoyodyne Renku instance!'
```suggestion
# set HOMEPAGE_MAIN_CONTENTMD '# Yoyodyne\nWelcome to the Yoyodyne Renku instance!'
```
I believe the extra `'` around the wrap word char slipped in by mistake.
Compare the output with the current solution (1) and with the suggested change (2)

![Screenshot_20210416_141314](https://user-images.githubusercontent.com/43481553/115022872-485d9700-9ebe-11eb-852d-d6114d9109db.png)

![Screenshot_20210416_141616](https://user-images.githubusercontent.com/43481553/115022905-56abb300-9ebe-11eb-8718-b0c3e8101ce6.png)

2021-04-16 12:31 UTC, lorenzo-cavazzi commented on client/src/landing/AnonymousHome.js
> +        <Col xs={12} lg={5} xl={4} className="rk-pl-s bg-primary">
```suggestion
        <Col xs={12} lg={5} xl={4} className="rk-pt-s bg-primary">
```

The extra space on left (and no space on top) makes the output on medium/small screen very close to the above content and misaligned on the left (as in screen 1).
The suggested correction (screen 2) works, but the `xl={4}` at line 293 should also get removed. Otherwise, the content is better on smaller sizes but it's misaligned on bigger.

![Screenshot_20210416_140350](https://user-images.githubusercontent.com/43481553/115023961-bd7d9c00-9ebf-11eb-8ac0-83dd46343904.png)

![Screenshot_20210416_140608](https://user-images.githubusercontent.com/43481553/115024013-cd957b80-9ebf-11eb-903c-40cba57d1c3a.png)

2021-04-16 12:31 UTC, lorenzo-cavazzi commented on client/src/landing/AnonymousHome.js
> +        <Col xs={12} lg={5} xl={4} className="rk-pl-s bg-primary">
```suggestion
        <Col xs={12} lg={5} xl={4} className="rk-pt-s bg-primary">
```
Check comment at line 296

2021-04-16 12:31 UTC, lorenzo-cavazzi commented on client/src/landing/AnonymousHome.js
> +        <Col xs={12} xl={4} >
```suggestion
        <Col xs={12}>
```
Check comment at line 296

2021-04-16 12:33 UTC, lorenzo-cavazzi commented
P.S: the acceptance tests may be failing due to a timeout. You could include the commit from here to prevent that #1317

2021-04-16 12:41 UTC, Panaetius commented
Looks gorgeous!

Not sure if it's supposed to be this way, but the empty white horizontal bar in the middle here seems odd:
![image](https://user-images.githubusercontent.com/664486/115025224-611b7c00-9ec1-11eb-89f1-6f04a94cc19a.png)
And the repeat renku logo there and the background image seem oddly positioned, I guess that's a problem with using a 4k display?

2021-04-16 13:11 UTC, ciyer commented on client/run-telepresence.sh
> +# set HOMEPAGE_MAIN_CONTENTMD '# Yoyodyne'\n'Welcome to the Yoyodyne Renku instance!'
That is because I use a different shell (fish) which handles strings differently from bash/zsh. I thought that syntax would be portable, but apparently not. I'm ok with switch to the one that works on bash/zsh and adapting it for myself.

2021-04-16 13:14 UTC, ciyer commented
Thanks for the feedback!

> Not sure if it's supposed to be this way, but the empty white horizontal bar in the middle here seems odd:

That bar is where the section that highlights some interesting projects will go, but the PR has gotten very large already, so that will be implemented in a follow-up.

> And the repeat renku logo there and the background image seem oddly positioned, I guess that's a problem with using a 4k display?

That's a good catch, something that isn't easy for me to spot on my 13" display. The background shouldn't repeat -- I will fix that.

2021-04-16 14:13 UTC, vfried reviewed
It feels really good to open renkulab and see this as the landing page!!! 🥳  

Things look really good in general but i found some things we could improve...

On my screen the background image on top is there twice (i think you fix this with background:no-repeat)
![image](https://user-images.githubusercontent.com/42647877/115031895-fb32f280-9ec8-11eb-842b-cf2b28536774.png)

I also think we should do as in inside renkulab and have a max-width and fit the content to that if the screen is bigger than that.

The green text here should be on the right
![image](https://user-images.githubusercontent.com/42647877/115032109-3af9da00-9ec9-11eb-8b81-24c6e61958d4.png)

I think we should add a bit of padding on the top here or vertically align the content so that there is not so much white space under the three sections...
![image](https://user-images.githubusercontent.com/42647877/115036751-10f6e680-9ece-11eb-90f3-e0b1db4db8ba.png)

I see under the h3 luca added some space (We could add padding here or just some <br/> so that there is space between title and paragraph). Also in the "Data drive projects...."

I would add a white border to this image...
![image](https://user-images.githubusercontent.com/42647877/115032192-56fd7b80-9ec9-11eb-9be8-830da9bc1766.png)
Something like this could work... 
    min-width: 300px;
    border-width: 40px;
    border-style: solid;
    border-color: white;


So that it looks like this...
![image](https://user-images.githubusercontent.com/42647877/115032238-64b30100-9ec9-11eb-96b7-7632c344ed8e.png)

I'm not sure the collapsible menu looks good the way it is now... I think it could be better if we make it be a vertical menu either similar to this...
![image](https://user-images.githubusercontent.com/42647877/115034181-80b7a200-9ecb-11eb-9044-429b59f3799e.png)

Or this...
![image](https://user-images.githubusercontent.com/42647877/115034253-94fb9f00-9ecb-11eb-97a9-a246aa632d74.png)

Otherwise, I would just add some buttons next to learn more where we say explore projects, explore datasets, etc.

2021-04-16 14:13 UTC, ciyer commented on client/src/landing/AnonymousHome.js
> +        <Col xs={12} lg={5} xl={4} className="rk-pl-s bg-primary">
So the designer had this for the layout on desktop:

![image](https://user-images.githubusercontent.com/1196411/115037207-8367c680-9ece-11eb-9eb1-ad82c12408ce.png)

So I want to maintain that for the larger sizes, but I now have this:

![image](https://user-images.githubusercontent.com/1196411/115037328-a4301c00-9ece-11eb-9dbc-81f0ac5502e1.png)

and this

![image](https://user-images.githubusercontent.com/1196411/115037384-b1e5a180-9ece-11eb-98b8-93b40aa16b4f.png)

for smaller sizes.

2021-04-19 12:32 UTC, ciyer commented
@vfried Thanks for the review. I have made the fixes you suggest. I set a max width on the main content, but I kept the content on the left side. I could make it centered if you think that is better, though.

2021-04-27 07:33 UTC, vfried commented
Thanks for applying the changes to the homepage, I really like the way the background expands when the window expands... it's a really cool effect.

I realized there is a yellow dot in the image, I don't think that should be there... could we change this ourselves?
![image](https://user-images.githubusercontent.com/42647877/116201090-6be3d580-a739-11eb-8cdf-63cc95dd55f6.png)

Regarding the content, I would prefer to center things (put the extra space in the right and left instead of only on the right) inside there the content can remain on the left (i think it's what Luca said we should do as well), if you prefer to leave things on the left we could also do that.

I noticed there is some blue background/rectanble opening when you open the menu, could we make this disappear?
![image](https://user-images.githubusercontent.com/42647877/116201407-c11fe700-a739-11eb-81d2-b7456eeb0215.png)
I tried and you can use something like this to at least make it smaller, i think if here you set the background to transparent it should be better. (what i used is... justify-content: flex-end;display: flex;)
<div style="justify-content: flex-end;display: flex;"><div class="mt-2 collapse show" style=""><nav class="container-fluid navbar rk-anon-home rk-navbar px-0 bg-primary navbar bg-primary">

I tested this on the mobile version and it also looks great, i noticed something strange happening with the footer... we should make it blue like in the other version (or make both light gray but with darker text). I'm not sure if this is something you did or if it was a bug i introduced... we can also address footer fixes in a separate PR.
![image](https://user-images.githubusercontent.com/42647877/116202874-5b345f00-a73b-11eb-833b-a7dd3c8d8543.png)


Everything else looks really good!!! Looking forward to having this merged :)

2021-04-27 12:21 UTC, ciyer commented
@vfried I had forgotten some of the things we discussed with the designer, but they should all be in now. I think I addressed everything you brought up, except the footer. Something happened to the footer after rebasing against the ui-design-2021 branch, but I will fix them in a follow-up pr.

2021-04-27 12:35 UTC, vfried commented
All looks good to me, I found a last small thing (I think current changes might have caused this) we could address this on a follow-up or as well...

when you access things from a phone you see this(there is a white line across things)
![image](https://user-images.githubusercontent.com/42647877/116241951-b8450a80-a765-11eb-8c23-0868c375d3d3.png)

2021-04-27 12:38 UTC, vfried approved these changes
I will approve this PR, you can make changes here or make the changes in a follow-up PR.

2021-04-27 13:26 UTC, merged