build: release 0.11.10
SwissDataScienceCenter/renku-ui pull request #1311
Opened 2021-04-13 12:38 UTC by lorenzo-cavazzi

/deploy

2021-04-13 15:10 UTC, ciyer requested changes
Looks good! Just a suggestion to make the description of a new feature clearer.

2021-04-13 15:10 UTC, ciyer commented on CHANGELOG.md
> +* create links to the project creation page embedding metadata to automatically pre-fill input fields ([#1288](https://github.com/SwissDataScienceCenter/renku-ui/issues/1288), [#1194](https://github.
```suggestion
* generate project-creation links, embedding metadata to automatically pre-fill input fields ([#1288](https://github.com/SwissDataScienceCenter/renku-ui/issues/1288), [#1194](https://github.com/SwissDataScienceCenter/renku-ui/issues/1194))
```

2021-04-13 17:47 UTC, ciyer approved these changes
👍

2021-04-14 07:53 UTC, aledegano approved these changes

2021-04-14 07:59 UTC, merged