feat(design): new grid display for project search
SwissDataScienceCenter/renku-ui pull request #1360
Opened 2021-05-25 14:01 UTC by vfried

2021-05-26 08:11 UTC, ciyer requested changes
This looks great! Especially with images. I found a few things in the code that I was unsure about, but they should all be small fixes.

2021-05-26 08:11 UTC, ciyer commented on client/src/project/list/ProjectList.container.js
> +  perPage: 12, // TODO: change to 10
Should this be 10 or 12?

2021-05-26 08:11 UTC, ciyer commented on client/src/project/list/ProjectList.container.js
> +
A `log` call that slipped in.

2021-05-26 08:11 UTC, ciyer commented on client/src/styles/components/_renku_search.scss
> +  display: -ms-flexbox;
Do we need this? I think flexbox is supported by all browsers we target.

2021-05-26 08:11 UTC, ciyer commented on client/src/styles/components/_renku_search.scss
> +    padding-left:1em;
For spacing consistency.

```suggestion
    padding-left: 1em;
```

2021-05-26 08:13 UTC, vfried commented on client/src/project/list/ProjectList.container.js
> +  perPage: 12, // TODO: change to 10
I decided to set it to 12 because that way we get 4 columns with 3 elements inside... otherwise it looks a bit weird

2021-05-26 08:15 UTC, vfried commented on client/src/styles/components/_renku_search.scss
> +  display: -ms-flexbox;
I will remove it wasn't sure we should have it or not, I took that css from mansonry's tutorial.

2021-05-26 11:31 UTC, ciyer commented on client/src/project/list/ProjectList.container.js
> +  perPage: 12, // TODO: change to 10
Makes sense -- just get rid of the comment then.

2021-05-27 09:12 UTC, ciyer commented on client/src/project/list/ProjectList.container.js
> +  perPage: 12, // TODO: change to 10
```suggestion
  perPage: 12,
```

2021-05-27 09:17 UTC, ciyer commented on client/src/styles/components/_renku_search.scss
> +  display: flex;
```suggestion
  display: flex;
```

2021-05-27 11:48 UTC, vfried commented
@ciyer all was fixed, let's wait until we can deploy+test

2021-05-28 07:25 UTC, ciyer approved these changes
Looks great! I'm hoping this will motivate users to add images, tags, and description, since the display looks even better when that information is available.

2021-06-02 08:13 UTC, merged