feat(design): improvements in datasets
SwissDataScienceCenter/renku-ui pull request #1364
Opened 2021-05-26 15:19 UTC by vfried

Small improvements in datasets...

![image](https://user-images.githubusercontent.com/42647877/119686323-81d2dc00-be46-11eb-90dd-05297c3ec41f.png)

I changed the circles to triangles, we could also do squares.

2021-05-27 06:59 UTC, ciyer requested changes
Great idea, and this looks nice. I have a naming suggestion that will give us more flexibility to change things if the designer proposes a different solution.

2021-05-27 06:59 UTC, ciyer commented on client/src/dataset/list/DatasetList.present.js
> +      <span className={"triangle me-3 mt-2 " + color}></span>
I suggest we name the class for its meaning — so `rk-ds` (and have `rk-proj` for projects). This will give us freedom to change the shape that is rendered in the css without having to modify the code elsewhere.

2021-06-03 13:24 UTC, ciyer commented on client/src/dataset/list/DatasetList.present.js
> +      <span className={"triangle me-3 mt-2 " + color}></span>
After looking at it longer, I think we should avoid using triangles because we use them for the warning sign.

2021-06-08 07:38 UTC, vfried commented
We decided to let go of this idea for now, we might want to ask the designer to make proper icons for datasets/projects/etc but we don't need this for now.

2021-06-08 07:38 UTC, closed without merging