feat(design): generic component to map items into a list applied to projects and datasets for now
SwissDataScienceCenter/renku-ui pull request #1372
Opened 2021-06-01 11:31 UTC by vfried

I created a List component that receives a list of items with different fields and maps them to a grid or list (depending on what the user wants).

![image](https://user-images.githubusercontent.com/42647877/120316181-6bf96700-c2dd-11eb-9968-efbf2907c20a.png)

It looks like the project grid, there is a benefit here... if we want to implement a generic search in the KG (for projects, datasets, etc) we could use this generic component to display a list of mixed elements.

I applied this to datasets and projects. I see the project row is used in the landing page as well, we could delete this code after we adapt the landing page to using this.

/deploy

2021-06-03 15:20 UTC, ciyer requested changes
Structuring this as a component will make it much easier to get a uniform display of lists across pages! 

I have a couple of suggestions for places were code could be restructured a bit and where some documentation would help, but I think this is overall very good.

2021-06-03 15:20 UTC, ciyer commented on client/src/dataset/list/DatasetList.present.js
> +      items={datasets.map(dataset => {
I think this could be extracted to a variable above. It's a lot of code to look at in a property.

2021-06-03 15:20 UTC, ciyer commented on client/src/project/list/ProjectList.present.js
> +    items={projects.map(project => {
This is a lot of code in a property. It could be extracted to a variable.

2021-06-03 15:20 UTC, ciyer commented on client/src/utils/List.js
> +function ListDisplay(props) {
This class could benefit from some documentation about the properties. What is expected in each of the properties.

2021-06-03 15:20 UTC, ciyer commented on client/src/project/list/ProjectList.present.js
> +            <RenkuMarkdown markdownText={project.description} fixRelativePaths={false} singleLine={true} />
Why is `MarkdownTextExcerpt` not used here?

2021-06-04 15:31 UTC, vfried commented on client/src/project/list/ProjectList.present.js
> +            <RenkuMarkdown markdownText={project.description} fixRelativePaths={false} singleLine={true} />
Copy-paste --> I just used what was used in the project before but I will change it to the Excerpt

2021-06-04 16:37 UTC, vfried commented
@ciyer thanks for your review,  I addressed all changes, all made sense to me.

Let me know if the documentation for the list component is clear enought.

2021-06-07 11:03 UTC, ciyer approved these changes
👍

2021-06-07 11:05 UTC, merged