feat(design): use of colours to identify entities
SwissDataScienceCenter/renku-ui pull request #1377
Opened 2021-06-02 14:34 UTC by vfried

We decided that each entity has a color, this will be useful when we have different entities returned by the same search results.

Green --> projects
Pink --> datasets
Yellow --> collaboration (until the tab is replaced by the iframe)

![image](https://user-images.githubusercontent.com/42647877/120499443-5610a280-c3c0-11eb-8ccf-086b377d66e8.png)

![image](https://user-images.githubusercontent.com/42647877/120499476-5d37b080-c3c0-11eb-8832-38bdf6fe27d8.png)

Closes #1376

2021-06-03 13:37 UTC, ciyer commented
I think yellow will probably be workflows, once those are also indexed into the KG.

2021-06-03 13:40 UTC, ciyer requested changes
This is a nice solution! The only thing that I think should be changed is the integration of collaboration. That is about to go away, and I think the next entity that we will want to so search for are workflows.

2021-06-03 13:40 UTC, ciyer commented on client/src/styles/icons/icons.scss
> +.circle.collaboration {
I think we can make this workflow or wait until we can actually integrate workflows.

2021-06-03 13:43 UTC, vfried commented on client/src/styles/icons/icons.scss
> +.circle.collaboration {
Yes, i thought that would be the case... shall I use some gray dots for collaboration while we have them? Also... I could make things be a different shape if we wanted to (for colorblind people)

2021-06-04 16:34 UTC, vfried commented
@ciyer i addressed the changes that were requested, i made an additional change to name the entities inside the items on top of the list, this will allow us to do lists with mixed items.

2021-06-07 12:59 UTC, ciyer approved these changes
👍

2021-06-08 07:37 UTC, merged