enable canary deployment
SwissDataScienceCenter/renku-ui pull request #1379
Opened 2021-06-02 16:54 UTC by rokroskar

To test, deploy this branch and set the cookie `new-ui` to `always` or `never`. The server name is currently hard-coded to rok.dev.renku.ch in the ingress template. This should be configurable through the values file somehow.

2021-06-02 21:18 UTC, ableuler reviewed
Looks good on first sight, haven't tried it yet though. If this canary option is going to stick around (which I believe it will as it's something very useful in general), it would be nice to avoid the duplication between the regular and the canary deployment spec. Not sure what's best here, maybe a range loop?

2021-06-02 21:44 UTC, rokroskar commented
hmm I don't know - they're very similar here but they might as well be very different for a different purpose. I'm not sure there's really much of a benefit in avoiding this duplication right now.

2021-06-03 14:14 UTC, ableuler requested changes

2021-06-03 14:14 UTC, ableuler commented on helm-chart/renku-ui/templates/ingress.yaml
> +spec:
Hmm, how does TLS termination actually work here? I've seen THAT it works, but I wonder how 😅. Is it handled according to the main ingress spec still?

2021-06-03 14:14 UTC, ableuler commented on helm-chart/renku-ui/templates/ingress.yaml
> +    - host: {{ .Values.canary.host }}
I think we could use `.Values.global.renku.domain` here (and do the same in our main renku ingress).

2021-06-03 14:24 UTC, rokroskar commented on helm-chart/renku-ui/templates/ingress.yaml
> +    - host: {{ .Values.canary.host }}
oh good point, I forgot about that one

2021-06-03 14:26 UTC, rokroskar commented on helm-chart/renku-ui/templates/ingress.yaml
> +spec:
good question - I actually don't know 😆 Probably because it's set per host and channeling the request to the correct service happens afterwards?

2021-06-03 14:28 UTC, rokroskar commented on helm-chart/renku-ui/values.yaml
> +  enabled: false
idk, i see it the other way (this is not required for a functioning UI) but you're right that the @SwissDataScienceCenter/renku-ui-maintainers  should decide the default for the release...

2021-06-03 14:44 UTC, rokroskar commented
> the duplicated section will get very stale

that's true, I just don't know of a clean way of doing this. I guess we could have a meta template file that gets injected and we modify the behavior via alias definitions? e.g. 

```
{{- $name := include "ui.fullname" . -}}-canary
{{ .Files.Get deployment.yaml.tpl }}
```

and `deployment.yaml.tpl` would have e.g.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
...
```

_maybe_ something like that would work and not be too crazy to maintain without tons of templating directives all over the place?

2021-06-04 13:36 UTC, ciyer requested changes

2021-06-04 13:36 UTC, ciyer commented on helm-chart/renku-ui/values.yaml
> +  host: example.com
Where does this line come from? Is `example.com` correct?

2021-06-04 14:00 UTC, rokroskar commented on helm-chart/renku-ui/values.yaml
> +  host: example.com
I've gotten rid of this actually -- it's fetched from `global.renku.domain` (haven't pushed the changes yet)

2021-06-04 16:48 UTC, ciyer commented
I tested this, and it works well, which is very cool!

We need to clarify the mechanics, though. I'm wondering if it makes more sense to apply this change to the 0.11.x branch (which is what is currently deployed in prod) and designate the latest build from the ui-design-2021 branch as the canary. To me, this approach would have several advantages:

1. The canary is the "canary" (right now, the tried-and-true version is the "canary", which is a bit confusing)
2. The "default" UI that you would get with no cookie set is the right default (right now, we would need to do a bit of extra work to get that behavior).

The current approach also has some advantages (e.g., if we add a new value to the chart, handling that is a bit more natural), but I feel like applying this change to the 0.11.x branch is still the better way to go.

Thanks for putting this together!

2021-06-04 16:54 UTC, rokroskar commented
@ableuler I've refactored the deployment template to avoid duplication. I think this will eventually need to be duplicated anyway to allow for different kinds of deployments, but for now I guess it's ok. 

@ciyer certainly, we can do it like that, I think that makes more sense. I'll change the reference branch

2021-06-04 16:57 UTC, ciyer commented
> @ciyer certainly, we can do it like that, I think that makes more sense. I'll change the reference branch

Great. I will add the UI changes to add a banner and set the cookie to this PR after you rebase against the HEAD of 0.11.x.

2021-06-04 19:20 UTC, rokroskar commented
@ciyer this branch is now based off `0.11.x`

2021-06-07 09:05 UTC, rokroskar commented
@ciyer - @ableuler [suggested](https://github.com/SwissDataScienceCenter/renku-ui/pull/1379#discussion_r644817981) we make canary enabled by default - what do you think about this? I think it's better to leave it off, but am open to changing it. It can be switched on for a specific release if needed, but I think it should be intentional.

2021-06-07 09:32 UTC, ciyer approved these changes
This works very well, thanks for putting it together!

2021-06-07 11:07 UTC, ableuler commented
For me the canary is rather a property of a given UI-version than a property of a Renku deployment just like a given version of a microservice might serve two API versions at the same time. But if you both prefer to leave it off per default I can definitely live with that.

2021-06-07 11:10 UTC, rokroskar commented
@ableuler I agree - my point is just that the "steady-state" should be with it off and when the UI makes a release that needs it on, it can be done for that release, with the expectation that it will be toggled off again in the near future.

2021-06-07 11:42 UTC, ciyer commented
> @ableuler I agree - my point is just that the "steady-state" should be with it off and when the UI makes a release that needs it on, it can be done for that release, with the expectation that it will be toggled off again in the near future.

Yes, I think we can merge this as is now. I am getting a PR ready that includes the banner to notify users about the preview. There, I will turn on and configure the canary.

2021-06-07 11:44 UTC, merged