Turn on the preview version banner
SwissDataScienceCenter/renku-ui pull request #1383
Opened 2021-06-07 12:35 UTC by ciyer

Fix #1373

2021-06-08 06:07 UTC, lorenzo-cavazzi commented
Something doesn't work, if I click on the banner the UI crashes with an error on `homeCustomized`
```
TypeError: e.homeCustomized is undefined
```

![Screenshot_20210608_080425](https://user-images.githubusercontent.com/43481553/121131514-351cd700-c830-11eb-80bb-22445d93979a.png)

More in general, would it make sense to add the banner also on the logged user home?
I generally don't even look at the landing page and click directly on login, I'm wondering if other users do the same

2021-06-08 06:08 UTC, lorenzo-cavazzi requested changes
Something doesn't work, if I click on the banner the UI crashes with an error on `homeCustomized`
```
TypeError: e.homeCustomized is undefined
```

![Screenshot_20210608_080425](https://user-images.githubusercontent.com/43481553/121131514-351cd700-c830-11eb-80bb-22445d93979a.png)

More in general, would it make sense to add the banner also on the logged user home?
I generally don't even look at the landing page and click directly on login, I'm wondering if other users do the same

2021-06-08 06:36 UTC, ciyer commented
Can you try it with a private browser session and tell me if you have the same crash?

2021-06-08 06:58 UTC, ciyer commented
> Can you try it with a private browser session and tell me if you have the same crash?

Don't worry about it, I have found out the source of the problem (caching). I will fix it.

2021-06-08 08:28 UTC, ciyer commented
> Something doesn't work, if I click on the banner the UI crashes with an error on `homeCustomized`

I was able to recreate and fix this problem.

> More in general, would it make sense to add the banner also on the logged user home?
> I generally don't even look at the landing page and click directly on login, I'm wondering if other users do the same

I think you are right, but I would prefer to get this released, so that users that are very eager to try out the new UI have a way to do so, and implement your suggestion in another Issue (#1384) / PR.

2021-06-08 08:49 UTC, lorenzo-cavazzi commented on helm-chart/renku-ui/values.yaml
> +    tag: "0.11.11-n045.h8e3df79"
Is this intended?

2021-06-08 08:50 UTC, rokroskar commented
@ciyer could we have a way to get back to the old UI? right now it seems to be a one-way sort of thing?

2021-06-08 09:51 UTC, ciyer commented
> @ciyer could we have a way to get back to the old UI? right now it seems to be a one-way sort of thing?

That will come with #1374. It is not possible to address that in this PR because the changes need to go to different branches.

2021-06-08 09:53 UTC, ciyer commented on helm-chart/renku-ui/values.yaml
> +    tag: "0.11.11-n045.h8e3df79"
That is the current tag of the ui-design-2021 branch. Before we tag the 0.11.13 release, we should tag the ui-design-2021 as `1.0.0-preview1`, and we can use that tag in this slot.

2021-06-10 07:52 UTC, lorenzo-cavazzi approved these changes
:+1:

2021-06-10 13:37 UTC, merged