fix(design): small fixes to the UI design
SwissDataScienceCenter/renku-ui pull request #1388
Opened 2021-06-10 13:51 UTC by vfried

change to text size in help page

![image](https://user-images.githubusercontent.com/42647877/121532409-98109880-c9ff-11eb-9dc4-54f262693de9.png)

fix to menu in environments
![image](https://user-images.githubusercontent.com/42647877/121532656-d73ee980-c9ff-11eb-8fee-10d63ce2f3f0.png)

![image](https://user-images.githubusercontent.com/42647877/121532735-ecb41380-c9ff-11eb-8f25-a812dc98afe0.png)

Pagination now looks like:
![image](https://user-images.githubusercontent.com/42647877/121534162-423cf000-ca01-11eb-9d0f-f2c74f4de807.png)

Warning sign style:
before
![image](https://user-images.githubusercontent.com/42647877/121536169-1d497c80-ca03-11eb-8041-f105b53c1a57.png)

after
![image](https://user-images.githubusercontent.com/42647877/121536029-fc812700-ca02-11eb-9caf-9cdc3453e786.png)

Dataset details table has less spacing 
before
![image](https://user-images.githubusercontent.com/42647877/121536697-9648d400-ca03-11eb-99c7-5601004a8099.png)

after
![image](https://user-images.githubusercontent.com/42647877/121536569-79140580-ca03-11eb-9d08-dc6c0702c72f.png)

Closes #1367

2021-06-14 07:33 UTC, ciyer requested changes
These are very nice fixes. One small correction request on a fix:

- Please bring back the pagination options to go to the beginning/end of the list

I think two of the improvements identified in the issue were missed:

## Dataset

The content should be closer to the titles. This has been fixed in the project/dataset page, but not the global dataset page.

![image](https://user-images.githubusercontent.com/1196411/120693955-ec6cc300-c4a9-11eb-8152-36d63a3a5753.png)

## Mouse Over on Buttons

Cannot read the text on buttons when the mouse is over it.

![image](https://user-images.githubusercontent.com/1196411/120164074-75f66980-c1fa-11eb-8be2-b933028e5299.png)

2021-06-14 07:33 UTC, ciyer commented on client/src/utils/UIComponents.js
> +      hideFirstLastPages={true}
Sorry, I think there was a misunderstanding in the design. The switch to "<" and ">" for previous/next is great, but the first and last page buttons should stay.

```suggestion
      hideFirstLastPages={false}
```

2021-06-21 14:44 UTC, vfried commented
Fixed outlined primary button 
![image](https://user-images.githubusercontent.com/42647877/122780901-94a6c800-d2af-11eb-8294-8280ca5d386c.png)

Pagination fixed --> I misunderstood what you wanted there

Datasets --> no fix needed the component is the same in both places (hard refresh should fix this)

General search
![image](https://user-images.githubusercontent.com/42647877/122781074-c029b280-d2af-11eb-9808-442ea4f14ef9.png)

Project
![image](https://user-images.githubusercontent.com/42647877/122781225-e4858f00-d2af-11eb-82d3-48f4aa6cc97c.png)

2021-06-22 13:01 UTC, vfried commented
Added loader to datasets search/list --> i had removed it accidentally 🤦‍♀️

2021-06-23 07:52 UTC, ciyer approved these changes
👍

2021-06-23 08:08 UTC, merged