feat: launch of environments
SwissDataScienceCenter/renku-ui pull request #1403
Opened 2021-06-24 10:01 UTC by lorenzo-cavazzi

_WIP - the content will be overwritten with a force-push_

/deploy renku=ui-design-2021
fix #1152

2021-06-28 13:22 UTC, ciyer requested changes
We have been waiting for this feature for a while; the experience of using Renku is much nicer now! 

The code is good, I have only a small request to change wording, but I am not 100% what the better wording is.

And a small cosmetic thing -- it looks like there are two spinners on this page, which is a bit weird. Can we have just one spinner?

![image](https://user-images.githubusercontent.com/1196411/123640334-5a927480-d821-11eb-9901-2b7e88b12f8f.png)

2021-06-28 14:11 UTC, lorenzo-cavazzi commented on client/src/notebooks/Notebooks.present.js
> +    message = "Starting Jupyter";
That step is about checking the running pods.
I tried to avoid technical words and I ended up with a somewhat wrong message. What about "Checking running pods?" Or just "Checking pods"?

2021-06-28 14:12 UTC, rokroskar commented on client/src/notebooks/Notebooks.present.js
> +    message = "Starting Jupyter";
"checking running sessions"?

2021-06-28 14:18 UTC, lorenzo-cavazzi commented
I changed the message and removed the double loader. if you think `Checking pods` is not a good definition, feel free to suggest something else (or directly change the text in the code on this PR)

![Screenshot_20210628_161128](https://user-images.githubusercontent.com/43481553/123652220-646da500-d82c-11eb-9876-6e604e3504b4.png)

![Screenshot_20210628_161142](https://user-images.githubusercontent.com/43481553/123652232-66cfff00-d82c-11eb-99ba-114702258789.png)

2021-06-28 15:20 UTC, lorenzo-cavazzi commented on client/src/notebooks/Notebooks.present.js
> +    message = "Starting Jupyter";
That sounds reasonable

2021-06-29 07:26 UTC, ciyer approved these changes
Woohoo! 🎉

2021-06-30 14:38 UTC, ciyer commented
This was included in #1385.

2021-06-30 14:38 UTC, closed without merging