feat: add link to registry images
SwissDataScienceCenter/renku-ui pull request #1404
Opened 2021-06-24 16:43 UTC by lorenzo-cavazzi

This adds a link on the image session setting to the container registry page in GitLab.

![image](https://user-images.githubusercontent.com/43481553/123301477-fb301e00-d51b-11eb-9759-317f8c285669.png)

2021-06-28 11:29 UTC, ciyer requested changes
Thanks for putting this together so quickly! It makes it much easier to find an image.

While testing, I identified an an improvement that would be good to make; it can be done in this issue, if easy, otherwise, we should create a new issue:

If there are advanced settings set for this project, the advanced settings section should be open by default.

2021-06-28 11:29 UTC, ciyer commented on client/src/project/settings/ProjectSettings.present.js
> +      <ExternalLink role="link" title="available images for this project" url={imagesUrl} />.
```suggestion
      A URL of a RenkuLab-compatible Docker image. For an image from this project, {" "}
       consult  <ExternalLink role="link" title="the list of images for this project" url={imagesUrl} />.
```

2021-06-28 14:07 UTC, lorenzo-cavazzi commented
The suggested change for the images is actually very easy to implement (I initially implemented that, then removed it later).
Both points have been addressed in the latest commit.

2021-06-29 07:11 UTC, ciyer approved these changes
👍

2021-07-01 07:37 UTC, merged