fix(migration): UX improvements to renku version
SwissDataScienceCenter/renku-ui pull request #1422
Opened 2021-07-13 09:23 UTC by vfried

Renku version status changed to behave like this...

https://github.com/SwissDataScienceCenter/renku-ui/issues/1233#issuecomment-834159960

Closes #1233

2021-07-14 14:38 UTC, ciyer reviewed
Code looks very good. It is much easier to follow! I still need to test, and will do that when I am back.

2021-11-09 23:53 UTC, rokroskar commented
It looks like this logic doesn't quite work correctly? See https://renku-ci-ui-1422.dev.renku.ch/projects/rokroskar/py090/overview/status which uses a template from master of the templates repo from 2 months ago and it should therefore be updated. The response from the service is 

```json
{"result": {"template_source": "https://github.com/SwissDataScienceCenter/renku-project-template", "latest_version": "0.16.2", "template_id": "python-minimal", "latest_template_version": "7598ddf356e28c80747f93ce97a55a69082b5cf1", "automated_template_update": false, "docker_update_possible": false, "project_version": "0.16.2", "template_ref": "master", "current_template_version": "36d1ab1b1a2996c9532095043cdd8ce6779c38c0", "migration_required": false, "project_supported": true, "template_update_possible": true}}
```

2021-12-07 14:32 UTC, ciyer commented
**From Virginia**

Renku version status changed to behave like this...

https://github.com/SwissDataScienceCenter/renku-ui/issues/1233#issuecomment-834159960

Logic has been split into three parts:
- Template
- RenkuLab compatibility (metadata)
- Renku Version (docker file related)

Since logic has been split the code was also split into 3 files.  Each file has scenarios that are then used in a switch/case to decide what will be displayed. Errors, loading, etc are not part of this scenarios.

### ProjectVersionStatus

RENKU_VERSION_SCENARIOS = {
  PROJECT_NOT_SUPPORTED: "PROJECT_NOT_SUPPORTED",
  RENKU_UP_TO_DATE: "RENKU_UP_TO_DATE",
  NEW_VERSION_NOT_REQUIRED_AUTO: "NEW_VERSION_NOT_REQUIRED_AUTO", --> new version not required automatic update possible
  NEW_VERSION_REQUIRED_AUTO: "NEW_VERSION_REQUIRED_AUTO", --> new version required automatic update possible
  NEW_VERSION_NOT_REQUIRED_MANUAL: "NEW_VERSION_NOT_REQUIRED_MANUAL", --> new version not required automatic update not possible
  NEW_VERSION_REQUIRED_MANUAL: "NEW_VERSION_REQUIRED_MANUAL" --> new version required automatic update not possible
};


### RenkuLabCompatibilityStatus

RENKULAB_COMPATIBILITY_SCENARIOS = {
  PROJECT_NOT_SUPPORTED: "PROJECT_NOT_SUPPORTED", 
  RENKULAB_UP_TO_DATE: "RENKULAB_UP_TO_DATE",
  NEW_VERSION_SHOW_BUTTON: "NEW_VERSION_SHOW_BUTTON", --> update needed and will be done with renku version
  NEW_VERSION_NO_BUTTON: "NEW_VERSION_NO_BUTTON" --> update needed but an update in renku version not needed, button to update only metadata will be displayed
};

### TemplateVersionStatus

TEMPLATE_VERSION_SCENARIOS = {
  PROJECT_NOT_SUPPORTED: "PROJECT_NOT_SUPPORTED",
  TEMPLATE_NOT_VERSIONED: "TEMPLATE_NOT_VERSIONED", --> template can't be updated
  TEMPLATE_UP_TO_DATE: "TEMPLATE_UP_TO_DATE", --> no update needed
  NEW_TEMPLATE_AUTO: "NEW_TEMPLATE_AUTO",  --> update needed automatic update posible
  NEW_TEMPLATE_MANUAL: "NEW_TEMPLATE_MANUAL" --> update needed automatic update not posible
};


Testing for messages can be done doing something like this.... 

change this
![image](https://user-images.githubusercontent.com/42647877/125430710-357f528a-4d84-454e-88cb-c5f10d06aa7e.png)

for
![image](https://user-images.githubusercontent.com/42647877/125430808-e051980a-95ab-4a6b-8101-910404bc0259.png)

Real testing coming soon :) 

Run telepresence on: https://renku-ci-rp-2122.dev.renku.ch 
A small temporary change on the telepresence file is required to do this on lines 80 and 81 `DEV_NAMESPACE=renku-ci-rp-${PR}`  ` SERVICE_NAME=renku-ci-rp-${PR}-ui`

2021-12-08 16:29 UTC, andre-code commented on client/src/project/Project.js
>      projectData.then(data => {
Once `data` is no longer used I would suggest removing it and instead of `.then` use  `const projectData = await this.projectCoordinator.fetchProject(this.props.client, pathComponents.projectPathWithNamespace);`

2021-12-08 16:49 UTC, andre-code commented
Great feature and also refactoring the code for the project model. 👏 
I suggest adding unit tests especially for functions in the MigrationUtils file.
Some projects to test with the expected behavior in the project description (as we did for the project overview suggestion) would be very useful for testing.

2021-12-14 12:41 UTC, ciyer commented on client/src/model/RenkuModels.js
> +      available: { [Prop.INITIAL]: null, [Prop.MANDATORY]: true },
I do not completely understand what this is used for, so I removed it. It does not seem to cause any problems.

2021-12-14 12:42 UTC, ciyer commented
> Great feature and also refactoring the code for the project model. 👏
I suggest adding unit tests especially for functions in the MigrationUtils file.
Some projects to test for all cases with the expected behavior in the project description (as we did for the project overview suggestion) would be very useful for testing.

Very good suggestions! I have done both of these.

2021-12-15 14:14 UTC, lorenzo-cavazzi requested changes
The code looks good!
Would it make sense to add a link to the external template repo in the "Template Version --> Template" URL? It would be the props `template_status.template_source`.

![Screenshot_20211215_151214](https://user-images.githubusercontent.com/43481553/146202166-a182de45-ddba-4ae6-9ee6-d97b99620790.png)

********

I've found just a couple of confusing cases, not 100% sure if it's the UI using the wrong field from the core service or if a wrong value is provided by the service.

This is an example, created from an old template
URL: https://github.com/SwissDataScienceCenter/renku-project-template
REF: 0.1.18

The `Renku version` field says the project is at `1.0.0`, the latest version is the same, but the user can click on update.
![Screenshot_20211215_150228](https://user-images.githubusercontent.com/43481553/146200750-36fae0f5-c571-428c-b158-d765ad1613d5.png)

Clicking on it actually makes it disappear, and the change seems to be a bump from dockerfile version 0.14.1 to 1.0.0


![Screenshot_20211215_150515](https://user-images.githubusercontent.com/43481553/146200891-6d23e2f3-1e96-4897-84f9-3c8a709a5701.png)

Is it possible that the intended field for `Project Renku Version` is the `dockerfile_renku_version` value?

In this project (https://renku-ci-ui-1422.dev.renku.ch/projects/lorenzo.cavazzi.tech/1-0-0-dev/overview/status ), forked by one of the examples, I see a similar issue.  The project version seems to be showing the template version. From the API, it seems that `dockerfle_renku_version` would be the right field to show

![Screenshot_20211215_150624](https://user-images.githubusercontent.com/43481553/146201528-74bedda0-0887-4cad-8dae-65eabc2a7297.png)

2021-12-16 14:29 UTC, ciyer commented
Good suggestions! I have done what I can to solve these problems. 

1. If the template_source is a link, show it as one + if the there is a template_ref, show it:

![image](https://user-images.githubusercontent.com/1196411/146390260-257daa0f-ca7e-4815-a4a5-ccdb75ba14c0.png)

![image](https://user-images.githubusercontent.com/1196411/146390428-e228854d-19ef-4ace-b0c9-24f461d7a068.png)


Compare with this project where the template_source is just a string and there is no template_ref:

![image](https://user-images.githubusercontent.com/1196411/146390374-0a7ff849-27f3-4bdb-b66a-8912df2558c9.png)

2021-12-16 17:06 UTC, lorenzo-cavazzi approved these changes
Great to see this big PR ready! :tada: 
I added a very minor comment, feel free to ignore it.

In general, I'm wondering if we should enforce more the outdated renku version, since it may create problems in sessions :thinking: 
Anyway, this is something to think about in a separate issue.
![Screenshot_20211216_173441](https://user-images.githubusercontent.com/43481553/146416461-d66076cd-cdba-4e37-947b-596b655a32d3.png)

2021-12-16 17:06 UTC, lorenzo-cavazzi commented on client/src/project/status/TemplateVersionStatus.present.js
> +  return <a href={template_source}>{lastComponent}</a>;
Would it make sense to use the `ExternalLink` component here to keep the behavior aligned with the other links? E.G. opening in a new tab

2021-12-16 17:37 UTC, merged