feat(dataset): ui to add and display dataset marquee image in projects
SwissDataScienceCenter/renku-ui pull request #1444
Opened 2021-08-09 14:22 UTC by vfried

Inside form
![image](https://user-images.githubusercontent.com/42647877/128721803-2381116f-40e1-4e99-b1d8-cf81c2e5ffec.png)

Edit mode (for now it's non edit because something is missing in the backend)
![image](https://user-images.githubusercontent.com/42647877/128721957-0082cdd3-9fa6-4020-93e7-06b5f592afa7.png)

Dataset inside project
![image](https://user-images.githubusercontent.com/42647877/128721924-6a9fffce-af3f-4c9c-be3c-2c70ada4eded.png)

Project List
![image](https://user-images.githubusercontent.com/42647877/128721884-59103884-2255-44fc-a9bb-bc3ab3d0b8be.png)

/deploy renku=ui-design-2021

Closes #1142

2021-08-17 15:02 UTC, ciyer requested changes
The screenshot look very good, and the code is good for the most part as well! 

I am still trying to get the feature deployed, but I have some comments on the code in the meantime. I will have more comments once I can actually test.

2021-08-17 15:02 UTC, ciyer commented on client/src/project/datasets/change/DatasetChange.container.js
> +    if (image && image.selected !== -1
I would prefer to have early return, I think the logic would be clearer. E.g., 
```
if (image == null) return images;
if (image.selected !== -1) return images;
...
```

2021-08-18 12:42 UTC, ciyer commented
I have now tested creation and viewing (editing does not work because the backend does not support it). It works well! I think we need to have a strategy for cropping images, though. Here is an example:

![image](https://user-images.githubusercontent.com/1196411/129899805-a1999ac9-e041-4785-befd-c4e62d5d61a0.png)


![image](https://user-images.githubusercontent.com/1196411/129899847-6a025eb8-b5a4-4d7d-a892-f6824d96a858.png)

2021-08-19 12:35 UTC, vfried commented on client/src/api-client/dataset.js
> +      if (response.data.result && response.data.result.datasets.length > 0) {
I think it's not necessary, i just removed it.

2021-08-19 12:38 UTC, vfried commented on client/src/api-client/dataset.js
> +    };
Done

2021-08-19 12:49 UTC, vfried commented on client/src/api-client/dataset.js
> +          dataset.mediaContent = git_url.substring(0, git_url.length - 4) + "/-/raw/master/"
I extracted the method, the check for length and not null is necessary because images could be null or empty for some reason.

I called it mediaContent because it gets mapped to mediaContent after. I could do an issue to rename all this to marqueeImage but i thin i should do this separate since it's in other places as well.

2021-08-19 12:50 UTC, vfried commented on client/src/project/datasets/change/DatasetChange.container.js
> +  const getDatasetImages = async (image, handlers) => {
You are right, the logic behind this name was because I need the dataset image id to fill in the field but I just renamed it to uploadDatasetImages

2021-08-19 12:51 UTC, vfried commented on client/src/project/datasets/change/DatasetChange.container.js
> +    if (image && image.selected !== -1
Done

2021-08-24 06:33 UTC, ciyer approved these changes
This will make datasets more visual. Now we just need to support edit. :)

2021-08-24 06:34 UTC, merged