feat: Get minimal project data for featured projects
SwissDataScienceCenter/renku-ui pull request #1553
Opened 2021-11-10 12:11 UTC by andre-code

2021-11-12 15:29 UTC, ciyer requested changes
With the first change and now this, the UI starts much quicker! 🎉 This works well for me, and I tested both the quick nav and forking, and everything seems to work as before, even though we are retrieving less data.

I just have one question about a code change, but otherwise, once the acceptance tests pass, I think this is ready to merge.

2021-11-12 15:29 UTC, ciyer commented on client/src/model/RenkuModels.js
> +      fetching: { [Prop.INITIAL]: false, [Prop.MANDATORY]: true },
Good catch. That must have slipped in an earlier PR!

2021-11-12 15:29 UTC, ciyer commented on client/src/project/shared/Projects.state.js
> +    let params = { query: "last_activity_at", per_page: 100 };
Is there a reason to switch from `const` to `let` for this variable?

2021-11-16 14:49 UTC, andre-code commented on client/src/project/shared/Projects.state.js
> +    let params = { query: "last_activity_at", per_page: 100 };
thanks for noticing, it was a mistake, it is not necessary to change the type of variable.

2021-11-16 15:56 UTC, ciyer requested changes
Code looks good!

But, when testing I came across a problem. If I use the quick nav to search for a project:

![image](https://user-images.githubusercontent.com/1196411/142019635-0a7c44c4-2774-40af-9d5d-2c29868641ff.png)

And then try to navigate to the project, I get this.

![image](https://user-images.githubusercontent.com/1196411/142019678-cbbee927-9608-4f40-b2df-6714d8656d69.png)

2021-11-17 08:03 UTC, ciyer approved these changes
That fixed it!

2021-11-24 10:10 UTC, ciyer approved these changes
🎉

2021-11-24 12:21 UTC, merged