feat: Add Showdown extension to render LaTeX math (#1552)
SwissDataScienceCenter/renku-ui pull request #1557
Opened 2021-11-11 10:02 UTC by andre-code

Closes #1552

2021-11-11 10:43 UTC, lorenzo-cavazzi commented
I think you forgot to push the updated package.json file containing the reference to the `showdown-katex` library

2021-11-12 14:47 UTC, lorenzo-cavazzi requested changes
Very nice! I added a couple of comments inline.

Do you think it's feasible to add a test to verify if a text formula is correctly translated into a visual formula?

P.S. When you make a PR, try to include a description of what the PR implements, and possibly a sample project or a description on how to test (unless it's a trivial change or something not testable).

2021-11-12 14:47 UTC, lorenzo-cavazzi commented on client/src/utils/HelperFunctions.js
> +// eslint-disable-next-line
Since `katex` is not a "real" word, our spellcheck is failing. But since it's a valid word for us, and you use it in different files, you could add it to the exception list in the `skipWords` section in the  "client/.eslintrc.json" file. You can then remove the `eslint-disable-next-line` command -- it should be used as a last resort

2021-11-12 14:47 UTC, lorenzo-cavazzi commented on client/src/utils/HelperFunctions.js
> +  // eslint-disable-next-line
see previous comment

2021-11-12 14:47 UTC, lorenzo-cavazzi commented on client/src/utils/HelperFunctions.js
> +      // eslint-disable-next-line
see previous comment

2021-11-12 14:47 UTC, lorenzo-cavazzi commented on client/src/utils/HelperFunctions.js
> +        errorColor: "#e50202",
We should try to use the renku colors when possible (see the file client/src/styles/bootstrap/_custom_bootstrap_variables.scss).
Besides, what are `throwOnError` and `errorColor` doing? Do you have an example of an error underlined in red?

2021-11-12 15:09 UTC, ciyer requested changes
This is a nice improvement. :tada: The showdown-latex seems to be giving us a bit of problems though. I added a couple of requests for comments in addition to Lorenzo's.

2021-11-12 15:09 UTC, ciyer commented on client/package.json
> +    "showdown-katex": "0.6.0",
I think there should be a comment here explaining that version 0.8.0 breaks tests so we do not accidentally update the library.

2021-11-12 15:09 UTC, ciyer commented on client/src/utils/HelperFunctions.js
> +import showdownKatex from "showdown-katex";
I think there should be a little comment explaining that version 0.8.0 causes the tests to break.

2021-11-15 08:54 UTC, lorenzo-cavazzi submitted a review, later dismissed
Very nice solution!

2021-11-15 10:35 UTC, ciyer approved these changes
👍

2021-11-16 15:46 UTC, ciyer approved these changes
Great fixes!

2021-11-17 16:38 UTC, merged