Hoist project state to global model
SwissDataScienceCenter/renku-ui pull request #1568
Opened 2021-11-16 09:59 UTC by ciyer

wip

Fix #1183

/deploy renku=448c938d4d4a4b263857fba8ff2d402f72ad9fba

2021-11-24 10:56 UTC, lorenzo-cavazzi requested changes
This PR is brilliant! It's taking me some time to review, I can't image the effort required to make all the changes :grin: 

I identified a couple of leftovers, i.e. properties still read from the old store (apart from the migrations data that will be moved in another PR). I left some comments inline.

2021-11-24 10:56 UTC, lorenzo-cavazzi commented on client/src/project/Project.state.js
> +  setProjectData(data, statistics = false) {
this shouldn't be necessary anymore since all the relevant data are now in the main store on the `project.medatata` object

2021-11-24 10:56 UTC, lorenzo-cavazzi commented on client/src/project/Project.state.js
> +  fetchProjectDatasetsFromKg(client) { //from KG
this seems to be a leftover since the same function has been moved to the newer coordinator

2021-11-24 10:56 UTC, lorenzo-cavazzi commented on client/src/project/Project.state.js
> +  fetchProjectDatasets(client, forceReFetch) {
leftover, same as above (already moved to the newer coordinator)

2021-11-24 10:56 UTC, lorenzo-cavazzi commented on client/src/project/Project.present.js
> +        project={projectCoordinator.get()}
This seems a bit excessive since the Notebook component is using only the commits data. I would change this to `commits={projectCoordinator.get("commits")}` and adjust the `StartNotebookServer` component on `propsToChildProps` on `this.props.project`.

P.S. I didn't check if the commits are already coming as a property like the branches. In that case it doesn't require the `projectCoordinator.get`

2021-11-24 16:02 UTC, ciyer commented on client/src/project/Project.state.js
> +      _transition: data
Yes, I added it as part of the transition process, but then forgot to remove it. Good catch!

2021-11-25 13:52 UTC, lorenzo-cavazzi requested changes
I have just a tiny request before merging. Otherwise, it looks ready to me!

2021-11-25 13:52 UTC, lorenzo-cavazzi commented on client/src/notebooks/Notebooks.container.js
> +        fetched: this.props.commits.fetched,
Great! Would you mind adding the `commits` to the JSDocs as a `@param`?
I think it's the only new parameter in this component

2021-11-25 16:07 UTC, lorenzo-cavazzi approved these changes
:tada: :rocket:

2021-11-26 15:31 UTC, merged