feat: Add project overview suggestions (#1512)
SwissDataScienceCenter/renku-ui pull request #1578
Opened 2021-11-18 15:11 UTC by andre-code

Show suggestions in the project overview
* Show readme suggestion if README.md file has no more than 1 commit.
* Show suggestion to create a dataset if the project has no datasets.

Closes #1512

2021-11-22 09:28 UTC, ciyer requested changes
This looks good, and I tried it out on a couple of projects.

I have one name change in the code to suggest, and, after actually using the feature, I want to make some changes to the wording of the user notifications.

2021-11-22 09:28 UTC, ciyer commented on client/src/project/Project.present.js
> +        so here are some suggestions for getting started. <br/>
The wording here is exactly as in the design, but after actually using the feature, I want to make a change:

```suggestion
        <strong>Welcome</strong> to your new Renku project! It looks like this project is just getting started, so here are some suggestions to help you. <br/>
```

2021-11-22 09:28 UTC, ciyer commented on client/src/project/Project.present.js
> +        <strong>Add README.md</strong>
The wording here is exactly as in the design, but after actually using the feature, I want to make a change:

```suggestion
        <strong>Edit README.md</strong>
```

2021-11-22 16:00 UTC, ciyer requested changes
This is looking very good, and having tests is great! 🙌 

I have a few suggestions to help modularity and reuse existing components.

2021-11-22 16:00 UTC, ciyer commented on client/src/project/Project.present.js
> +    : <li><p style={{ fontSize: "14px" }}>
See comment above about font size.

2021-11-22 16:00 UTC, ciyer commented on client/src/project/Project.present.js
> +      <a href="https://zenodo.org/" className="mx-1" target="_blank" rel="noreferrer noopener">
This is nice! It would be good to use the `<ExternalLink role="text">...` component for this.

2021-11-22 16:00 UTC, ciyer commented on client/src/project/Project.present.js
> +      <a href="https://dataverse.harvard.edu/" className="mx-1" target="_blank" rel="noreferrer noopener">
Comment on using `ExternalLink` applies here as well.

2021-11-24 09:30 UTC, ciyer requested changes
This is now very close to being ready!

While testing, I found two cases with problems with the suggestions box.

1. README has been modified, but I still get the suggestion to modify the README

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/1196411/143210566-d32bffa0-26e3-4939-9809-bd18dd551857.png">

(I think I found the code where this bug is caused and suggested a fix)

2. User does not have write access to project, but suggestions still appear

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/1196411/143211448-bb99bb1e-6bbd-4d6a-9153-1a493439c8ea.png">

We should only show the suggestions if the user is the maintainer of the project. There are examples of testing this in `Project.js` if you look for `accessLevel >= ACCESS_LEVELS.MAINTAINER`

2021-11-24 09:30 UTC, ciyer commented on client/src/project/Project.present.js
> +  const cantTotalCommits = props.model?.get("project.commits.list")?.length ?? 0;
```suggestion
  const countTotalCommits = props.model?.get("project.commits.list")?.length ?? 0;
```

2021-11-24 09:30 UTC, ciyer commented on client/src/project/Project.present.js
> +  if (cantTotalCommits > 4 || (countCommitsReadme > 1 && hasDatasets)) return "";
```suggestion
  if (countTotalCommits > 4 || (countCommitsReadme > 1 && hasDatasets)) return "";
```

2021-11-24 09:30 UTC, ciyer commented on client/src/project/Project.present.js
> +  const suggestionReadme = countCommitsReadme > 1 ? null
This should be > 0, I think.

```suggestion
  const suggestionReadme = countCommitsReadme > 0 ? null
```

2021-11-24 16:28 UTC, andre-code commented on client/src/project/Project.present.js
> +  const suggestionReadme = countCommitsReadme > 1 ? null
Thanks for the revision, it should be 1 because the automatic initial commit should not be included.
The reason the suggestion component was not updating after a new commit is because it was being calculated when the project was loaded, I have modified it to calculate the number of readme commits once the total amount of commits in the project changes.

2021-11-26 14:47 UTC, ciyer commented on client/src/project/Project.present.js
> +  const suggestionReadme = countCommitsReadme > 1 ? null
Yes, you are correct!

2021-11-26 15:23 UTC, ciyer requested changes
This is coming together!

The behavior on projects where I am not a maintainer is now correct: I do not see suggestions. 

But the behavior on projects where I have updated the readme still isn't correct. I think the logic to detect if the readme has been modified needs to be looked at again.

See https://renku-ci-ui-1578.dev.renku.ch/projects/cramakri/mathjax

I can help put together a test case if you are having difficulties recreating the issue.

2021-11-26 15:23 UTC, ciyer commented on client/src/project/Project.present.js
> +  if (isLoadingData || countTotalCommits > 4 || (countCommitsReadme > 1 && hasDatasets)) return "";
I think it would be better to return null here. There is no need to add an empty string to the DOM.

```suggestion
  if (isLoadingData || countTotalCommits > 4 || (countCommitsReadme > 1 && hasDatasets)) return null;
```

2021-11-26 15:23 UTC, ciyer commented on client/src/project/Project.present.js
> +  const projectSuggestActions = props.visibility.accessLevel < ACCESS_LEVELS.MAINTAINER ? ""
Nice, this does fix the problem, and I do not see the suggestions when I am not maintainer. But, I think code-wise, it would be better to 
1. Make this check in the ProjectSuggestActions component
2. Return `null` if there is nothing to show (rather than an empty string).

2021-11-26 15:46 UTC, ksanao commented on client/src/project/Project.present.js
> +        so here are some suggestions for getting started. <br/>
We have been reviewing nudging users towards dataset creation and it turns out that this does NOT fit all Renku use cases, for example:

- Omero users cannot create Renku datasets (we do not support this yet for streaming data)
- There is no dataset in projects that generate data outputs without using input files (simulation etc.) - we do not yet support workflow output asa dataset

2021-11-29 07:55 UTC, ciyer commented on client/src/project/Project.present.js
> +        so here are some suggestions for getting started. <br/>
Thanks for that feedback; what you are saying makes sense. 

I think that is support to our approach of _suggesting_, but not requiring, that users make datasets. Once it is clear that the project is underway (has more than 4 commits), we do not show the messages anymore, since we assume that users have made an informed decision about whether or not they want to do the things we suggest.

2021-11-30 14:02 UTC, andre-code commented on client/src/project/Project.present.js
> +  if (isLoadingData || countTotalCommits > 4 || (countCommitsReadme > 1 && hasDatasets)) return "";
sure, updated to return null

2021-11-30 14:03 UTC, andre-code commented on client/src/project/Project.present.js
> +  const projectSuggestActions = props.visibility.accessLevel < ACCESS_LEVELS.MAINTAINER ? ""
agree, I moved the validation to the ProjectSuggestActions component

2021-12-01 15:48 UTC, andre-code commented
Added validation to show readme suggestion if readme commit is the initial commit when there is only one readme commit

2021-12-02 15:02 UTC, andre-code commented
✨  Included new styles: 


![Screenshot 2021-12-02 at 15 39 14](https://user-images.githubusercontent.com/43388408/144446727-ce8662d1-3fbb-4cdb-8c86-137282c53c65.png)

![Screenshot 2021-12-02 at 15 39 32](https://user-images.githubusercontent.com/43388408/144446836-b2465c47-ab26-484a-93a1-b2f8f73e3a36.png)


![Screenshot 2021-12-02 at 15 39 58](https://user-images.githubusercontent.com/43388408/144446885-74884095-ccf3-4331-867b-602f5ca813e1.png)

2021-12-03 12:28 UTC, ciyer approved these changes
Feature works great! And tests pass! Let's merge it! 🎉

I know it took a bit of time to get here, but the feature is now robust and handles many situations well, so I think it was worth it.

2021-12-03 13:43 UTC, merged