feat: Validate URL before using it  in iframe (1572)
SwissDataScienceCenter/renku-ui pull request #1584
Opened 2021-11-24 08:28 UTC by andre-code

Added endpoint in serverui to validate if URL can be used in an iframe.
This validation is used in the Collaboration component (Issues and Merge requests).

/deploy

2021-11-25 12:39 UTC, lorenzo-cavazzi requested changes
This will be a very useful feature!

Unfortunately, I fear using the `X-Frame-Options` header won't work in our case. The reference issue #1572 suggests using `content-security-policy` instead, and that seems to be a more reliable way.
Giving a look at the various options, it may be a bit more complicated https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

As an example, in the response from the API invoked in the PR deployment, I got the following data:

```
x-frame-options:'DENY'
content-security-policy:"frame-ancestors 'self' https://dev.renku.ch https://renku-ci-ui-1584.dev.renku.ch"
```

This means it's embeddable, even if the API response says otherwise.
You can verify it by running `PR=1579 ./run-telepresence.sh` from the master branch of renku-ui and accessing a collaboration page.

2021-11-25 12:39 UTC, lorenzo-cavazzi commented on server/src/routes/apis.ts
> +    };
I think returning just `true/false` would be enough. But you added just a little extra information, nothing against keeping it as you already did :slightly_smiling_face:

2021-11-25 12:39 UTC, lorenzo-cavazzi commented on server/src/routes/apis.ts
> +        data.error = `X-Frame-Options: ${requestExternalURL?.headers.get("X-Frame-Options")}`;
I fear this is not the right way to test if the page is embeddable in an iframe. You should check the `content-security-policy` header as suggested in the reference issue #1572

2021-11-25 12:59 UTC, ciyer commented on server/src/routes/apis.ts
> +  app.get(prefix + "/check-url/:url", async (req, res) => {
My vote is for `allows-iframe`

2021-11-25 13:01 UTC, ciyer commented on server/src/routes/apis.ts
> +    };
I also think json response here is nice -- it will allow us to extend the information if necessary (not sure what, but maybe we want to pass the content of the CSP to the browser).

2021-11-29 16:28 UTC, andre-code commented on server/src/routes/apis.ts
> +  app.get(prefix + "/check-url/:url", async (req, res) => {
Great, it was updated to `allows-iframe`

2021-11-29 16:30 UTC, andre-code commented on server/src/routes/apis.ts
> +        data.error = `X-Frame-Options: ${requestExternalURL?.headers.get("X-Frame-Options")}`;
sure, the logic has been updated to use the content-security-policy header to check if the URL can be embedded in an iframe

2021-11-30 15:00 UTC, ciyer requested changes
This is starting to look very good! I have a couple of minor whitespace issues to keep git happy.

I am not sure I understand the logic of some of the tests. I would have assumed that validateCSP return false in a few example, but they are true. Maybe you could explain the reason why embedding should be allowed in those cases?

2021-12-01 08:32 UTC, andre-code commented on server/tests/utils/url.test.ts
> +    expect(validateCSP(url, `frame-ancestors ${originUrl.origin}`).isIframeValid).toBe(true);
yes, because the URL is the URL (https://www.example.org) to which we are making the request of the headers, and their headers indicate in the iframe-ancestor from which URL allows embedding in iframes(https://dev.renku.ch), is these test we add these URL and compare them with the URL of our server(config.server.url) that is from where the request is finally going to be made.

2021-12-01 13:49 UTC, lorenzo-cavazzi requested changes
Great PR! It seems to work as expected, and the multiple tests are great for understanding how it works (altough I'm still a bit confused by the part where you replace `www`... but it works)

I added some comments, but almost all of them are just tiny changes on cosmetics rather than real problems in the code. So it's almost ready to ship :smile:

2021-12-01 13:49 UTC, lorenzo-cavazzi commented on server/src/routes/apis.ts
> +        const validation = validateCSP(req?.params?.url, requestExternalURL?.headers.get("content-security-policy"));
```suggestion
        const validation = validateCSP(req.params.url, requestExternalURL.headers.get("content-security-policy"));
```

2021-12-01 13:49 UTC, lorenzo-cavazzi commented on server/src/routes/apis.ts
> +function registerApiRoutes(app: express.Application, prefix: string, authenticator: Authenticator): void {
Ah, thanks for spotting the typo!

2021-12-01 13:49 UTC, lorenzo-cavazzi commented on server/src/utils/url.ts
> +import { parse } from "tldts";
This is really just cosmetics: I tried to keep the import from libraries separated by the import from local files, so we can immediately identify what we defined locally. Let's just add a blank line:

```suggestion
import { parse } from "tldts";

import config from "../config";
import { CheckURLResponse } from "../routes/apis.interfaces";
```

2021-12-01 13:49 UTC, lorenzo-cavazzi commented on server/src/routes/apis.ts
> +import fetch from "cross-fetch";
Cosmetics only: let's move the import from an external library together with the others (after line 20 `import { createProxyMiddleware } from "http-proxy-middleware";`)

2021-12-01 13:49 UTC, lorenzo-cavazzi commented on server/src/utils/url.ts
> +    const originUrl = new URL(config.server.url);
Technically, you need the UI client url instead of the UI server URL. This may be a problem in cases where the UI server is reachable from `https://myrenkulab.io` and the UI client from `https://ui.myrenkulab.io`.
I think it's fine if we ignore that case since it's not really a thing, but please add a note to clarify it, maybe something like:
```
// We should use the UI client URL since it will be embedded there and the URL may be different
```

2021-12-01 13:49 UTC, lorenzo-cavazzi commented on server/tests/utils/url.test.ts
> +    expect(validateCSP(url, `frame-ancestors ${originUrl.origin}`).isIframeValid).toBe(true);
It's a bit confusing, but that's meant to be the external gitlab URL.
I think we can use a more realistic URL instead of example.com to make it more explicit.
I suggest using:
```
https://gitlab.com/myNamespace/myProject/-/issues
```
(that should be set at line 25))

2021-12-01 13:49 UTC, lorenzo-cavazzi commented on server/tests/utils/url.test.ts
> +    config.server.url = "https://test.dev.renku.ch";
The `validateCSP` function uses it. Technically it's not 100% correct since we should use the UI client URL instead of the UI server -- it may be a problem if someone has different origins for client and server, like:
UI server: https://myrenkulab.io
UI client from https://ui.myrenkulab.io

I don't think this is expected. We may still make it more robust by either:
- Including the UI client URL in the config (through the values), or
- Adding the current UI URL as a second parameter to the function, and use that instead of config.server.url

Between the 2, I would go for the second

2021-12-02 15:26 UTC, andre-code commented on server/tests/utils/url.test.ts
> +    expect(validateCSP(url, `frame-ancestors ${originUrl.origin}`).isIframeValid).toBe(true);
Thx, great suggestion to make more clean the example, I updated the test

2021-12-02 15:27 UTC, andre-code commented on server/tests/utils/url.test.ts
> +    config.server.url = "https://test.dev.renku.ch";
We decided to leave this server url, we add the note to update it when the client url is different from the server url

2021-12-02 15:47 UTC, andre-code commented on server/tests/utils/url.test.ts
> +    expect(validateCSP(url, `frame-ancestors *.renku.ch`).isIframeValid).toBe(true);
I updated the test to make it more clear with a  more realistic example

2021-12-02 15:53 UTC, andre-code commented on server/src/utils/url.ts
> +    const originUrl = new URL(config.server.url);
A comment has been added to remember to update the url once it is different from the server url.

2021-12-02 16:22 UTC, andre-code commented on client/src/collaboration/lists/CollaborationList.container.js
> +  }, []); // eslint-disable-line
if we remove the dependencies or add props as dependency or onIFrameLoad function it will be executed n times causing repeated calls to the API even if the iframe URL has not changed, so we can add the dependency to the iframe URL and the comment to disable the warning

As I understand, the onIFrameLoad function triggers the hook because this function is from hook useState used in the CollaborationList component which is rendered every time the props change.

2021-12-03 09:03 UTC, ciyer commented
I tested this, and it works very well! 🤩 

![image](https://user-images.githubusercontent.com/1196411/144575338-12b7f64b-0102-496f-b1b6-a7188e6de56b.png)

2021-12-03 16:42 UTC, lorenzo-cavazzi requested changes
Great! I have a final _tiny_ change request on the `test-client.js` file. You added the response for `isValidUrlForIframe` at the end, but it would be nice to keep it coherent with the other mocked responses for the other client functions (see inline).

Otherwise, great PR! Iframes and security policies are a beast :grin:  
Can't wait to see this PR merged! :rocket:

2021-12-03 16:42 UTC, lorenzo-cavazzi commented on client/src/api-client/test-client.js
> +client.isValidUrlForIframe = () => true;
Could you move this above, together with the other methods with a mocked response, like `getTemplatesManifest` and the others?.
Lines 168-174 already take care of making a valid function response out of it (response also comes as a Promise)

2021-12-03 16:42 UTC, lorenzo-cavazzi commented on server/tests/utils/url.test.ts
> +    config.server.url = "https://test.dev.renku.ch";
This is the same as the previous one. Is this intended or is it a typo?

2021-12-03 16:42 UTC, lorenzo-cavazzi commented on server/tests/utils/url.test.ts
> +    config.server.url = "https://test.dev.renku.ch";
Ok I see that one test is on `http` and the other `https`.
Should we remove this line since the value for `config.server.url` stays the same?

2021-12-06 09:48 UTC, lorenzo-cavazzi approved these changes
:rocket:

2021-12-06 10:07 UTC, lorenzo-cavazzi approved these changes

2021-12-06 11:31 UTC, ciyer approved these changes

2021-12-06 12:57 UTC, merged