feat: add e2e using cypress (#1522)
SwissDataScienceCenter/renku-ui pull request #1599
Opened 2021-12-06 16:10 UTC by andre-code

Create project cypress
Create test register user, login and logout user

/deploy

2021-12-10 13:04 UTC, olevski requested changes
One minor clarification/change. Otherwise this is great Andrea! I am glad that you are also going to be using the cypress dashboard.

2021-12-13 08:07 UTC, ciyer requested changes
Wow, this is great! 🤩  The tests are easy to read and understand, and Cypress makes them easy to run and debug! 

There are a few minor suggestions, but the main request is to have a bit more flexibility for providing information to the tests. Usernames and passwords should be provided using environment variables so they are not in the code.

The other request is to have some flexibility around the URLs for the application (i.e., it would be nice if `dev.renku.ch` is not hard-coded), but this second one is something we can also do later.

2021-12-13 08:07 UTC, ciyer commented on e2e/cypress/support/authentication/gui_commands.ts
> +    else if (url.includes("dev.renku.ch/auth/realms/Renku/protocol/openid-connect/auth")) {
Could `dev.renku.ch` be made a parameter called `giLlabProvider`? This will give us a bit more flexibility.

2021-12-13 08:07 UTC, ciyer commented on e2e/cypress/support/index.ts
> + * Copyright 2020 - Swiss Data Science Center (SDSC)
```suggestion
 * Copyright 2021 - Swiss Data Science Center (SDSC)
```

2021-12-13 10:28 UTC, andre-code commented on e2e/cypress.json
> +  "baseUrl": "https://dev.renku.ch/",
Yes, it is the default value, but the baseUrl is reassigned by the PR development URL, you can see that in the acceptance-tests.yml file as CYPRESS_BASE_URL

2021-12-14 08:14 UTC, andre-code commented on e2e/cypress/integration/homepage.spec.ts
> +  const userData = { firstname: "e2e", lastname: "tests", email: "e2e@renku.ch", password: "123456" };
sure, I added ENV variables and use secrets to store it

2021-12-14 08:14 UTC, andre-code commented on e2e/cypress/support/authentication/gui_commands.ts
> +    else if (url.includes("dev.renku.ch/auth/realms/Renku/protocol/openid-connect/auth")) {
sure, added also as ENV variable

2021-12-14 16:34 UTC, andre-code commented on e2e/cypress/integration/homepage.spec.ts
> +  const userData = { firstname: "e2e", lastname: "tests", email: "e2e@renku.ch", password: "123456" };
Thank you very much for the suggestion, the PR description and README have been updated to include the instructions for the user data.

2021-12-15 12:41 UTC, ciyer approved these changes
Works very well! The tests are so easy to write and debug!

2021-12-16 14:34 UTC, merged