1272 add visibility when fork a project
SwissDataScienceCenter/renku-ui pull request #1617
Opened 2021-12-21 11:28 UTC by andre-code

Added a Visibility option to the modal dialog. The initial value should be the same as the project being forked, and only as visible or less visible options should be available.

For a public project: public, internal, private
For an internal project: internal, private
For a private project: private

Display an informative text in the fork modal dialog when the project was forked but the custom visibility can't be added.

/deploy

2021-12-22 10:20 UTC, lorenzo-cavazzi requested changes
It works well in all cases I tried! :tada: 

Just a tiny change on using an `input` field a a condition to show the element to set that input.

I also added a note on a function you created. Feel free to ignore it if it's not easy to derive a common function

2021-12-22 10:20 UTC, lorenzo-cavazzi commented on client/src/project/shared/Projects.state.js
> +    return availableVisibilities;
This is a very nice function!
We have something on the same line in `ProjectNew.state.js` at line 466 (`async getVisibilities(namespace)`). I'm wondering if it would make sense to merge the 2, or extrapolate a common function. Maybe it's not that straightforward tho...

2021-12-22 10:20 UTC, lorenzo-cavazzi commented on client/src/project/new/ProjectNew.present.js
> +    else if (meta.namespace.fetching || !meta.namespace.visibilities || !input.visibility) {
Are you sure about `!input.visibility` here? Since `input.visibility` is set when the user selects the visibility, if that case ever happens the user can't click it anyway.
I would remove it from here.

2021-12-22 10:20 UTC, lorenzo-cavazzi commented on client/src/project/shared/Projects.state.js
> +    return availableVisibilities;
P.S. this is just a "nice to have". If you think it's feasible (and reasonably easy) let's include it in the PR. Otherwise, feel free to leave this out.

2021-12-22 10:42 UTC, ciyer commented on client/src/project/shared/Projects.state.js
> +    return availableVisibilities;
At the very least, I think it would be nice to merge the `computeVisibilities` functions. It may be necessary to introduce a `maxVisibility(projectVisibility, groupVisibility)` function.

2021-12-22 11:00 UTC, ciyer commented
This is great and works well! I tried several cases, and all were handled properly. On _minor_ request. Not critical, but nice to have if easy. Could the message shown when updating the visibility be changed to `Determining options` instead of `Verifying`? 

![image](https://user-images.githubusercontent.com/1196411/147082624-b71a1eba-ed49-4b81-aae8-67ccb3fe9752.png)

2021-12-22 15:49 UTC, andre-code commented on client/src/project/shared/Projects.state.js
> +    return availableVisibilities;
Thanks for the suggestion, I refactor the function to be used also by the NewProjectCoordinator class.

2021-12-22 15:54 UTC, andre-code commented on client/src/project/new/ProjectNew.present.js
> +    else if (meta.namespace.fetching || !meta.namespace.visibilities || !input.visibility) {
It is necessary to avoid choosing invalid values (null) in the visibilities select, for example when recalculating the visibilities list.
This validation does not block the visibility selection because after the list calculation a valid default value is set.

2021-12-23 12:21 UTC, lorenzo-cavazzi commented on client/src/project/new/ProjectNew.present.js
> +    else if (meta.namespace.fetching || !meta.namespace.visibilities || !input.visibility) {
I think that value is never set to `null`. It's initialized as `""` in the RebkuModel, and it should always be default to a valid value when re-computed.
We can leave it here, it's not a big deal, I just thought it's a bit confusing for someone who doesn't know the magic happening in the state file pre-setting the `input.visibility`

2021-12-23 12:24 UTC, lorenzo-cavazzi commented on client/src/project/new/ProjectNew.present.js
> +    else if (meta.namespace.fetching || !meta.namespace.visibilities || !input.visibility) {
Ah nevermind, I just noticed `resetVisibility` is now a thing and it temporarily sets the visibility to `null`. Ignore this comment :smile:

2021-12-23 12:33 UTC, lorenzo-cavazzi approved these changes
Very nice addition to the fork feature! :rocket:

2021-12-23 13:12 UTC, ciyer approved these changes
Very nice!

2021-12-23 14:17 UTC, merged