feat(client): support session autosaves
SwissDataScienceCenter/renku-ui pull request #1645
Opened 2022-01-17 17:37 UTC by lorenzo-cavazzi

_STILL A DRAFT_

* Get and delete autosaves.
* Select new session commit based on autosaves and running sessions.
* Update CheckNotebookStatus component to support per-branch sessions.

/deploy renku=1.0-next renku-graph=cli-v1 renku-core=0000-disbale-check-migration-optimization
fix #1345

2022-01-18 14:23 UTC, ciyer requested changes
Nice feature which I think simplifies and improves the handling of autosave information! 🎉 

After trying it out, I think we should make some additional simplifications to the UI to make it even easier to use.

1. If there is an autosave for a particular branch, and the user wants to start a session on that branch, then force the user to either start on the commit with the autosave information or delete the autosave.

Right now, if the user starts on a different commit, the autosave information is removed for them; this makes that step more explicit and reduces opportunities for accidental data loss, I think.

In that case, we can change the message to be:
```
There is unsaved work from your last session which will be restored. If you do not wish to keep it, 
you can [delete the unsaved work](invoke delete command).

For more options, start a session and look at the session cheatsheet, which is available under this icon [show the session cheatsheet icon].
```

Add the following to the session cheatsheet:

## Autosave

If you see what work was saved you can diff the current contents against the previous state:

    git diff HEAD^

or against the latest state of the project:

    git diff origin [default branch name]

If you want to discard the unsaved work in a running session and return to the latest version:

    git reset --hard origin/[default branch name]

If you would like to keep this work around for later, but continue working with the latest version for now:

    git push --set-upstream origin your-branch-name-here
    git reset --hard origin/[default branch name]

## Autosave information not being correctly updated

I had an autosave branch, which I removed by starting from another commit. However, I still get this message, even though the autosave branch is gone.

![image](https://user-images.githubusercontent.com/1196411/149951935-06106868-bd45-4da3-975a-914e515b9c20.png)


![image](https://user-images.githubusercontent.com/1196411/149952225-1fe8465d-a8c8-4a4d-b35f-dde2cfe2fa72.png)

2022-01-19 13:52 UTC, lorenzo-cavazzi commented
I've added the autosave info on the Cheatsheet (I slightly changed the words to use the 2 column design, but I can switch back to the linear one and use your suggestion verbatim), changed the alert info, and fixed the bug resulting in the autosave list not being cleaned when the last available autosave is deleted.

![Screenshot_20220119_144658](https://user-images.githubusercontent.com/43481553/150143535-f73fc459-3e37-4dee-a575-e9a836e6871d.png)

2022-01-20 13:18 UTC, ciyer requested changes
This is very close now. I just added a commit to clean up the cheat sheet a bit. I also found an issue with the `faBook` icon, which should be easy to fix.

I want to understand the situations where the Autosave service can return an error, but that is more for my knowledge.

2022-01-20 17:27 UTC, lorenzo-cavazzi commented on client/src/notebooks/Notebooks.present.js
> +          which is available under this icon <FontAwesomeIcon icon={faBook} />.
Ah true, thanks for spotting that!

2022-01-20 17:31 UTC, lorenzo-cavazzi commented
> I want to understand the situations where the Autosave service can return an error

This happens when the page to start a new session is already open and the autosave banner is visible, but the autosave gets removed from somewhere else (E.G. the branch is manually removed from GitLab, or the user starts a session on that branch from a different commit on another tab).
If the user tries to remove the autosave, then the `DELETE /autosave` API will return an error.

2022-01-24 09:17 UTC, olevski commented
@lorenzo-cavazzi this looks good to me. I tested a few cases.

One thing that I saw is that if you make a new branch but do not push it, then the autosave branch gets properly created but it is impossible to get the data out of it. This is because there is still no such branch in the remote repo. And the newly created branch does not show up in the list of branches to select when starting a session.

This is not a result of this PR though. It is just a problem with how the autosave system currently works. I will think of how we can tackle this and open a new issue for it somewhere. Let me know if you have any ideas.

2022-01-24 12:06 UTC, lorenzo-cavazzi commented
Thanks for the feedback @olevski !
I'm wondering if using the starting branch for generating the autosave instead of the current branch would be a solution. But maybe it's not the way to go. It may be very confusing to start a session on a branch and end up in a different one.

Also, the UI will switch at some point to a per-branch approach, where the user can select/change the branch when browsing a project, and the UI will show the related content. There it will be even more difficult to identify a non-pushed branch.

I would call this a corner case though. Autosaves should prevent data loss, but branching off and not pushing may be a bit of a misuse of autosaves. And probably not a very common case.

2022-01-24 14:47 UTC, olevski commented
So yeah this issue is good to go as far as I am concerned. In terms of the additional stuff I found here is an issue that would address it on the notebook side. https://github.com/SwissDataScienceCenter/renku-notebooks/issues/884.

I think that the pre-stop hook that creates the autosave branch can check for this specific weird situation. And if we are in this situation when the user just created a new branch without publishing it then the pre-stop script can simply publish the branch and allow the user to then recover from it later on.

2022-01-25 17:32 UTC, merged