feat(client): add sentry performance (#1634)
SwissDataScienceCenter/renku-ui pull request #1648
Opened 2022-01-18 15:46 UTC by andre-code

This PR update sentry configuration to support performance monitoring using sentry.

To visualize some tracked transaction 👉  [sentry dashboard](https://sentry.dev.renku.ch/organizations/swiss-datascience-center/performance/?project=5) there are some examples in the andrea namespace

### Note

By default the monitoring is disabled `SENTRY_SAMPLE_RATE=0`, when runs telepresence and sentry is enabled the default value is 1.0, which means to track all transactions.

In production is recommended to set `sampleRate=0.2` in `helm-chart/renku-ui/values.yaml`. This would track 20% of all requests in Sentry performance monitoring. It is 0 by default

/deploy

2022-01-20 09:12 UTC, ciyer requested changes
Code looks good! Just one minor suggestion for catching out-of-bounds values.

2022-01-20 09:12 UTC, ciyer commented on client/src/utils/sentry/Sentry.js
> +  sentrySampleRate = parseFloat(sampleRate) || 0;
I think it would be good to add a clamp to set values < 0 to 0 and values > 1 to 1.

2022-01-20 10:05 UTC, lorenzo-cavazzi commented on client/src/App.js
> -export default App;
Since Sentry is initialized in the index file, would it make sense to keep the whole Sentry logic there? That would move `Sentry.withProfiler(App)` to somewhere else, ideally made in a function inside `utils/helpers/sentry` and invoked in the index under the same condition used to configure Sentry  (`if (params.SENTRY_URL) {`)
In that way, we won't even import the Sentry library when it's not needed

2022-01-20 10:15 UTC, lorenzo-cavazzi commented on client/src/App.js
> +export default Sentry.withProfiler(App);
Since Sentry is initialized in the index file, would it make sense to keep the whole Sentry logic there? That would move `Sentry.withProfiler(App)` to somewhere else, ideally made in a function inside `utils/helpers/sentry` and invoked in the index under the same condition used to configure Sentry  (`if (params.SENTRY_URL) {`)
In that way, we won't even import the Sentry library when it's not needed

2022-01-20 10:45 UTC, lorenzo-cavazzi requested changes

2022-01-20 10:45 UTC, lorenzo-cavazzi commented on helm-chart/renku-ui/templates/deployment-template.yaml
> +              value: { { .Values.sentry.sampleRate | quote } }
```suggestion
              value: {{ .Values.sentry.sampleRate | quote }}
```
I think this is throwing the error in the deployment.

2022-01-24 15:23 UTC, andre-code commented
Thank @ciyer  and @lorenzo-cavazzi  for the review, I implemented all the suggestions.

2022-01-25 09:40 UTC, ciyer commented on client/src/utils/helpers/sentry/Sentry.js
> +  sentrySampleRate = _.clamp(parseFloat(sampleRate) || 0, 0, 1);
Nice solution!

2022-01-25 09:52 UTC, ciyer reviewed
Code looks great!

2022-01-25 10:16 UTC, Panaetius approved these changes
Should we set https://docs.sentry.io/platforms/javascript/performance/instrumentation/automatic-instrumentation/#maxtransactionduration ? The default of 600s seems rather large, maybe 30s is enough.

I've approved for now since I think everything would work as is, just the two comments/suggestions to consider.

2022-01-25 10:16 UTC, Panaetius commented on client/src/utils/helpers/sentry/Sentry.js
> +      { tracingOrigins: ["localhost", /^\//, /ui-server\/api/] },
Do we need to add `renkulab.io` (i.e. `.Values.global.renku.domain` from the chart), maybe instead of `localhost`? What scenarios are there were localhost would be user?

2022-01-26 13:20 UTC, andre-code commented on client/src/utils/helpers/sentry/Sentry.js
> +      { tracingOrigins: ["localhost", /^\//, /ui-server\/api/] },
thx @Panaetius  for the review 🙌. So far there is no particular usage for localhost so I updated it to send only the URL of the UI server and the value of maxTransactionDuration

2022-01-27 08:50 UTC, ciyer submitted a review, later dismissed
🎉

2022-01-27 12:21 UTC, lorenzo-cavazzi approved these changes

2022-01-28 15:17 UTC, merged