1523 error handling UI server
SwissDataScienceCenter/renku-ui pull request #1658
Opened 2022-01-24 08:19 UTC by andre-code

This PR adds an error handler middleware for Exception,  unhandled rejection, and uncaught Exception in server-ui.
Enabled Sentry for server-ui.
Create an error log for exceptions.

2022-01-24 10:06 UTC, lorenzo-cavazzi reviewed
Nice to see this taking form!
Just a couple of early comments on the draft.

2022-01-24 10:06 UTC, lorenzo-cavazzi commented on server/src/index.ts
> +app.use(errorHandlerMiddleware);
Nice to see this packed in a middleware!
It seems to be invoked twice here. I guess this is the right one, and the other one is redundant?

2022-01-24 10:06 UTC, lorenzo-cavazzi commented on server/src/logger.ts
> +    }),
We don't need to create a local file.
The console is fine for live debugging, while errors should be permanently logged with Sentry.

2022-01-25 07:02 UTC, andre-code commented on server/src/index.ts
> +logger.info(`Sentry Initialized: ${sentryInitialized}`);
sure 😉, I moved to the sentry file

2022-01-25 07:52 UTC, andre-code commented on server/src/index.ts
> +app.use(errorHandlerMiddleware);
actually, if everything goes well initializing the authenticator, the error middleware registered after registering the authentication routes would be more effective because it would apply for the auth routes (/login, /callback...) and the other paths (/api/*) since it is asynchronous. I have left it only once.

2022-01-25 07:52 UTC, andre-code commented on server/src/logger.ts
> +    }),
sure, removed

2022-01-25 17:14 UTC, lorenzo-cavazzi requested changes
Nice to see this taking form!
I added some comments for cleaning a bit the code, which looks good.

I still need to review the middleware and the initialization function, but the deployment is not sending the exceptions to sentry when checking here https://sentry.dev.renku.ch/organizations/swiss-datascience-center/issues/?project=9.
The variables seem to be set up correctly when checking the UI server pod (I run a console there and typed `env | sort`)
```
SENTRY_NAMESPACE=renku-ci-ui-1658
SENTRY_TRACE_RATE=1
SENTRY_URL=https://182290b8e1524dd3b7eb5dd051852f9f@sentry.dev.renku.ch/5
```
![Screenshot_20220125_175534](https://user-images.githubusercontent.com/43481553/151025350-2ae48858-811d-4477-b442-993a354aefdf.png)

2022-01-25 17:14 UTC, lorenzo-cavazzi commented on server/src/utils/index.ts
> +function getRelease(version: string): string {
It took me a while to realize what this function does. And I realized only later that it's the same logic as in the client :sweat_smile: 
Would it make sense to add a couple of tests as an explanation?
Feel free to take them from the client, maybe adding something like `1.3.0-n24.h376dd06` which is the current `UI_SERVER_VERSION` in the deployed environment.

P.S. that example is not in the client because the version string changed a bit with the latest version of chartpress, so it may need a (minor) update

2022-01-25 17:14 UTC, lorenzo-cavazzi commented on server/src/utils/middlewares/errorHandlerMiddleware.ts
> +  next: express.NextFunction): void => {
If you are not invoking `next`, you can just leave it out.
```suggestion
  res: express.Response): void => {
```

2022-01-26 17:17 UTC, andre-code commented on server/package.json
> +    "dotenv": "^14.2.0",
I have found a simple way to avoid the use of this extra library that for this case is not extremely necessary. Thanks for the suggestion. 😉

2022-01-26 17:18 UTC, andre-code commented on server/src/utils/sentry/sentry.ts
> +      tracesSampleRate: _.clamp(options.sampleRate, 0, 1),
thx for the suggestion, I agree so I removed the library and added the clamp function as an utility function

2022-01-26 17:21 UTC, andre-code commented on server/run-telepresence.sh
> +
sure, updated to activate Sentry when `SENTRY=1 ./run-telepresence.sh `
I am wondering if is necessary to handle the case when debug  or console y/o sentry runs at the same time.

2022-01-26 17:22 UTC, andre-code commented on server/src/config.ts
> +  enabled: !!process.env.SENTRY_URL ?? false,
sure, done 😉!

2022-01-26 17:24 UTC, andre-code commented on server/src/utils/index.ts
> +function getRelease(version: string): string {
I added a unit test for that function and was necessary to update it for that case `1.3.0-n24.h376dd06`. If u agree with the fix I can include it in the client part as well.

2022-01-26 17:25 UTC, andre-code commented on server/src/utils/middlewares/errorHandlerMiddleware.ts
> +  next: express.NextFunction): void => {
The error handler doesn't work if the `next` is not specified as a parameter. 🤷‍♀️

2022-01-26 17:27 UTC, andre-code commented
@lorenzo-cavazzi thank you very much for your code review. 🙌

2022-01-27 08:28 UTC, ciyer reviewed
This is very nice! The errors are easy to see in both the logs and in sentry. 🚀

2022-01-27 12:12 UTC, ciyer approved these changes
Ready to merge for me.

2022-01-31 12:47 UTC, lorenzo-cavazzi requested changes
I have a couple of very minor changes (see inline).
As soon as Sentry is back, I'll do a couple of other quick tests to verify all is logged as expected -- mostly to test metrics, but I'm pretty sure all is already on point :slightly_smiling_face:

2022-02-01 10:22 UTC, andre-code commented on server/src/utils/sentry/sentry.ts
> +  logger.info(`Sentry Initialized: ${sentryInitialized}`);
Good point, I will add a catch to unblock the app

2022-02-01 10:22 UTC, andre-code commented on server/src/index.ts
> +initializeSentry(app);
for sure, I will include that change in the next commit

2022-02-01 13:36 UTC, andre-code commented on server/src/routes/apis.ts
> +
I have added a flag to facilitate access to this path for debugging purposes, even for this PR.

2022-02-01 13:38 UTC, andre-code commented
PR updated with the last suggestions from  @lorenzo-cavazzi ✌️

2022-02-01 16:43 UTC, lorenzo-cavazzi submitted a review, later dismissed
Great work!

So nice to see the error details in sentry! This will greatly simplify debugging!

![Screenshot_20220201_173718](https://user-images.githubusercontent.com/43481553/152011300-cd47fb78-89a4-4c3a-950b-2ae9723edfc9.png)

2022-02-02 09:17 UTC, lorenzo-cavazzi approved these changes
Great! :tada: 

We probably need to merge SwissDataScienceCenter/renku#2446 before this PR, to be sure the values are set up properly in the main renku repository

2022-02-03 09:52 UTC, lorenzo-cavazzi approved these changes

2022-02-03 09:53 UTC, ciyer approved these changes
👍

2022-02-03 09:59 UTC, merged