1627 remember accessed projects
SwissDataScienceCenter/renku-ui pull request #1661
Opened 2022-01-26 09:34 UTC by andre-code

This PR adds the tracking of the projects accessed by a user
- Each request for a project that is accessed and is from an authenticated user is logged by the userId.
- The /api/last-projects/:length endpoint has been added to retrieve the list of the last projects accessed by the user.

### Test
1. Access one or more projects from the UI
2. Use this endpoint to retrieve the list

Closes #1627

2022-01-27 10:13 UTC, lorenzo-cavazzi requested changes
I like the approach you used here, but I have a few change requests that may require a bit of rework.

The general idea is to keep the storage as generic/abstract as possible, so that we can virtually modify anything there (even using postgres instead of redis) without requiring changes to the code invoking it.
It requires more work now, but we will benefit from that in the long term.

2022-01-27 10:13 UTC, lorenzo-cavazzi commented on server/tests/storage/index.test.ts
> +    ];
This will change a bit with the abstraction of ordered sets.
A thorough set of tests may include verifying:
- no duplicates when saving again the last element
- re-ordering when saving a previously saved element
- cutting the first element when there is a limit and we add another (new) element

2022-01-27 14:01 UTC, andre-code commented on server/src/storage/index.ts
> +  }
I appreciate your suggestions @lorenzo-cavazzi , thanks for reviewing my PR 🙌.

I like the idea of using options to indicate the behavior of the list. Something like:
```
saveListOptions {
  direction: "left|right";
  limit: number; // number of items you want to save
  allowDuplicate: boolean; // direction won't have effect if this is true
}
```

As for the data to be recorded, the idea of saving the records as they are collected even if they already exist (which makes the list have duplicate data) is because the client can decide whether to use them to show the projects according to the order or the number of times they have been visited recently (both cases need extra data in the ui). 

In the ui: 
case a: by order of last transaction, from the list [a,a,c,b,b,b,d,d,e,d,e,a,z] => a,c,b,d,e,z
case B: by recently visited quantity, from the list [a,a,c,b,b,b,d,d,e,d,e,a,z] => a(3), b(3), d(3), e(2),c(1), z(1)

And for that case is easier to use ltrim and lrange

2022-01-27 15:32 UTC, lorenzo-cavazzi commented on server/src/storage/index.ts
> +  }
I see, although we would probably miss data this way if we keep duplicates and we limit the history.
Assume a user works primarily on project A, and we store N items. At some point, it's very possible we saved only A multiple times in the queue, which is probably not what we want if the final goal is to show the last accessed projects in the logged-in landing page

2022-01-31 10:03 UTC, andre-code commented
Thank you @lorenzo-cavazzi for your review. 🙌
I'm all for the simplest approach possible and after defining with the team that it is not necessary to keep track of how many times the projects were requested I move to use the ZADD redis solution to keep the list short with the values sorted by access time. 
I also simplified the option to save and retrieve values from storage by adding the options argument to indicate how to operate on the values and abstracted storage into an interface to make it more extensible.

2022-01-31 13:35 UTC, ciyer requested changes
Wow, this is great! It works very well, and the design changes that were implemented here are fantastic.

Only one comment -- with the changes that have been made, I think we can reduce the size limit of the projects collection to 20 or maybe even 10.

2022-01-31 13:35 UTC, ciyer commented on server/src/utils/const.ts
> +const LPROJECTS_DEFAULT_LENGTH = 100;
I think we can make this default smaller, say 20.
```suggestion
const LPROJECTS_DEFAULT_LENGTH = 20;
```

2022-02-02 08:13 UTC, ciyer approved these changes
This is great 🙌 . Let us get it merged!

2022-02-02 09:59 UTC, lorenzo-cavazzi approved these changes
:rocket:

2022-02-02 12:36 UTC, merged