feat(chart)!: use global redis
SwissDataScienceCenter/renku-ui pull request #1699
Opened 2022-02-16 15:31 UTC by olevski

Hopefully I did this right. It is really cool that you use typescript in the ui server. I did not know this.

With this change everything the ui server needs is specified in the global redis section. So if someone brings their own redis then they do not install the redis chart bundled with renku but they fill out all stuff in global.redis. If people use the included redis then they can stick with the defaults and everything should work. If they change the defaults then the global.redis section and regular redis section need to be compatible and some values between the two will be duplicated.

**THIS IS A BREAKING CHANGE FOR THE HELM CHART**

/deploy #persist

~Please add any comments on the helm chart and its organization in the parent PR in the renku repo at https://github.com/SwissDataScienceCenter/renku/pull/2483. That way we can all agree on the any potential changes to the helm chart.~

2022-02-16 16:38 UTC, lorenzo-cavazzi commented
Hey, not sure if it's relevant but there was already a stub on using the global redis instance on the UI server #1554

2022-02-16 21:29 UTC, olevski commented
> Hey, not sure if it's relevant but there was already a stub on using the global redis instance on the UI server #1554

I am sorry Lorenzo, I missed that. I should have looked first. I will close this PR and add the changes on the original one.

2022-02-17 07:53 UTC, lorenzo-cavazzi commented
Don't worry, the other PR is now outdated (looking at "File changed" is very confusing), and it's probably better to keep the structure in line with the other repos.
When this is ready, I can quickly check if there is anything useful in the other PR that I can port here, and then close it.

2022-02-28 21:57 UTC, olevski commented
@lorenzo-cavazzi this is ready for review and testing. All other dependent/required PRs have been merged.

2022-03-14 12:46 UTC, lorenzo-cavazzi requested changes
Hey Tasko, sorry for the delay!
There are a few adjustments to the code, mainly to comply with the lining rules.

You can add them into a commit and re-run the acceptance tests to see if it works -- mind that I changed the deploy string to include some requirements for the current UI master branch to work with tests

2022-03-14 12:46 UTC, lorenzo-cavazzi commented on server/src/config.ts
> +  isSentinel: (process.env.REDIS_IS_SENTINEL || "false") == "true",
```suggestion
  isSentinel: convertType(process.env.REDIS_IS_SENTINEL) || false,
```

2022-03-14 12:46 UTC, lorenzo-cavazzi commented on server/src/storage/RedisStorage.ts
> +    if (isSentinel){
```suggestion
    if (isSentinel) {
```

2022-03-14 12:46 UTC, lorenzo-cavazzi commented on server/src/storage/RedisStorage.ts
> +      if (password) {
```suggestion
      if (password)
```

2022-03-14 12:46 UTC, lorenzo-cavazzi commented on server/src/storage/RedisStorage.ts
> +      }
```suggestion
```

2022-03-14 12:46 UTC, lorenzo-cavazzi commented on server/src/storage/RedisStorage.ts
> +    } else {
```suggestion
    }
    else {
```

2022-03-14 12:46 UTC, lorenzo-cavazzi commented on server/src/storage/RedisStorage.ts
> +    isSentinel: boolean = config.redis.isSentinel,
```suggestion
    isSentinel: boolean = config.redis.isSentinel as boolean,
```

2022-03-14 16:47 UTC, lorenzo-cavazzi submitted a review, later dismissed
Thank you Tasko for this PR! It works well :+1:

2022-03-18 16:11 UTC, lorenzo-cavazzi approved these changes

2022-03-18 16:24 UTC, merged