feat(client): show recent projects (#1628)
SwissDataScienceCenter/renku-ui pull request #1708
Opened 2022-02-23 10:54 UTC by andre-code

### Description
This PR include visualization of the last visited projects on the landing page (only valid projects), in case there is no last projects it displays the user projects (previous behavior)

![Screenshot 2022-02-23 at 11 49 24](https://user-images.githubusercontent.com/43388408/155305135-14357aac-ecd6-4ea6-ae23-eeaa77613008.png)

### Testing
Visit different projects owned or not and then go to the landing page, those projects should appear under the title **Recent Projects** in order of last visited first.

/deploy #persist

2022-02-23 15:28 UTC, andre-code commented
PR ready for review, it includes already e2e tests ✌️

2022-02-25 09:28 UTC, lorenzo-cavazzi requested changes
Great PR! And thumb up for the e2e tests!
I identified a corner case we could handle. It's probably rare, but we could introduce a 1-line fix to prevent it.
Otherwise, this looks good to me :rocket:

2022-02-25 09:28 UTC, lorenzo-cavazzi commented on client/src/project/shared/Projects.state.js
> +      else {
```suggestion
      if (!lastProjectsVisited?.length || !projectList.length) {
```

It's possible the projects previously visited have been deleted or otherwise not available (permissions, ...).
It's a rare case, but the message would be confusing for someone with some projects (see screenshot).
I wouldn't put too much effort into solving this case in a very elegant way.
Checking if at least one valid project was fetched from the list should be enough (the "recent projects" still flashes for a second or two, but it's a rare case, I think it's fine)

![Screenshot_20220225_101857](https://user-images.githubusercontent.com/43481553/155689182-c80fe1ff-12d7-48d4-b2cc-6a677aa4a09e.png)

2022-02-25 14:42 UTC, lorenzo-cavazzi approved these changes

2022-03-03 08:19 UTC, ciyer submitted a review, later dismissed
Very nice! This makes the landing page much easier to use and much more useful!

2022-03-04 09:46 UTC, ciyer approved these changes

2022-03-04 16:52 UTC, ciyer approved these changes

2022-03-04 17:20 UTC, merged