feat(client): show session logs for sub containers
SwissDataScienceCenter/renku-ui pull request #1713
Opened 2022-02-25 15:03 UTC by andre-code

/deploy renku-notebooks=get-all-session-logs

2022-03-01 09:12 UTC, olevski commented
I did a quick test of the feature. Looks good to me @andre-code

2022-03-01 09:12 UTC, olevski approved these changes

2022-03-01 09:21 UTC, olevski commented
Also I think the best way to tackle this is to merge this and the dependent PR on the notebooks at the same time, make releases for notebooks and the UI at the same time and then bump the requirements.yaml in the renku repo in one single PR for both notebooks and UI.

2022-03-02 09:31 UTC, ciyer submitted a review, later dismissed
This is a very useful feature and nicely presented. I added a commit that introduces some minor cosmetic changes to use the standard background and tab styles in the popup.

2022-03-09 12:58 UTC, lorenzo-cavazzi requested changes
Nice solution! The zipped file for the download is a great addition!

I added a comment inline, not sure if it's relevant (feel free to ignore it if not :slightly_smiling_face:  ).

Mind that we show the logs also in a tab on the session page. They seem to be gone from there. In the screenshot, on the left it's the current PR (no logs), while on the right it's the old behavior.

![Screenshot_20220309_134905](https://user-images.githubusercontent.com/43481553/157446260-a2986750-1166-4582-95f0-337bf0a02705.png)

2022-03-09 12:58 UTC, lorenzo-cavazzi commented on client/src/notebooks/Notebooks.css
> +}
Mind that this will impact **all** the elements application-wide, not only in the notebooks components -- although I believe the default for the `.nav-item` is already a pointer.

If you only need to change the behaviour for the logs tab, you could create a new class.

2022-03-09 14:42 UTC, andre-code commented
🙌 thx @lorenzo-cavazzi , I am happy for the zip file addition 💙 😅

And also thanks for noticing that the logs were also shown in the session view, I included them in the last commit. ✌️

2022-03-10 08:27 UTC, lorenzo-cavazzi commented
Thanks for fixing it!
I noticed the view is a bit off on that page. On both firefox and chrome , I get scroll bars halfway, as if the height was fixed (see screenshot). Could you check that?
P.S. if it's no low effort, it would be nice to add the download logs button also there, next to the "Refresh logs" button on the top.

![Screenshot_20220310_092419](https://user-images.githubusercontent.com/43481553/157619706-8458cf3f-098f-4f4b-8f61-7594f308964b.png)

2022-03-14 13:23 UTC, merged