feat(client): use simplified session state (#1646)
SwissDataScienceCenter/renku-ui pull request #1718
Opened 2022-03-02 13:45 UTC by andre-code

This PR is for refactoring the session status display with the changes in renku-notebooks [here](https://github.com/SwissDataScienceCenter/renku-notebooks/pull/898)

The session status changed from:
````
status: {
    message: "containers with unready status: [jupyter-server oauth2-proxy git-proxy]" // string
    phase: "Pending", // Pending, Running, Error
    ready: false
    reason: "ContainersNotReady"
    step: "Ready"
}
```` 
To:
````
status: {
   message: "Containers with non-ready statuses: git-proxy, jupyter-server, oauth2-proxy, init-certificates, git-clone." // string or undefined
   state: "starting" // starting, running, stopping, failed
}
````
![status session](https://user-images.githubusercontent.com/43388408/156799262-afd1b6f9-3af3-4a19-80ca-cfc736ead308.gif)

### Testing
Error case: https://renku-ci-ui-1718.dev.renku.ch/projects/tasko.olevski/test-failing-project-1/sessions/new?autostart=1
![error session status](https://user-images.githubusercontent.com/43388408/156801342-f48bd73b-147c-440e-886b-0ef3ffd8fe3a.gif)

Closes #1646 

/deploy renku-notebooks=simplify-session-status renku=000-acceptance-tests #persist

2022-03-08 08:51 UTC, ciyer submitted a review, later dismissed
This works very well! I think this is an improvement to the interaction and way of presenting the information.

2022-03-08 12:37 UTC, olevski submitted a review, later dismissed
This is great @andre-code!

Also the error shown when a session fails will improve further when we merge https://github.com/SwissDataScienceCenter/renku-notebooks/pull/923

Basically after this PR is merged I am pretty sure that both https://github.com/SwissDataScienceCenter/renku-notebooks/pull/923 and https://github.com/SwissDataScienceCenter/renku-notebooks/pull/898 can be merged. https://github.com/SwissDataScienceCenter/renku-notebooks/pull/898 is more directly tied to this PR and that is what you tested against.

2022-03-08 12:46 UTC, olevski commented
p.s. I am ready to merge the corresponding stuff on the notebook side and tag a release. But I would like to do it at the same time as when you release this in the UI. When do you plan on doing this?

2022-03-09 10:00 UTC, andre-code commented
> p.s. I am ready to merge the corresponding stuff on the notebook side and tag a release. But I would like to do it at the same time as when you make a new release for the UI. When do you plan on doing this?

Hi @olevski thanks for your review.
Hopefully the day is today 🎉
Once passed the acceptance test I will merge this Pr and #1713 and tag a release.

2022-03-09 10:50 UTC, lorenzo-cavazzi requested changes
I've found a small detail to fix when saving the notebook state. In some cases, the `fetching` variable isn't falsified after finishing the fetch operation (see inline).

Should we make the "Error" message and icon red in this case?
![Screenshot_20220309_114616](https://user-images.githubusercontent.com/43481553/157426621-2ba1bd5b-63c1-4109-ae1f-bdf2a1d55c90.png)

More in general, I've noticed that, after starting a new session, when the status is initially marked as "running" the notebook is still not reachable for a few seconds. Opening the iframe results in a 503 error -- it happens to me very often when using the autostart button.
After a few seconds, the session is actually available, but the user needs to manually refresh the page.
@olevski is it possible the notebook is marked as ready when it's not yet ready?

2022-03-09 10:50 UTC, lorenzo-cavazzi commented on client/src/notebooks/Notebooks.state.js
> +        }
It's better to avoid using multiple `this.model.set` and use a single `this.model.setObject` to prevent information being updated in different transactions.

Here, I would always set both `fetching` and `fetched` cause this ends the fetching phase and the data are actually up-to-date (even if no notebook was actually changed in the store)

2022-03-09 14:13 UTC, olevski commented
> @olevski is it possible the notebook is marked as ready when it's not yet ready?
I guess it is. I have not noticed this. We have a readiness probe that will essentially disable ingress into the sessions before passes the probe - this results in a 503. I think though that the status of the session should not conflict with this. But let me check.

2022-03-09 14:32 UTC, olevski commented
I see what you mean with the 503 error. It seems that k8s happily sets all container statuses to running even though the readiness probes are not fully cleared. There is an easy way to figure this out - just by sending a request to where you are supposed to access the session. But ideally I can get this info from the manifest itself and not send a full http request on every GET request I get from the UI. I am looking into this rn.

2022-03-09 16:10 UTC, olevski commented
So with the edits on the notebook service the 503 error is gone.

But one think I notice is that with this version of the UI I see sessions from other projects when I switch projects. Or at least they kind of flash in and out.

For example:
- launch a session in project 1
- navigate to project 2 (where there are no sessions)
- go to see the sessions for project 2
- here you will see the session from project 1 for a few seconds before it disappears

I am pretty certain that this is not because of the notebooks. When I look at the network requests that are sent and then received the notebook service sends the right responses.

Could it be that the state in the UI is getting out of sync or smth?

2022-03-10 09:25 UTC, andre-code commented
> So with the edits on the notebook service the 503 error is gone.
> 
> But one think I notice is that with this version of the UI I see sessions from other projects when I switch projects. Or at least they kind of flash in and out.
> 
> For example:
> 
> * launch a session in project 1
> * navigate to project 2 (where there are no sessions)
> * go to see the sessions for project 2
> * here you will see the session from project 1 for a few seconds before it disappears
> 
> I am pretty certain that this is not because of the notebooks. When I look at the network requests that are sent and then received the notebook service sends the right responses.
> 
> Could it be that the state in the UI is getting out of sync or smth?

Thanks @olevski  for noticing, it was indeed a change introduced in the UI, I have already corrected it in the last commit.
And thanks for fixing the 503 error in record time ⚡️ 🎉.

2022-03-10 12:22 UTC, lorenzo-cavazzi approved these changes
Lgtm! :rocket:

2022-03-10 16:27 UTC, merged