Prevent changes to a project while the core-service is modifying it.
SwissDataScienceCenter/renku-ui pull request #1720
Opened 2022-03-04 17:24 UTC by ciyer

Fix #1603

2022-03-09 08:08 UTC, andre-code reviewed
Great new feature 🎉
It will definitely help the user to coordinate actions in the app that could generate unexpected behavior or lose data.
I left some suggestions to improve the UX experience.
Is there a possibility that the user can find what exactly is being modified on the project status page?

2022-03-09 08:08 UTC, andre-code commented on client/src/dataset/Dataset.present.js
>            : null}
To improve the user experience, I suggest that instead of hiding the add to project button,  would be better to disable it and show a tooltip to explain that there is an ongoing process that needs to finish first.

2022-03-09 08:25 UTC, lorenzo-cavazzi requested changes
Very nice feature! Just a couple of details to fix in the code (see inline).

As a general comment, I've noticed the `GET /project.lock_status` API is invoked only once. This works fine for a single tab, but it doesn't prevent multiple actions if a user accidentally clicks on another tab, or if an action is ongoing when the user loads the project.

We could invoke the `lock_status` API again when the user clicks on a tab potentially affected (Datasets, Sessions, Settings, Overview --> Status), and/or just before invoking a blocking action (datasets or settings modifications, and project update).
When the status is "blocked", we should also have a way to get out of it.
A possible solution would be polling until the project is not blocked anymore. An alternative (quicker to implement but worse UX) would be adding a "verify status" fa-redo icon in top, close to the "currently being modified" message, invoking again the `lock_status` API.

2022-03-09 08:25 UTC, lorenzo-cavazzi commented on client/src/project/Project.present.js
> +    return <Col sm={12}>x
That `x` sneaked in :grin: 

![Screenshot_20220309_090549](https://user-images.githubusercontent.com/43481553/157398858-815225f0-b9bc-481a-bd2e-4633fc641832.png)

2022-03-09 08:32 UTC, ciyer commented on client/src/project/Project.present.js
> +    return <Col sm={12}>x
Oops!

2022-03-10 12:06 UTC, ciyer commented on client/src/project/datasets/DatasetsListView.js
> +        null :
Good suggestion! I have made this change.

2022-03-10 12:07 UTC, ciyer commented on client/src/dataset/Dataset.present.js
>            : null}
Also a good suggestion. This has been done as well.

2022-03-10 12:07 UTC, ciyer commented on client/src/api-client/project.js
> +/* eslint-disable max-len */
Good point. I have made this change.

2022-03-10 12:52 UTC, lorenzo-cavazzi approved these changes
Lgtm! :rocket:

2022-03-11 08:07 UTC, andre-code approved these changes
Great work! 👏

2022-03-11 09:29 UTC, merged