feat(client): redirect Notebook connect button to session
SwissDataScienceCenter/renku-ui pull request #1725
Opened 2022-03-09 08:23 UTC by andre-code

This PR redirect Notebook connect button to renku session link in the same window.

![notebook connect](https://user-images.githubusercontent.com/43388408/157401039-8fb34e97-3fd8-4ac0-8ec0-146f30372b2a.gif)

Closes #1613 

/deploy renku=000-acceptance-tests #persist

2022-03-09 10:16 UTC, lorenzo-cavazzi requested changes
Nice work! I think it requires a couple of changes before merging:
1. The file information should be preserved and used to open the target notebook in the relevant session.
2. The modifications in `GoBackButton` may not be necessary. Saving the original URL in the state instead of a fixed string may be easier to handle and maintain.
More details inline

2022-03-09 10:16 UTC, lorenzo-cavazzi commented on client/src/project/Project.present.js
> +  const history = useHistory();
This is good in general, but you already have `props.history` here

2022-03-09 10:16 UTC, lorenzo-cavazzi commented on client/src/project/Project.present.js
> +    label={backButtonLabel} url={props.notebookServersUrl} useGoBack={!!locationFrom} />);
I like the approach here!
What about simplifying by adding the return link directly into `from`, and using it as `url` instead of changing the logic of `GoBackButton` to fit in `history`?

2022-03-09 10:16 UTC, lorenzo-cavazzi commented on client/src/notebooks/NotebookStart.present.js
> +        link = <Link to={{ pathname: sessionUrl, state: { from: "notebookFile" } }} >{icon}</Link>;
This is the right approach, but it may require including extra information in the URL (or even better saving it somewhere else, maybe adding a `filePath` state) to preserve the file path.
The notebook URL used for the iframe should then include a prefix `/tree/${this.props.filePath}` to open directly the notebook in the running session

2022-03-09 14:16 UTC, andre-code commented
> Nice work! I think it requires a couple of changes before merging:
> 
> 1. The file information should be preserved and used to open the target notebook in the relevant session.
> 2. The modifications in `GoBackButton` may not be necessary. Saving the original URL in the state instead of a fixed string may be easier to handle and maintain.
>    More details inline

Hey, thx for your suggestions. I updated the useHistory part. ✌️

2022-03-11 09:06 UTC, lorenzo-cavazzi approved these changes
Lgtm! :+1:

2022-03-14 12:22 UTC, lorenzo-cavazzi approved these changes

2022-03-14 12:24 UTC, merged