feat(client): project template selector component (#1734)
SwissDataScienceCenter/renku-ui pull request #1760
Opened 2022-03-28 12:12 UTC by andre-code

This PR adds the component for the Template Selector with improved UX for disabled and invalid states. 
![template selector storybook](https://user-images.githubusercontent.com/43388408/160395184-986e874a-2f1c-4acf-abee-e9c4bff12da2.gif)

/deploy renku-core=develop renku=tests-new-project-form-changes #persist

2022-03-29 12:08 UTC, lorenzo-cavazzi requested changes
Functionality-wise it's all good.
There are a few glitches in the appearance. Sometimes the vertical space is wider than other components (there are extra `py-3` classes here and there, see screenshot in the bottom)

![Screenshot_20220329_140134](https://user-images.githubusercontent.com/43481553/160607631-f397412c-a75f-4a8d-abef-85076d5a0234.png)

Also, some components don't seem to be displayed as blocks (see screen in the bottom part)

![Screenshot_20220329_140323](https://user-images.githubusercontent.com/43481553/160607746-04bad915-1980-4ff9-9e4d-f72ada1bbba5.png)

2022-03-31 07:45 UTC, andre-code commented
Hi @lorenzo-cavazzi , thanks for your review.
I have added some changes to include the fetching cases in the Template Selector component, so the fetching messages should be displayed as part of the Selector component and not next to the Create Project button.
The appearance of the components in the project creation form (margin, fills, etc.) will be handled in the https://github.com/SwissDataScienceCenter/renku-ui/issues/1736 story.

This is ready for review 🙌

2022-03-31 11:55 UTC, ciyer requested changes
I think this is going in a great direction and will give us much more consistency in the UI! Since we are looking at this closely, I think we should take our time and get this right -- I have a few suggestions for improvements in that direction.

2022-03-31 11:55 UTC, ciyer commented on client/src/utils/components/formlabels/FormLabels.css
> +    font-size: 15px;
I don't think we should set the font size here -- this can cause the label to be out of sync with the other labels.

2022-03-31 11:55 UTC, ciyer commented on client/src/utils/components/formlabels/FormLabels.tsx
> +    <div className="helper-label"><Label>{ text }</Label></div>
I think we should use the react-strap `FormText` component for this: https://reactstrap.github.io/?path=/docs/components-forms--form-feedback

2022-03-31 11:55 UTC, ciyer commented on client/src/utils/components/formlabels/FormLabels.tsx
> +const LoadingLabel = ({ text }: LabelProps) => {
Incorporating the Loader is nice; I think I think we should use the react-strap `FormText` component for the label: https://reactstrap.github.io/?path=/docs/components-forms--form-feedback

2022-03-31 11:55 UTC, ciyer commented on client/src/utils/components/formlabels/FormLabels.tsx
> +    <Label className="input-hint">{ text }</Label>
I think we should use the react-strap `FormText` component for this: https://reactstrap.github.io/?path=/docs/components-forms--form-feedback

2022-03-31 11:55 UTC, ciyer commented on client/src/utils/components/formlabels/FormLabels.tsx
> +const ErrorLabel = ({ text }: LabelProps) => {
I think we should use the react-strap `FormText` component for this: https://reactstrap.github.io/?path=/docs/components-forms--form-feedback.

I think it would be good if the triangle were yellow for consistency of use.

2022-03-31 11:55 UTC, ciyer commented on client/src/utils/components/templateSelector/TemplateSelector.tsx
> +        <FontAwesomeIcon id={repositoryInfoId} className="ms-2 cursor-pointer" icon={faQuestionCircle} />
After looking at this in context, I think a blue "i" icon for information would be better here for consistency -- that's what we usually use for this kind of interaction. (I know you are just taking over what was there before, but since we are revisiting this component, we can go ahead and make some improvements).

2022-04-01 09:46 UTC, andre-code commented
Thanks @ciyer for the suggestions, the label components were updated to use reactstrap components. This PR is ready for review

2022-04-01 11:38 UTC, ciyer approved these changes
This is very, very nice! 🙌

2022-04-01 11:46 UTC, merged