1735 progress component
SwissDataScienceCenter/renku-ui pull request #1761
Opened 2022-03-29 14:53 UTC by andre-code

Closes #1735

/deploy renku-core=develop renku=tests-new-project-form-changes #persist

2022-03-30 09:16 UTC, ciyer requested changes
I like these animations a lot -- it will lead to a more engaging interface. 🎉 

There are few small thinks I would like to tweak, maybe you could play with the duration of the different sections and distribution of keyframes a bit, to achieve a smoother, less nervous final version.

2022-03-30 09:16 UTC, ciyer commented on client/src/utils/components/progress/Progress.css
> +    background-color: #C5CBCF;
Where did this color come from? Would it be possible to compute it from one of the style-guide colors?

2022-03-30 09:16 UTC, ciyer commented on client/src/utils/components/progress/Progress.css
> +    animation-duration: 5s;
This is a little too fast -- it makes me nervous watching. :) Could we make this `10s` or so?

2022-03-30 09:16 UTC, ciyer commented on client/src/utils/components/progress/Progress.css
> +    }
This one is also too fast for my eyes. Here is something that I think is in a improvement, but it could still be better, It think:

```
.progress-bar-indeterminate {
    width: 0;
    height: var(--progress_height);
    position: absolute;
    background-color: var(--bs-primary);
    transform-origin: 0 100%;
    animation-name: indeterminateAnimationWaiting;
    animation-fill-mode: forwards;
    animation-duration: 20s;
    animation-timing-function: linear;
    animation-iteration-count: infinite;
    animation-direction: normal;
}

@keyframes indeterminateAnimationWaiting {
    0% {
        width: 0;
        visibility: hidden;
    }
    20% {
        width: 100%;
        visibility: hidden;
        transform:  translateX(0) scaleX(0);
    }
    20.1% {
        width: 100%;
        visibility: visible;
        transform:  translateX(0) scaleX(0);
    }
    75% {
        width: 100%;
        visibility: visible;
        transform:  translateX(0) scaleX(0.4);
    }
    80% {
        width: 100%;
        visibility: visible;
        transform:  translateX(100%) scaleX(0.5);
    }
    80.1% {
        visibility: hidden;
    }
    82% {
        visibility: hidden;
        width: 0;
        transform:  translateX(0) scaleX(0);
    }
    82.1% {
        visibility: visible;
        width: 100%;
        transform:  translateX(0) scaleX(0);
    }
    95% {
        visibility: visible;
        width: 100%;
        transform:  translateX(0) scaleX(0.4);
    }
    100% {
        visibility: visible;
        width: 100%;
        transform:  translateX(100%) scaleX(0.5);
    }
}```

2022-03-31 08:30 UTC, andre-code commented
@ciyer thanks for the suggestions. I included them all :)
This is ready for review 🙌

2022-03-31 12:01 UTC, ciyer approved these changes
Looking forward to using this component and seeing it in use! 🎉

2022-04-01 07:09 UTC, merged