feat(client): use the progress indicator when importing the dataset (#1736)
SwissDataScienceCenter/renku-ui pull request #1774
Opened 2022-04-05 15:03 UTC by andre-code

### Description
This PR is to use the progress indicator component when the dataset import process is running.

####  Import the dataset into the existing project
![add dataset existing project progress indicator](https://user-images.githubusercontent.com/43388408/161721900-f5c9ba68-d83f-4fab-891f-ffa0db30aa12.gif)

####  Import the dataset into a new project
![add dataset new project progress indicator](https://user-images.githubusercontent.com/43388408/161722359-ff3c9289-5253-43bf-b80c-7b748d646e12.gif)

/deploy renku-core=develop renku=tests-new-project-form-changes #persist

2022-04-06 08:56 UTC, ciyer requested changes
Small suggestion for change in a string.

2022-04-06 08:56 UTC, ciyer commented on client/src/dataset/addtoproject/addDatasetStatus.js
> +          description="We've received your project information. This may take a while."
```suggestion
          description="Project is being created, afterwards the data set will be imported into it."
```

2022-04-06 09:35 UTC, andre-code commented on client/src/dataset/addtoproject/addDatasetStatus.js
> +          description="We've received your project information. This may take a while."
Suggestion included!

2022-04-08 07:54 UTC, ciyer approved these changes
👍

2022-04-08 08:12 UTC, merged