feat(client): use the progress indicator component when forking a project
SwissDataScienceCenter/renku-ui pull request #1775
Opened 2022-04-05 15:19 UTC by andre-code

### Description
This PR is to use the progress indicator component when forking a project

![for projeck progress indicator](https://user-images.githubusercontent.com/43388408/161758889-653d27c6-376e-445c-b72b-267abe6a642e.gif)

/deploy renku-core=develop renku=tests-new-project-form-changes #persist

2022-04-06 08:58 UTC, ciyer requested changes
Small change to the label.

2022-04-06 08:58 UTC, ciyer commented on client/src/project/new/ProjectNew.present.js
> +        description="We've received your project information. This may take a while."
```suggestion
        description="Project is being created."
```

2022-04-06 09:47 UTC, andre-code commented on client/src/project/new/ProjectNew.present.js
> +        description="We've received your project information. This may take a while."
Updated! :)

2022-04-08 07:56 UTC, ciyer requested changes
One small request: I know this isn't part of the PR, but since you are making changes to this code, could we switch the position of the Close and Fork buttons so that it is

    Close   Fork

That is, close on the left, fork on the right?

2022-04-08 09:06 UTC, andre-code commented
> One small request: I know this isn't part of the PR, but since you are making changes to this code, could we switch the position of the Close and Fork buttons so that it is
> 
> ```
> Close   Fork
> ```
> 
> That is, close on the left, fork on the right?

yes, position changed.

2022-04-08 12:38 UTC, ciyer approved these changes
👍

2022-04-25 12:27 UTC, merged