WIP feat: update ux dataset form
SwissDataScienceCenter/renku-ui pull request #1854
Opened 2022-05-17 11:41 UTC by andre-code

Draft: Update UX dataset form
 
 /deploy renku=000-tests-ui-2_0-next #persist

2022-05-20 09:59 UTC, lorenzo-cavazzi requested changes
The look is much better now! Very nice changes!

I added a few comments to keep some code coherent -- mostly cosmetics, and I know the code is already messy somewhere else.

The only thing I would change is in the Model. Is it really necessary to add extra properties to the fields? (see inline comment).

2022-05-20 09:59 UTC, lorenzo-cavazzi commented on client/src/project/datasets/change/DatasetChange.present.js
> +    addDatasetOptionSelected={"addDataset"}
```suggestion
    addDatasetOptionSelected="addDataset"
```
Not really something to fix, but I noticed you sometimes specify text in properties as `prop={"text"}` and sometimes `prop="text"`. It would make sense to keep it coherent when it's a fixed string

2022-05-20 09:59 UTC, lorenzo-cavazzi commented on client/src/project/datasets/import/DatasetImport.present.js
> +      addDatasetOptionSelected={"importDataset"}
```suggestion
      addDatasetOptionSelected="importDataset"
```

2022-05-20 09:59 UTC, lorenzo-cavazzi commented on client/src/utils/components/formgenerator/FormGenerator.present.js
> +          currentStatus={""}
```suggestion
          currentStatus=""
```

2022-05-20 09:59 UTC, lorenzo-cavazzi commented on client/src/utils/components/formgenerator/fields/FormLabel.js
> +      <InputLabel text={label} isRequired={required} isOptional={optional} />
Having both `isRequired` and `isOptional` seems redundant. Would it make sense to keep only one? Although I see it's already used like this somewhere else in the code

2022-05-20 09:59 UTC, lorenzo-cavazzi commented on client/src/model/Model.js
> +  OPTIONAL: "optional",
Isn't `OPTIONAL` just the opposite of `REQUIRED`?

2022-05-20 09:59 UTC, lorenzo-cavazzi commented on client/src/model/Model.js
> +  IMAGECONTROLSDISABLED: "imageControlsDisabled",
I don't particularly like adding more properties to the model. I feel we already have a bunch that should really not be here.
I guess there is another property to pilot when it's editable (or being edited). Do we need this one too?

2022-05-20 12:00 UTC, andre-code commented on client/src/utils/components/formgenerator/fields/FormLabel.js
> +      <InputLabel text={label} isRequired={required} isOptional={optional} />
It was done that way to keep the case where no action is required, for example when it has a default value or the field is disabled, for example for this form the Creators case, and for example in the new project form for Template source or the identifier.

2022-05-20 12:11 UTC, ciyer requested changes
Wow, the entire dataset experience is much better with these changes! 🎉 I agree with Lorenzo's suggestions to change the code, but the code is overall very good.

I have a few things regarding the appearance and experience that I wanted to mention:

1. Dataset Description

<img width="755" alt="image" src="https://user-images.githubusercontent.com/1196411/169524170-873b4473-608e-4094-bc76-e32d533d6231.png">

I think this field should be a little larger vertically -- it seems a little squashed. I think the _minimum_ size should allow display of two lines of text, but the expanding behavior of the component is otherwise nice.

Also, the help text is incorrect in this case: in this mode, you cannot use Markdown, but you can style the text using the tools on the tool bar.

2. Action display

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/1196411/169525350-0de8db91-0777-4b7c-bb57-32c05f025871.png">


When an add or modify action is running, we still show the left-hand action text (modify dataset in this case). I think we should not show this text and the progress indicator should take up the whole width.

2022-05-23 06:40 UTC, andre-code commented
> The look is much better now! Very nice changes!
> 
> I added a few comments to keep some code coherent -- mostly cosmetics, and I know the code is already messy somewhere else.
> 
> The only thing I would change is in the Model. Is it really necessary to add extra properties to the fields? (see inline comment).

Thank you very much for your review. I agree with all your suggestions, so you can find them implemented in the last 2 commits. 🙌

2022-05-23 06:44 UTC, andre-code commented
> Wow, the entire dataset experience is much better with these changes! 🎉 I agree with Lorenzo's suggestions to change the code, but the code is overall very good.
> 
> I have a few things regarding the appearance and experience that I wanted to mention:
> 
> 1. Dataset Description
> 
> <img alt="image" width="755" src="https://user-images.githubusercontent.com/1196411/169524170-873b4473-608e-4094-bc76-e32d533d6231.png">
> 
> I think this field should be a little larger vertically -- it seems a little squashed. I think the _minimum_ size should allow display of two lines of text, but the expanding behavior of the component is otherwise nice.
> 
> Also, the help text is incorrect in this case: in this mode, you cannot use Markdown, but you can style the text using the tools on the tool bar.
> 
> 2. Action display
> 
> <img alt="image" width="1085" src="https://user-images.githubusercontent.com/1196411/169525350-0de8db91-0777-4b7c-bb57-32c05f025871.png">
> 
> When an add or modify action is running, we still show the left-hand action text (modify dataset in this case). I think we should not show this text and the progress indicator should take up the whole width.

Thank you very much for the review.
It was a bit confusing to set the CKEditor height, so the library will probably need to be updated. The change to not display the form header when the progress indicator component is visible was implemented for the data set form and the project form.

2022-05-23 09:46 UTC, lorenzo-cavazzi submitted a review, later dismissed
:rocket:

2022-05-23 09:51 UTC, ciyer submitted a review, later dismissed
This looks very nice!

2022-05-23 12:28 UTC, lorenzo-cavazzi submitted a review, later dismissed

2022-05-23 14:56 UTC, lorenzo-cavazzi approved these changes

2022-05-23 14:56 UTC, merged