1812 search page
SwissDataScienceCenter/renku-ui pull request #1869
Opened 2022-05-30 08:26 UTC by andre-code

PR to integrate UI entity search and entity search api

/deploy

2022-05-31 10:17 UTC, ciyer requested changes
This is a big step towards offering a much better search experience! 🎉 

In general, it looks good and works very well.

I have some suggestions for small changes to the code and wording, which I have mentioned in the appropriate place. And here are some things I noticed in the UI.

### No search results found

(I like the sad face icon!)
<img width="758" alt="image" src="https://user-images.githubusercontent.com/1196411/171149866-9db534c0-6e42-4f52-8b82-bdf775d59ef4.png">

### Filter on mobile

The pop-up that goes to the left, right, and bottom edges of the screen looks strange. I think there should be some margin space on those sides.

<img width="503" alt="image" src="https://user-images.githubusercontent.com/1196411/171150491-7ad2dcbc-aab3-49dc-aa02-9dc3b3769a9c.png">

### Author filter

I do not think this filter does anything.

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/1196411/171151173-69bbe4e2-3860-4dee-8e02-2ca71021033e.png">

2022-05-31 10:17 UTC, ciyer commented on client/src/utils/components/searchResultsContent/SearchResultsContent.tsx
> +      { phrase ? phraseText : " We could not find any matching." }
```suggestion
      { phrase ? phraseText : " We could not find any matches." }
```

2022-05-31 14:58 UTC, andre-code commented on client/src/utils/components/quicknav/QuickNav.container.js
> +  const [currentPhrase, setCurrentPhrase] = useState("");
yes, it is necessary. The currentPhrase state is used to store the phrase that is updated each time the user types while KgSearchForm slice state is updated only when the text is ready to be queried (submit event), i.e. when the user presses enter or clicks the search button.

2022-05-31 15:02 UTC, andre-code commented
Thanks @ciyer for your review and suggestions. 😉
You are right, there was a bug with the query so the author was not working, fixed in the last commit.
I have also included all the suggestions about styles and texts.

2022-06-01 09:05 UTC, ciyer requested changes
This is very close! I found a few more things in testing.

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/1196411/171368024-2106afb9-e149-4857-8527-1f306dd7c71d.png">

2022-06-01 13:39 UTC, andre-code commented on client/src/utils/components/sortingEntities/SortingEntities.tsx
> +          <Label className="mx-2 sorting-label--desk">Sort By</Label> :
sure, done

2022-06-01 13:39 UTC, andre-code commented on client/src/utils/components/entitySearchFilter/EntitySearchFilter.tsx
> +      <h3 className="filter-label d-none d-sm-none d-md-none d-lg-block d-xl-block pb-3">Filter by</h3>
sure, done

2022-06-01 13:42 UTC, andre-code commented
> This is very close! I found a few more things in testing.
> 


Thanks @ciyer for your review, find the text hierarchy fix in the last commit.

2022-06-02 10:08 UTC, ciyer approved these changes
Looks great and works well on a variety of viewport sizes!

2022-06-07 09:24 UTC, merged