1804 UI server saving user last search queries
SwissDataScienceCenter/renku-ui pull request #1875
Opened 2022-05-31 09:52 UTC by andre-code

A middleware has been added in the ui server to log the user's last search queries (keywords). And the endpoint /ui-server/api/last-searches to request it. By default it logs the last 10 queries.

### to test

1. Authenticate in https://renku-ci-ui-1875.dev.renku.ch/
2. Request entities including the keyword in the query parameter e.g. https://renku-ci-ui-1875.dev.renku.ch/ui-server/api/kg/entities?query=*test*
3.  Request list of latest search queries https://renku-ci-ui-1875.dev.renku.ch/ui-server/api/last-searches/4

Closes #1804 

/deploy #persist

2022-05-31 11:57 UTC, lorenzo-cavazzi requested changes
The code looks good, I added a few comments to improve a bit the readability.

I'll add `#persist` to the deployment to these it "live"

2022-05-31 11:57 UTC, lorenzo-cavazzi commented on server/src/routes/helperFunctions.ts
> +    stop: (length || 0 ) - 1
instead of `length?` in the argument and then `(length || 0 )` later, I would assign a default value to the argument `length = 0` to make it explicit.
Also, the default case would be start=0 and stop=-1. Is that intended?

2022-05-31 11:57 UTC, lorenzo-cavazzi commented on server/src/routes/apis.ts
> +    const data = await getUserData(config.data.projectsStoragePrefix, token, storage, parseFloat(req.params["length"]));
```suggestion
    const data = await getUserData(config.data.projectsStoragePrefix, token, storage, parseInt(req.params["length"]));
```

2022-05-31 11:57 UTC, lorenzo-cavazzi commented on server/src/utils/middlewares/lastSearchQueriesMiddleware.ts
> +        if (![304, 200].includes(res.statusCode) || !token) {
This seems very specific. I would relax it to `res.statusCode >= 400`

2022-05-31 11:57 UTC, lorenzo-cavazzi commented on server/src/utils/middlewares/lastSearchQueriesMiddleware.ts
> +        if (![304, 200].includes(res.statusCode) || !token) {
It probably makes sense to change it also in the other middleware `lastProjectsMiddleware`

2022-05-31 14:41 UTC, andre-code commented on server/src/routes/helperFunctions.ts
> +    stop: (length || 0 ) - 1
Thanks Lorenzo, I updated to make it clear
yes, -1 would bring all records, in case of a positive number > 0 it would bring that amount of records. Also note that the number of records is limited by the user. For projects 20, for search queries 10.

2022-05-31 15:25 UTC, lorenzo-cavazzi commented
This looks great! It's basically ready to merge, but I tried it on the fly and I'm wondering if we should really strip the `*` from the query or not.
E.G: If I search for `query=flight*data`, then I get `{"queries":["flightdata"]}` in the list of the last queries. Looking for `flightdata` won't probably return the same result.
Maybe this is not really relevant since my understanding is that users won't need to add `*` -- and it doesn't even seem to work correctly atm when used in the middle of the sentence. Nevertheless `.replace(/\*/g, "")` doesn't seem necessary.
P.S: we can quickly discuss this during tomorrow's standup.

2022-06-01 08:36 UTC, andre-code commented
> This looks great! It's basically ready to merge, but I tried it on the fly and I'm wondering if we should really strip the `*` from the query or not. E.G: If I search for `query=flight*data`, then I get `{"queries":["flightdata"]}` in the list of the last queries. Looking for `flightdata` won't probably return the same result. Maybe this is not really relevant since my understanding is that users won't need to add `*` -- and it doesn't even seem to work correctly atm when used in the middle of the sentence. Nevertheless `.replace(/\*/g, "")` doesn't seem necessary. P.S: we can quickly discuss this during tomorrow's standup.

@lorenzo-cavazzi  In the UI is being attached to the query * at the beginning and the end is why it was being removed from here to save the query without *, but according to what you mentioned I have opted to leave the logic of removing and discarding what is not needed for the frontend. Thanks for your suggestion 🙌

2022-06-01 08:51 UTC, lorenzo-cavazzi approved these changes
Looks great!

P.S: we really need to add (at least) unit tests at some point. I will create an issue. Not strictly related to this PR, I just thought things like `lastSearchQueriesMiddleware` should be tested

2022-06-01 13:22 UTC, merged