feat: UI show the user last search queries
SwissDataScienceCenter/renku-ui pull request #1884
Opened 2022-06-07 11:11 UTC by andre-code

UI Last search queries

/deploy

2022-06-08 07:59 UTC, ciyer requested changes
This is a cool feature! 🎉  

I have a comment about how the API is structured and one small thing about the number of search results that are shown, but they should both be easy to address.

2022-06-08 07:59 UTC, ciyer commented on client/src/utils/components/quicknav/KgLastQueriesApi.ts
> +export const kgLastQueriesApi = createApi({
I like this approach a lot! The question is, though, what is the right scope for this RTK-Query API?

We also have the "recent-projects" API that is quite similar, and I think it makes sense to combine that (and other future endpoints) into a `recentUserActivityApi`. 

I don't think the other query needs to integrated as part of this PR, but we can prepare for it by using the name and setting the `baseQuery` to `/ui-server/api/`.

2022-06-08 07:59 UTC, ciyer commented on client/src/utils/components/quicknav/KgLastQueriesApi.ts
> +export const TOTAL_QUERIES = 5;
Do we store a total of 4 or 5 queries? I never see more than 4:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/1196411/172563519-2a67fc1d-3ab9-42a6-8b59-6d080d42c7c2.png">

2022-06-09 09:13 UTC, andre-code commented on client/src/utils/components/quicknav/KgLastQueriesApi.ts
> +export const kgLastQueriesApi = createApi({
Thanks, great suggestion. I moved the kgLastQueries to recentUserActivityApi.

2022-06-09 09:25 UTC, andre-code commented on client/src/utils/components/quicknav/KgLastQueriesApi.ts
> +export const TOTAL_QUERIES = 5;
The reason was that the last searches query also returns `*` and in the frontend we removed that option reducing the amount of results. I have added a change to always have the last 5 words if those exist.

2022-06-09 09:57 UTC, ciyer approved these changes
This is very nice to use!

2022-06-09 14:24 UTC, merged