build(chart): remove duplicates in client/server charts
SwissDataScienceCenter/renku-ui pull request #1998
Opened 2022-08-12 12:36 UTC by ciyer

Remove duplicate values from chart

2022-08-15 13:00 UTC, lorenzo-cavazzi requested changes
I think we might want to merge the URLs in the values so that we don't have something like `server.serverData.url` + `server.serverData.prefix` anymore, but just `uiServerUrl` or even better `server.url`. The same applies to similar values like `gatewayUrl` that currently comes from different sources: `gatewayUrl` for the client and `server.gateway.url` for the server.

In the PR, we define `ui.uiserverUrl` in the helpers taking it from `ui.server.*`, which is confusing and not coherent with what we wrote here https://github.com/SwissDataScienceCenter/renku/blob/master/helm-chart/values.yaml.changelog.md#upgrading-to-renku-0150 

I suggest aiming for the following structure:
```
ui:
  gatewayUrl:
  client:
    url:
    *
  server:
    url:
    *
  global:
    *
```

I would remove all the unnecessary `global.*` values, an probably also `ui.ingress` (is it actually used? If yes, then `ui.client.ingress` and its server counterpart are probably redundant). And give it a look to other values not used anymore, so that we have breaking changes only once and then we resume working with a clean values structure.

P.S: switching to `ui.gatewayUrl` and to `ui.server.url` will likely require changes to the server and/or client code. I don't mind if we keep them separate as `server.url.base` + `server.url.prefix` (easier to adapt the server code) or we just merge to `server.url` (easier to adapt for the client code) as long as we define them only once in the values.

2022-08-18 12:42 UTC, lorenzo-cavazzi requested changes
Thank you, this goes in the right direction!
I would change the `baseUrl` to `client.url` to follow the same structure of the gateway.
I'm also tempted to suggest dropping the `url`+`prefix` structure for the server. In that case, we would have just a full URL as `server.url`. The reason is that I find the naming a bit confusing since it's different than what we do with gateway and client; also, `url` is in fact what is usually defined as `origin`, and `prefix` is the `pathname`.
We might actually just limit to adding a comment to clarify that in the values, or maybe change the actual names so that they are `server.origin` and `server.pathname` (+ `server.port`).

Do you have any preference for how to handle that? I would probably go with the last suggestion (i.e. server.pathname + server.origin + server.port) or the first one (server.url, intended as full URL, and server.port -- that will require a little change to the config file to separate pathanme and origin).

2022-08-18 12:42 UTC, lorenzo-cavazzi commented on helm-chart/renku-ui/templates/ui-client-deployment-template.yaml
>                value: {{ .Values.baseUrl | default (printf "%s://%s" (include "ui.protocol" .) .Values.global.renku.domain) | quote }}
I would change also the `baseUrl` to be `client.url`

2022-08-18 12:42 UTC, lorenzo-cavazzi commented on helm-chart/renku-ui/values.yaml
>      url:
Should we add a comment to explain that this URL should be the "origin" (i.e. schema + domain) only?

2022-08-18 12:42 UTC, lorenzo-cavazzi commented on helm-chart/renku-ui/values.yaml
>      prefix: /ui-server
Should we add a comment to explain this is the "pathname"?

2022-08-18 12:53 UTC, ciyer commented
> Thank you, this goes in the right direction! I would change the `baseUrl` to `client.url` to follow the same structure of the gateway. I'm also tempted to suggest dropping the `url`+`prefix` structure for the server. In that case, we would have just a full URL as `server.url`. The reason is that I find the naming a bit confusing since it's different than what we do with gateway and client; also, `url` is in fact what is usually defined as `origin`, and `prefix` is the `pathname`. We might actually just limit to adding a comment to clarify that in the values, or maybe change the actual names so that they are `server.origin` and `server.pathname` (+ `server.port`).
> 
> Do you have any preference for how to handle that? I would probably go with the last suggestion (i.e. server.pathname + server.origin + server.port) or the first one (server.url, intended as full URL, and server.port -- that will require a little change to the config file to separate pathanme and origin).

I like your suggestions. I myself stumbled on the fact that the `url` was not actually the `url`, which is annoying. I think it should be possible to further clean up the terminology so that the structures have enough flexibility but with sensible names.

2022-08-18 14:37 UTC, ciyer commented on helm-chart/renku-ui/values.yaml
>      prefix: /ui-server
As discussed, this can just be dropped from the values file. We do not need to give admins control over the pathname.

2022-08-19 09:19 UTC, lorenzo-cavazzi requested changes
Thank you! This looks cleaner to me. Just a minor change on the hard-coded "/ui-server" value and it's ready to get merged

2022-08-19 09:19 UTC, lorenzo-cavazzi commented on helm-chart/renku-ui/templates/ui-server-deployment.yaml
> +              value: "/ui-server"
Keeping the env variable here and using a hard-coded string seems a bit counter-intuitive.
I would completely remove `SERVER_PREFIX` from here, and just hardcode it in server/src/config.ts in `SERVER.prefix`.

2022-08-22 08:18 UTC, lorenzo-cavazzi approved these changes
Looks good now, thanks!

2022-09-06 07:44 UTC, olevski requested changes
Sekhar, as we discussed I took a quick look at this helm chart PR. I think these changes look really good. 

Just two minor things.

2022-09-06 07:44 UTC, olevski commented on helm-chart/renku-ui/values.yaml
> +  port: 8080
There is really no point in making this a parameter in the values file. Just hardcode the value and remove the option to set it. I see that the value is not even properly templated in all places. I.e. it is hardcoded in the service and in the list of ports in the deployment. Also you do not even use this value to access the server, you use the service port which is different. You can leave the service port as is in the values file below.

2022-09-06 07:44 UTC, olevski commented on server/src/config.ts
> +    (process.env.GATEWAY_URL || SERVER.url + "/api") +
I know this was the same before you made this change. But does javascript have a `urljoin` or equivalent function that is smart about joining urls and avoiding double slashes in the final url. Not sure how much of a problem double slashes are in the first place.

2022-09-15 09:25 UTC, olevski approved these changes
Thank you!

2022-09-16 13:47 UTC, merged