1984 entity header
SwissDataScienceCenter/renku-ui pull request #2001
Opened 2022-08-16 10:04 UTC by andre-code

This PR add project header styles...

/deploy #persist

2022-08-22 12:13 UTC, ciyer requested changes
This looks very good, and already works well! 🎉 And the changes that are being done in parallel will make it work even better.

In testing, I found a few problems to fix:

- I cannot view datasets in Safari -- there is a crash in the TimeCaption (though it works in Chrome)
- On very old projects, ones that are not supported anymore, the "Linked Datasets" just shows the loading links spinner forever. (See https://renku-ci-ui-2001.dev.renku.ch/projects/cramakri/dataset-test-test-project/datasets)

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/1196411/185913531-589cc20a-5dac-4f7e-bae5-2d67dbdd6fb6.png">

- I do not understand what I'm supposed to be seeing in the second section of this dataset https://renku-ci-ui-2001.dev.renku.ch/projects/cramakri/dataset-test-project/datasets/image-dataset-3/

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/1196411/185914126-cd9f6169-3a73-42ef-bfae-2c66fd05fc62.png">

(That is a dataset with an image, but no files)

I also have a couple of comments in the code, but overall, this looks great and is close to being complete.

2022-08-22 12:13 UTC, ciyer commented on client/src/utils/components/entities/LinkedEntitiesByItemType.tsx
> +      noLinks: "No dataset has been added yet.",
I think ORDES should provide the text we show when there are no datasets, and also what interaction they want (show a button let users add a dataset?, do nothing?)

2022-08-22 12:13 UTC, ciyer commented on client/src/utils/components/entities/LinkedEntitiesByItemType.tsx
> +  const addDatasetLink = devAccess && itemType === "project" ?
I think ORDES should specify if they want an interaction here and what text they want shown.

2022-08-23 07:29 UTC, andre-code commented on client/src/utils/components/TimeCaption.js
> +    <ThrottledTooltip target={ref} tooltip={Time.toIsoString(time)} /> : null;
Yes, it has been fixed in the last commit

2022-08-23 07:32 UTC, andre-code commented
Hi @ciyer thanks for your review and suggestions. I have fixed all the crash cases in safari and also included the option to show an error message when the linked dataset list or project cannot be retrieved.
Everything about the product (texts and expected behavior) I will confirm to ORDES.

2022-08-23 11:05 UTC, ciyer approved these changes
Looks really great! I am approving. I know there are some questions with ORDES that might still be open. If you want, you can wait for those to be resolved, or you can merge and then make the changes in a later PR.

2022-08-24 10:13 UTC, merged