feat(server): websocket server
SwissDataScienceCenter/renku-ui pull request #2004
Opened 2022-08-19 16:19 UTC by lorenzo-cavazzi

_Still a draft_  :warning:
_For the documentation, check the README file in the `/server/src/websocket` folder._

Websocket channel available at `wss://<URL>/ui-server/ws`

/deploy #persist
re #1338

2022-08-24 14:19 UTC, ciyer requested changes
This is really fantastic! We have been waiting for this for a while, and I think it will enable many UI improvements going forward.

I have some minor comments in the code about how the server is configured and parameterized, but it all works well in postman, and I think the architecture is well constructed.

2022-08-25 09:45 UTC, lorenzo-cavazzi commented on server/src/config.ts
> +  enabled: convertType(process.env.WEBSOCKET_ENABLED) || true,
I would leave this setting there since I imagine some deployments not allowing wss channels at all -- although I hope this is a very rare occurrence :grin:

2022-08-25 09:47 UTC, lorenzo-cavazzi commented on server/src/config.ts
> +  delayStart: 3, // ? in seconds
I renamed the variables as suggested, it makes guessing the measure unit more immediate

2022-08-25 09:50 UTC, lorenzo-cavazzi commented on server/src/websocket/handlers/clientVersion.ts
> +function hearthbeatClientVersion(channel: Channel): void {
Ahah thank you for spotting this, I guess there is no hearth here :fire: :facepalm:

2022-08-25 11:23 UTC, lorenzo-cavazzi commented
Thank you for the thorough review! I addressed all the points, apart from leaving the `enabled` settings (see inline for more context)

2022-08-26 07:29 UTC, ciyer approved these changes
Fantastic!

2022-08-26 08:15 UTC, merged