feat(client): add WebSocket channel setup
SwissDataScienceCenter/renku-ui pull request #2013
Opened 2022-08-26 14:40 UTC by lorenzo-cavazzi

_This is still a draft_

/deploy renku-gateway=master #persist
fix #1338

2022-08-30 11:52 UTC, ciyer requested changes
This looks very good!

I have a few minor comments on some code improvements, but I overall like the structure.

2022-08-30 13:10 UTC, lorenzo-cavazzi commented on client/src/websocket/handlers/userHandlers.ts
> +    webSocket.send(JSON.stringify(new WsMessage({ requestServerVersion: true }, "init")));
This pattern is repeated in every `send` function of both the client and server WebSocket channel. I changed it everywhere so that all the `JSON.stringify(<content>)` become `(<content>).toString()`.

2022-08-30 13:12 UTC, lorenzo-cavazzi commented
Thank you for the review! I addresses the points you mentioned, and improved the logic to open/close the channel so that we won't miss the session cookies (or retry shortly after when that happens)

2022-09-01 09:46 UTC, ciyer submitted a review, later dismissed
This is great and works well. The occasional initialization problem on first load seems to be fixed now. Looking forward to using this to improve the UX!

2022-09-01 12:58 UTC, lorenzo-cavazzi commented
Thanks for the review!
I ended up force-pushing to this branch to keep 2 separate commits merged to master (WebSocket infrastructure vs moving the UI version check to WebSocket) instead of squashing the 10+ commits together.

Could you re-approve?

2022-09-01 15:41 UTC, ciyer approved these changes

2022-09-01 15:45 UTC, merged