feat(server): prevent gateway from setting anon users cookies
SwissDataScienceCenter/renku-ui pull request #2032
Opened 2022-09-12 13:22 UTC by lorenzo-cavazzi

This should prevent propagating the headers to set the anon-id related cookies from the gateway to the UI since that is managed by the UI server now.

/deploy #persist

2022-09-12 14:51 UTC, olevski commented on server/src/routes/apis.ts
> +      else {
@lorenzo-cavazzi will the part in the `else` clause not handle cases where `set-cookie` is only setting a single cookie? I think it will. Why do you have two separate cases for when there is one `set-cookie` vs many.

2022-09-12 15:07 UTC, lorenzo-cavazzi commented on server/src/routes/apis.ts
> +      else {
I guess I can merge the 2 parts to make it less confusing if you think it's for the good.
My idea was that, most of the time, this will match the first set of `if` hitting line 80. If we have another case having multiple cookies (this shouldn't happen atm), then the `for` cycle would handle it better but slower -- ok I know, the performance difference is negligible here.

2022-09-13 12:46 UTC, ciyer requested changes

2022-09-13 12:46 UTC, ciyer commented on server/src/routes/apis.ts
> +      else {
Can't this be simplified to 
```
    // Prevent gateway from setting anon-id cookies. That's not needed in the UI anymore
    const setCookie = null ?? clientRes.headers["set-cookie"];
    if (setCookie == null || setCookie.length == 0) return;
    const allowedSetCookie = [];
    for (const cookie of setCookie) {
      if (!cookie.startsWith(config.auth.cookiesAnonymousKey))
        allowedSetCookie.push(cookie);
    }
    if (allowedSetCookie.length < 1)
      clientRes.headers["set-cookie"] = null;
    else
      clientRes.headers["set-cookie"] = allowedSetCookie;
```

2022-09-14 14:00 UTC, olevski approved these changes

2022-09-14 16:37 UTC, merged