Shape Up #1 - Workflows UI
SwissDataScienceCenter/renku-ui pull request #2038
Opened 2022-09-15 13:59 UTC by lorenzo-cavazzi

_More info soon - stay tuned 📺_

/deploy #persist

2022-11-02 11:44 UTC, ciyer requested changes
Nice functionality in here! All of this code has already been reviewed before, but I found a few small things to improve in the code. The changes should be small, and then we can get this feature merged! 🎉

2022-11-02 11:44 UTC, ciyer commented on client/src/utils/components/entityHeader/EntityHeader.tsx
> +          { visibility ? (<VisibilityIcon visibility={visibility} className="" />) : null }
Why `className=""`? Couldn't that just be left out?

2022-11-02 11:44 UTC, ciyer commented on client/src/utils/components/entities/Duration.tsx
> +  );
I think it makes sense to make the description for the duration configurable. It is not necessary to add it to the props, but this way, it will be easy to make that change later.
```suggestion
  if (duration == null)
    return null;
  const elemId = `duration-${workflowId}`;
  const durationDesc = "Estimated runtime";

  return (
    <>
      <p id={elemId}>
        <span className="text-rk-text small">Runs in</span> {Time.getDuration(duration)}
      </p>
      <UncontrolledTooltip key={`duration-elem-${elemId}`} placement="top" target={elemId}>
        <span>{durationDesc}</span>
      </UncontrolledTooltip>
    </>
  );
```

2022-11-02 11:44 UTC, ciyer commented on client/src/workflows/Workflows.present.tsx
> +  const sorted = secondSorted.sort((a, b) => (a[orderBy] > b[orderBy]) ? 1 : ((b[orderBy] > a[orderBy]) ? -1 : 0));
I do not follow the logic here. I think the last invocation of sort will determine how the collection is sorted. Why not do it like this?:

```
function workflowCompare(orderBy, a, b) {
  const orderByCompare = (a[orderBy] > b[orderBy]) ? 1 : ((b[orderBy] > a[orderBy]) ? -1 : 0);
  const lastExecutedCompare = a["lastExecuted"].localeCompare(b["lastExecuted"]);
  const nameCompare = a["name"].localeCompare(b["name"]);
  if (orderByCompare !== 0) return orderByCompare;
  if (lastExecutedCompare !== 0) return lastExecutedCompare;
  return nameCompare;
}
[...]
 const sorted = filtered.sort((a, b) => workflowCompare(orderBy, a, b);
```

2022-11-02 15:53 UTC, lorenzo-cavazzi commented on client/src/utils/components/entityHeader/EntityHeader.tsx
> +          { visibility ? (<VisibilityIcon visibility={visibility} className="" />) : null }
Ops, that's an oversight -- I'll remove the `className` property

2022-11-02 16:25 UTC, lorenzo-cavazzi commented on client/src/workflows/Workflows.present.tsx
> +  const sorted = secondSorted.sort((a, b) => (a[orderBy] > b[orderBy]) ? 1 : ((b[orderBy] > a[orderBy]) ? -1 : 0));
The first pre-sorting is necessary because many properties used for `orderBy` might have the same value (E.G: author, runtime, ...) and the workflows API returns items in a non-deterministic order. Since we occasionally refresh the list of workflows, the order of the elements seems to change at random when clicking on a new workflow.

The second ordering is a request from the shape-up group: always order by lastest execution on ties -- sadly, that's not enough to remove the above pre-sorting since we still might have ties.

2022-11-02 16:26 UTC, lorenzo-cavazzi commented on client/src/workflows/Workflows.present.tsx
> +  const sorted = secondSorted.sort((a, b) => (a[orderBy] > b[orderBy]) ? 1 : ((b[orderBy] > a[orderBy]) ? -1 : 0));
I tried the proposed solution, but it requires a few adjustments because
* `localeCompare` doesn't seem to work on non-string elements (like dates) and
* it doesn't take into account that some elements might be missing.

2022-11-02 16:39 UTC, lorenzo-cavazzi commented
Thank you for the review!
I implemented all the suggestions apart from the new solution for sorting. I added a verbose explanation of the reasons behind adopting the overcomplicated multi-stage sorting, and what is not working in the suggested alternative -- I'm still open to update it if you think we should simplify it.

2022-11-03 15:57 UTC, ciyer approved these changes
Looks great! I think there still could be some improvements to that workflow sorting code, but I see that it is not as straightforward as I had hoped, and I think we can live with it as is for the time being.

2022-11-04 11:21 UTC, ciyer approved these changes
👍

2022-11-04 13:48 UTC, merged