fix(server): use the correct redis namespace
SwissDataScienceCenter/renku-ui pull request #2053
Opened 2022-09-28 14:54 UTC by olevski

The ui server was defaulting to using the `0` redis namespace which is reserved for the gateway.

This has not caused issues as far as I know because the likelihood of collisions is low.

But it is better to use a dedicated redis namespace for the ui-server and not put keys in the gateway's namespace.

/deploy #persist

2022-09-28 15:01 UTC, lorenzo-cavazzi requested changes
Thank you @olevski for the fix! :pray: 
Just a tiny change to keep it coherent with the other fields.

2022-09-28 15:01 UTC, lorenzo-cavazzi commented on server/src/config.ts
> +  database: parseInt(process.env.REDIS_DATABASE || "0"),
```suggestion
  database: convertType(process.env.REDIS_DATABASE) || 0),
```

2022-09-28 20:17 UTC, olevski commented
@lorenzo-cavazzi the change you suggested does not work because `convertType` returns `string | number | true` but typescript expects only `number` for that field. 

So what is the proper "typescript" way to resolve this? I am not really sure.

2022-09-29 08:00 UTC, lorenzo-cavazzi commented
I pushed the change to pass the `db` variable through the constructor where we can specify the expected type.

Your solution was the most reasonable way to do it in Typescript, but we introduced a custom convert function that doesn't throw errors so that a wrong config value wouldn't crash the server at the startup (ofc, depending on the variable, the server might crash just after :grin: )

2022-09-29 12:31 UTC, lorenzo-cavazzi approved these changes

2022-10-03 07:11 UTC, merged