feat: add star session progressbar
SwissDataScienceCenter/renku-ui pull request #2054
Opened 2022-10-03 09:15 UTC by andre-code

PR to add progressBar for status when start a session.

/deploy renku-notebooks=feat-detailed-status-message #persist

2022-10-04 11:14 UTC, ciyer requested changes
Thanks for showing the progress this morning -- I think this is look very good! I have added a couple of suggestions from our discussion, maybe they help, otherwise, just implement things as we discussed in the meeting.

2022-10-04 11:14 UTC, ciyer commented on client/src/notebooks/Notebooks.container.js
> +      return <div className="d-flex flex-column align-items-center fst-italic"><Loader />Fetching session data</div>;
As discussed in the call, this can be removed.

2022-10-04 11:14 UTC, ciyer commented on client/src/utils/components/progress/ProgressSteps.tsx
> +    case StatusStepProgressBar.WAITING:
An idea for realizing what we discussed in the meeting this morning: if **all** steps are in 'ready' or 'waiting' state, then display the first step in waiting state with a loader as well (so the same as executing).

This makes the logic here a bit more complex, but I think it is an ok tradeoff.

2022-10-07 11:07 UTC, ciyer approved these changes
Wow, this looks great and works very well! Very nice job done here! 🎉

2022-10-07 12:28 UTC, rokroskar commented
This is awesome! My only comment is that it's a bit verbose and showing too many steps.  - but we can leave it for now imho. Also, is there a reason to use a different style for "preparing session" vs "starting session"?

2022-10-07 21:11 UTC, ciyer commented
BTW, there is a comment in the discussion thread of #1879 that there should be an indication that the user is going to be put into an autosave branch in the startup information sequence. This was not included in this PR, so a new issue should be created for this part.

2022-10-10 07:52 UTC, andre-code commented
> This is awesome! My only comment is that it's a bit verbose and showing too many steps. - but we can leave it for now imho. Also, is there a reason to use a different style for "preparing session" vs "starting session"?

Yes, the idea is to unify the style or screens, but we defined to do it in another Issue.
https://github.com/SwissDataScienceCenter/renku-ui/issues/2064

2022-10-12 08:00 UTC, merged