Shape Up #1 - Third prototype: workflow browser with workflow details
SwissDataScienceCenter/renku-ui pull request #2065
Opened 2022-10-10 12:29 UTC by lorenzo-cavazzi

This prototype includes a fully working workflow browser and a first draft of the workflow details page.
Mind that the details components will be simplified and streamlined.

**What should be tested**
Using a couple of projects, we should verify that:
- The workflows browser works well, including the filters and the ordering
- The information should be consistent and up-to-date: this means the details components on the right are always in sync with the browser

![Screenshot_20221012_154517](https://user-images.githubusercontent.com/43481553/195359458-3b40fb06-1e31-40a3-b7de-329e64a22722.png)

renku-python reference: https://github.com/SwissDataScienceCenter/renku-python/pull/3135 
/deploy renku-core=workflow-ui-feature-branch #persist extra-values=core.sentry.dsn=https://0cc02f3a02d3474d9f7e90915873ab4d@sentry.dev.renku.ch/2,core.sentry.environment=renku-dev,core.sentry.enabled=true

2022-10-13 08:46 UTC, andre-code requested changes
This works very well 👏 
It's nice to see this functionality in action.
Do you have plans to include unit tests or e2e test in other PRs?
I left some minor requests otherwise this looks ready.

2022-10-13 08:46 UTC, andre-code commented on client/src/workflows/Workflows.state.ts
> +    let workflowsList: any;
Is it possible to define interfaces for these variables?

2022-10-13 15:48 UTC, lorenzo-cavazzi commented on client/src/utils/components/Tree.tsx
> +function TreeDetails({ backElement, waiting, workflow, workflowId }: TreeDetailsProps) {
That would make sense. I initially planned to make all the Tree elements more generic so they could be reused.
For the details component, maybe that doesn't make sense. Or, I could make a very generic `TreeDetails` container, and then render whatever `{children}` is passed. I would then make the `WorkflowTreeDetails` element as you suggested and move it to a Workflows file. Would that be a good solution?

2022-10-13 16:11 UTC, lorenzo-cavazzi commented on client/src/workflows/Workflows.state.ts
> +    let workflowsList: any;
That would contain either `error` or `result`. I swapped `any` with a generic `Record<string, any>`. I can make an interface to specify the 2 values if you think it's a valuable solution, but they will both be optional.

2022-10-14 07:11 UTC, andre-code commented on client/src/utils/components/Tree.tsx
> +function TreeDetails({ backElement, waiting, workflow, workflowId }: TreeDetailsProps) {
Yes, that would be a good solution, so far we don't have a tree component in our design system, but if we have the component we can apply in the future the definitions and styles easily to all components using that component.

2022-10-14 07:16 UTC, andre-code commented on client/src/workflows/Workflows.state.ts
> +    let workflowsList: any;
Or you can define the interface for a valid result and an error result and assign both to the variable.
```
interface WorkflowsList {
...
}
interface WorkflowsError {
...
}

let workflowssList: WorkflowsList | WorkflowsError;
```

2022-10-14 09:50 UTC, lorenzo-cavazzi commented on client/src/workflows/Workflows.state.ts
> +    let workflowsList: any;
As discussed offline, I went for a single interface with optional values `error?` and `result?`. Feel free to suggest otherwise if you think there is a better solution

2022-10-14 09:52 UTC, lorenzo-cavazzi commented on client/src/utils/components/Tree.tsx
> +function TreeDetails({ backElement, waiting, workflow, workflowId }: TreeDetailsProps) {
I went for the `{children}` solution. As you said, this makes the component more reusable :+1: 
P.S. I temporarily moved almost everything to the new component. In the next prototype, I'll add back some content to the generic `TreeDetails` component so that it handles the alignment/positioning.

2022-10-14 09:55 UTC, lorenzo-cavazzi commented
Thank you @andre-code for the review! I addressed your comments.

About this question:
> Do you have plans to include unit tests or e2e test in other PRs?

Yes, definitely! I prefer to postpone that to the last prototype since we kept changing the components a few times during the first phases and I didn't want to spend time on something temporary. It's on my list, together with using the RTK for storing the state instead of the 2 Coordinators

2022-10-14 13:24 UTC, andre-code approved these changes
lgtm 🚀

2022-10-14 13:27 UTC, merged