feat: add env variables in start session form
SwissDataScienceCenter/renku-ui pull request #2066
Opened 2022-10-10 19:00 UTC by andre-code

This PR add the env variables fields in start session form.

/deploy #persist

2022-10-12 09:06 UTC, lorenzo-cavazzi requested changes
Nice addition! It works well, but I feel the logic for storing the environment variables in the presentation component is redundant since you already store them in the redux store.

I would remove `const [environmentVariables, setEnvironmentVariables] = useState(` and use the variables coming from the redux model direcly.

2022-10-12 09:06 UTC, lorenzo-cavazzi commented on client/src/notebooks/NotebookStart.present.js
> +
This logic seems redundant to me.
If you are already save the status in the redux store, you can get it from `props.filters.environment_variables`.
Why saving it locally with a different format? Wouldn't it be easier to use only the redux store?

I feel the easiest thing would be adopting the pattern `[ { key: "", value: "" }]` also for the redux store, although that requires a few extra changes.

2022-10-12 09:06 UTC, lorenzo-cavazzi commented on client/src/model/RenkuModels.js
> +      environment_variables: { initial: [{ key: "", value: "" }] },
P.S: after finishing the review, I now understand this better.
I feel going for `[{ key: "", value: "" }]` is the best alternative since it's easier to add empty fields.

2022-10-12 11:36 UTC, andre-code commented
> Nice addition! It works well, but I feel the logic for storing the environment variables in the presentation component is redundant since you already store them in the redux store.
> 
> I would remove `const [environmentVariables, setEnvironmentVariables] = useState(` and use the variables coming from the redux model direcly.

Thanks @lorenzo-cavazzi for your review.
I agree to use the redux state in the environmentVariables component, that would be cleaner and remove some of the complexity.
Find the suggestion implemented in the last commit.

2022-10-12 13:23 UTC, lorenzo-cavazzi requested changes
This looks great! A tiny detail before merging.

I personally think we can start with an empty array for the variables and let the user click on "Add Variable" instead of showing an empty one since it's optional and probably only very few people will use them. The initial state would be as in the following screenshot.

If you agree, I think I added all the necessary changes as suggestions. If you prefer to keep an initial empty entry, I would then move `const DEFAULT_ENV_VARIABLES` away from the RenkuModel file to a "NotebooksSomething" file since it looks like a session-related constant.

![Screenshot_20221012_151822](https://user-images.githubusercontent.com/43481553/195353181-7f0079b2-6f94-409b-8432-dcd801d968f5.png)

2022-10-12 13:23 UTC, lorenzo-cavazzi commented on client/src/model/RenkuModels.js
> +
```suggestion
```

2022-10-12 13:23 UTC, lorenzo-cavazzi commented on client/src/model/RenkuModels.js
> +      environment_variables: { initial: DEFAULT_ENV_VARIABLES },
```suggestion
      environment_variables: { initial: [] },
```

2022-10-12 13:23 UTC, lorenzo-cavazzi commented on client/src/model/RenkuModels.js
> +  projectSchema, projectsSchema, statuspageSchema, userSchema, webSocketSchema, DEFAULT_ENV_VARIABLES
```suggestion
  projectSchema, projectsSchema, statuspageSchema, userSchema, webSocketSchema
```

2022-10-12 13:23 UTC, lorenzo-cavazzi commented on client/src/notebooks/Notebooks.container.js
> +import { DEFAULT_ENV_VARIABLES } from "../model/RenkuModels";
```suggestion
```

2022-10-12 13:23 UTC, lorenzo-cavazzi commented on client/src/notebooks/Notebooks.container.js
> +      environmentVariables : DEFAULT_ENV_VARIABLES;
```suggestion
      environmentVariables : [];
```

2022-10-14 09:11 UTC, lorenzo-cavazzi submitted a review, later dismissed
Lgtm! :rocket:

2022-10-14 13:44 UTC, lorenzo-cavazzi approved these changes

2022-10-14 17:43 UTC, merged