fix: fill new project form
SwissDataScienceCenter/renku-ui pull request #2089
Opened 2022-10-20 15:16 UTC by andre-code

This PR is to fix prefill of new project form

/deploy #persist

2022-10-24 08:50 UTC, lorenzo-cavazzi requested changes
Nice fix! There is one problem with visibilities since our code is a bit messy and we need to cover the selectable items too -- I suggested a dirty trick but feel free to explore other solutions if you wish.

I didn't get the change on `handleCheckbox`; could you provide an example link where the new code results in better output for the user? I tried a few but I'm probably missing something

2022-10-24 08:50 UTC, lorenzo-cavazzi commented on client/src/project/new/ProjectNew.container.js
> +        this.coordinator.setAutomated(data, undefined, this.projectsCoordinator);
This partially works because the visibilities get fetched, but the user can still select a wrong one -- try with a private namespace, and `private` will be selected but you will still be able to click on `public`.

A better solution would be to pass the `calculateVisibilities` function. A dirty trick for doing that would be passing a function where you save `this`, something like the following:
```
this.coordinator.setAutomated(data, undefined, (namespace) => {
    const self = this;
    self.calculateVisibilities(namespace);
});
```
And you change the code in the NewProjectCoordinator to invoke that function instead of invoking `projectsCoordinator.getVisibilities(namespaceAvailable);`

Ofc feel free to spend a bit more time on this and avoid the ugly `const self = this;` if you wish :smile:

2022-10-24 08:50 UTC, lorenzo-cavazzi commented on client/src/project/new/components/ShareLinkModal.js
> +      setInclude({ ...include, [target]: event.target.checked });
I'm not sure I get the logic here... What unexpected situation is this trying to cover? I quickly tried with the previous solution and I always get the same result as with this change.

The first `if (target === "template" &&` seems redundant since we don't need to set `templateRepo` in that case. And for the second case `else if (target === "templateRepo"` I couldn't find an example where the output is different. Do you have one?

2022-10-24 14:29 UTC, andre-code commented on client/src/project/new/ProjectNew.container.js
> +        this.coordinator.setAutomated(data, undefined, this.projectsCoordinator);
yes, thanks for the review. I found the option to use the function `setVisibilities` to update the visibilities state. Check it in the last commit

2022-10-24 14:37 UTC, andre-code commented on client/src/project/new/components/ShareLinkModal.js
> +      setInclude({ ...include, [target]: event.target.checked });
Yes, the case it covers is when the user select a custom template but do not select the template source that is needed to load the template.
In that case, when it load the link params the user will get the error:
![Screenshot 2022-10-24 at 16 32 04](https://user-images.githubusercontent.com/43388408/197551444-8837ded6-db78-4717-a7bf-5e20cfc17068.png)
With this check we make sure that all the necessary data is included in the creation of the link.

2022-10-24 14:38 UTC, andre-code commented
> Nice fix! There is one problem with visibilities since our code is a bit messy and we need to cover the selectable items too -- I suggested a dirty trick but feel free to explore other solutions if you wish.
> 
> I didn't get the change on `handleCheckbox`; could you provide an example link where the new code results in better output for the user? I tried a few but I'm probably missing something

Thanks for the review and reporting the visibilities status issue. Let me know if you have any further questions.

2022-10-25 06:44 UTC, lorenzo-cavazzi approved these changes

2022-10-25 09:22 UTC, merged