WIP Shape Up #1 - Apply Design
SwissDataScienceCenter/renku-ui pull request #2092
Opened 2022-10-25 11:36 UTC by andre-code

This PR is to apply design in workflows table.

/deploy renku-core=workflow-ui-feature-branch #persist

2022-10-26 12:26 UTC, lorenzo-cavazzi requested changes
This looks great! I added a suggestion in line; let me know if ye or if you prefer to keep it as is.
Apart from that, the only thing that bothers me a little bit is the vertical alignment when composite workflows are open. Exeuctions and run-time are not aligned on the same column. Also, the number of children workflows seems a bit too much on the right
![image](https://user-images.githubusercontent.com/43481553/198026730-c63d1fa5-d063-4e86-8153-669125ffec96.png)

2022-10-26 12:26 UTC, lorenzo-cavazzi commented on client/src/utils/components/Tree.tsx
> +  const elementStyle = { marginLeft: `${indentation * 30}px` };
Would it make sense to add 30px up to the 2nd level and then go 5 by 5 (or 10 by 10)? I feel that would preserve readability for the (few) cases with more nested workflows

2022-10-26 12:26 UTC, lorenzo-cavazzi commented on client/src/utils/components/Tree.tsx
> +  const elementStyle = { marginLeft: `${indentation * 30}px` };
So the total margin would be
L1 --> 30
L2 ----> 60
L3 ------> 70
L4 --------> 80

2022-10-27 11:06 UTC, andre-code commented
> This looks great! I added a suggestion in line; let me know if ye or if you prefer to keep it as is. Apart from that, the only thing that bothers me a little bit is the vertical alignment when composite workflows are open. Exeuctions and run-time are not aligned on the same column. Also, the number of children workflows seems a bit too much on the right.


Thanks @lorenzo-cavazzi for the review and suggestions, definitely aligning columns is a great improvement for data readability, and for margin in nested workflows I don't have workflows with more than 3 levels to check but the logic is in the code.
Something new is that I included also some improvements for small screens for the table and detail workflows. 

As the base branch changed I found it easier to put everything in one commit, I hope it's ok for the revision.

2022-10-27 11:45 UTC, andre-code commented
Thank you @ciyer for your review.
I have used the border box for filters (toggle element) as it is the design used in kg-search filters. The idea is to keep unified those elements that have in common their functioning as in this case where they are filters of the content shown below.
Regarding your second suggestion, I have included it.
Thanks again 🙂
Let me know if you have more questions

2022-10-27 12:39 UTC, lorenzo-cavazzi requested changes
It looks great!
I personally feel the dot showing the number of composite workflows looks better when aligned on the left, but this is a tiny detail and we can confront on that on Monday.

I played a bit with windows sizes and I noticed 2 details. I tested with Firefox.

* At any window size, after opening the details page, the left browser shows an unnecessary horizontal scroll bar -- maybe there is an extra margin somewhere?
  ![Screenshot_20221027_143213](https://user-images.githubusercontent.com/43481553/198285801-e73a2704-2d3c-49be-857e-6bb728666059.png)
* When reducing the width of the browser, components mess up a little bit: on the left screenshot they start compacting, on the right (smaller width) they expand again and overflow -- maybe they are no wrapping correctly?
  ![Screenshot_20221027_143019](https://user-images.githubusercontent.com/43481553/198285981-5f0ba107-6452-4a4a-b119-87c3d24118e4.png)

2022-10-27 13:07 UTC, ciyer approved these changes
🎉

2022-10-27 14:04 UTC, lorenzo-cavazzi approved these changes
This looks amazing!
As discussed offline, we will bring up the question on the small-width browser again at a later point. Let merge this :rocket:

2022-10-27 14:09 UTC, merged