Shape Up #1 - Fifth prototype fixes
SwissDataScienceCenter/renku-ui pull request #2093
Opened 2022-10-26 07:56 UTC by lorenzo-cavazzi

_work in progress_
/deploy renku-core=workflow-ui-feature-branch #persist

2022-10-27 16:44 UTC, ciyer requested changes
Overall, this looks good, and the things mentioned in the description work as explained.

The only thing I think should be changed in the code is that I think you can use `map` better to avoid having to introduce a counter. 

A minor comment: I find the "Loading" page a bit distracting

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/1196411/198349942-bd8dbc62-fb6d-4156-9c2e-f7187f79ed13.png">

I think it could be improved by just removing the "Loading details" header and leaving just the spinner.

2022-10-27 16:44 UTC, ciyer commented on client/src/workflows/Workflows.present.tsx
> +  let links = data.map((t: any) => {
If you provide a second argument, you can get the index in map.
```suggestion
  let links = data.map((t: any, num: number) => {
  
  }
```

2022-10-27 16:44 UTC, ciyer commented on client/src/workflows/Workflows.present.tsx
> +    const targets = t.sinks.map((target: any) => {
```suggestion
    const targets = t.sinks.map((target: any, targetCounter: number) => {
```

2022-10-27 16:44 UTC, ciyer commented on client/src/workflows/Workflows.present.tsx
> +    const newName = `[WF: ${targetWorkflow.name}] @ ${subItem.replace("/", " #")}`;
What does WF stand for? "Workflow"? I think it's ok to leave it as is ATM, but something that should be fixed before the feature is finalized.

2022-10-27 20:01 UTC, lorenzo-cavazzi commented on client/src/workflows/Workflows.present.tsx
> +    const newName = `[WF: ${targetWorkflow.name}] @ ${subItem.replace("/", " #")}`;
You are right, this is definitely not clear. We should come up with a better output
![image](https://user-images.githubusercontent.com/43481553/198386820-d6151d05-2354-4a53-9a77-e594bf7d725f.png)

2022-10-27 20:02 UTC, lorenzo-cavazzi commented on client/src/workflows/Workflows.present.tsx
> +  let links = data.map((t: any) => {
Ah, thanks! I added it in a separate commit since I will also initialize it

2022-10-27 20:07 UTC, lorenzo-cavazzi commented
Thanks for the review! I addressed the comments and removed the header above the spinner: that wasn't looking good. Here is the new output

![image](https://user-images.githubusercontent.com/43481553/198387787-79bc2e1f-838f-4b3b-88db-495ac4abbdbd.png)

2022-10-27 20:38 UTC, ciyer requested changes
I like the improvements! I think one variable increment slipped through -- I think the `num++` should be removed now.

2022-10-27 20:38 UTC, ciyer commented on client/src/workflows/Workflows.present.tsx
>      num++;
This looks a bug!

2022-10-28 09:21 UTC, ciyer approved these changes

2022-10-28 09:21 UTC, merged