fix: e2e tests after gitlab url changed
SwissDataScienceCenter/renku-ui pull request #2111
Opened 2022-11-02 11:01 UTC by andre-code

This PR is to fix e2e tests after gitlab url changed.

/deploy #persist

2022-11-02 11:51 UTC, ciyer requested changes
Thanks for investigating this! Your change made a variable unreferenced, so we can remove it.

2022-11-02 11:51 UTC, ciyer commented on e2e/cypress/support/authentication/gui_commands.ts
> +    else if (url.includes(`/auth/realms/Renku/protocol/openid-connect/auth`)) {
The assignment to GITLAB_PROVIDER can be removed since it is not used anymore.

2022-11-03 15:10 UTC, lorenzo-cavazzi approved these changes

2022-11-03 15:11 UTC, ciyer approved these changes
Thanks for sorting this out!

2022-11-03 15:14 UTC, merged