feat(server): Add pull session status websocket handler (#2016)
SwissDataScienceCenter/renku-ui pull request #2145
Opened 2022-11-16 16:16 UTC by andre-code

PR to add session status websocket handler.

Related #2016 

/deploy #persist

2022-11-30 15:10 UTC, lorenzo-cavazzi commented on server/src/websocket/handlers/sessions.ts
> +        channel.data.set("sessionStatus", cleanStatus);
Since we use `cleanStatus` just to compare with the previous one, can't we just store a hash of the stringified object?

2022-11-30 15:11 UTC, lorenzo-cavazzi commented on server/src/api-client/index.ts
> +  async sessionStatus(authHeathers: Record<string, string>): Promise<Response> {
This is just a cosmetic detail: can we call it `getSessionStatus` to make it clear it's a function to get some data?

2022-12-01 15:37 UTC, andre-code commented on server/src/api-client/index.ts
> +      options.headers.set("cookie", newCookies.join("; "));
thanks, I have moved to add the cookie to the wsRenkuAuth function

2022-12-01 15:37 UTC, andre-code commented on client/src/App.js
> +        this.webSocket?.send(JSON.stringify(new WsMessage({}, "pullSessionStatus")));
true 😉, added in the onopen function

2022-12-01 15:53 UTC, andre-code commented on client/src/utils/helpers/url/Url.js
> +}
added unit tests👌

2022-12-01 15:56 UTC, andre-code commented on server/src/websocket/handlers/sessions.ts
> +        channel.data.set("sessionStatus", cleanStatus);
if we make a hash of the object to save it in the channel then the comparison would be hash vs hash of the new state and it is not recommended since there is no guarantee that the order of the properties in the object will always be the same, this also applies after the cleanup.

2022-12-01 16:44 UTC, lorenzo-cavazzi requested changes
Great, almost there! I have just another detail on how we handle server-side headers so that we can keep that coherent with the changes already done in the `kg-search` branch.

2022-12-01 16:44 UTC, lorenzo-cavazzi commented on client/src/websocket/index.ts
> +
The `model.setObject` function gets invoked just before `startPullingSessionStatus`. In the past, it happened that the effect wasn't immediate and it took a moment before `model.get` can return the correct value. I suggest removing the section
```
if (model.get("open") && targetWebSocket.readyState === targetWebSocket.OPEN)
```
and moving the `startPullingSessionStatus` invocation (see the other comment below)

2022-12-01 16:44 UTC, lorenzo-cavazzi commented on client/src/websocket/index.ts
> +    startPullingSessionStatus(webSocket);
I would move this in the `if (webSocketOpen) {` block above so that we don't need to check for the `model` status in the function. Also, a `model.get` is occasionally unreliable if invoked just after the corresponding `model.set`

2022-12-01 16:44 UTC, lorenzo-cavazzi commented on client/src/utils/helpers/url/Url.test.js
> +  });
Could we add a test to verify that `"projects/namespaceProject/session"` tests `false`? Just in case someone calls the project `session` :grin: 
P.S: better to verify first that other parts of the UI work well in that case. If not, we can ignore this case

2022-12-01 16:44 UTC, lorenzo-cavazzi commented on server/src/authentication/middleware.ts
> +  return headers;
This is the right place where to handle the anonymous users' case, but the change seems inconsistent with what we did in the `kg-search` PR.
What about keeping the `Record<string, string>` approach and we re-work things so that we get something like:

```
 if (tokens) {
    const value = config.auth.authHeaderPrefix + tokens.access_token;
  return { [config.auth.authHeaderField]: value };
}
else {
    const value = sessionId;
return {[config.auth.cookiesAnonymousKey]: value}  
}
```

Then the API would be similar to this: https://github.com/SwissDataScienceCenter/renku-ui/pull/2170/files#diff-05130c6c244b058adb42428a05517effbe3d9f809cc76224e7552b3cce1b4d89

2022-12-01 16:44 UTC, lorenzo-cavazzi commented on server/src/websocket/handlers/sessions.ts
> +        channel.data.set("sessionStatus", cleanStatus);
Can't use alphabetically order servers so that we won't have inconsistencies? Altough I remember trying this is the past and the ordering was consistent with the start order of the servers, so it might not be necessary. We are saving a lot of data just to compare 2 strings.
I suggest either giving it a try now or, if you prefer, we can make a follow-up issue time-limited to 1 day to try that change and see if it works.

2022-12-05 09:41 UTC, andre-code commented on server/src/authentication/middleware.ts
> +  return headers;
👌, I went back to using Record instead of Header to make it easier to rebase with the kg-search branch.

2022-12-05 14:05 UTC, lorenzo-cavazzi requested changes
Great! This works well!
I tested a bit more with anonymous users and I submitted a change to clean the headers (it should work but give it a quick test) along with a couple of other cosmetic changes. Nothing big, the PR is basically ready.

Also, give a run to `npm run lint` on the "server" folder. There are a couple of lining errors but somehow the tests are not failing on that
![image](https://user-images.githubusercontent.com/43481553/205655656-2361adad-5570-44c4-b912-ddf2b1134b6a.png)

2022-12-06 11:03 UTC, lorenzo-cavazzi approved these changes
This works well! Let's merge it :rocket:

2022-12-06 17:15 UTC, merged