WIP feat: add namespace api
SwissDataScienceCenter/renku-ui pull request #2176
Opened 2022-11-30 11:18 UTC by andre-code

PR to fix fork component

/deploy #persist

2022-12-02 09:45 UTC, ciyer approved these changes
Code looks great! Good to see these modernizations getting implemented. I tried forking a few projects, and everything worked as before as far as I can tell.

2022-12-05 10:52 UTC, lorenzo-cavazzi requested changes
All works very well!
With RTK, we have a few extra names for functions. How do you feel about always starting with a verb that describes the action (e.g. `get`, `set`, `delete`...)?

2022-12-05 10:52 UTC, lorenzo-cavazzi commented on client/src/features/projects/ProjectApi.ts
> +    namespaces: builder.query({
I suggest trying to start the RTK Query functions with a verb that explains the action.
Here it would be `getNamespaces` instead of `namespaces`. Similar pattern for the other endpoints.
Following the current naming convention, the exported API would become something like `useGetNamespacesQuery` that makes it clear what the action is.

2022-12-05 10:52 UTC, lorenzo-cavazzi commented on client/src/utils/customHooks/UseGetProjects.ts
> +function useGetProjects() {
Instead of `GetProjects`, should that be `GetUserProjects`?

2022-12-05 12:54 UTC, andre-code commented on client/src/features/projects/ProjectApi.ts
> +    namespaces: builder.query({
> All works very well! With RTK, we have a few extra names for functions. How do you feel about always starting with a verb that describes the action (e.g. `get`, `set`, `delete`...)?

Thanks for your suggestions, I have implemented them in the last commit. 🙌

2022-12-05 12:55 UTC, andre-code commented
> All works very well! With RTK, we have a few extra names for functions. How do you feel about always starting with a verb that describes the action (e.g. `get`, `set`, `delete`...)?

Thanks for your suggestions, I have implemented them in the last commit. 🙌

2022-12-05 14:40 UTC, lorenzo-cavazzi approved these changes
Lgtm :rocket: 
P.S. Do you mind opening another issue to migrate all the other APIs from the `ProjectsCoordinator` (I saw it's mentioned here https://github.com/SwissDataScienceCenter/renku-ui/issues/2157 )? Since you worked on this, you know better than me which parts are left :wink:

2022-12-05 17:43 UTC, merged