Integrate test-renku-cypress action
SwissDataScienceCenter/renku-ui pull request #2182
Opened 2022-12-01 12:27 UTC by ciyer

WIP

/deploy #cypress

2022-12-01 17:20 UTC, ciyer commented
# Testing

Try commands like 
```
/deploy #persist #notest #cypress renku=update-renku-to-use-new-gitlab-chart
```

2022-12-05 13:24 UTC, lorenzo-cavazzi requested changes
I would remove the timeout for now and rely on the default (that we can better adjust later).
Otherwise, all good! Thanks for going through the renku-actions repo and implementing all the necessary logic!

As you suggested, let's wait for the referenced action to be merged before merging this

2022-12-05 13:24 UTC, lorenzo-cavazzi commented on .github/workflows/acceptance-tests.yml
> +          test-timeout-mins: "20"
Should we try to leave this out for now and rely on the default timeout of the action? It would be nice to set that to a proper value so that we don't need to adjust it in every repo where the actions are used (P.S. default is 60 mins iirc, but it's fine since the Selenium tests last longer anyway -- we can re-adjust once we add more tests and have a better estimation of the expected runtime)

2022-12-08 15:27 UTC, lorenzo-cavazzi approved these changes
Lgtm! It's great to have the cypress test available in the UI!

2022-12-09 09:41 UTC, lorenzo-cavazzi approved these changes

2022-12-09 11:04 UTC, merged