WIP feat: get namespaces owned only when fork a project
SwissDataScienceCenter/renku-ui pull request #2187
Opened 2022-12-05 10:49 UTC by andre-code

PR to fetch namespaces owned only for fork and create projects.

/deploy #persist

closes #2027

2022-12-09 10:54 UTC, lorenzo-cavazzi submitted a review, later dismissed
This looks good!
I suggest using a wrapper instead of creating the old "NewProjectCoordinator" in other contexts for the time being -- I added a description inline but I'm also happy to implement it if the comment is not clear.

I've noticed a detail with visibilities: when creating a new project, while re-computing the available visibilities, it doesn't show the temporary loader. The behavior is correct on the Fork tho. 
I added a gif to explain it better (the comparison is PR vs DEV since I didn't notice it was already working well on forks also in the PR)

![Peek 2022-12-09 11-29](https://user-images.githubusercontent.com/43481553/206685992-44f3725c-82ed-4da4-bec6-16dc37859a18.gif)

P.S. the local e2e tests are failing; it's probably necessary to update them.

2022-12-09 10:54 UTC, lorenzo-cavazzi commented on client/src/App.js
> +                props.client, props.model.subModel("newProject"), props.model.subModel("projects"))}
I understand the reason for this, but it feels a bit weird importing and creating the `NewProjectCoordinator` here in the App (or in the `AddDatasetNewProject` section).
What about adding a temporary wrapper?
This would mean creating a `class NewProjectWrapper` in the "ProjectNew.coordinator.js" file that takes the props, create the coordinator and passes it as a prop to the functional component. And that can be exported as `export { NewProjectWrapper as NewProject}`
That way, once we remove the wrapper, we don't need to modify the code wherever we use `NewProject` but just clean up the  "ProjectNew.coordinator.js" content.
P.S: I realize this is harder to explain than to implement. I'm happy to push a commit with this change.

2022-12-09 10:54 UTC, lorenzo-cavazzi commented on client/src/project/new/ProjectNew.state.js
> +      warnings["title"] = "Fetching projects to avoid duplicated projects...";
```suggestion
      warnings["title"] = "Fetching projects to prevent duplicates...";
```

2022-12-09 11:02 UTC, ciyer requested changes
This looks very good! When reviewing the code, I noticed a couple of small things. The first one was there before your code, but since we are making changes, I think it would make sense to improve.

2022-12-09 16:05 UTC, lorenzo-cavazzi commented
Another detail: could you incorporate the fix to the `getSlugAndReset` function from here? https://github.com/SwissDataScienceCenter/renku-ui/pull/2209

It's just a tiny change, from this line
> return `${creation.newNamespace}/${creation.newName}`;

to this line
> return `${creation.newNamespace}/${creation.newNameSlug}`;

2022-12-12 14:38 UTC, andre-code commented on client/src/App.js
> +                props.client, props.model.subModel("newProject"), props.model.subModel("projects"))}
sure, added the wrapper

2022-12-12 14:40 UTC, andre-code commented on client/src/project/new/ProjectNew.state.js
> +    } while (!templates);
cool, I added a counter to stop the loop if the resource has not been stopped/find after ˜60sec.

2022-12-12 14:41 UTC, andre-code commented on client/src/project/new/ProjectNew.container.js
> +    projectsMember,
because it is used in the function called in the useEffect, if the data changes, it must call the function again.

2022-12-12 14:42 UTC, andre-code commented
thanks team for your review, I added all your suggestions 💪

2022-12-13 14:30 UTC, lorenzo-cavazzi reviewed
This works very well!

The acceptance tests seem to break at project creation. Is it possible that a change in this PR breaks them?

2022-12-13 15:19 UTC, andre-code commented
> This works very well!
> 
> The acceptance tests seem to break at project creation. Is it possible that a change in this PR breaks them?

Thanks @lorenzo-cavazzi I re-deployed everything because I can't reproduce the error locally 🤞.

2022-12-23 13:49 UTC, ciyer approved these changes
The changes look good! There were some problems with the tests because the test user had thousands of projects and some of the actions were taking longer now, but those problems have now been fixed.

2022-12-23 14:22 UTC, merged