chore(client): update links to documentation
SwissDataScienceCenter/renku-ui pull request #2199
Opened 2022-12-07 14:22 UTC by lorenzo-cavazzi

Update some outdated links to documentation.

/deploy #notest #persist
fix #2197

2022-12-08 09:51 UTC, ciyer requested changes
The new links work! I noticed that one of the links navigates within the same browser tab, whereas we probably want to open a new tab/window.

2022-12-08 09:51 UTC, ciyer commented on client/src/project/settings/ProjectSettings.present.js
> +      way. <a href={Docs.rtdTopicGuide("customizing-sessions.html")}>
This navigates the browser to the documentation page, but I think we want to have it open in a new page (e.g., using `ExternalLink` instead of `a`).

2022-12-08 11:52 UTC, lorenzo-cavazzi commented
Thank you for the review. I swapped the anchor with an `ExternalLink` component as suggested.
I included in the same PR a minor fix to the "start session" page. The bug prevented one of the documentation links from showing up correctly for some users.

Now the "We found unsaved work" text should appear in every repo where you have an own autosave

![Screenshot_20221208_124926](https://user-images.githubusercontent.com/43481553/206439810-7076fc60-02d1-4929-8be1-626251badba1.png)

2022-12-08 15:20 UTC, lorenzo-cavazzi commented
Ooops, I accidentally fixed another anchor element :facepalm: 
I added the correct fix now

2022-12-08 17:02 UTC, lorenzo-cavazzi commented
fix #2204

2022-12-09 09:41 UTC, ciyer approved these changes
Looks good!

2022-12-09 09:43 UTC, merged