WIP feat: add new header styles
SwissDataScienceCenter/renku-ui pull request #2231
Opened 2022-12-16 14:23 UTC by andre-code

PR to add new header styles

/deploy #persist

2022-12-20 08:31 UTC, ciyer requested changes
This looks really, really great! 🎉  I like the code and the use of grid layout. I just have a small comment about extracting some shared code to a function.

2022-12-20 08:31 UTC, ciyer commented on client/src/dataset/Dataset.present.js
> +
I see this code in at least one other place. I think it would be good to extract a shared utility function.

2022-12-20 08:31 UTC, ciyer commented on client/src/dataset/list/DatasetList.present.js
> +        imageUrl: dataset.images?.length > 0 ? dataset.images[0]["_links"][0].href : undefined,
See comment about extracting this to a function.

2022-12-20 08:53 UTC, lorenzo-cavazzi requested changes
This looks great!
I have an inline comment, but I noticed it is almost the same comment you already got from @ciyer 

Two other details:

* The project warning icon doesn't show the cursor for links (see screenshot). It also looks vertically misaligned, could you check that? Maybe it's because the text is in a `div` element instead of a text element.
  ![Screenshot_20221220_091134](https://user-images.githubusercontent.com/43481553/208624544-9a87ca4e-098e-44ba-82d8-a7c9b718b27b.png)

* On Firefox, the start button wrap word
  ![Screenshot_20221220_090326](https://user-images.githubusercontent.com/43481553/208624732-2dc00036-ecac-4875-b2f2-53dd7f56c856.png)

2022-12-20 08:53 UTC, lorenzo-cavazzi commented on client/src/dataset/Dataset.present.js
> +      dataset.images[0]["_links"][0].href : undefined;
If `dataset.images` is an array but contains no links, the application will crash.
Should we do a more conservative check here and also verify that `_links` exists, is an array, and contains elements?

2022-12-20 08:53 UTC, lorenzo-cavazzi commented on client/src/dataset/list/DatasetList.present.js
> +        imageUrl: dataset.images?.length > 0 ? dataset.images[0]["_links"][0].href : undefined,
Same comment on testing `images[0]["_links"][0].href` before using it

2022-12-20 15:29 UTC, andre-code commented
@ciyer @lorenzo-cavazzi thanks for your review.
I have added a new function to extract the image url from the dataset and some unit tests for that function.

I have also included the cursor pointer for the project status indicator, as for the start session button there is another PR #2243  to implement the new styles for that button and there that problem does not exist. So in this case we are not going to include a solution for that.

2022-12-21 07:47 UTC, lorenzo-cavazzi requested changes
Great, the changes fix the icon!
I suggested a tiny code change. Otherwise, ready to go from my side :rocket:

2022-12-21 07:47 UTC, lorenzo-cavazzi commented on client/src/dataset/DatasetFunctions.js
> +  }
```suggestion
  try {
    return images[0]["_links"][0].href;
  }
  catch {
    return undefined;
  }
```
Testing for the length of the first array seems unnecessary since we rely on `try/catch` for all the other unexpected cases (and the `getDatasetImageUrl` function is always invoked after a `images?.length > 0 ?` in the code).

2022-12-21 12:39 UTC, lorenzo-cavazzi approved these changes
Lgtm! :rocket:

2022-12-23 09:31 UTC, ciyer approved these changes
Looks great -- both the new design and the code!

2022-12-23 11:21 UTC, merged