WIP add image input
SwissDataScienceCenter/renku-ui pull request #2246
Opened 2022-12-20 14:43 UTC by andre-code

PR to add image editor.

/deploy #persist

2023-01-04 10:14 UTC, ciyer requested changes
Very nice implementation. The edit feature looks good and works well!

I have a few minor things that could be improved.

* It was not immediately obvious that I could reposition the center of the image. I think either adding some text to say that you can reposition the image or some controls (arrows) to move the center would make this clearer

* It would be nice to have a "Reset" button to go back to how the image looked in the beginning.

* The image "moves" when switching to "Edit," even though I did not reposition the image

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1196411/210531801-c93a1c89-919d-4685-8430-03b929f460b4.png">

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1196411/210532005-c05e6b35-81e0-4ada-bf54-837b8ac1e649.png">

2023-01-04 10:14 UTC, ciyer commented on client/src/model/RenkuModels.js
> +    maxSize: 10000 * 1024,
This seems like a *very* high size limit to me. I can understand wanting to permit images larger than 200KB, but 10MB seems really big. I think 2MB would be a good _big_ image size.

2023-01-04 10:57 UTC, lorenzo-cavazzi commented on client/src/model/RenkuModels.js
> +    maxSize: 10000 * 1024,
This is just for selecting the image, the uploaded one should be resized/downgraded to <200kb.
We can allow for bigger images here. Maybe users wish to take just a tiny part of a bigger image (E.G. I often take a full-screen screenshot and use just a tiny part from it -- that would be bigger than 2MB)

2023-01-06 14:59 UTC, ciyer requested changes
I like the new changes, I think this works very well!

I found one small problem, which is that the old images seem to be cached in the dataset. Try the following:
- create a dataset (with an avatar image)
- change the avatar

Then the UI will still show the old image. If you *refresh* the page, the new image will appear, but not until then.

2023-01-10 08:05 UTC, andre-code commented
> I like the new changes, I think this works very well!
> 
> I found one small problem, which is that the old images seem to be cached in the dataset. Try the following:
> 
> * create a dataset (with an avatar image)
> * change the avatar
> 
> Then the UI will still show the old image. If you _refresh_ the page, the new image will appear, but not until then.

Thanks for reporting this, I have added a workaround to display the latest image available. 
FYI, Gitlab returns the same url after editing so it was necessary to add an extra value in the url to force the browser to fetch the latest image.

2023-01-10 10:14 UTC, ciyer approved these changes
👍

2023-01-10 11:33 UTC, merged