test: eliminate console errors and warnings in unit tests (#2228)
SwissDataScienceCenter/renku-ui pull request #2293
Opened 2023-01-11 17:41 UTC by andre-code

PR to eliminate console errors and warning in unit tests.

Close #2228 

/deploy renku=000-cypres-tests-new-search #persist #cypress

2023-01-13 12:43 UTC, lorenzo-cavazzi requested changes
The errors are all gone :tada: 

I'm not sure about manually implementing a sanitizing function. That doesn't seem to work since I see extra code blocks elements . I added a suggestion inline.
In general, we might want to sanitize the pure text before it's wrapped by HTML elements.

![Screenshot_20230113_133633](https://user-images.githubusercontent.com/43481553/212322496-41effa66-0a19-458f-8699-90166c0d8741.png)

2023-01-13 12:43 UTC, lorenzo-cavazzi commented on client/src/file/FilePreview.tsx
> +
Should we consider using a sanitizing function from a library instead of writing our own? I see we are already using `DOMPurify` somewhere else.
Maybe `DOMPurify.sanitize` already does what we need

2023-01-16 11:15 UTC, andre-code commented on client/src/file/FilePreview.tsx
> +
thanks @lorenzo-cavazzi  for your review, unfortunately `DOMPurify.sanitize` does not escape the HTML which is what the unit test warning refers to.

I've removed the error from the displayed `<code>`, so now we don't have the warning and the code displays just fine as before.

2023-01-16 12:59 UTC, lorenzo-cavazzi approved these changes
I swapped the custom sanitize function with the one from `DOMPurify`.

If this looks ok to you. let's merge it. Otherwise, we can look for a different solution.

2023-01-16 14:57 UTC, merged