Revive storybook
SwissDataScienceCenter/renku-ui pull request #2297
Opened 2023-01-13 13:47 UTC by ciyer

Changes that allow storybook to work with the react-scripts v5 environment. 

Problems remain with the following components

- FileUploaderInput
- ListBar
- ListCard
- LoginAlert
- SortingEntities

But the others should work.

2023-01-13 17:27 UTC, ciyer commented
Please check that after installing the dependencies, you can still use telepresence.

2023-01-16 08:12 UTC, lorenzo-cavazzi requested changes
Nice to have Storybook back and working!
Can we temporarily remove the broken components (and create a follow-up issue)? When I load one of them, I can't use Storybook anymore unless I move to another component and reload the whole page

![image](https://user-images.githubusercontent.com/43481553/212628639-8385e10a-5c97-432c-b087-77247c07cb81.png)

2023-01-16 08:12 UTC, lorenzo-cavazzi commented on client/.storybook/preview.js
> +const store = createStoreWithEnhancers({}, [withReduxEnhancer]);
This is not used. Was it an attempt to inject the store? If that's the case, should we add a comment to clarify why it's not used?

2023-01-16 09:26 UTC, ciyer commented on client/.storybook/preview.js
> +const store = createStoreWithEnhancers({}, [withReduxEnhancer]);
You are right, this is a little confusing! It is how the documentation says you should introduce the redux store https://storybook.js.org/addons/@dreamworld/addon-redux/, but I added an export so that the value does not go unused.

2023-01-16 09:28 UTC, ciyer commented
> Nice to have Storybook back and working! Can we temporarily remove the broken components (and create a follow-up issue)? When I load one of them, I can't use Storybook anymore unless I move to another component and reload the whole page
> 
> ![image](https://user-images.githubusercontent.com/43481553/212628639-8385e10a-5c97-432c-b087-77247c07cb81.png)

For info, you can just click the "x close" button there and then continue to use storybook, but I agree that disabling the broken storybooks is better, and I have added a commit that does this.

2023-01-16 09:43 UTC, andre-code submitted a review, later dismissed
Thanks @ciyer , happy to see this working again! 
I have tested telepresence and the storybook components that should work and those work perfect.
Like @lorenzo-cavazzi my only suggestion is to create the following issue for the broken components.

2023-01-16 09:54 UTC, lorenzo-cavazzi approved these changes
Lgtm :+1:

2023-01-17 09:20 UTC, lorenzo-cavazzi approved these changes

2023-01-17 10:07 UTC, merged