WIP: add project dashboard (#2303)
SwissDataScienceCenter/renku-ui pull request #2320
Opened 2023-01-19 17:05 UTC by andre-code

PR for project dashboard...

/deploy #persist #notest

2023-01-27 12:34 UTC, ciyer requested changes
This looks very good! 🚀 

I noticed that some of the changes made for React 18 got lost in the rebase: those should be brought back. Otherwise, I have some questions about code in a small number of places and a few wording change suggestions. But, these are all minor things, and I think this I close to being ready to merge.

2023-01-27 12:34 UTC, ciyer commented on client/src/landing/Landing.test.js
> +import ReactDOM from "react-dom";
It looks like some of the changes that came from upgrading to react 18 were lost. The use of `createRoot` should be brought back.

2023-01-27 12:34 UTC, ciyer commented on client/src/landing/Landing.test.js
> +      ReactDOM.render(
Should use `createRoot` / `root.render` here.

2023-01-27 12:34 UTC, ciyer commented on client/src/landing/Landing.test.js
> +      ReactDOM.render(
Should use `createRoot` / `root.render` here.

2023-01-27 12:34 UTC, ciyer commented on tests/cypress/support/authentication/gui_commands.ts
> +    cy.get("[data-cy='dashboard-title']").contains(`Renku Dashboard - ${user.firstname} ${user.lastname}`);
```suggestion
    cy.get_cy("dashboard-title").contains(`Renku Dashboard - ${user.firstname} ${user.lastname}`);
```

2023-01-27 12:34 UTC, ciyer commented on client/src/utils/customHooks/useGetRecentlyVisitedProjects.ts
> +function useGetRecentlyVisitedProjects(cantProjects: number) {
```suggestion
function useGetRecentlyVisitedProjects(projectsCount: number) {
```

2023-01-27 12:34 UTC, ciyer commented on client/src/utils/customHooks/useGetRecentlyVisitedProjects.ts
> +  const { data, isFetching, refetch } = useGetRecentlyVisitedProjectsQuery(cantProjects);
```suggestion
  const { data, isFetching, refetch } = useGetRecentlyVisitedProjectsQuery(projectsCount);
```

2023-01-27 12:34 UTC, ciyer commented on client/src/utils/customHooks/useGetRecentlyVisitedProjects.ts
> + */
Is this necessary? For me, this doesn't seem to add much to `useGetRecentlyVisitedProjectsQuery`, but maybe I'm missing something.

2023-01-27 12:34 UTC, ciyer commented on tests/cypress/e2e/local/dashboard.spec.ts
> +  it("user does has not own projects and no projects recently visited", () => {
```suggestion
  it("user does has no own projects and no projects recently visited", () => {
```

2023-01-27 12:34 UTC, ciyer commented on tests/cypress/e2e/local/dashboard.spec.ts
> +  it("user does not has own project but has visited projects", () => {
```suggestion
  it("user does not have own project but has visited projects", () => {
```

2023-01-27 12:34 UTC, ciyer commented on tests/cypress/e2e/local/dashboard.spec.ts
> +  it("user does has own projects and recently visited projects", () => {
```suggestion
  it("user has own projects and recently visited projects", () => {
```

2023-01-27 12:34 UTC, ciyer commented on client/src/features/dashboard/components/ProjectsDashboard.tsx
> +        <h3><strong>You don’t have any project yet.</strong></h3>
I think it would be a bit better like this:
```suggestion
        <h3><strong>You do not have any projects yet.</strong></h3>
```

2023-01-30 09:08 UTC, andre-code commented on client/src/utils/customHooks/useGetRecentlyVisitedProjects.ts
> + */
Yes, there is not much logic now, but once the session is integrated, I am planning to return the number of requested projects that are not duplicated if a session already exists.

2023-01-30 09:11 UTC, andre-code commented
> This looks very good! 🚀
> 
> I noticed that some of the changes made for React 18 got lost in the rebase: those should be brought back. Otherwise, I have some questions about code in a small number of places and a few wording change suggestions. But, these are all minor things, and I think this I close to being ready to merge.


 Thanks for the review @ciyer, yes I have brought back the changes in the tests and also apply all your suggestions in the last commit, all the text changes makes sense to me.

2023-02-01 09:26 UTC, ciyer approved these changes
🎉 Ready to merge!

2023-02-01 10:05 UTC, merged