Fix errors in tests
SwissDataScienceCenter/renku-ui pull request #2358
Opened 2023-02-06 10:23 UTC by lorenzo-cavazzi

Remove console errors from the unit tests

2023-02-08 08:18 UTC, ciyer requested changes
Overall, this looks good. The updates to the tests are necessary, and fixing the memory leak is a great improvement!

I only wonder about the change to the `test_and_ci` workflow file. That change was introduced recently to make debugging problems with installing packages easier to diagnose and fix. What are the advantages to returning to the previous configuration with one step that installs and builds (and therefore takes much longer) together?

2023-02-08 08:18 UTC, ciyer commented on .github/workflows/test-and-ci.yml
> +    - name: Install client dependencies and build
This was split into two steps as part of a recent PR #2187. The reason was that debugging install problems was much more time consuming and painful when the two steps were merged into one. 

What is the advantage to returning to just one install/build step rather than keeping it as two steps?

2023-02-08 17:04 UTC, lorenzo-cavazzi commented on .github/workflows/test-and-ci.yml
> +    - name: Install client dependencies and build
Fair point! I thought about keeping it aligned with the UI server action, I forgot about the reasons for introducing that change.
I reverted it in the last commit.

2023-02-16 16:17 UTC, ciyer approved these changes
Looks good! I think we can merge this once the release is out.

2023-02-17 07:56 UTC, merged