WIP feat: Add commit selector (#2240)
SwissDataScienceCenter/renku-ui pull request #2362
Opened 2023-02-07 10:56 UTC by andre-code

PR to add commit selector.

Closes #2240 

/deploy #cypress #persist

2023-02-10 16:58 UTC, lorenzo-cavazzi requested changes
This looks nice! :star_struck:  The arrows seem to be inverted tho, could you swap them? (see inline)

A more generic detail: I noticed that commits are shown a bit too early (E.G. when branches are still loading). Would it make sense to keep showing a temporary message instead? I believe we were used a `disabled` property to handle that (see inline), perhaps you could reuse that as an on/off switch for the new component. P.S. the previous implementation was showing a disabled element in that case, not sure that's great. Probably keep showing a temporary text is better or... any other idea is welcome :smile: 

![Peek 2023-02-10 17-43](https://user-images.githubusercontent.com/43481553/218149820-522a2af1-8f1b-46f8-ba1f-fd3f6399f448.gif)

2023-02-10 16:58 UTC, lorenzo-cavazzi commented on client/src/notebooks/NotebookStart.present.js
> +    const { delays, filters } = this.props;
Was the `disabled` property useful to prevent showing the dropdown menu when a branch is still not selected (or while refreshing them)?

2023-02-10 16:58 UTC, lorenzo-cavazzi commented on client/src/utils/components/commitSelector/CommitSelector.tsx
> +              {isSelectorOpened ? <ChevronDown size="20" /> : <ChevronUp size="20" /> }
These seem to be inverted -- I see the arrow pointing up when the element is collapsed and down when it's expanded. Usually it's the opposite.

2023-02-10 16:58 UTC, lorenzo-cavazzi commented on client/src/utils/components/commitSelector/CommitSelector.tsx
> +              {isSelectorOpened ? <ChevronDown size="20" /> : <ChevronUp size="20" /> }
Same here

2023-02-13 14:02 UTC, ciyer requested changes
This looks very good, and for the most part works well. I did notice a few issues and thought it would be worth checking how easy they are to fix.

1. The suggestions background does not go all the way to the border, leaving a weird region where content from below peaks through.

<img width="825" alt="image" src="https://user-images.githubusercontent.com/1196411/218477453-6688cea2-444b-45d6-851c-ec63f006a0b7.png">


2. Clicking on the top option in the commit list causes the list to flicker (see video). I think it should minimize the options.

https://user-images.githubusercontent.com/1196411/218477518-4dee4e91-0893-4ae0-98df-e961cc6476c7.mov


3. The different columns of content do not line up, making it a bit more effort to processes what you are looking at. It would very nice if it could be shown more like a table.
<img width="823" alt="image" src="https://user-images.githubusercontent.com/1196411/218476621-6b6586b1-cbc1-404c-949f-4748a3417d14.png">


I think 1. and 2. should be fixed/improved. I realize that 3 might not be easy to improve, but if something could be done, it would be nice.

2023-02-14 13:44 UTC, andre-code commented
Thanks @ciyer for your review, I have addressed and corrected all reported cases in the last commit.

2023-02-15 11:52 UTC, ciyer approved these changes
Everything I suggested has now been fixed with latest changes. Thanks, looks great! 🚀

2023-02-15 13:44 UTC, lorenzo-cavazzi approved these changes
Lgtm! :rocket:

2023-02-15 13:47 UTC, merged