refactor(client): convert workflows coordinator to RTK Query
SwissDataScienceCenter/renku-ui pull request #2405
Opened 2023-03-02 22:41 UTC by lorenzo-cavazzi

Refactor the workflows coordinator to use RTK instead of the old Model approach.

/deploy #persist #cypress
fix #2113

2023-03-03 11:48 UTC, ciyer requested changes
Nice refactoring! I tested the UI, and it looks like the behavior is the same as before (good!).

I have some minor suggestions for code improvements, but I think this is overall very good.

2023-03-03 11:48 UTC, ciyer commented on client/src/features/workflows/WorkflowsSlice.ts
> +      const expandedCurrent = [...state.expanded];
I do not think this copy is necessary.

2023-03-03 11:48 UTC, ciyer commented on client/src/workflows/Workflows.container.tsx
> +  const waiting = !versionUrlAvailable || workflowsQuery.isLoading;
Is this correct, or would it be better to use `workflows.fetching`?

2023-03-03 11:48 UTC, ciyer commented on client/src/workflows/Workflows.container.tsx
> +  const skipDetails = (!versionUrlAvailable || !repositoryUrl || !selected) ? true : false;
```suggestion
  const skipDetails = (skipList || !selected) ? true : false;
```

2023-03-06 14:59 UTC, lorenzo-cavazzi commented on client/src/features/workflows/Workflows.d.ts
> +  type: "Plan" | "CompositePlan"
Fair point! Actually `WorkflowType` already exists in the components entities. I imported that here too -- and re-exported it since it seems more natural to look for that in the Workflows definitions

2023-03-06 15:00 UTC, lorenzo-cavazzi commented on client/src/features/workflows/WorkflowsApi.ts
> +    }>({
Good idea! I added that to the workflows definitions file

2023-03-06 15:02 UTC, lorenzo-cavazzi commented on client/src/workflows/Workflows.container.tsx
> +  const waiting = !versionUrlAvailable || workflowsQuery.isLoading;
This is correct: the idea is to show the spinning wheel on the first fetch, but we don't want to flash it later.
Still, your comment made be realize we lost the mechanism to "refetch when stale" so I added `refetchOnMountOrArgChange`

2023-03-07 08:25 UTC, ciyer submitted a review, later dismissed
Looks great!

2023-03-08 08:59 UTC, ciyer approved these changes
The updates to handle errors look good. No need to make it overly complicated.

2023-03-08 09:04 UTC, merged