Skip the workflow list query if a migration is required for core
SwissDataScienceCenter/renku-ui pull request #2460
Opened 2023-04-06 12:53 UTC by leafty

When such a migration is required, the workflow list query will return an error, so we should skip it.

Fixes #2443.

/deploy #persist #cypress

2023-04-06 14:09 UTC, lorenzo-cavazzi requested changes
Nice solution! You will also need to handle the presentational component to prevent crashes on the UI.

However, the situation is slightly more complicated cause we support multiple project versions at the same time. See inline for a (verbose) explanation and a few tips.

2023-04-06 14:09 UTC, lorenzo-cavazzi commented on client/src/workflows/Workflows.container.tsx
> +  const skipList = !versionUrlAvailable || !repositoryUrl || coreMigrationRequired;
The idea here is correct: we need to skip the query when there is no support from the backend.
However, it's possible that the project requires to be updated but it's not necessary for the workflows query. This is an example of a project still at version 9 where you can still query the workflows: https://dev.renku.ch/projects/workflows-pet-projects/workflows-flights-tutorial/workflows

You need to check that the current project version is in the list of the supported version from renku-core; we query that from `GET /ui-server/api/renku/version` and store it in the Redux store in "environment/coreVersions"
![image](https://user-images.githubusercontent.com/43481553/230398628-400e77e0-66ee-44e0-bdf5-4886a16a696a.png)
Sadly, the query fetching it is not in RTK Query yet -- feel free to let it untouched and get the information from the current Redux (nothing prevents you from converting  the query to RTK Query, but it would require updating the other places where this information is currently used).

A few tips:
* You can access the old "stateModel" global object in the Redux store using `props.model.get("environment.coreVersions")` in the `ProjectViewWorkflows` component. If you need an example from the existing code base, search for `model.baseModel.get("environment.coreVersions");` to find one.
* `versionUrl` is a string containing the version number. You can check the `checkRenkuCoreSupport` function to understand how to derive the project's metadata version number from `versionUrl`. That's enough to solve this issue, but feel free to create a dedicated function or pass the "pure" version number through the components if you prefer a cleaner solution.

Additionally, the current solution crashes when skipping the fetch -- try opening https://renku-ci-ui-2460.dev.renku.ch/projects/workflows-pet-projects/workflows-flights-tutorial
Depending on the final solution you implement, you might need to handle the skipped case also in the `WorkflowsTreeBrowserPresent`.

P.S. To be on the safe side, you can also add `unsupported` to the elements causing `skipList` to be `true`; The `skipList` variable will look like
```
const skipList = !versionUrlAvailable || !repositoryUrl || unsupported || <something_else_here>;
```

2023-04-11 22:35 UTC, lorenzo-cavazzi requested changes
A tiny change request to keep the minimum version for the workflows -- pre v9, we have no support from the backend (more details inline).

The e2e tests seem to fail because the presentational component tries to read unavailable values when it should probably stop earlier; I guess the `unsupported` variable in the `WorkflowsTreeBrowserPresent` component might be `undefined` -- this is based on the error I read on the console when running the tests manually (see screenshot); please double check if this is actually the case.

You might need to update the tests to invoke the function to simulate the API response for the renku-core versions (the endpoint should be something like `check_migration`), and be sure `unsupported` is always `true` or `false`.

![image](https://user-images.githubusercontent.com/43481553/231303544-ebf41a92-9428-4260-b3be-65308ca3a89f.png)

2023-04-11 22:35 UTC, lorenzo-cavazzi commented on client/src/workflows/Workflows.container.tsx
> -const MIN_CORE_VERSION_WORKFLOWS = 9;
We may want to keep this for a bit longer; there was no support for workflows on renku-core before version 9. That means we can't show info for projects v8 in any case.

2023-04-11 22:35 UTC, lorenzo-cavazzi commented on client/src/workflows/Workflows.container.tsx
> +  coreMigrationRequired: boolean;
Not necessary anymore

2023-04-12 07:52 UTC, leafty commented on client/src/workflows/Workflows.container.tsx
> +  coreMigrationRequired: boolean;
Done in [65c223c](https://github.com/SwissDataScienceCenter/renku-ui/pull/2460/commits/65c223cf1f55e173a9793f79fd1b0c12c27f7a5c).

2023-04-12 07:52 UTC, leafty commented on client/src/workflows/Workflows.container.tsx
> -const MIN_CORE_VERSION_WORKFLOWS = 9;
Added back in [77b27fe](https://github.com/SwissDataScienceCenter/renku-ui/pull/2460/commits/77b27fec358690ebb6b0fb18740f0c1977502fdd).

2023-04-12 12:35 UTC, lorenzo-cavazzi approved these changes
Great, the fix works well!
Let's wait for the acceptance tests -- those failures didn't make much sense to me since they are unrelated to the changes in this PR :thinking:

2023-04-14 11:19 UTC, merged