Leafty/2237 fix session options
SwissDataScienceCenter/renku-ui pull request #2461
Opened 2023-04-11 15:34 UTC by leafty

2023-04-12 11:40 UTC, leafty commented
Current UI, without a lot of styling:
![leafty dev renku ch_projects_workflows-pet-projects_workflows-flights-tutorial_sessions_new_](https://user-images.githubusercontent.com/951086/231446263-3be107d7-b057-472b-8d5a-3ef48f87da42.png)
![leafty dev renku ch_projects_workflows-pet-projects_workflows-flights-tutorial_sessions_new_ (1)](https://user-images.githubusercontent.com/951086/231446273-53b4b346-2a95-4575-a0c7-bd9f106e5d5e.png)

2023-04-13 07:15 UTC, lorenzo-cavazzi requested changes
Nice solution using CSS modules!

Apart from a couple of linting errors to fix, it would be nice to use the same thicker border already in use for the selected radio button. Otherwise, it feels "unselected".

![image](https://user-images.githubusercontent.com/43481553/231682442-4f269cc0-7717-4f1f-8c4f-700a84ae2ead.png)

I noticed the size is also slightly different; perhaps it's related to the borders? Please double-check it again after adjusting borders just to be on the safe side :grin: 

![image](https://user-images.githubusercontent.com/43481553/231682245-08155ae3-163c-492b-bfc4-8b72eb0d7409.png)

2023-04-13 19:31 UTC, lorenzo-cavazzi submitted a review, later dismissed
Excellent solution, it works well!

2023-04-14 11:31 UTC, lorenzo-cavazzi approved these changes

2023-04-17 06:33 UTC, merged