Add prettier to format UI code
SwissDataScienceCenter/renku-ui pull request #2468
Opened 2023-04-13 12:27 UTC by leafty

Add prettier to the `client` project and scripts to format only changed files.

To format changed files:
```bash
npm run format-changed
```

Also, we add a pre-commit hook to check staged files, but we don't format them and re-stage them for now.

Fixes #2427.

2023-04-13 12:28 UTC, leafty commented on package.json
> +}
Note: we can only install `husky` at the same location as the root of the git project.

2023-04-25 09:31 UTC, leafty commented
Note: example of CI failing because of formatting -> https://github.com/SwissDataScienceCenter/renku-ui/actions/runs/4795881027/jobs/8530980159

2023-04-25 15:52 UTC, lorenzo-cavazzi requested changes
Very nice! Finally no formatting discrepancies anymore :raised_hands: 

A couple of details:
1. If I run `npm run format` there are still a couple of minimal changes, just 4 files. Perhaps we should re-run it?
2. Could you update the base README.md file, adding a reference to "Prettier", the additional `npm install` step in the "Developing" sections, and updating the "Unit Tests and Linting" sections as well? Bonus for adding a quick description of how to set up VScode to auto-format on save (this last step not 100% necessary tbh). Thank you :pray:

2023-04-26 13:51 UTC, leafty commented
> Very nice! Finally no formatting discrepancies anymore raised_hands
> 
> A couple of details:
> 
> 1. If I run `npm run format` there are still a couple of minimal changes, just 4 files. Perhaps we should re-run it?
> 2. Could you update the base README.md file, adding a reference to "Prettier", the additional `npm install` step in the "Developing" sections, and updating the "Unit Tests and Linting" sections as well? Bonus for adding a quick description of how to set up VScode to auto-format on save (this last step not 100% necessary tbh). Thank you pray

Updated readme in 65b04c1a25eb6097376c95bd8f07fc2a1001b64c.

2023-04-26 15:08 UTC, lorenzo-cavazzi submitted a review, later dismissed
:rocket:

2023-04-27 14:10 UTC, lorenzo-cavazzi approved these changes

2023-04-27 14:13 UTC, merged