refactor: use redux for kg search (React.Context version)
SwissDataScienceCenter/renku-ui pull request #2491
Opened 2023-04-24 11:15 UTC by leafty

WIP to fix https://github.com/SwissDataScienceCenter/renku-ui/issues/2446 and https://github.com/SwissDataScienceCenter/renku-ui/issues/2447.

/deploy #persist #cypress

2023-04-25 14:41 UTC, lorenzo-cavazzi requested changes
The code looks great! I agree it's simpler and less error-prone than the other solution.

I added a couple of inline comments. They don't target changes from you, but since we are already touching the code, it's worth considering them.

Another tiny change: in the "features/kgSearch/KgSearchApi.ts" file, we might add a parameter in the `createApi` section to cache the content for a bit longer (I believe it's `keepUnusedDataFor` but please double-check this). If we set it to something like 30 seconds , browsing back and forth in a short sequence (or ticking/unticking the same filters) won't trigger new queries.

P.S. I just realized that would actually also fix https://github.com/SwissDataScienceCenter/renku-ui/issues/2448
Feel free to include it in the PR or we can make a separate one later

2023-04-25 14:41 UTC, lorenzo-cavazzi commented on client/src/features/kgSearch/KgSearch.d.ts
> +export const TOTAL_RESULT_PER_PAGE = 20;
We are not using this. We can drop it entirely

2023-04-25 14:41 UTC, lorenzo-cavazzi commented on client/src/features/kgSearch/KgSearchState.ts
> +/* eslint-disable @typescript-eslint/no-non-null-assertion */
I feel we could remove the `eslint-disable` rule here, and fix the code later.
The `Object.keys(val!)` sections trigger the warnings. I feel we can wrap them around an `if (val !== undefined) {` conditional -- something like the following:

```
if (val !== undefined) {
        Object.keys(val).forEach((k) => {
          if (val[k as keyof typeof val] === true) stateMap.push([key, k]);
        });
      }
```

:warning: Please double-check the code, I haven't tried it thoroughly

2023-04-26 07:00 UTC, leafty commented on client/src/features/kgSearch/KgSearch.d.ts
> +export const TOTAL_RESULT_PER_PAGE = 20;
Done in [f45dbd1](https://github.com/SwissDataScienceCenter/renku-ui/pull/2491/commits/f45dbd16eb27e76019b2d67f2220b4547d21e842).

2023-04-26 07:02 UTC, leafty commented
> The code looks great! I agree it's simpler and less error-prone than the other solution.
> 
> I added a couple of inline comments. They don't target changes from you, but since we are already touching the code, it's worth considering them.
> 
> Another tiny change: in the "features/kgSearch/KgSearchApi.ts" file, we might add a parameter in the `createApi` section to cache the content for a bit longer (I believe it's `keepUnusedDataFor` but please double-check this). If we set it to something like 30 seconds , browsing back and forth in a short sequence (or ticking/unticking the same filters) won't trigger new queries.
> 
> P.S. I just realized that would actually also fix #2448 Feel free to include it in the PR or we can make a separate one later

Done in [e21a96f](https://github.com/SwissDataScienceCenter/renku-ui/pull/2491/commits/e21a96f1a9f0b764fdaadf313e865bab5ac6245b).

2023-04-26 08:18 UTC, lorenzo-cavazzi approved these changes
Lgtm :rocket:

2023-04-26 10:56 UTC, merged