WIP: add a clone button
SwissDataScienceCenter/renku-ui pull request #2495
Opened 2023-04-25 14:22 UTC by leafty

Fixes #2440.

2023-05-02 13:23 UTC, leafty commented
### Update

Clone card:
![image](https://user-images.githubusercontent.com/951086/235678656-36c9e44d-d5f4-416e-897a-b8a7d36d483a.png)

Clone card with git:
![image](https://user-images.githubusercontent.com/951086/235678790-a2b3c2fc-169f-4720-9254-e9162037e768.png)

Removed clone commands from settings:
![image](https://user-images.githubusercontent.com/951086/235678980-77f2c57e-38dd-4726-a56c-11b995b8c0c7.png)

Settings when access is lower than `maintainer`:
![image](https://user-images.githubusercontent.com/951086/235679123-9b163f0b-b52e-4623-8f57-5a0e37cb3696.png)

2023-05-02 14:53 UTC, leafty commented
### Other components updated

Create a shareable link:
![image](https://user-images.githubusercontent.com/951086/235689153-96cffa93-d16a-489f-9ce5-e2a22544c9ac.png)
![image](https://user-images.githubusercontent.com/951086/235689225-b65b9c0a-b61b-492d-9fc3-002c31f71df3.png)

Connect with SSH (ignore "SSH not supported"):
![image](https://user-images.githubusercontent.com/951086/235690180-99b621b9-9c9d-4de9-a103-fa7832e9f87e.png)

Unsaved work modal:
![image](https://user-images.githubusercontent.com/951086/235692845-95168fa4-dab8-44c4-8254-f6c3c5ad2fd7.png)

Session cheat sheet:
![image](https://user-images.githubusercontent.com/951086/235694866-1b650d07-f1a4-4e41-bf47-e3c6b689e036.png)

Workflow details:
![image](https://user-images.githubusercontent.com/951086/235702056-05057b17-58f6-4cad-a6cb-2e47b9b91688.png)

Create link for new project:
![image](https://user-images.githubusercontent.com/951086/235702822-3cc6f1c6-adfa-4adb-9bc9-de838fc912f3.png)

2023-05-03 07:23 UTC, lorenzo-cavazzi requested changes
This works well already! And thank you for going through the code and updating copy/paste everywhere to make it consistent :pray: 
I have a couple of comments:

* Clicking again on the "Clone" button once opened gives inconsistent results: when clicking on the arrow, nothing happens; when clicking on the text "Clone", it closes the dropdown. I would keep the same behavior (my personal preference would be to close, but all other dropdown buttons don't close on the second click, so let's privilege consistency)

* Do you mind adding a bottom margin after "Do not have renku?"
It has non and looks visually very close to the following element
![image](https://user-images.githubusercontent.com/43481553/235852085-dda420ea-10de-41db-9124-5e37ed66292d.png)

2023-05-03 07:23 UTC, lorenzo-cavazzi commented on client/src/components/Clipboard.tsx
> +          <FontAwesomeIcon icon={faCheck} size="1x" style={{ minWidth: 16 }} />
Why manually specify the pixels? Should we rely only on the size instead?

2023-05-03 07:23 UTC, lorenzo-cavazzi commented on client/src/project/clone/CloneSettings.tsx
> +      <div /*className="text-end"*/>
```suggestion
      <div>
```

2023-05-03 07:28 UTC, lorenzo-cavazzi commented
Also, it might be necessary to update the acceptance tests (Cypress for sure, perhaps also the others? :thinking: )

![image](https://user-images.githubusercontent.com/43481553/235855112-ecc04046-4d0e-4efd-9cf9-8dcc2199c50b.png)

2023-05-03 08:15 UTC, lorenzo-cavazzi commented
As discussed offline, let's use an `InfoAlert` element for logged-in users without permission to inform them the settings are available only to maintainers.

For non-logged users, let's use something similar to the Settings Session section

![image](https://user-images.githubusercontent.com/43481553/235864038-21c7902e-c837-45e0-bafe-0bbabb47152d.png)

2023-05-03 08:51 UTC, leafty commented
Updated settings:

![Screenshot 2023-05-03 at 10 49 02](https://user-images.githubusercontent.com/951086/235871343-30b6b53a-9e25-4ab4-a28f-06e7be9badd3.png)

![Screenshot 2023-05-03 at 10 43 03](https://user-images.githubusercontent.com/951086/235871390-d9c2674d-4a97-41ca-9f43-dcd982c2b1d0.png)

2023-05-03 08:56 UTC, leafty commented
> This works well already! And thank you for going through the code and updating copy/paste everywhere to make it consistent 🙏 I have a couple of comments:
> 
> * Clicking again on the "Clone" button once opened gives inconsistent results: when clicking on the arrow, nothing happens; when clicking on the text "Clone", it closes the dropdown. I would keep the same behavior (my personal preference would be to close, but all other dropdown buttons don't close on the second click, so let's privilege consistency)
> * Do you mind adding a bottom margin after "Do not have renku?"
>   It has non and looks visually very close to the following element
>   ![image](https://user-images.githubusercontent.com/43481553/235852085-dda420ea-10de-41db-9124-5e37ed66292d.png)

Updated margins in fbf2ebad012f8972fab5326828004e40a779c2a4.

Also I do not know how to fix the behaviour of the button parts, it's using reactstrap components the same way as in their docs.

2023-05-03 08:57 UTC, leafty commented on client/src/components/Clipboard.tsx
> +          <FontAwesomeIcon icon={faCheck} size="1x" style={{ minWidth: 16 }} />
Fixed with 9ebb1b6c98bd72e73196081dd956f2fc4531c80b.

2023-05-03 08:57 UTC, leafty commented on client/src/project/clone/CloneSettings.tsx
> +      <div /*className="text-end"*/>
Thanks, fixed.

2023-05-04 06:53 UTC, lorenzo-cavazzi approved these changes
This works well :tada: 
Let's merge once both acceptance tests are fixed :rocket:

2023-05-04 11:12 UTC, merged