feat(client): rework the projects status page
SwissDataScienceCenter/renku-ui pull request #2503
Opened 2023-04-28 13:52 UTC by lorenzo-cavazzi

_Temporary deployment_
_This takes the place of #2426_

/deploy renku-core=feature/3057-service-doctor-check renku-gateway=add-webhooks-path renku-graph=development #persist #notest
fix #2315

2023-05-25 13:41 UTC, leafty commented on client/.eslintrc.json
> +    "@typescript-eslint/no-unused-vars": [
I suggest we use `"@typescript-eslint/no-unused-vars": "error"` or `"@typescript-eslint/no-unused-vars": "warn"`.

2023-05-25 13:41 UTC, leafty commented on client/src/features/versions/versionsApi.ts
> +      },
nitpick:
```suggestion
      query: () => ({
        url: "renku/version",
      }),
```

2023-05-25 13:41 UTC, leafty commented on client/src/App.js
> +  versionsApi.useGetCoreVersionsQuery(null, { pollingInterval: 20000 });
nitpick:
```suggestion
  versionsApi.useGetCoreVersionsQuery(null, { pollingInterval: 20_000 });
```

2023-05-25 13:41 UTC, leafty commented on client/src/api-client/project.js
> +      webhook = (resp?.data?.message ?? "").includes("created") ? true : false;
```suggestion
      webhook = (resp?.data?.message ?? "").includes("created");
```

2023-05-25 13:41 UTC, leafty commented on client/src/components/errors/RtkErrorAlert.tsx
> +    errorCode = error.code.toString();
General code style comment: prefer to use `const` whenever possible.

This prevents assigning another value to the variable unintentionally.

```suggestion
  const errorCode = "status" in error ? error.status.toString() : "code" in error && error.code !== undefined ? error.code.toString() : "Unknown";
```

2023-05-25 13:41 UTC, leafty commented on client/src/components/errors/RtkErrorAlert.tsx
> +  }
Same here, use a `const`. The code can be pulled into a function:

```ts
const errorMessage = extractErrorMessage(error);
```

```ts
const extractErrorMessage = (error: FetchBaseQuery | SerializedError): string => {
  if ("error" in error && error.error.length)
    return error.error.toString();
  if ("message" in error && error.message?.length)
    return error.message.toString();
  if ("data" in error && typeof error.data === "object" &&
      error.data !== null &&
      "message" in error.data
  )
    return (error.data as unknown as Record<string, unknown>)
        .message as string;
  if ("data" in error) return JSON.stringify(error.data);
  return "No details available.";
};
```

2023-05-25 14:12 UTC, leafty commented on client/src/components/kgStatus/KgStatus.tsx
> +            to=""
```suggestion
            to="."
```

2023-05-25 14:12 UTC, leafty commented on client/src/components/kgStatus/KgStatus.tsx
> +      namespace: "",
Is this correct?

2023-05-25 14:12 UTC, leafty commented on client/src/components/kgStatus/KgStatus.tsx
> +  return props.children;
I think the correct form is:

```suggestion
  return <>{props.children}</>;
```

Test code:
```tsx
const TestComponent: React.FunctionComponent = ({
  children,
}: {
  children?: React.ReactNode;
}) => {
  return <>{children}</>;
};
```

2023-05-25 14:12 UTC, leafty commented on client/src/components/loginAlert/LoginAlert.tsx
> +  noWrapper: boolean;
```suggestion
  noWrapper?: boolean;
```

2023-05-25 14:12 UTC, leafty commented on client/src/components/loginAlert/LoginAlert.tsx
> +  noWrapper = false,
```suggestion
  noWrapper,
```

2023-05-25 15:11 UTC, lorenzo-cavazzi commented on client/src/components/errors/RtkErrorAlert.tsx
> +    errorCode = error.code.toString();
This makes sense, but I find nested ternary operators hard to interpret

2023-05-25 15:37 UTC, lorenzo-cavazzi commented on client/src/components/kgStatus/KgStatus.tsx
> +            to=""
Is the behavior different here? This is overwritten by `onClick={(e) => {  e.preventDefault();  refetch(); }` . I just need to refetch

2023-05-25 15:40 UTC, lorenzo-cavazzi commented on client/src/components/kgStatus/KgStatus.tsx
> +      namespace: "",
Ouch :facepalm: 
Technically, it's correct cause `props.projectPath` already contains the full slug. Still, on the following `settingsUrl` I use namespace and name separately. I'll update it here to keep things coherent. Thanks for spotting this!

2023-05-25 17:15 UTC, leafty commented on client/src/components/kgStatus/KgStatus.tsx
> +            to=""
The generated html is `<a href="<same URL>">` and not `<a href="/">` which is better as we stay on the page.

2023-05-25 17:23 UTC, leafty commented on client/.eslintrc.json
> +    "@typescript-eslint/no-unused-vars": [
with default options

2023-05-26 07:02 UTC, ciyer commented on client/.eslintrc.json
> +    "@typescript-eslint/no-unused-vars": [
See also #2547

2023-05-26 07:07 UTC, leafty commented on client/src/workflows/Workflows.container.tsx
> +  const skipList = !versionUrl || !repositoryUrl || unsupported ? true : false;
```suggestion
  const skipList = !versionUrl || !repositoryUrl || unsupported;
```

2023-05-26 07:07 UTC, leafty commented on client/src/workflows/Workflows.container.tsx
> +      : false;
This is less readable, do not do `const x = cond ? true : false`.

2023-05-26 07:23 UTC, ciyer commented on client/src/components/kgStatus/KgStatus.tsx
> +  } else if (isError) {
No need for the the nested if/else branches here, since the code has already returned from the previous branch by this point.

2023-05-26 07:29 UTC, ciyer commented on client/src/features/project/components/ProjectSettings.tsx
> +    props.metadata?.accessLevel >= ACCESS_LEVELS.MAINTAINER ? true : false;
If the LHS is `undefined` the expression will evaluate to false, so it can be simplified.

```suggestion
  const isMaintainer =
    props.metadata?.accessLevel >= ACCESS_LEVELS.MAINTAINER;
```

2023-05-26 10:23 UTC, ciyer commented on client/src/workflows/Workflows.container.tsx
> +      : false;
```suggestion
    backendAvailable === false || coreSupport.cached.metadataVersion == null || 
    (coreSupport.cached.metadataVersion < MIN_CORE_VERSION_WORKFLOWS);
```

2023-05-26 13:19 UTC, lorenzo-cavazzi commented on client/src/features/inactiveKgProjects/InactiveKgProjects.tsx
> +  socket: any; // eslint-disable-line @typescript-eslint/no-explicit-any
:100:

2023-05-26 13:31 UTC, lorenzo-cavazzi commented on client/src/workflows/Workflows.container.tsx
> +      : false;
I went for a slightly different solution cause the inverted logging seems easier (finding `supported` instead of `unsupported`)

2023-05-26 13:38 UTC, lorenzo-cavazzi commented on client/src/components/errors/RtkErrorAlert.tsx
> +    errorCode = error.code.toString();
I'll go for you solution since it's safer

2023-05-26 13:42 UTC, lorenzo-cavazzi commented on client/src/features/project/components/migrations/ProjectCoreMigrations.tsx
> +  }
This is a fair point, the logic here could be clearer. Do you mind moving this comment to a follow-up issue, together with the next 2 similar comments? Thank you :pray:

2023-05-26 13:42 UTC, lorenzo-cavazzi commented on client/src/features/project/components/migrations/ProjectCoreMigrations.tsx
> +  }
See above.

2023-05-30 09:21 UTC, leafty commented on client/src/features/project/Project.d.ts
> +        type: "detail";
This field does not seem to exist!

2023-05-30 09:28 UTC, ciyer requested changes
Tests are working, and the feedback is now better for the projects that I had identified which had updates that failed. 

I suggest some changes to the wording of error messages, and I will make a commit to fix that. I think the other problems can be fixed in #2553.

2023-05-30 09:28 UTC, ciyer requested changes
Tests are working, and the feedback is now better for the projects that I had identified which had updates that failed. 

I suggest some changes to the wording of error messages, and I will make a commit to fix that. I think the other problems can be fixed in #2553.

2023-05-30 09:28 UTC, ciyer commented on client/src/features/project/components/migrations/ProjectCoreMigrations.tsx
> +        ? "The project is strongly outdated, and most interaction on RenkuLab will not be available (E.G. with datasets, workflows, session settings, ...)."
```suggestion
        ? "The project is very outdated, and an upgrade is necessary for support of most project from the UI."
```

2023-05-30 09:28 UTC, ciyer commented on client/src/features/project/components/migrations/ProjectCoreMigrations.tsx
> +            ? " Updating brings new features and bug-fixes; it should be safe on this project since it is a minor step."
```suggestion
            ? " Updating brings new features and bug-fixes; it should be safe on this project since it is a minor upgrade."
```

2023-05-30 09:28 UTC, ciyer commented on tests/cypress/e2e/projectStatus.spec.ts
> +      .contains("it should be safe on this project since it is a minor step")
```suggestion
      .contains("it should be safe on this project since it is a minor update")
```

2023-05-30 09:28 UTC, ciyer commented on tests/cypress/e2e/projectStatus.spec.ts
> +      .contains("it should be safe on this project since it is a minor step")
```suggestion
      .contains("it should be safe on this project since it is a minor update")
```

2023-05-30 11:07 UTC, ciyer approved these changes
Let's merge! 🎉 🎉 🎉  

Any remaining issues can be fixed in #2553.

2023-05-30 11:11 UTC, merged

2023-06-06 13:49 UTC, leafty commented on client/src/features/project/projectSlice.ts
> +  // ? after fetching the migration status.
Tracked in #2555, fixed in #2554.