fix(client): enable start session button after load
SwissDataScienceCenter/renku-ui pull request #2574
Opened 2023-06-05 14:24 UTC by leafty

Do not let the user start a session until the options have been populated from the project settings or defaults.

2023-06-06 08:52 UTC, ciyer requested changes
Just a minor suggestion about equality testing.

2023-06-06 08:52 UTC, ciyer commented on client/src/notebooks/NotebookStart.present.js
> +  const hasSessionClass = sessionClass != 0;
```suggestion
  const hasSessionClass = sessionClass !== 0;
```

2023-06-06 09:06 UTC, leafty commented on client/src/notebooks/NotebookStart.present.js
> +  const hasSessionClass = sessionClass != 0;
Note that in TypeScript, the compiler would error on `<string> != <number>`, so `==` vs `===` is less of an issue in TypeScript code.

2023-06-07 08:14 UTC, ciyer approved these changes
LGTM!

2023-06-07 08:14 UTC, merged