WIP: remove form generator from dataset import
SwissDataScienceCenter/renku-ui pull request #2582
Opened 2023-06-06 11:20 UTC by ciyer

/deploy renku-core=develop renku=2315ui-project-status #persist #cypress

2023-06-12 07:09 UTC, leafty commented on client/src/project/datasets/import/DatasetImport.tsx
> +function DatasetImport(props: DatasetImportProps) {
Since this component is the default export, it should in principle be declared first, or very close to the top of the file.

2023-06-12 07:12 UTC, leafty commented on tests/cypress/e2e/newDataset.spec.ts
> +    cy.contains("Datasets List").should("be.visible");
Would it be possible to check that the new dataset appears in the list? Something like `cy.contains("<Dataset title").should("be.visible")`?

2023-06-12 12:08 UTC, ciyer commented on tests/cypress/e2e/newDataset.spec.ts
> +    cy.contains("Datasets List").should("be.visible");
I think the `cy.wait("@datasetList")` will achieve this.

2023-06-14 11:52 UTC, leafty requested changes
I think a `.catch()` or `.finally()` branch should still be added for `client.getJobStatus()`. See code suggestion.

2023-06-14 11:52 UTC, leafty commented on client/src/project/datasets/import/DatasetImport.tsx
> +      client.getJobStatus(job_id, versionUrl).then((job) => {
The counting logic should be:

```ts
  .finally(() => {
    pollCount++;
        if (pollCount >= 50) {
          handlers.setSubmitLoader({ value: false, text: "" });
          handlers.setServerErrors(ImportStateMessage.TOO_LONG);
          clearInterval(monitorJob);
          resolve();
          return;
        }
  })
```

and remove it from `.then()`.

This means that any error / network issue from the client will not make this code poll forever.

2023-06-15 06:54 UTC, ciyer commented
> I think a `.catch()` or `.finally()` branch should still be added for `client.getJobStatus()`. See code suggestion.

You are right, thanks for pointing this out.

2023-06-15 11:38 UTC, leafty approved these changes

2023-06-16 10:19 UTC, merged