feat(client): add a customizable message to the dashboard page
SwissDataScienceCenter/renku-ui pull request #2592
Opened 2023-06-07 12:42 UTC by leafty

Fixes #2434.

![renku-ci-ui-2592 dev renku ch_](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/49568b61-6773-468a-b11e-8ffdb697c5ea)

/deploy #persist #cypress

2023-06-12 10:00 UTC, leafty commented on client/src/features/dashboard/message/dashboardMessage.utils.ts
> +      : null;
Good point :+1:, using "plain" whenever we cannot parse the `style` option as any allowed value is a better experience for the instance admin.

2023-06-12 14:09 UTC, leafty commented
> This is implemented nicely! My only comments are a correction in the wording of a comment and the suggestion to default the style.

@ciyer Thanks for the suggestions, they have been added. I also included new e2e tests for this feature.

2023-06-13 07:21 UTC, ciyer submitted a review, later dismissed
The JupyterNotebookForPrivateProjectSpec Selenium test is failing, but that is expected and should automatically resolve itself once renku-python is tagged, so we can merge this.

2023-06-14 14:56 UTC, lorenzo-cavazzi requested changes
Good implementation :raised_hands: 
I spotted a typo that led to an unexpected default setting (see inline).

An additional comment: once we expand the text, the arrow direction changes but the text still says "Read more...". Should we change the text too?

2023-06-14 14:56 UTC, lorenzo-cavazzi commented on helm-chart/renku-ui/values.yaml
> +    dismissable: true
This seems to be a typo, it should be `dismissible`.
I was initially confused by the tests working properly and the CI deployment showing no dismiss button despite it being set in the parameters :joy: 
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/2569ecde-3a1c-455e-aa2c-f5ce6c2ba33f)

2023-06-15 15:53 UTC, lorenzo-cavazzi submitted a review, later dismissed
Lgtm! :rocket:

2023-06-16 14:12 UTC, lorenzo-cavazzi commented
Oh no, I accidentally pushed a commit to the wrong PR :facepalm:  Sorry for that! I'll remove it immediately

2023-06-19 06:19 UTC, merged