feat(client): update session project settings for resource pools
SwissDataScienceCenter/renku-ui pull request #2615
Opened 2023-06-21 13:40 UTC by leafty

Remove the session class selector and add input for existing settings.

![Screenshot 2023-06-21 at 15 39 34](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/4692f6e0-6800-4b0d-b42a-eb188fb72f5e)

2023-06-22 13:12 UTC, leafty commented
Updated style:

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/1d8484b0-a4f6-41e1-b279-097038c0d8a7)

2023-06-22 15:22 UTC, lorenzo-cavazzi requested changes
This looks generally good!

I suggest removing `max` on the inputs.
Apart from that, I would update the warning message to clarify what's the problem when we can't pick the flavor. As a user, I would need help understanding exactly _where_ the problem is.

Instead of `The session cannot be configured exactly as requested for this project.` we can explicitly mention the requirements, as in `The project requires 4 CPUs and there is no Session class that matches it`

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/6d71bc72-3ea5-4a9a-9d49-57bb4202e17e)

2023-06-23 06:48 UTC, leafty commented
> This looks generally good!
> 
> I suggest removing `max` on the inputs. Apart from that, I would update the warning message to clarify what's the problem when we can't pick the flavor. As a user, I would need help understanding exactly _where_ the problem is.
> 
> Instead of `The session cannot be configured exactly as requested for this project.` we can explicitly mention the requirements, as in `The project requires 4 CPUs and there is no Session class that matches it`

I am not updating the "Start with options" page in this PR because it needs to be updated to support the CRC service telling the user which session classes meet their compute resource requirements.

2023-06-23 15:23 UTC, lorenzo-cavazzi approved these changes

2023-06-23 15:57 UTC, merged