build(server): set up premetheus on
SwissDataScienceCenter/renku-ui pull request #2621
Opened 2023-06-28 13:16 UTC by lorenzo-cavazzi

Set up Prometheus

/deploy #persist #notest

2023-06-28 13:21 UTC, lorenzo-cavazzi commented
- Move the setup to a separate function specific for setting up monitoring.
- Activate `includePath` and set it up https://www.npmjs.com/package/express-prom-bundle
- We need to setup the annotations on the pod. E.G: this is the current one, ofc to adapt
```
metadata:
  annotations:
    prometheus.io/path: /ui-server/metrics
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
```

2023-08-03 08:53 UTC, ciyer requested changes
It will be nice to be able to access Prometheus metrics! I have some minor code suggestions.

2023-08-03 08:53 UTC, ciyer commented on server/src/config.ts
> +  enabled: [true, "true"].includes(process.env.PROMETHEUS_ENABLED),
I believe process.env values will always be strings, so no need to check for the boolean, but maybe lowercase and/or allow 1 or "yes". 🤷

2023-08-03 08:53 UTC, ciyer commented on server/src/utils/prometheus/prometheus.ts
> +  if (config.prometheus.enabled === false) {
`config.prometheus` is a boolean, so I think this is simpler. 
```suggestion
  if (!config.prometheus.enabled) {
```

2023-08-03 12:31 UTC, lorenzo-cavazzi commented on server/src/config.ts
> +  enabled: [true, "true"].includes(process.env.PROMETHEUS_ENABLED),
Fair point, I guess "1" is also pretty common. What about using this?

```
enabled: ["true", "1"].includes(
    (process.env.PROMETHEUS_ENABLED ?? "").toLowerCase()
),
```

2023-08-03 14:41 UTC, ciyer approved these changes
LGTM! 🎉

2023-08-03 15:21 UTC, merged