test
SwissDataScienceCenter/renku-ui pull request #2631
Opened 2023-07-03 13:47 UTC by lorenzo-cavazzi

/deploy #persists #notest

2023-07-28 09:59 UTC, leafty requested changes
Good to see the project description editing going to RTK

The loading state looks broken:
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/89c3a36c-abe1-4857-9bd1-8dfe6d2ab069)

2023-07-28 09:59 UTC, leafty commented on client/src/components/formlabels/FormLabels.tsx
> +        {text} <Loader inline size={16} />
We should avoid inserting extra `[space]` characters:

```suggestion
        {text}
        <Loader className="ms-1" inline size={16} />
```

2023-07-28 09:59 UTC, leafty commented on client/src/components/buttons/Button.tsx
> +      <LoadingLabel className="feedback mx-1" text={submittingText || " "} />
This should render fine, without adding a space character:

```suggestion
      <LoadingLabel className="feedback mx-1" text={submittingText} />
```

2023-07-28 09:59 UTC, leafty commented on client/src/components/entities/Description.tsx
> +    height: isHeightFixed ? `${25 * numberLines}px` : undefined,
Note: this will break if the font size is not the one expected. Maybe a `lh` multiplier would work better?

https://developer.mozilla.org/en-US/docs/Web/CSS/length

2023-07-28 09:59 UTC, leafty commented on client/src/components/entities/Description.tsx
> +  const descriptionStyles: CSSProperties = {
Nitpick: name it the same way as the prop.

```suggestion
  const style: CSSProperties = {
```

2023-07-28 09:59 UTC, leafty commented on client/src/components/entities/Description.tsx
>        style={{ ...descriptionStyles, margin: "12px 0 0 0" }}
Margin is added again here. We can just have:

```suggestion
      style={style}
```

2023-07-28 09:59 UTC, leafty commented on client/src/components/entities/Description.tsx
>   */
Nitpick: I would remove this, the component is named `EntityDescription` which is plenty clear.

2023-07-28 09:59 UTC, leafty commented on client/src/components/entities/Description.tsx
> +  let content: React.ReactNode = null;
Avoid `let` and use ternaries (coding guidelines).

2023-07-28 09:59 UTC, leafty commented on client/src/components/formlabels/FormLabels.css
> +}
We should avoid adding global CSS rules if possible. I think this can be achieved by:
* Adding bootstrap class names to `InlineSubmitButton`
* Or by adding a CSS module for `InlineSubmitButton`

2023-07-28 09:59 UTC, leafty commented on client/src/components/formlabels/FormLabels.tsx
>  import * as React from "react";
We can modernize imports, maybe:
```suggestion
import React from "react";
```

2023-07-28 09:59 UTC, leafty commented on client/src/components/visibility/Visibility.tsx
> +  value?: Visibilities;
I think the original typing is more semantically correct:

```suggestion
  value: Visibilities | null;
```

2023-07-28 09:59 UTC, leafty commented on client/src/features/project/components/ProjectEntityHeader.tsx
> +  const { branch, devAccess, fullPath, gitUrl, projectId } = props;
Nitpick: deconstruct props

```tsx
export function ProjectEntityHeader({
  branch,
  devAccess,
  [...]
}: ProjectEntityHeaderProps) {
  [...]
}
```

2023-07-28 09:59 UTC, leafty commented on client/src/features/project/components/ProjectEntityHeader.tsx
> +  const projectMetadata = useProjectMetadataQuery(
Nitpick: variable name for readability

```suggestion
  const projectMetadataQuery = useProjectMetadataQuery(
```

2023-07-28 09:59 UTC, leafty commented on client/src/features/project/components/ProjectEntityHeader.tsx
> +    value: projectMetadata.data?.description || "",
```suggestion
    value: projectMetadata.data?.description ?? "",
```

2023-07-28 09:59 UTC, leafty commented on client/src/features/project/components/ProjectSettingsDescription.tsx
> +  };
Create only one callback function here:

```suggestion
  const onSubmit = useCallback(() => {
    updateDescriptionMutation({
      description,
      gitUrl,
      projectId,
    });
  }, [description, gitUrl, projectId, updateDescriptionMutation]);
```

2023-07-28 09:59 UTC, leafty commented on client/src/features/project/components/ProjectSettingsUtils.tsx
> +  const localClass = className ? cx(className) : "d-block mt-2";
No need for `cx` here:

```suggestion
  const localClass = className ?? "d-block mt-2";
```

2023-07-28 09:59 UTC, leafty commented on client/src/features/project/components/ProjectSettingsUtils.tsx
> +      Graph integration
Avoids extra `[space]`:

```suggestion
      <FontAwesomeIcon className="me-5" icon={faExclamationTriangle} />
      This requires Knowledge Graph integration
```

2023-07-28 09:59 UTC, leafty commented on client/src/features/project/components/migrations/ProjectStatusIcon.tsx
> +  // if (isLoading) return null;
```suggestion
```

2023-07-28 09:59 UTC, leafty commented on client/src/features/project/projectCoreApi.ts
> +  tagTypes: ["project-status", "project", "ProjectConfig"],
I think we should use the same convention as [RTK docs](https://redux-toolkit.js.org/rtk-query/usage/automated-refetching) for tags, which is `CamelCase` like types, interfaces, classes, etc.

```suggestion
  tagTypes: ["ProjectStatus", "Project", "ProjectConfig"],
```

2023-07-28 09:59 UTC, leafty commented on client/src/features/project/projectCoreApi.ts
> +      // ? Invalidating immediatley won't work since KG needs a moment to pick up the change.
What does `// ?` mean? (Question mark at start of comment)

2023-07-28 09:59 UTC, leafty commented on client/src/features/project/projectCoreApi.ts
> +      onCacheEntryAdded: (params, { dispatch, cacheDataLoaded }) => {
Non-blocking: This may not be the most reliable way to wait for status.
Maybe polling until the status is correct would work? e.g. https://github.com/SwissDataScienceCenter/renku-ui/blob/b5a035b1e7d6ae52bc67c330fc28cfdd72c4e7a7/client/src/features/session/useWaitForSessionStatus.hook.ts

2023-07-28 09:59 UTC, leafty commented on client/src/features/project/projectCoreApi.ts
> +          }, 1000 * 5);
Define a constant for this.

2023-07-28 09:59 UTC, leafty commented on client/src/project/new/components/Visibility.tsx
> +  visibility?: Visibilities;
This feels suspicious. The prop should always be defined I think.

```suggestion
  visibility: Visibilities;
```

2023-07-28 09:59 UTC, leafty commented on client/src/project/new/components/Visibility.tsx
> +  } = useGetProjectByIdQuery(forkedProjectId as number, {
```suggestion
  } = useGetProjectByIdQuery(forkedProjectId ?? 0, {
```

2023-07-28 09:59 UTC, leafty commented on client/src/project/new/components/Visibility.tsx
> +  const isLoadingSomething =
Nitpick: feels more serious to simply call it `isLoading`

```suggestion
  const isLoading =
```

2023-07-28 09:59 UTC, leafty commented on client/src/project/new/components/Visibility.tsx
> +      <label>Visibility</label>
DOM semantics (#2653):

```suggestion
      <div className="form-label">Visibility</div>
```

2023-07-28 09:59 UTC, leafty commented on client/src/components/formlabels/FormLabels.tsx
> +import { FormText, FormFeedback, Label } from "../../utils/ts-wrappers";
Import these from `reactstrap`

2023-07-28 13:01 UTC, lorenzo-cavazzi commented on client/src/project/new/components/Visibility.tsx
> +  const isLoadingSomething =
Actually `isLoading` is already used for something else in that component :sweat_smile: 
I will rename that to `isLoadingMutation` and change this to `isLoadingAnything`. `isLoading` would be too confusing since there are 4 isLoading variables

2023-07-28 13:15 UTC, lorenzo-cavazzi commented on client/src/components/entities/Description.tsx
> +    height: isHeightFixed ? `${25 * numberLines}px` : undefined,
`lh` cannot be used for `height`, it's marked as invalid in Firefox. I tried a couple of other solutions but they didn't work either.

If it's ok for you I would leave this change to another issue since it doesn't impact the settings page but rather the listings (e.g. Datasets tab, search results, ...)

2023-07-28 13:23 UTC, lorenzo-cavazzi commented on client/src/features/project/components/ProjectEntityHeader.tsx
> +  const { branch, devAccess, fullPath, gitUrl, projectId } = props;
There are quite props we don't use here but still need to pass down to `EntityHeader` as `{...props}`. Not sure restructuring here would be beneficial

2023-07-28 13:27 UTC, lorenzo-cavazzi commented on client/src/features/project/components/ProjectSettingsDescription.tsx
> +  };
Could you briefly explain why this is a better solution? Just to be more concise or is there any impact on performances?

2023-07-28 13:35 UTC, lorenzo-cavazzi commented on client/src/features/project/projectCoreApi.ts
> +  tagTypes: ["project-status", "project", "ProjectConfig"],
I'm not sure about this. We actually use kebab case in all the other tags so far, with the one exception `ProjectConfig` that is pascal case. I personally find pascal case the most confusing choice here since we use that only for types and react components, and I wouldn't consider switching to yet another convention (camel case)

2023-07-28 13:37 UTC, leafty commented on client/src/components/entities/Description.tsx
> +    height: isHeightFixed ? `${25 * numberLines}px` : undefined,
Yes, this is not a blocking comment.

I think it could be done like this: https://tailwindcss.com/docs/line-clamp

2023-07-28 13:41 UTC, lorenzo-cavazzi commented on client/src/features/project/projectCoreApi.ts
> +      // ? Invalidating immediatley won't work since KG needs a moment to pick up the change.
We use it in many places in the UI to explain non-trivial choices in the code.

I guess the main added benefit is that many plugins color it, immediately distinguishing it from the other comments. I believe we use also `// !` for critical and `// TODO` for things to remember when further touching some code)

2023-07-28 13:43 UTC, leafty commented on client/src/features/project/components/ProjectSettingsDescription.tsx
> +  };
It's simpler, and it's less code to read. Performance-wise, it's also better since doing `onClick={onSubmit}` will be a stable reference.

2023-07-28 13:46 UTC, leafty commented on client/src/features/project/projectCoreApi.ts
> +  tagTypes: ["project-status", "project", "ProjectConfig"],
The idea of that convention is that the tag type should be the return type of the query (e.g. `builer.query<ProjectStatus, GetProjectStatusParams>({ ... })`). In that way, it makes sense to adopt the same identifier as the type being returned.

2023-07-28 13:47 UTC, lorenzo-cavazzi commented on client/src/features/project/projectCoreApi.ts
> +      onCacheEntryAdded: (params, { dispatch, cacheDataLoaded }) => {
That's a fair point. Your solution sounds a bit better, but we can still miss the updates in several cases. I guess we really need a message queue system notifying the UI about changes in the project status/indexing to really address this

2023-07-28 13:47 UTC, leafty commented on client/src/features/project/projectCoreApi.ts
> +  tagTypes: ["project-status", "project", "ProjectConfig"],
Also, I am already using that convention in all my RTK endpoints since I followed the docs :wink:

2023-07-28 14:02 UTC, lorenzo-cavazzi commented on client/src/features/project/projectCoreApi.ts
> +  tagTypes: ["project-status", "project", "ProjectConfig"],
I see the reason, but this doesn't seem easy in all cases. E.G: in the KG API we use `KgMetadataResponse`, that doesn't sound like a good tag name.

I'm ok with using pascal case, but since this PR doesn't touch the tag directly I would rather make a PR that changes all the params to a new convention, and add that the coding guides

2023-07-28 14:13 UTC, lorenzo-cavazzi commented
Thank you @leafty for the review! I either addressed the points or responded inline.
I also improved the UX for anonymous users for both the description and the visibility to prevent unnecessary errors

2023-07-28 15:07 UTC, leafty commented on client/src/project/new/components/Visibility.tsx
> +  const isLoadingSomething =
I would avoid "Something" and "Anything" because they do not help explain what is happening in the code. Something like `isLoadingQueries` or `isLoadingData` gives a hint about what we are loading.

2023-07-28 15:08 UTC, leafty commented on client/src/features/project/projectCoreApi.ts
> +      // ? Invalidating immediatley won't work since KG needs a moment to pick up the change.
OK :+1: I have not found any syntax highlighter which does this in vscode though.

2023-07-28 15:14 UTC, leafty commented on client/src/features/project/components/ProjectSettingsDescription.tsx
> +      onSubmit={() => onSubmit()}
Technicality: `() => onSubmit()` creates a new function at each render, while `onSubmit` may stay the same.

```suggestion
      onSubmit={onSubmit}
```

2023-08-02 10:06 UTC, andre-code reviewed
I'm glad we use RTK to update the description and get the project data.
The delay doesn't convince me much in terms of UX because the user doesn't know what's going on, why the value doesn't change, could navigate and see the previous value again.
We also lost the "updating description" message in the project header when it was changing (2nd image attached).

 Is it possible to update the value in the store when the change is successful? if something fails which would be in minor percentage of cases 🤞 then it will revert to the fetched value after 5 sec. By the way the wait to see the updated value was more than 5 seconds 😔.

![update desc](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/3ef151c1-8783-425e-9c6c-774219780152)


![update desc before](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/264a6c50-ba76-47ff-883f-55bb31015ee8)

2023-08-02 12:10 UTC, lorenzo-cavazzi commented on client/src/features/project/projectCoreApi.ts
> +// TODO: this won't be useful anymore once we get status updates though WebSockets.
Fair point!
In this case, we don't have an issue yet cause the feature isn't defined yet

2023-08-07 08:27 UTC, leafty approved these changes
LGTM

2023-08-07 21:32 UTC, merged