WIP feat: change visibility on an existing project (#2515)
SwissDataScienceCenter/renku-ui pull request #2648
Opened 2023-07-11 11:16 UTC by andre-code

PR to include change the visibility on an existing project

/deploy #persists #notest

2023-07-19 09:03 UTC, leafty requested changes
Overall, the logic is good.

Sorry for all the code quality comments, but these are important for readability and avoiding bugs.

2023-07-19 09:03 UTC, leafty commented on client/src/utils/helpers/TextUtils.ts
> +  for (const key in obj) {
nitpick: I would favour using `.map()` or `.flatpMap()` here:

```ts
export function extractTextFromObject(obj: Record<string, unknown>): string[] {
  const textValues = Object.values(obj).flatMap((value) => {
    if (typeof value === 'string') {
      return [value as string]
    }
    if (Array.isArray(value)) {
      const mapped = (value as unknown[]).flatMap((element) => {
        if (typeof element === 'string') {
          return [element as string]
        }
        if (typeof element === 'object') {
          return extractTextFromObject(element as Record<string, unknown>)
        }
        return []
      })
      return mapped;
    }
    if (typeof value === 'object') {
      return extractTextFromObject(value as Record<string, unknown>)
    }
    return []
  })
  return textValues;
}
```

2023-07-19 09:03 UTC, leafty commented on client/src/styles/components/_renku_general.scss
> +}
Would it be possible to add this inside a CSS or SCSS module instead? This will avoid CSS pollution (for example grouped inputs or broken because of bootstrap misconfiguration at the moment).

2023-07-19 09:12 UTC, leafty commented on client/src/styles/components/_renku_general.scss
> +}
Actually, using bootstrap classes would be the most favoured option.

2023-07-19 12:18 UTC, andre-code commented on client/src/utils/helpers/TextUtils.test.ts
> +  });
Thanks for the feedback.
As I understand the definition of expected result (expected) is defined within the Arrange section.

2023-07-19 13:10 UTC, andre-code commented on client/src/utils/helpers/TextUtils.ts
> +  for (const key in obj) {
Good idea. That would be cleaner and remove some of the complexity. I have redone this, you can find it in the last commit.

2023-07-19 13:15 UTC, andre-code commented on client/src/styles/components/_renku_general.scss
> +}
I am not sure if I understood this suggestion correctly, could you please clarify which module you are referring to, one per component? In the meantime I have added the class in the css module we have created for the forms `_renku-form.scss`.

2023-07-19 13:18 UTC, andre-code commented
> Overall, the logic is good.
> 
> Sorry for all the code quality comments, but these are important for readability and avoiding bugs.

Thanks @leafty  for your time in reviewing my PR.
I have carefully considered all your suggestions and implemented them in the latest commit, only a couple of cases are missing as they are not quite clear. I have left some comments.

2023-07-19 14:10 UTC, leafty commented on client/src/utils/helpers/TextUtils.test.ts
> +  });
This is a nitpick, you can ignore it if you think it makes more sense in the arrange section.

It would be nice to have:
```
<arrange>
new line
<act>
new line
<assert>
```
if possible.

2023-07-19 15:12 UTC, leafty commented on client/src/styles/components/_renku_form.scss
> +}
Adding global CSS classes should be avoided when possible as they leak style globally (see next comment for how to achieve the same style).

```suggestion
```

2023-07-19 15:12 UTC, leafty commented on client/src/project/settings/ProjectSettings.present.js
> +          <div className="form-rk-section">
To avoid defining a new global CSS class, I have found that we can do:

```tsx
  return (
    <div className="form-rk-green mb-4">
      <Row className="gy-4">
        <SettingsCard>
          <ProjectTags
            tagList={props.metadata.tagList}
            onProjectTagsChange={props.onProjectTagsChange}
            settingsReadOnly={props.settingsReadOnly}
          />
        </SettingsCard>
        <SettingsCard>
          <ProjectDescription {...props} />
        </SettingsCard>
        <SettingsCard>
          <EditVisibility
            projectId={props.metadata.id}
            namespace={namespace}
            forkedProjectId={props.forkedFromProject?.id}
            visibility={props.metadata.visibility}
          />
        </SettingsCard>
        <SettingsCard>
          <ProjectAvatarEdit
            externalUrl={props.externalUrl}
            avatarUrl={props.metadata.avatarUrl}
            onAvatarChange={props.onAvatarChange}
            settingsReadOnly={props.settingsReadOnly}
            includeRequiredLabel={false}
          />
        </SettingsCard>
      </Row>
    </div>
  );
}

function SettingsCard({ children }) {
  return (
    <Col xs={12}>
      <Card>
        <CardBody className="py-2">
          <Row>
            <Col>{children}</Col>
          </Row>
        </CardBody>
      </Card>
    </Col>
  );
}
```

Note that this makes all the cards have the same spacing around them (which was not the case before).

2023-07-19 15:12 UTC, leafty commented on client/src/components/visibility/Visibility.tsx
> +      </legend>
The legend renders with a large font size, you can style it with:

```suggestion
      <legend className="form-label fs-6">
        Visibility{" "}
        {includeRequiredLabel && <RequiredLabel isRequired={isRequired} />}
      </legend>
```

2023-07-20 17:19 UTC, lorenzo-cavazzi requested changes
Very useful addition!
I added just a couple of inline comments about working or tiny changes.

There is just one additional thing I would change. We should ignore clicks to the current visibility. E.G. if the project is Private already and the user tries to click on Private, we should not open the modal to confirm changing it. Mind that this happens only when clicking on the label, while the radio button already ignores the click correctly (see video)

![Peek 2023-07-20 19-04](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/22de14ef-de97-4ed2-bc0f-27a4c65e9b08)

2023-07-20 17:19 UTC, lorenzo-cavazzi commented on client/src/components/visibility/Visibility.tsx
> +    private: `Public and Internal options are not available due to ${
```suggestion
    private: `Public and Internal not available due to ${
```
slightly shorter

2023-07-20 17:19 UTC, lorenzo-cavazzi commented on client/src/components/visibility/Visibility.tsx
> +    internal: `Public is not available due to ${
```suggestion
    internal: `Public not available due to ${
```
same pattern as the previous message

2023-07-20 17:19 UTC, lorenzo-cavazzi commented on client/src/project/new/components/Visibility.tsx
> +        Edit visibility to{" "}
```suggestion
        Change visibility to{" "}
```
Mind that this requires adjusting the e2e test -- I'll add that as a suggestion too

2023-07-20 17:19 UTC, lorenzo-cavazzi commented on tests/cypress/e2e/project.spec.ts
> +    cy.get(".modal-title").should("contain.text", "Edit visibility to Private");
```suggestion
    cy.get(".modal-title").should("contain.text", "Change visibility to Private");
```

2023-07-20 17:19 UTC, lorenzo-cavazzi commented on client/src/project/new/components/Visibility.tsx
> +        this project. If you need more information about visibility, please
This message is correct for public and internal projects but misleading for private projects; it's actually the opposite.
In that case, I would change it to something like "Users will not find this project anymore unless you explicitly add them to the Members list", with a link to the members page in GitLab

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/12ee058b-058b-4e37-ac51-607a3698580e)

2023-07-20 17:19 UTC, lorenzo-cavazzi commented on client/src/project/new/components/Visibility.tsx
> +  const buttons = !isError && !isLoading && !isSuccess && (
Should we show a "Close" button in all the other cases?
Feel free to disagree and keep the current solution here :slightly_smiling_face:

2023-07-21 07:46 UTC, andre-code commented
> Very useful addition! I added just a couple of inline comments about working or tiny changes.
> 
> There is just one additional thing I would change. We should ignore clicks to the current visibility. E.G. if the project is Private already and the user tries to click on Private, we should not open the modal to confirm changing it. Mind that this happens only when clicking on the label, while the radio button already ignores the click correctly (see video)
> 
> ![Peek 2023-07-20 19-04](https://user-images.githubusercontent.com/43481553/254959493-22de14ef-de97-4ed2-bc0f-27a4c65e9b08.gif)

Thanks @lorenzo-cavazzi for your suggestions, I have implemented them and also those discussed in the product ui meeting.
In addition I have included here the endpoint kg to update the visibility, if the project is not yet activated we show an Alert.

2023-07-24 12:46 UTC, lorenzo-cavazzi requested changes
This looks good! It does include #2675 already, right?

I added a couple of minor comments inline. We can then merge it

2023-07-24 12:46 UTC, lorenzo-cavazzi commented on client/src/project/new/components/Visibility.tsx
> +      </WarnAlert>
Should we make this non-dismissible? Otherwise, we are left with a white space.

![Peek 2023-07-24 14-39](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/5218847e-18da-4c4b-b1dc-6d8a90a44e9a)

2023-07-25 06:20 UTC, leafty commented on client/src/components/formlabels/FormLabels.tsx
> +  // TODO: remove this component
See https://github.com/SwissDataScienceCenter/renku-ui/pull/2648#discussion_r1267722707. This adds one level of indirection for no benefit. Just use `FormText`.

2023-07-25 13:25 UTC, leafty commented on client/src/components/formlabels/FormLabels.tsx
> +  );
Done in 84a42dde5fcb849d5ce683668a7632c2fc20c111

2023-07-25 13:40 UTC, leafty commented on client/src/components/visibility/Visibility.tsx
> +        <ThrottledTooltip
Use `UncontrolledTooltip` from `reactstrap`.

2023-07-26 08:42 UTC, lorenzo-cavazzi approved these changes
Lgtm! :rocket:

2023-07-26 12:02 UTC, lorenzo-cavazzi approved these changes

2023-07-26 13:22 UTC, merged