refactor session list views
SwissDataScienceCenter/renku-ui pull request #2663
Opened 2023-07-17 08:40 UTC by leafty

2023-07-18 15:01 UTC, lorenzo-cavazzi requested changes
The code quality is really high! I added inline just an alternative solution for the sessions Cypress tests, and a generic comment on when to use `cx` (feel free to disagree on that :grin: ).

Generally, I believe we should keep suggesting how to start a session in the new Session tab when no sessions are running. I would add back an InfoAlert similar to the previous one, suggesting using the button on top (ofc no need to recreate the old button since now it's in the normal header) or clicking straight on a "New session" link that brings the user to the "Start with options" page.

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/a12135bf-d118-4146-abf2-b9a1ad3f050d)


At first sight, I'm tempted to say that duplicating the session button on the sessions tab might be redundant. Still, removing it might be confusing for some users and I can't think of a better alternative. We can live with that

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/48d10b5f-b5e7-4075-a452-760ec53348ec)

2023-07-19 09:23 UTC, leafty commented on tests/cypress/support/sessions/gui_commands.ts
> +  cy.get_cy("open-session").first().click();
Done in 9b84b1d.

2023-07-19 09:24 UTC, leafty commented on client/src/features/session/components/SessionsList.tsx
> +          <div className={cx("project", "d-inline-block", "text-truncate")}>
I have found that it makes changing and experimenting with classes faster (can add or comment one class name).

2023-07-19 09:25 UTC, leafty commented
> Generally, I believe we should keep suggesting how to start a session in the new Session tab when no sessions are running. I would add back an InfoAlert similar to the previous one, suggesting using the button on top (ofc no need to recreate the old button since now it's in the normal header) or clicking straight on a "New session" link that brings the user to the "Start with options" page.

Yes, I will add the alert and button in another PR, which would make it easier to discuss the UI/UX for the updated sessions tab.

2023-07-19 11:32 UTC, lorenzo-cavazzi approved these changes
Lgtm :rocket:

2023-07-19 14:07 UTC, merged