[wip] client(feat): support persistent sessions in the UI
SwissDataScienceCenter/renku-ui pull request #2686
Opened 2023-07-21 06:51 UTC by leafty

Fixes #2526.

The components to support interactive sessions (e.g. Jupyter notebooks, R studio) have been refactored and updated to support persistent sessions.

2023-08-28 12:22 UTC, ciyer requested changes
This looks good and works well. I have one suggestion for a change of name, and one proposal for improving UX.

2023-08-29 07:15 UTC, leafty commented on client/src/features/session/components/SessionButton.tsx
> +function SessionActions({ className, session }: SessionActionsProps) {
🤔 yes it seems that logs are simply not available, so I will remove the option.

`Create Session Link` should always be available (as this is about creating `Launch in Renku` badges).

2023-08-29 09:05 UTC, leafty commented on client/src/features/session/components/SessionButton.tsx
> +function SessionActions({ className, session }: SessionActionsProps) {
Done in [005eee2](https://github.com/SwissDataScienceCenter/renku-ui/pull/2686/commits/005eee268e679548344fc69582296bef924b67ef)

2023-08-29 15:58 UTC, lorenzo-cavazzi commented
Something else I noticed while playing around. I believe we should not give the `pause` option when the session is in an error state. Pieces might be missing, and this state usually happens at the start time. Pausing can easily fail.
Should we only offer to delete the session in this case?
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/74119612-b97e-413b-82f8-f1a7c172e89a)

2023-08-30 05:48 UTC, leafty commented
> Something else I noticed while playing around. I believe we should not give the `pause` option when the session is in an error state. Pieces might be missing, and this state usually happens at the start time. Pausing can easily fail. Should we only offer to delete the session in this case? ![image](https://user-images.githubusercontent.com/43481553/264081077-74119612-b97e-413b-82f8-f1a7c172e89a.png)

We should definitely offer a chance for users to cycle their session and not lose their work

2023-08-30 06:28 UTC, lorenzo-cavazzi commented
It's unlikely that "Pause" will work when sessions are in that state.
If you wish to preserve this action, we should find a way to handle the error we will probably get.
Currently, we keep showing the spinning wheel even when the API errors. That's not a good UX
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/2442f048-3e9c-4fb7-964c-0285eeee0d46)

2023-08-30 07:13 UTC, leafty commented
> 

🤔 I will fix that

2023-08-31 10:46 UTC, leafty commented
> It's unlikely that "Pause" will work when sessions are in that state. If you wish to preserve this action, we should find a way to handle the error we will probably get. Currently, we keep showing the spinning wheel even when the API errors. That's not a good UX

Done in [9f31c08](https://github.com/SwissDataScienceCenter/renku-ui/pull/2686/commits/9f31c0845c1f9c3a64c64ff3892605fecffeba19).

2023-08-31 14:53 UTC, lorenzo-cavazzi commented
Thanks!

I tested the system quite a bit. It works pretty well! I can't wait to see this deployed on RenkuLab :star_struck: 
I got confusing feedback only with failures on the migrations endpoint -- sadly, that seems to happen quite often lately...
When that happens, I get the following:

* On the quickstart page, it hangs in Step 1 on "Loading project settings". We should probably show a red cross on that step and add a notification
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/129b5527-d458-4169-a9c9-2b61719e91de)
* On the "Start session" page the feedback is messed up cause we keep re-invoking the `GET /renku/config.show` API. We should show an error alert and not invoke the API if we don't have the project version
![Peek 2023-08-31 16-48](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/8cfc7293-5781-43a8-a915-139ee91c9173)

2023-08-31 21:04 UTC, rokroskar commented
Pausing a session always brings up an error - is it supposed to work at the moment?

2023-09-01 06:43 UTC, leafty commented
> Pausing a session always brings up an error - is it supposed to work at the moment?

Should be working now.

2023-09-01 07:16 UTC, leafty commented
> Thanks!
> 
> I tested the system quite a bit. It works pretty well! I can't wait to see this deployed on RenkuLab 🤩 I got confusing feedback only with failures on the migrations endpoint -- sadly, that seems to happen quite often lately... When that happens, I get the following:
> 
> * On the quickstart page, it hangs in Step 1 on "Loading project settings". We should probably show a red cross on that step and add a notification
>   ![image](https://user-images.githubusercontent.com/43481553/264683983-129b5527-d458-4169-a9c9-2b61719e91de.png)
> * On the "Start session" page the feedback is messed up because we keep re-invoking the `GET /renku/config.show` API. We should show an error alert and not invoke the API if we don't have the project version
>   ![Peek 2023-08-31 16-48](https://user-images.githubusercontent.com/43481553/264685546-8cfc7293-5781-43a8-a915-139ee91c9173.gif)

I just added [728fa15](https://github.com/SwissDataScienceCenter/renku-ui/pull/2686/commits/728fa1525b6d6ecf77c8b6ee5115248c364a3feb), I hope this will cover enough cases on `core` not supporting the project or failing.

2023-09-01 08:22 UTC, lorenzo-cavazzi requested changes

2023-09-01 08:22 UTC, lorenzo-cavazzi commented on client/src/features/session/components/options/AutostartSessionOptions.tsx
> +    skip: !coreSupportComputed || !commit,
I believe this is not enough to properly handle an error from the `migrations_check` endpoint. When I get an error, the `coreSupport` object contains the following:
```
{
  "backendAvailable": false,
  "backendErrorMessage": "Our servers generated an unexpected error while processing data.",
  "computed": true
}
```

`computed` is true, so it fetches the config anyway. You should check both `computed` and `backendAvailable`. Otherwise, it fetches the config with a URL not containing the project version (it works the same only when projects are on the latest version)

![Peek 2023-09-01 10-10](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/67486521-4383-4521-88c0-4cba6b0793de)

2023-09-01 09:02 UTC, leafty commented on client/src/features/session/components/options/AutostartSessionOptions.tsx
> +    skip: !coreSupportComputed || !commit,
Would [4e40d77](https://github.com/SwissDataScienceCenter/renku-ui/pull/2686/commits/4e40d772b3ac838572b14ee0a1b4fa98bb55b7d0) be OK? The UI will error if the project is not supported by core.

2023-09-01 09:32 UTC, lorenzo-cavazzi commented on client/src/features/session/components/options/AutostartSessionOptions.tsx
> +    skip: !coreSupportComputed || !commit,
Yes, that's much better!

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/818d679a-7423-4617-8e8a-b2b7364570a5)

Ideally, we could show the error message from renku-core since it's more on point (it's already in `backendErrorMessage`). In the sample above, there was an error on the server side and it might work again later. Saying the project is not supported is a bit confusing for a user who could wonder what should be done to make the project supported. Still, we can keep the current solution if it's a bigger change.

2023-09-01 09:37 UTC, leafty commented on client/src/features/session/components/options/AutostartSessionOptions.tsx
> +    skip: !coreSupportComputed || !commit,
I think I will try, but I would like to do it in another PR.

2023-09-05 13:34 UTC, lorenzo-cavazzi commented on client/src/project/Project.present.js
I think the code that triggers infinite queries for the servers is the `constructor` in the `ProjectViewHeader`. It invokes `fetchNotebooks` from `NotebooksCoordinator`.
It can _probably_ be removed entirely without any change since now we query sessions differently, but it's worth checking whether we need to add `useGetSessionsQuery` to compensate.
The same goes for the Dashboard component in "features/dashboard/Dashboard.tsx".

Could you give it a look? Otherwise, I can do it sometimes tomorrow

2023-09-08 13:05 UTC, ciyer approved these changes
Thanks for addressing my suggestions.

2023-09-13 11:55 UTC, lorenzo-cavazzi submitted a review, later dismissed
I played around a little bit and all worked well. I can't wait so see this merged! :star_struck:  :rocket: 
Thank you for the big effort on this!

2023-09-18 09:00 UTC, lorenzo-cavazzi commented
A tiny detail I noticed: when reaching the "Start with options" page, the UI briefly flashes the error message for the project settings. It's easy to reproduce if you refresh the page from the browser

![Peek 2023-09-18 10-57](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/8898ef7d-eb05-45df-a6a4-0d42ab7797f2)

2023-09-19 08:00 UTC, leafty commented
> A tiny detail I noticed: when reaching the "Start with options" page, the UI briefly flashes the error message for the project settings. It's easy to reproduce if you refresh the page from the browser

Should be fixed in [c149bf5](https://github.com/SwissDataScienceCenter/renku-ui/pull/2686/commits/c149bf56fe03672be89cd12d0da700244f111379)

2023-09-19 13:48 UTC, lorenzo-cavazzi approved these changes

2023-09-25 08:43 UTC, lorenzo-cavazzi commented
P.S. Before merging, we might need to update the Cypress acceptance tests here https://github.com/SwissDataScienceCenter/renku/pull/3240

2023-09-25 14:00 UTC, merged