feat: pass gitlab urls to core APIs instead of project ids fetched from the backend cache
SwissDataScienceCenter/renku-ui pull request #2717
Opened 2023-08-03 15:50 UTC by lorenzo-cavazzi

Phase out the code to invoke deprecated renku-core APIs.
Those were primarily datasets APIs requiring to pass the renku-core cached project id reference.

Mind that the PR includes a few minor fixes on the datasets page:
* Avatar elements take the required vertical space.
* Avatar not accidentally removed when editing a dataset.
* No grey-background cells for tables on the dataset page.
* Stable datasets URL (not everywhere).

/deploy #persist renku-core=develop renku=renku-ui/3.11-acceptance-tests
fix #2713

2023-08-18 12:55 UTC, lorenzo-cavazzi commented
The biggest changes are with:
* Creating datasets.
* Editing datasets.
* Deleting datasets.

The logic to import datasets is mostly unchanged.

2023-08-18 14:45 UTC, ciyer requested changes
This is a much needed and long overdue refactoring! For the most part, it looks good to me. I have a few small suggestions for improvements to the code, but that is all.

2023-08-18 14:45 UTC, ciyer commented on client/src/utils/types/coreService.types.ts
> +}
I think defining the structure, but leaving the type of `result` to subtypes of `CoreResponse` could be better handled this way:

```suggestion
export interface CoreResponse<T> {
  error?: CoreErrorContent;
  result?: T;
}
```

2023-08-18 14:45 UTC, ciyer commented on client/src/features/project/projectCoreApi.ts
> +          url: `/project.edit`,
Is this not a versioned endpoint?

2023-08-18 14:45 UTC, ciyer commented on client/src/dataset/Dataset.present.js
> +          : location.pathname + "/modify",
Could this be shared with the similar code in `ErrorAfterCreation`?

2023-08-18 14:45 UTC, ciyer commented on client/src/features/datasets/datasets.types.ts
> +}
Assuming the changes suggested in `coreService.types`:

```suggestion
export type DeleteDatasetResponse = CoreResponse<DatasetOperationResponse>
```

2023-08-18 14:45 UTC, ciyer commented on client/src/features/datasets/datasets.types.ts
> +}
Assuming the changes suggested in coreService.types:

```suggestion
export type AddFilesResponse = CoreResponse<AddFilesOperationResponse>
```

2023-08-18 14:45 UTC, ciyer commented on client/src/features/datasets/datasets.types.ts
> +}
Assuming the changes suggested in coreService.types:

```suggestion
export type PostDatasetResponse = CoreResponse<DatasetOperationResponse>;
```

2023-08-18 14:45 UTC, ciyer commented on client/src/features/project/dataset/DatasetModify.tsx
> +        <p>Some files could not be updated.</p>
Is the old message no longer accurate? If it is, I think we should communicate to the user that some of their changes were applied, but the files in the dataset were not changed.

2023-08-21 15:13 UTC, lorenzo-cavazzi commented on client/src/features/project/projectCoreApi.ts
> +          url: `/project.edit`,
Good catch, this should be versioned. I'll move that to another PR since it touches a different functionality

2023-08-22 08:49 UTC, ciyer approved these changes
Fantastic!

2023-08-22 12:50 UTC, merged