Add start session page
SwissDataScienceCenter/renku-ui pull request #2719
Opened 2023-08-07 12:28 UTC by leafty

/deploy #persist extra-values=notebooks.userSessionPersistentVolumes.enabled=true,notebooks.amalthea.image.repository=renku/amalthea,notebooks.amalthea.image.tag=db70f80ef1983d49a1b167faa57d02d9d8b9554f renku-notebooks=pitch/session-persistence

2023-08-08 16:31 UTC, lorenzo-cavazzi requested changes
Wow, the code reads so much better now! It's actually much easier to review it than expected :smile: 

I added some inline comments for a few changes. The code quality is great overall.

I still need to test it on the browser. I noticed a few issues but I'm not going to rush feedback and I'll test it carefully tomorrow, then give a final review

2023-08-08 16:31 UTC, lorenzo-cavazzi commented on client/src/features/session/components/options/SessionStorageOption.tsx
Not actually a change from this PR, but since I'm going through this...
Do you mind changing:
* `cx(styles.container, "d-grid gap-sm-3 align-items-center")` --> `cx(styles.container, "d-grid", "gap-sm-3", "align-items-center")`
* className={"rounded-end"} --> className="rounded-end"
Thank you :pray:

2023-08-09 08:06 UTC, leafty commented on client/src/features/repository/repository.api.ts
> +        while (true) {
I can replace this with a `for` loop (e.g. 10 iterations so 1,000 commits).

2023-08-09 08:07 UTC, leafty commented on client/src/features/session/components/StartNewSession.tsx
> +  const projectUrl = Url.get(Url.pages.project, projectUrlData);
I will check this. I was following code I saw elsewhere, using `pathWithNamespace`. I think the one using `namespace` and `path` is because for that `Url.get()`, it does not work otherwise.

2023-08-09 08:10 UTC, leafty commented on client/src/features/session/components/options/SessionCommitOption.tsx
> +  const [limit, setLimit] = useState<number>(25);
OK, I can probably set this as an issue and address it soon. I would rewrite the commit selector to use `react-select` and not `react-autosuggest` (which does weird things, not great for accessibility). I think I can easily have a "Load more" button which would trigger fetching the next page.

2023-08-09 08:33 UTC, leafty commented on client/src/features/session/components/options/SessionCloudStorageOption.tsx
> +  return <SessionS3CloudStorageOption />;
Done in [7872714](https://github.com/SwissDataScienceCenter/renku-ui/pull/2719/commits/787271437d9cfc57cb65750965a453ed1a33fdf1).

2023-08-09 08:34 UTC, leafty commented on client/src/features/session/components/options/SessionCloudStorageOption.tsx
> +        <div className={cx("form-label", "small", "text-rk-text")}>
Done in [7872714](https://github.com/SwissDataScienceCenter/renku-ui/pull/2719/commits/787271437d9cfc57cb65750965a453ed1a33fdf1).

2023-08-09 08:34 UTC, leafty commented on client/src/features/session/components/options/SessionStorageOption.tsx
Done in [7872714](https://github.com/SwissDataScienceCenter/renku-ui/pull/2719/commits/787271437d9cfc57cb65750965a453ed1a33fdf1).

2023-08-09 11:31 UTC, leafty commented on client/src/features/pipelines/pipelines.api.ts
Done in [143b872](https://github.com/SwissDataScienceCenter/renku-ui/pull/2719/commits/143b872366f7bad45a157f722b5bc210b4a05594).

2023-08-09 11:41 UTC, leafty commented on client/src/features/repository/repository.api.ts
Done in [d2cc517](https://github.com/SwissDataScienceCenter/renku-ui/pull/2719/commits/d2cc517577763ec75aba544c5d8a0539422881d5).

2023-08-09 11:45 UTC, leafty commented on client/src/features/registry/registry.api.ts
Done in [abc145c](https://github.com/SwissDataScienceCenter/renku-ui/pull/2719/commits/abc145cb691ef9018b3e273d0ecf719abc4c0f00).

2023-08-09 11:55 UTC, leafty commented on client/src/features/repository/repository.api.ts
> +        while (true) {
Done in [6eb561a](https://github.com/SwissDataScienceCenter/renku-ui/pull/2719/commits/6eb561a3ef83ad4a5a1edaee41ef33246a714881).

2023-08-09 12:05 UTC, leafty commented on client/src/features/session/components/StartNewSession.tsx
> +  const projectUrl = Url.get(Url.pages.project, projectUrlData);
I think I would move this to refactoring the `Url` utilities. We should rely on [generatePath](https://v5.reactrouter.com/web/api/generatePath) from `react-router`.

2023-08-09 12:56 UTC, leafty commented on client/src/features/session/components/options/SessionCommitOption.tsx
> +  const [limit, setLimit] = useState<number>(25);
Referenced in https://github.com/SwissDataScienceCenter/renku-ui/issues/2725.

2023-08-10 15:28 UTC, lorenzo-cavazzi approved these changes
Let's merge this :rocket: 

P.S: there are a few details to polish but I can do a final pass on the main PR once that is ready; most of the points I have aren't strictly related only to the start session page

2023-08-11 06:58 UTC, merged