Llog redis failures during operations
SwissDataScienceCenter/renku-ui pull request #2732
Opened 2023-08-11 10:32 UTC by ciyer

Check return values from redis and log errors when appropriate.

Fix #2610

/deploy #persist renku=renku-ui/3.11-acceptance-tests

2023-08-14 10:19 UTC, lorenzo-cavazzi requested changes
The code makes sense to me, but I spotted a strange case with the "lastVisistedProjects" middleware (more info inline).

After a few more trials, I wonder if the problem is in the `RedisStorage` class. I got the following error when simulating a failure; we are not catching exceptions from `ioredis`, perhaps we should wrap `this.redis.<someAction>` around a `try/catch`

```
[start:dev-debug] [ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms. Last error: Connection is closed.
[start:dev-debug]     at SentinelConnector.<anonymous> (/home/lorenzo/development/sdsc/renku-ui/server/node_modules/ioredis/built/connectors/SentinelConnector/index.js:73:31)
[start:dev-debug]     at Generator.next (<anonymous>)
[start:dev-debug]     at /home/lorenzo/development/sdsc/renku-ui/server/node_modules/ioredis/built/connectors/SentinelConnector/index.js:8:71
[start:dev-debug]     at new Promise (<anonymous>)
[start:dev-debug]     at __awaiter (/home/lorenzo/development/sdsc/renku-ui/server/node_modules/ioredis/built/connectors/SentinelConnector/index.js:4:12)
[start:dev-debug]     at connectToNext (/home/lorenzo/development/sdsc/renku-ui/server/node_modules/ioredis/built/connectors/SentinelConnector/index.js:59:37)
[start:dev-debug]     at SentinelConnector.<anonymous> (/home/lorenzo/development/sdsc/renku-ui/server/node_modules/ioredis/built/connectors/SentinelConnector/index.js:125:24)
[start:dev-debug]     at Generator.throw (<anonymous>)
[start:dev-debug]     at rejected (/home/lorenzo/development/sdsc/renku-ui/server/node_modules/ioredis/built/connectors/SentinelConnector/index.js:6:65)
```

2023-08-14 10:19 UTC, lorenzo-cavazzi commented on server/src/utils/middlewares/lastProjectsMiddleware.ts
> +          });
The code here makes sense to me, but when I try to simulate a storage failure just before navigating to a project from the UI (I manually delete all the Redis instances from Rancher) I get a `500 internal error` response; from the code, I assume it should log the error to Sentry and jump to the next step.

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/911e5609-657c-413c-b165-146f1ce2b9cd)

Perhaps something with `storage.save` is off?

2023-08-14 11:13 UTC, leafty commented
> The code makes sense to me, but I spotted a strange case with the "lastVisistedProjects" middleware (more info inline).
> 
> After a few more trials, I wonder if the problem is in the `RedisStorage` class. I got the following error when simulating a failure; we are not catching exceptions from `ioredis`, perhaps we should wrap `this.redis.<someAction>` around a `try/catch`
> 
> ```
> [start:dev-debug] [ioredis] Unhandled error event: Error: All sentinels are unreachable. Retrying from scratch after 10ms. Last error: Connection is closed.
> [start:dev-debug]     at SentinelConnector.<anonymous> (/home/lorenzo/development/sdsc/renku-ui/server/node_modules/ioredis/built/connectors/SentinelConnector/index.js:73:31)
> [start:dev-debug]     at Generator.next (<anonymous>)
> [start:dev-debug]     at /home/lorenzo/development/sdsc/renku-ui/server/node_modules/ioredis/built/connectors/SentinelConnector/index.js:8:71
> [start:dev-debug]     at new Promise (<anonymous>)
> [start:dev-debug]     at __awaiter (/home/lorenzo/development/sdsc/renku-ui/server/node_modules/ioredis/built/connectors/SentinelConnector/index.js:4:12)
> [start:dev-debug]     at connectToNext (/home/lorenzo/development/sdsc/renku-ui/server/node_modules/ioredis/built/connectors/SentinelConnector/index.js:59:37)
> [start:dev-debug]     at SentinelConnector.<anonymous> (/home/lorenzo/development/sdsc/renku-ui/server/node_modules/ioredis/built/connectors/SentinelConnector/index.js:125:24)
> [start:dev-debug]     at Generator.throw (<anonymous>)
> [start:dev-debug]     at rejected (/home/lorenzo/development/sdsc/renku-ui/server/node_modules/ioredis/built/connectors/SentinelConnector/index.js:6:65)
> ```

Just a non-blocking remark here: wrappers like the RedisStorage class are usually prone to create bugs and issues over time. I would rather use the redis client library directly and handle error states at the call site.

2023-08-14 12:08 UTC, lorenzo-cavazzi commented
> wrappers like the RedisStorage class are usually prone to create bugs and issues over time.

I agree with this.
The main driver to have a wrapper was the idea to move away from Redis soon (delegate auth to Gateway, and use permanent storage for everything else). How confusing are responses from `ioresdis` was another point for that solution. Ofc that played out badly and in insight I would not go for this solution again.

At this point we will probably repurpose the UI server soon, I would say we can keep the current approach for the time being.

2023-08-15 14:05 UTC, lorenzo-cavazzi approved these changes
Lgtm! :rocket:

2023-08-16 07:07 UTC, merged