Updates to Anonymous Landing Page
SwissDataScienceCenter/renku-ui pull request #2741
Opened 2023-08-16 09:57 UTC by ciyer

Fix #2681

2023-08-17 12:19 UTC, ciyer commented
From the meeting today:
- Buttons on first section should have translucent background with white text and outlines that turn green on hover
- "Get Started" links to https://renku.readthedocs.io/en/stable/tutorials/01_firststeps.html
- Leave the "Connecting dots" section unchanged
- Drop the Explore column in the bottom nav
- "Renku version" links to the the same page as the release number
- "Why Renku" links to https://renku.readthedocs.io/en/stable/introduction/why.html
- Remove "Features page" from the Help page

2023-08-22 09:44 UTC, ciyer commented
Testing: check that the new design matches [Figma](https://www.figma.com/file/qFKV4jeWVr0v6y9XB0bmQO/Make-the-search-button-more-immediate-%232681?type=design&node-id=358%3A3472&mode=design&t=54yP7xhG6NN6H0jM-1)

2023-08-22 11:22 UTC, leafty commented on client/src/landing/anonymousHomeNav.tsx
> +              <BottomNavExternalLink title="Twitter" url={Links.TWITTER} />
:nerd_face: 
```suggestion
              <BottomNavExternalLink title="𝕏 (formerly Twitter)" url={Links.TWITTER} />
```

2023-08-22 11:51 UTC, lorenzo-cavazzi requested changes
This looks good! A couple of tiny changes before merging:

- The buttons margin/spacing could be improved by removing the right margin and adding X margins, and adding either the bottom or Y margins. Currently, they have no bottom margin and the first 2 buttons have a right margin, making their borders collapse together on smaller screens and moving them into a non horizonatally centered position.
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/815ecd2c-8f7f-4291-8e3b-d3abbd7ac6b4)

- Bottom margins on the top container are inconsistent, depending on the browser size
![Peek 2023-08-22 13-23](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/86aeac2a-ba49-4406-a1ea-b8d2976ebb44)

- See inline typos

2023-08-22 11:51 UTC, lorenzo-cavazzi commented on client/src/landing/anonymousHomeNav.tsx
> +              <BottomNavExternalLink title="Form" url={Links.DISCOURSE} />
```suggestion
              <BottomNavExternalLink title="Forum" url={Links.DISCOURSE} />
```

2023-08-22 11:51 UTC, lorenzo-cavazzi commented on client/src/landing/anonymousHomeNav.tsx
> +                <TopNavExternalLink title="Form" url={Links.DISCOURSE} />
```suggestion
                <TopNavExternalLink title="Forum" url={Links.DISCOURSE} />
```

2023-08-22 11:56 UTC, leafty reviewed
About styling: I would suggest avoiding global CSS definitions and using Bootstrap's utility classes as much as possible. For cases when custom styling is required, (S)CSS modules seem appropriate as they will not affect components outside of their scope.

2023-08-22 11:56 UTC, leafty commented on client/src/styles/bootstrap_ext/_button.scss
> +.btn-outline-rk-white {
This class is generated by Bootstrap, I would prefer if we do not change its behavior globally. Would it be possible to override this in a (S)CSS module?

Also, overriding the color can be done with the bootstrap CSS variables (e.g. check the overrides from `btn-danger` or `btn-outline-danger`).

2023-08-22 11:56 UTC, leafty commented on client/src/styles/components/_renku_home.scss
> +  @extend .my-2, .mx-3;
It seems simpler to assign `my-2` and `mx-3` to the class name.

2023-08-22 11:56 UTC, leafty commented on client/src/styles/components/_renku_home.scss
> +  color: $rk-white;
Use `text-rk-white` as a class name.

2023-08-22 11:56 UTC, leafty commented on client/src/styles/components/_renku_home.scss
> +  list-style-type: none;
`list-unstyled`: https://getbootstrap.com/docs/5.3/content/typography/#unstyled

2023-08-22 11:56 UTC, leafty commented on client/src/styles/components/_renku_home.scss
> +  padding-left: 0px;
`pl-0`

2023-08-22 21:21 UTC, ciyer commented on client/src/styles/components/_renku_home.scss
> +  @extend .my-2, .mx-3;
Good point.

2023-08-23 07:28 UTC, ciyer commented
Thanks for the reviews, it's important that this page be polished. I think I have addressed all requests.

2023-08-23 08:42 UTC, leafty commented on client/src/landing/anonymousHome.types.ts
> +    projects: [];
Unless `never[]` is intended:

```suggestion
    projects: unknown[];
```

2023-08-23 08:42 UTC, leafty commented on client/src/landing/anonymousHomeNav.tsx
> +              <BottomNavExternalLink title="Twitter" url={Links.TWITTER} />
Some companies have already updated it actually. e.g. a marketing email I received:
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/4f5b9f9f-a199-4c58-862b-77c9a2230824)

2023-08-23 12:28 UTC, lorenzo-cavazzi approved these changes
Lgtm.
Keep using "Twitter" works fine for me since the new name is hard to relate to the product without the icon or specifying that it's actually what used to be Twitter

2023-08-24 07:26 UTC, merged