test(storybook): add test runner and interactive stories (#2212)
SwissDataScienceCenter/renku-ui pull request #2748
Opened 2023-08-17 14:32 UTC by andre-code

This pull request introduces the **Storybook test runner**, which transforms our stories into executable tests, covering both Chromium and Firefox browsers.

And also **Storybook  Interactive stories** for CreatorsInput and ButtonWithOption components  that are useful when we want to demonstrate and verify the behavior of the components in a realistic and dynamic manner. 

## How to test
To run tests `npm run test-storybook`

For interactive stories:
![interaction stories](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/f877cdd0-e126-43c5-95ca-4c1154c7f3c5)

/deploy #persist

2023-08-21 17:25 UTC, lorenzo-cavazzi requested changes
This is very interesting!

2023-08-21 17:25 UTC, lorenzo-cavazzi commented on client/package.json
> +    "test-storybook": "test-storybook --browsers firefox chromium"
Should this also start storybook? 
If I run just `test-storybook`, I get

> [test-storybook] It seems that your Storybook instance is not running at: http://127.0.0.1:6006. Are you sure it's running?

2023-08-21 17:25 UTC, lorenzo-cavazzi commented on client/src/components/form-field/CreatorsInput.tsx
> +            data-testId="creator-add"
Could we re-use the `data-cy` here since it's about testing? Or perhaps we should have a generic `data-test`, but I would not distinguish between Cypress or Storybook, it seems redundant

2023-08-21 17:25 UTC, lorenzo-cavazzi commented on client/src/components/form-field/CreatorsInput.tsx
> +            data-testId="creator-delete"
same as above

2023-08-23 08:43 UTC, andre-code commented on client/src/components/form-field/CreatorsInput.tsx
> +            data-testId="creator-add"
Storybook test uses Jest, which has limited query capabilities, in this scenario, we can address the need to utilize an attribute other than data-testId by implementing a  [Custom Queries in DOM Testing Library](https://testing-library.com/docs/dom-testing-library/api-custom-queries/).

In my view, maintaining consistency with the choice of a single attribute for testing purposes is important. While data-cy is closely associated with Cypress, it would be advantageous to modify the tests across different repositories (both Cypress in the UI and Renku) to employ the data-test attribute. However, this might warrant a separate issue.

At the moment, we have the option to either work with the default attribute used by Jest or to create a custom query. I am open to both solutions.

2023-08-23 11:49 UTC, andre-code commented on client/package.json
> +    "test-storybook": "test-storybook --browsers firefox chromium"
yes,  test runner requires either a locally running Storybook instance or a published Storybook to run the tests.

2023-08-23 14:11 UTC, lorenzo-cavazzi commented on client/package.json
> +    "test-storybook": "test-storybook --browsers firefox chromium"
Ok. Can we make the action start storybook and run the tests without requiring 2 separate steps?

2023-08-23 14:15 UTC, lorenzo-cavazzi commented on client/src/components/form-field/CreatorsInput.tsx
> +            data-testId="creator-add"
Thanks for pointing me to that documentation.

I thought about this and I feel implementing a selector to reuse `data-cy` would be nice. That way, we will have only one custom attribute for all tests. Also, that might incentives us to use it even more and it will automatically be available to other set of tests (E.G: the Cypress acceptance tests)

2023-08-26 12:56 UTC, andre-code commented on client/package.json
> +    "test-storybook": "test-storybook --browsers firefox chromium"
This might be a bit tricky to implement straightforwardly. Even if I utilize tools like `concurrently` to wait for server accessibility, there's still the possibility that the server might be reachable but not fully prepared for testing.

2023-08-26 14:29 UTC, andre-code commented on client/src/components/form-field/CreatorsInput.tsx
> +            data-testId="creator-add"
I have found a way to do it without using the custom queries 🙂

2023-08-29 16:51 UTC, lorenzo-cavazzi commented on README.md
> +4. Testing Stories:
Let's adapt this to the current format from the `2298-fix-broken-components` branch: 

```suggestion
#### Test stories
```

The content might need to be slightly adjusted if we for for this solution https://github.com/SwissDataScienceCenter/renku-ui/pull/2748/files#r1309106040

2023-08-29 16:54 UTC, lorenzo-cavazzi commented
This looks good! And we are on the right way!
Give a look at the comment here https://github.com/SwissDataScienceCenter/renku-ui/pull/2748#discussion_r1309106040 (sorry I messed up when using the review buttons so this is just a comment now :facepalm: )

2023-08-30 16:32 UTC, lorenzo-cavazzi reviewed
This looks good now :rocket: 

I added a few commits to streamline some details (readme formatting, new npm commands, gitignore file). I pushed them directly since it's just formatting/chores, but ofc feel free to change anything you don't like from my last changes.

Storybook tests work well now :raised_hands: 
The last missing piece is running them in a GitHub action. Since we don't need any existing deployment, we can run them in the `test-and-ci.yml` action. I suggest adding a `run-storybook` job similar to `run-e2e`.
The setup should be simple since we just need to checkout, setup node, and run the new all-in-one action to build and test.
P.S. if you need a reference, there is a section in the Storybook documentation https://storybook.js.org/tutorials/ui-testing-handbook/react/en/automate/
We need only a subset of the `interaction-and-accessibility` job; it's probably simpler to copy from our other existing jobs. Text me if you need any help

2023-09-05 19:51 UTC, andre-code commented
@lorenzo-cavazzi Thanks for your review! I appreciate your suggestion regarding the tests. I've incorporated it into the PR #2773 , which also includes the deploy. This way, we can easily run the tests on the deployed Storybook.

2023-09-12 15:28 UTC, lorenzo-cavazzi requested changes
Great, thank you for adding the tests in the GitHub action!
Just a tiny change on the Readme file and this can be merged :rocket:

2023-09-12 15:28 UTC, lorenzo-cavazzi commented on README.md
> +    $ npm run start-storybook-and-test
We changed the command here

```suggestion
    $ npm run storybook-compile-and-test
```

2023-09-12 16:15 UTC, lorenzo-cavazzi approved these changes
:rocket:

2023-09-13 10:21 UTC, lorenzo-cavazzi approved these changes
Let's merge this :star_struck:

2023-09-13 10:52 UTC, merged