[wip] feat(client): add admin interface for resource pools
SwissDataScienceCenter/renku-ui pull request #2752
Opened 2023-08-21 14:00 UTC by leafty

/deploy #persist #notest

2023-10-23 10:16 UTC, ciyer requested changes
Overall, this look good. I know that we want to keep the scope of this limited, so I do not want to propose larges changes, but I have one thing in addition to the review comments.

Could the dialog boxes all be made modal (that is, only close when the `X` or the "close this dialog" button is clicked)? As is, it is too easy to lose work by accidentally clicking outside the dialog. I do not think we need to confirm close: making the close action a bit more deliberate this way would be sufficient.

2023-10-23 10:16 UTC, ciyer commented on client/src/features/admin/AdminPage.tsx
> +      <ul className={cx("mt-2", "mb-0", "vstack", "gap-2")}>
Could a table be used here instead?

I think this would be a small change that would greatly improve the appearance by making all the columns line up correctly.

<img width="498" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/1196411/59047817-f4ff-4639-a8dd-3879c0f38be3">

2023-10-23 11:36 UTC, leafty commented on tests/cypress/support/renkulab-fixtures/admin.ts
> +      realm = "Renku"
I would prefer doing this in another PR and fix it for all e2e tests.

2023-10-23 11:40 UTC, leafty commented on client/src/features/user/user.api.ts
Done in [81ede32](https://github.com/SwissDataScienceCenter/renku-ui/pull/2752/commits/81ede32f66bd2ccc79814d2d9f018a2600af5c89).

2023-10-23 11:40 UTC, leafty commented on client/src/features/user/user.api.ts
> +const userApi = createApi({
Done in [81ede32](https://github.com/SwissDataScienceCenter/renku-ui/pull/2752/commits/81ede32f66bd2ccc79814d2d9f018a2600af5c89).

2023-10-23 11:58 UTC, leafty commented
> Could the dialog boxes all be made modal (that is, only close when the `X` or the "close this dialog" button is clicked)? As is, it is too easy to lose work by accidentally clicking outside the dialog. I do not think we need to confirm close: making the close action a bit more deliberate this way would be sufficient.

Done in [7fcf20f](/SwissDataScienceCenter/renku-ui/pull/2752/commits/7fcf20fcb17b868decd966121919b1bc20903d19).

2023-10-23 13:24 UTC, leafty commented on client/src/features/admin/AdminPage.tsx
> +      <ul className={cx("mt-2", "mb-0", "vstack", "gap-2")}>
Done in [92316b5](https://github.com/SwissDataScienceCenter/renku-ui/pull/2752/commits/92316b5602f7e015d68ecd82459729c22f118a7b).

Note that tables are not responsive, so the bootstrap grid is being used instead.

2023-10-24 09:33 UTC, ciyer submitted a review, later dismissed
Very nice improvement. It will make configuration of resources **much** better than before. 🎉

2023-10-26 13:38 UTC, ciyer submitted a review, later dismissed
👍

2023-10-27 08:35 UTC, ciyer approved these changes
👍

2023-10-27 08:43 UTC, merged