Update the status text when the session is paused
SwissDataScienceCenter/renku-ui pull request #2771
Opened 2023-08-29 09:33 UTC by leafty

2023-08-29 10:02 UTC, lorenzo-cavazzi requested changes

2023-08-29 10:02 UTC, lorenzo-cavazzi commented on client/src/features/session/components/status/SessionStatusText.tsx
> +      Paused, will be deleted{" "}
We don't need to repeat the status here. From you screenshot, the "Paused" word is already written one line above this sentence. I would go for something shorter like
```suggestion
      Deleting in{" "}
```

2023-08-29 10:02 UTC, lorenzo-cavazzi commented on client/src/features/session/components/status/SessionHibernationStatusDetails.tsx
> +              <span className="fw-bold">Will be deleted:</span>{" "}
To keep it consistent with the other suggestion
```suggestion
              <span className="fw-bold">Deleting in </span>{" "}
```

2023-08-29 10:02 UTC, lorenzo-cavazzi commented on client/src/features/session/components/status/SessionHibernationStatusDetails.tsx
> +              <span className="fw-bold">Will be deleted:</span>{" "}
Oh wait, is the time absolute here?

2023-08-29 11:00 UTC, leafty commented on client/src/features/session/components/status/SessionStatusText.tsx
> +      Paused, will be deleted{" "}
"Paused" is not written in the first screenshot.

2023-08-29 11:08 UTC, lorenzo-cavazzi commented on client/src/features/session/components/status/SessionStatusText.tsx
> +      Paused, will be deleted{" "}
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/1477c0e9-c1ff-4b44-a558-b5646ff30f56)

2023-08-29 11:12 UTC, leafty commented on client/src/features/session/components/status/SessionStatusText.tsx
> +      Paused, will be deleted{" "}
This one: ![Screenshot 2023-08-29 at 11 22 15](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/2ce0335f-f421-48ee-adf5-43aac2ba9963)

2023-08-30 06:33 UTC, lorenzo-cavazzi commented on client/src/features/session/components/status/SessionStatusText.tsx
> +      Paused, will be deleted{" "}
Ok, on the sessions tab it makes sense to keep `Paused` at the beginning.
I still believe the message on the dashboard is unnecessarily long and can be abbreviated as suggested, but I'm ok with keeping it as is

2023-08-30 06:33 UTC, lorenzo-cavazzi approved these changes

2023-08-31 07:32 UTC, merged