WIP build(storybook): deploy storybook
SwissDataScienceCenter/renku-ui pull request #2773
Opened 2023-08-29 12:16 UTC by andre-code

PR deploy storybook

/deploy #persist #notest

2023-09-06 11:44 UTC, leafty commented on .github/workflows/acceptance-tests.yml
> +          node-version: '18.x'
To follow our other action and Dockerfiles:
```suggestion
          node-version: "18.17.1"
```

2023-09-06 11:46 UTC, leafty commented on .github/workflows/acceptance-tests.yml
> +        run: npm i
```suggestion
        run: npm install
```

2023-09-06 11:50 UTC, leafty commented on .github/workflows/acceptance-tests.yml
> +          TARGET_URL: 'https://renku-ci-ui-${{ github.event.number }}.dev.renku.ch/storybook/'
I would like to try this:

```suggestion
          TARGET_URL: ${{ needs.deploy-pr.environment.url }}
```

2023-09-06 13:56 UTC, lorenzo-cavazzi requested changes
I'm not sure we should rely on the PR deployment for testing Storybook since it's not strictly required (as in https://github.com/SwissDataScienceCenter/renku-ui/pull/2762) and PR deployments are rather unstable atm, so that would make this test shaky as well.

Can we remove the bits for running tests from this PR? If you need them to keep working on other issues, I suggest adding that part temporarily in a separate draft PR

2023-09-12 15:45 UTC, lorenzo-cavazzi requested changes
Very nice! Just a tiny change

2023-09-12 15:45 UTC, lorenzo-cavazzi commented on client/package.json
> +    "storybook-test": "test-storybook ",
```suggestion
    "storybook-test": "test-storybook",
```

2023-09-13 07:44 UTC, merged