fix(client): avatar url
SwissDataScienceCenter/renku-ui pull request #2791
Opened 2023-09-11 15:15 UTC by andre-code

PR to fix dataset avatar url

Fix #2765

2023-09-12 07:19 UTC, leafty commented on client/src/utils/helpers/DatasetFunctions.ts
[CODING_GUIDELINES.md](https://github.com/SwissDataScienceCenter/renku-ui/blob/master/CODING_GUIDELINES.md#r005-file-naming-conventions)

This file should probably be renamed to `dataset.utils.ts` or similar.

2023-09-12 08:03 UTC, leafty requested changes

2023-09-12 08:03 UTC, leafty commented on client/src/utils/helpers/Dataset.utils.ts
> +  if (mediaUrl !== null && mediaUrl.startsWith(".renku/dataset_images/"))
I find this logic non-intuitive here. Why do we not consider any relative path inside the repository? Non-relative locations would start with a URL scheme (`<scheme>://`). Also, we should probably validate external URLs and only allow those starting with `https://`.

2023-09-12 08:18 UTC, leafty commented on client/src/utils/helpers/Dataset.utils.ts
> +  if (mediaUrl !== null && mediaUrl.startsWith(".renku/dataset_images/"))
My suggestion is to use the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) class:

```ts
const mediaUrl = new URL("https://example.com/image.jpg", "https://gitlab.renkulab.io/namespace/name/-/raw/main/");
mediaUrl.toString() // 'https://example.com/image.jpg'
```

```ts
const mediaUrl = new URL("path/to/image.jpg", "https://gitlab.renkulab.io/namespace/name/-/raw/main/");
mediaUrl.toString() // 'https://gitlab.renkulab.io/namespace/name/-/raw/main/path/to/image.jpg'
```

```ts
const mediaUrl = new URL("s3://example/image.jpg", "https://gitlab.renkulab.io/namespace/name/-/raw/main/");
mediaUrl.toString() // 's3://example/image.jpg'
```

The URL constructor will handle relative vs absolute locations for you without needing to re-implement it.

2023-09-12 13:48 UTC, andre-code commented on client/src/utils/helpers/Dataset.utils.ts
> +  return dataset;
I understand the suggestion to avoid mutating arguments in functions. In this specific context, we intend to mutate the object when fetching datasets in order to add the mediaContent property. While we could refactor this code chain to return a new object, it's not within the scope of this PR. We may consider making such a change when transitioning to the use of Redux Toolkit

2023-09-13 06:44 UTC, leafty approved these changes

2023-09-14 06:32 UTC, merged