WIP feat: update project using kg api
SwissDataScienceCenter/renku-ui pull request #2793
Opened 2023-09-12 14:14 UTC by andre-code

PR to use kg api to update project properties

/deploy #persist #notest

2023-09-25 14:10 UTC, lorenzo-cavazzi reviewed
I started reviewing the PR but I keep getting a 409 error every time I try to update something. Could you check that?

In the meanwhile, I added a comment for a small refactoring that would simplify the RTK query logic by always using local tags on KG APIs (see inline comment)

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/308a3743-3363-4159-b848-3265b122ad85)

2023-09-29 12:02 UTC, andre-code commented on client/src/features/project/projectKgApi.ts
> +          });
Thanks @lorenzo-cavazzi thats a fair point, I moved the mutation to the projectKgApi

2023-10-03 07:15 UTC, lorenzo-cavazzi requested changes
This works very well now! :raised_hands: 

I added a couple of comments inline, just minor cleanups before merging

2023-10-03 07:15 UTC, lorenzo-cavazzi commented on client/src/features/project/components/ProjectWarningForMerge.tsx
> +      </p>
```suggestion
      <p>
        The operation was successful, but this project has protected branches.
      </p>
      <p>
        You need to manually create a merge request from{" "}
        <strong>{remoteBranch}</strong> to <strong>{defaultBranch}</strong> to
        see the new {changeDescription} in your project.
      </p>
```

2023-10-03 07:15 UTC, lorenzo-cavazzi commented on client/src/project/shared/ProjectTag.container.js
This is the last place where the `onProjectTagsChange` was used.
You can remove that from the `Project.js` file, and then `setTags`  from the coordinator.
Please double-check if we can remove something else, I guess also `setVisibility` is not necessary anymore

2023-10-03 07:15 UTC, lorenzo-cavazzi commented on client/src/components/errors/RtkErrorAlert.tsx
> +}
I wonder if we should handle errors specific to just a subset of APIs in smaller components. This function adopts a good approach, but it's used in the more generic `extractRkErrorMessage` component even if it only handles errors specifically from the new KG APIs.

We don't need to change it right now, but it is something to keep in mind.

2023-10-03 08:38 UTC, andre-code commented on client/src/project/shared/ProjectTag.container.js
We can definitely remove `onProjectTagsChange`, but not `setVisibility` as it is still needed when creating a new project... until the new service to create projects works.

2023-10-04 11:44 UTC, merged