Show project showcases on landing page
SwissDataScienceCenter/renku-ui pull request #2799
Opened 2023-09-14 13:49 UTC by ciyer

WIP

Fix #2747

2023-09-22 11:43 UTC, ciyer commented
# Testing

- See that the showcase section is rendered on the landing page
- Look at how it is configured and think about if that is fine or could be improved

2023-09-25 07:29 UTC, leafty commented on client/src/landing/SectionShowcase.tsx
> + */
Please update this header 🙂

2023-09-25 07:29 UTC, leafty commented on client/package.json
> +    "swiper": "^9.4.1",
😿 can we not start from an outdated version?

2023-09-25 07:29 UTC, leafty commented on client/src/landing/SectionShowcase.tsx
> +    : {};
I am a bit confused here. Why is this approach used instead of simple top image for card? https://getbootstrap.com/docs/5.3/components/card/#images-1

2023-09-25 07:29 UTC, leafty commented on client/src/landing/SectionShowcase.tsx
> +  if (overrideTitle) details.title = overrideTitle;
This is simpler to understand:

```suggestion
  const details: Partial<ShowcaseCardDisplayProps> = {
    description: overrideDescription ?? projectMetadata?.description,
    identifier,
    imageUrl: overrideImageUrl ?? images?.at(0)?.location,
    title: overrideTitle ?? projectMetadata?.name,
  };
```

2023-09-25 07:53 UTC, ciyer commented on client/package.json
> +    "swiper": "^9.4.1",
Unfortunately, no. There is a dependency hell situation that arises because swiper 10 requires typescript 5, which is incompatible with create-react-app, which is EOL. So to use swiper 10, we need to first change the build toolchain.

2023-09-25 10:47 UTC, ciyer commented on client/src/landing/SectionShowcase.tsx
> +    : {};
This code was taken from the search cards, where it is implemented this way. I have re-implemented this using the card top image. Personally, the img-based version is not clearly simpler or superior, but if you prefer it, it is also ok with me.

2023-09-26 08:34 UTC, leafty reviewed
Added configuration-related comments.

2023-09-26 08:34 UTC, leafty commented on client/run-telepresence.sh
> +SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
```suggestion
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
```

See: https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script

2023-09-26 08:34 UTC, leafty commented on helm-chart/renku-ui/values.yaml
> +      enabled: true
We probably should not ship this turned `on` by default.

2023-09-26 08:34 UTC, leafty commented on client/src/landing/AnonymousHome.tsx
> +      <SectionShowcase {...props.homeCustomized.showcase} />
Note: it could be useful to validate the params, e.g. https://github.com/SwissDataScienceCenter/renku-ui/blob/master/client/src/features/dashboard/message/dashboardMessage.utils.ts

2023-09-26 08:56 UTC, ciyer commented on helm-chart/renku-ui/values.yaml
> +      enabled: true
No, that's not the idea. This was set this way for testing the feature, but will be reset before merging the PR. See the commit message for this commit: https://github.com/SwissDataScienceCenter/renku-ui/pull/2799/commits/d779527b0fbc83a3c943464ff03b117f18b3b1a0

2023-09-26 09:01 UTC, leafty commented on helm-chart/renku-ui/values.yaml
> +      enabled: true
You can set `extra-values=ui.client.showcase.enabled=true` in your deploy string.

2023-09-28 06:50 UTC, leafty commented on client/.eslintrc.json
> +          "clsx",
I suspect this is a leftover?

2023-09-28 06:50 UTC, leafty commented on client/src/landing/SectionShowcase.tsx
> +            800: {
Would it make sense to use bootstrap breakpoints? https://getbootstrap.com/docs/5.3/layout/breakpoints/

2023-09-28 06:50 UTC, leafty commented on client/src/landing/sectionShowcase.module.scss
> +  height: 566px;
These dimensions seem like they would not align with a grid based on bootstrap (16px).

2023-09-28 06:50 UTC, leafty commented on client/src/landing/sectionShowcase.module.scss
> +  border-radius: 7px 7px 0 0;
Would it not work to use `className="rounded-top"`? The value of 7px seem like it would not work with bootstrap (8px, 16px, etc.).

2023-09-28 06:50 UTC, leafty commented on client/src/landing/SectionShowcase.tsx
I think it would be nice to check if this is adding a big chunk on the bundle, now that we can analyze this.

2023-09-28 12:03 UTC, ciyer commented on client/src/landing/sectionShowcase.module.scss
> +  border-radius: 7px 7px 0 0;
In an earlier version, it looked better this way, but some changes were made, and now it also looks fine using the `rounded-top` class, so I will switch to that.

2023-09-28 12:28 UTC, ciyer commented on client/src/landing/SectionShowcase.tsx
As previously implemented, it did increase the bundle size, but switch to LazyRenkuMarkdown brought down the bundle size again.

2023-09-28 13:04 UTC, ciyer commented on client/src/landing/sectionShowcase.module.scss
> +  height: 566px;
I believe the bootstrap grid is structured around multiples of 12. I have changed width to be 372 (12 * 31).

2023-10-02 12:13 UTC, leafty commented
Swiper takes a bit of space in the bundle, but this looks acceptable:

![127 0 0 1_8888_](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/21a06447-ea82-4400-b029-b1ffd7919d66)

2023-10-02 12:36 UTC, ciyer commented
> Mind that, after merging #2823, the values should go into the main Renku repository. I thought that would take more time -- sorry that this PR is taking longer than planned

Already done: see https://github.com/SwissDataScienceCenter/renku/pull/3269

2023-10-06 08:01 UTC, leafty requested changes
LGTM, just need to update the bash script (https://github.com/SwissDataScienceCenter/renku-ui/pull/2799/files#r1336798548)

2023-10-06 09:15 UTC, leafty approved these changes

2023-10-06 16:03 UTC, ciyer commented
Waiting for [ciyer/ui-2799-project-showcase-docs ](https://github.com/SwissDataScienceCenter/renku/pull/3269) to get approved to merge.

2023-10-17 08:22 UTC, merged