[wip] feat: use kg to update avatar (#2778)
SwissDataScienceCenter/renku-ui pull request #2806
Opened 2023-09-20 15:33 UTC by andre-code

PR to use kg api to update project avatar

/deploy #persist

2023-10-03 15:20 UTC, lorenzo-cavazzi submitted a review, later dismissed
Good to see this change!

I added a few inline comments, and I have a couple more points here:

- Error message: should we format it better? Showing a JSON string isn't the best solution. In this case, it should be "avatar is too big ...". Also, there should be some spacing before the error message instead of touching the button.
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/e97e0a6f-08fe-436d-a089-e8e133a1d3b5)

- File size: I thought we were downsizing the avatar. I tried to zoom it in so much that it should be very few pixels, but I still get the 200kb size error. Why is that? Also, the message "max 3 MB" is misleading in this case.

2023-10-03 15:20 UTC, lorenzo-cavazzi commented on client/src/features/project/components/ProjectSettings.tsx
> +      ) : (
I'm not sure if this is the best approach. If we do this, users without permission will not see the settings at all. I suggest disabling them instead as it already happens for Visibility and Description.
P.S. I realize I missed this when reviewing the other PR
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/13e9d0bf-6384-4213-b981-373c6c11a846)

2023-10-03 15:20 UTC, lorenzo-cavazzi commented on client/src/project/shared/ProjectAvatar.container.js
I might be missing something here. It seems to me that `ProjectAvatarEdit` is imported only in the index file, re-exported from there, but no other component is actually importing or using it. Is this correct?

2023-10-04 13:33 UTC, andre-code commented on client/src/features/project/components/ProjectSettings.tsx
> +      ) : (
yes, you are right. In order to maintain transparency and clarity in the user interface the combination of read-only inputs and a permission-related message would be the best approach.

that how looks now: 
![Screenshot 2023-10-04 at 15 23 59](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/3b0e7d70-dc48-44d6-b5de-342b5c150c98)

2023-10-04 13:33 UTC, andre-code commented on client/src/project/shared/ProjectAvatar.container.js
yes, I removed that code

2023-10-04 14:17 UTC, andre-code commented
Thank you for your review, @lorenzo-cavazzi. I have updated the input helper text to display a more accurate message regarding the limits of the image to upload compared to the image after cropping. It's possible that the calculation of the file size after crop and resize could be greater than the expected final size, and this message reflects that accurately.

I have also improved the parsing of error messages when there is an issue with changing the image. With these two changes, it now looks like this:

![Screenshot 2023-10-04 at 15 23 21](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/f93ab36a-1307-478e-a545-8d7020eb86be)

2023-10-05 09:43 UTC, ciyer requested changes
Overall, this looks very good! 🎉 I'm still doing some manual testing, but I have a couple of small suggestions about the code.

2023-10-05 09:43 UTC, ciyer commented on client/src/components/form-field/FormGeneratorImageInput.js
> +          {CARD_IMAGE_DIMENSIONS.height}px to achieve the desirable size{" "}
```suggestion
          {CARD_IMAGE_DIMENSIONS.height}px to achieve the target size{" "}
```

2023-10-05 09:43 UTC, ciyer commented on client/src/features/project/components/ProjectSettingAvatar.tsx
> +  };
I think useCallback should be used here...
```suggestion
  const setAvatarAndReset = useCallback((newAvatar: ImageValue) => {
    setAvatar(newAvatar);
    reset();
  }, [setAvatar, reset]);
```

2023-10-05 09:43 UTC, ciyer commented on client/src/features/project/components/ProjectSettingAvatar.tsx
> +  };
Could this function be lifted to outside the function? It does not use anything from the lexical context, and I think it would be cleaner/easier if it were declared at the module level.

2023-10-05 09:43 UTC, ciyer commented on client/src/features/project/components/ProjectSettingAvatar.tsx
> +  };
```suggestion
  const onCancel = useCallback(() => {
    setAvatar(
      getCurrentImageAvatar(
        projectMetadata.data?.images as unknown as ImagesLinks[]
      )
    );
    reset();
  }, [reset, setAvatar]);
```

2023-10-05 09:43 UTC, ciyer commented on client/src/features/project/components/ProjectSettingAvatar.tsx
> +          {errorAlert}
I think adding some spacing to the margin would be good here. The alert is a little to close to the buttons here.

<img width="724" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/1196411/05a385ad-a7b3-4c7c-bed4-467f42abbec0">

2023-10-10 11:32 UTC, leafty approved these changes

2023-10-10 11:32 UTC, leafty commented on client/src/features/project/components/ProjectSettingAvatar.tsx
> +  );
```suggestion
  const [succeeded, setSucceeded] = useState<boolean | undefined>(
    undefined
  );
```

2023-10-11 07:44 UTC, leafty approved these changes

2023-10-11 11:31 UTC, merged