chore: update the readme file
SwissDataScienceCenter/renku-ui pull request #2808
Opened 2023-09-21 15:32 UTC by lorenzo-cavazzi

This PR restructures the Readme file to provide more consistent information to the developers.

* The initial `Development` section explains how to start developing code for the whole UI.
* The `UI client` and `UI server` have been restructured and expanded (especially the Client section). Grouping should be more intuitive going through the "tool stack", then the "code structure", then "testing" and finally mentioning other utilities useful for the development.

fix #2775

2023-09-22 07:15 UTC, leafty commented on README.md
> +be refactored in the future.
Typo?

```suggestion
document and you might find older code using deprecated technologies. That will
be refactored in the future.
```

2023-09-22 07:15 UTC, leafty commented on README.md
> +- Use the `useSelector` hook to access information from slices in components.
```suggestion
- Use slice-specific selector hooks (e.g. [useWorkflowsSelector](https://github.com/SwissDataScienceCenter/renku-ui/blob/master/client/src/features/workflows/WorkflowsSlice.ts)), or the `useSelector` hook to access global state.
```

2023-09-22 07:15 UTC, leafty commented on README.md
> +- `features`: create/use sub-folders to contain files identifying single features. These sometimes correspond to Renku abstractions, like "Projects", "Datasets", "Sessions", or to cross-entity featur
> All RTK queries should be triggered by components in this folder.

What does this mean? This sounds like a over restrictive rule.

2023-09-22 07:48 UTC, ciyer requested changes
Nice improvement to the documentation! I have made some suggestions for clarification.

2023-09-22 07:48 UTC, ciyer commented on README.md
> +#### **Use CSS modules**
I think this should emphasize that the css modules are for styles that are local to a component.

```suggestion
#### **Use CSS modules for local styles**
```

2023-09-22 07:48 UTC, ciyer commented on README.md
> +We use [jest](https://jestjs.io) for unit testing.
```suggestion
We use [jest](https://jestjs.io) for **unit testing**.
```

2023-09-22 07:48 UTC, ciyer commented on README.md
> +the most important functions used by components.
```suggestion
the most important functions used by components. Note, we do not test components using jest/jsdom. Tests that require a browser/DOM environment are implemented either in Storybook or Cypress (see below).
```

2023-09-22 07:48 UTC, ciyer commented on README.md
> +You can run component tests using the following command:
```suggestion
You can run component tests using the following command in the client subfolder:
```

2023-09-22 07:48 UTC, ciyer commented on README.md
> +    $ npm run e2e:local
`:local` is not necessary
```suggestion
    $ npm run e2e
```

2023-09-22 07:48 UTC, ciyer commented on README.md
> +in your development RenkuLab instance.
```suggestion
in your development RenkuLab instance.

**Configuration**
The script allows configuration of certain aspects of the deployment through environment variables. Take a look at the script to see all the options that are available.

The script generates a `config.json` file into the `client/public` folder, and you can modify this file with a text editor and reload the browser to test out different configuration settings.
```

2023-09-22 07:48 UTC, ciyer commented on README.md
> +only Redis and we don't plan to use the UI server to store non-volatile data.
```suggestion
only Redis, and we do not currently use the UI server to store non-volatile data.
```

2023-09-25 06:44 UTC, lorenzo-cavazzi commented on README.md
> +- `features`: create/use sub-folders to contain files identifying single features. These sometimes correspond to Renku abstractions, like "Projects", "Datasets", "Sessions", or to cross-entity featur
That sounds indeed a bit misleading. I changed the text to emphasize that code interacting with the Redux store should go here in `*Api.ts` and `*Slice.ts` files.
See https://github.com/SwissDataScienceCenter/renku-ui/pull/2808/commits/ec811b333cc1d4969711d9452b37a81012340638

2023-09-25 06:50 UTC, lorenzo-cavazzi commented on README.md
> +in your development RenkuLab instance.
Great addition, thanks!

2023-09-25 07:06 UTC, leafty commented on README.md
> +- Use slice-specific selector hooks (E.G.
```suggestion
- Use slice-specific selector hooks (e.g.
```

see https://en.wiktionary.org/wiki/e.g.

2023-09-25 07:07 UTC, leafty commented on README.md
> +  files for slices.
Per the coding guidelines, these should end in `.api.ts` and `.slice.ts`

```suggestion
  Wherever relevant, please add `*.api.ts` files containg the RTK queries and `*.slice.ts`
  files for slices.
```

2023-09-25 08:08 UTC, lorenzo-cavazzi commented on README.md
> +- Use slice-specific selector hooks (E.G.
Changed the other occurrences too for consistency

2023-09-25 08:48 UTC, ciyer approved these changes
👍

2023-09-25 09:00 UTC, leafty approved these changes

2023-09-25 09:21 UTC, merged