Improve logic in inactive-kg-projects page
SwissDataScienceCenter/renku-ui pull request #2833
Opened 2023-10-04 09:32 UTC by ciyer

WIP

Fix #2774

2023-10-09 08:11 UTC, leafty requested changes
To me, it seems that the activate button should be disabled when nothing is selected:

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/ee073e09-c55e-43f2-bf3f-b4dd9b1cde2c)

Also, the status column should probably say "Not indexed" to keep our wording consistent.

Right after clicking the button the status bars are set to 100%

(Screenshot taken too late, but second bar is full)
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/6dbbb532-d76b-4e58-b7ee-fc3a0824bb50)

Also, the animated looks feels off for Renku, but this topic may be another discussion.

Lastly, the "activating..." status seems to not propagate to other browser tabs which is most likely something which can cause consistency issues.

2023-10-09 08:19 UTC, leafty commented
Another note: I have a project which fails being activated in this PR deployment and the lack of error messages from KG makes for a terrible UX :crying_cat_face: .

2023-10-09 11:15 UTC, ciyer commented on client/src/features/inactiveKgProjects/components/KgActivationHeader.tsx
> +        Projects requiring indexing
This is true, but I think we need a bit more work to support that, like somehow designating a project as being a regular git and non-renku project. Otherwise, you will always get a warning that the project is not indexed.

2023-10-09 11:45 UTC, ciyer commented on server/src/index.ts
> +});
Termnius is necessary to cleanly handle interruption signals. Without it, the server just hangs after `CTRL-C` and does not exit cleanly. This isn't an issue in production, but it makes the dev experience a bit nicer.

2023-10-09 12:06 UTC, leafty commented on server/src/index.ts
> +});
I fixed that recently, are you sure you still experience issues in dev mode?

2023-10-13 11:41 UTC, ciyer commented on server/src/index.ts
> +});
Yes, I was having problems terminating the server when I worked on this feature (and the code was up-to-date).

2023-10-13 13:17 UTC, leafty commented on server/src/index.ts
> +});
I can reproduce the problem; the server is not closing down websocket clients and so is hanging on forever.

Here is a fix (not super nice but works):
```ts
# From line 98
// start the WebSocket server
let wsServer: ws.Server | null = null;
if (config.websocket.enabled) {
  const path = `${config.server.prefix}${config.server.wsSuffix}`;
  wsServer = new ws.Server({ server, path });
  addWebSocketServerContext(wsServer);
  authPromise.then(() => {
    logger.info("Configuring WebSocket server");
    configureWebsocket(wsServer, authenticator, storage, apiClient);
  });
}

function shutdown() {
  if (wsServer != null) {
    logger.info("Shutting down wsServer");
    wsServer.clients.forEach((ws) => {
      ws.close();
    });
    wsServer.close((error) => {
      if (error) {
        logger.error(error);
        process.exit(1);
      } else {
        logger.info("Shutting down server");
        server.close((error) => {
          if (error) {
            logger.error(error);
            process.exit(1);
          } else {
            logger.info("Shutting down storage");
            storage.shutdown();
            logger.info("Shutdown completed.");
            setImmediate(() => {
              process.exit(0);
            });
          }
        });
      }
    });
  } else {
    logger.info("Shutting down server");
    server.close((error) => {
      if (error) {
        logger.error(error);
        process.exit(1);
      } else {
        logger.info("Shutting down storage");
        storage.shutdown();
        logger.info("Shutdown completed.");
        setImmediate(() => {
          process.exit(0);
        });
      }
    });
  }

  process.on("unhandledRejection", (error) => {
    logger.error(error);
    process.exit(1);
  });
}
```

2023-10-17 08:07 UTC, ciyer commented
# Changes

1. Show "Starting..." and not a 100% indexed display while waiting for indexing to start

<img width="1365" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/1196411/ea0a9089-3111-40f3-99d6-dbcefdc17634">

2. Show progress correctly (this had been broken due to changes in the response from the KG)

<img width="1365" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/1196411/7b2a27ae-8275-4d16-9fe1-bbce7fe6ab64">

3. If the KG does not report progress for some time (20s), then a message is shown

<img width="1365" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/1196411/9e72508e-5ad0-4b31-a7bb-ad7b5788b2fe">

4. Disable "Activate indexing" if not projects are selected

<img width="1365" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/1196411/5c7707a5-4478-4eff-b62f-008a92c89126">

2023-10-17 09:25 UTC, andre-code reviewed
👏The code looks much cleaner, and the user experience has also been improved! 

There is one pending issue that needs to be addressed. It occurs when the last WebSocket message indicates that an activation is in progress (progress > 0), but it is actually fully activated. Unfortunately, the UI never receives the 100% progress message, resulting in the UI displaying the activation as ongoing indefinitely.

My suggestion is to implement a check on the server side. After a certain number of seconds without an update, we can verify if the message has not been received from KG as expected. If not, we should investigate why the UI isn't receiving the confirmation, and if the corresponding ID is removed from the list of IDs to monitor on the server. Additionally, on the UI side, we could provide an option for users to manually retrieve the status if it takes too long.
![project indexed](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/4e6a5e72-d60d-49f0-bc2b-66686f251b1e)

![activation list](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/3a655a79-c570-4c7c-8529-a86db552a711)

2023-11-22 11:44 UTC, leafty approved these changes

2023-11-22 11:44 UTC, leafty commented on client/src/websocket/handlers/kgActivationStatusHandler.ts
> +  if (now - lastUpdateAt > SLOW_ACTIVATION_CUTOFF_MS) {
nitpick: I usually prefer writing timestamp logic with `luxon` as it tends to reduce bugs.

2023-11-22 11:44 UTC, leafty commented on server/src/websocket/handlers/activationKgStatus.ts
> +  return diffSecs >= MAX_NO_UPDATE_INTERVAL_SEC;
same comment here about using `luxon`.

2023-11-23 09:58 UTC, ciyer commented on client/src/websocket/handlers/kgActivationStatusHandler.ts
> +  if (now - lastUpdateAt > SLOW_ACTIVATION_CUTOFF_MS) {
This is a good suggestion. I had been using the [d3Time](https://github.com/d3/d3-time) for more complex time calculations, but I will switch to using Luxon in the future, even for simple manipulations.

2023-11-24 10:01 UTC, merged