[wip] feat: update style in outline-btn
SwissDataScienceCenter/renku-ui pull request #2857
Opened 2023-10-19 14:43 UTC by andre-code

PR to add styles for  outline-btn that works well in different background color

/deploy #persist

2023-10-24 07:49 UTC, leafty commented on client/public/frame.svg
Note: I think making the icon into a component may be required to have it use `currentColor`.

2023-10-24 14:10 UTC, leafty commented on client/src/project/Project.present.js
> +      id="fork-project2"
This breaks the dashboard page!

2023-10-25 07:24 UTC, leafty requested changes

2023-10-25 07:24 UTC, leafty commented on client/src/features/dashboard/components/DatasetsDashboard.tsx
> +        <SearchEntityIcon className="me-2" size={20} />
I notice that on https://dev.renku.ch the size of this icon is `24`. Maybe we should keep that?

2023-10-25 07:24 UTC, leafty commented on client/src/features/dashboard/components/ProjectsDashboard.tsx
>          <div className="d-flex gap-2 text-rk-green">
You should remove this `<div>` here, it messes up the alignment. The other buttons look good, while this one looks very off.

2023-10-25 07:24 UTC, leafty commented on client/src/styles/bootstrap_ext/_button.scss
> +  --#{$prefix}-btn-active-color: white;
Rule not working:

```suggestion
  --#{$prefix}btn-active-color: white;
```

2023-10-25 07:24 UTC, leafty commented on client/src/styles/bootstrap_ext/_button.scss
> +      color: white;
I think that you could also use the bootstrap variables here:

```scss
.input-group {
   --#{$prefix}btn-hover-color: white;
   --#{$prefix}btn-hover-bg: #{$rk-pink-highlight};
   --#{$prefix}btn-hover-border-color: #{$rk-pink-highlight};
}
```

Also, we need different colors for each state (hover, active, focus) as is the case in default bootstrap.

2023-10-25 07:24 UTC, leafty commented on client/src/styles/bootstrap_ext/_button.scss
> +      color: white;
Same comment about using variables here.

2023-10-25 07:24 UTC, leafty commented on client/src/styles/bootstrap_ext/_button.scss
> +  --#{$prefix}-btn-active-color: white;
```suggestion
  --#{$prefix}btn-active-color: white;
```

Also, I'm not sure the rule is needed.

2023-10-25 07:24 UTC, leafty commented on client/src/styles/bootstrap_ext/_button.scss
> +  --#{$prefix}-btn-active-color: white;
```suggestion
  --#{$prefix}btn-active-color: white;
```

2023-10-25 07:24 UTC, leafty commented on client/src/components/icons/ExploreIcon.tsx
> +        />
This is causing some weirdness when hovering.

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/b7e311d5-325e-4dc1-af06-c9320643d58c)

2023-10-25 07:24 UTC, leafty commented on client/src/components/icons/ExploreIcon.tsx
We should check if we can re-export these files to SVG as they use complex curves which can render badly.

2023-10-25 07:24 UTC, leafty commented on client/src/components/icons/SearchEntityIcon.tsx
Same here, it would probably be good to re-export this icon and make it much lighter.

2023-10-25 07:31 UTC, leafty commented on client/src/components/icons/SearchEntityIcon.tsx
> +      width={`${size}px`}
height?

```suggestion
      height={`${size}px`}
      width={`${size}px`}
```

2023-10-31 14:06 UTC, andre-code commented on client/src/components/icons/SearchEntityIcon.tsx
> +      width={`${size}px`}
The height adjusts itself based on the width setted, especially when the icon isn't a perfect square

2023-10-31 14:07 UTC, andre-code commented on client/src/features/dashboard/components/DatasetsDashboard.tsx
> +        <SearchEntityIcon className="me-2" size={20} />
we review it with @jdupre81  and that size is not needed

2023-10-31 14:09 UTC, andre-code commented on client/src/components/icons/ExploreIcon.tsx
> +        />
@jdupre81 suggested to change the icon, already included the new icon in the last commit

2023-11-01 09:05 UTC, leafty requested changes
Good, only a small set of changes left :+1:

2023-11-01 09:05 UTC, leafty commented on client/src/components/entities/Buttons.tsx
> +            className="btn-outline-rk-green text-decoration-none" //link-rk-dark
leftover?

```suggestion
            className="btn-outline-rk-green text-decoration-none"
```

2023-11-01 09:05 UTC, leafty commented on client/src/features/dashboard/components/DatasetsDashboard.tsx
>          className="btn btn-outline-rk-pink"
For centered alignment:
```suggestion
        className={cx("btn", "btn-outline-rk-pink", "d-flex", "align-items-center")}
```

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/7aec88bd-9440-490b-b1ea-1350f041424a)
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/29b2db2f-fee1-4dd2-b6ca-4470a51990ca)

2023-11-01 09:05 UTC, leafty commented on client/src/styles/bootstrap_ext/_button.scss
> +  --#{$prefix}btn-active-border-color: #{$rk-green-highlight};
non-blocking: it would be good to have different colors here.

2023-11-01 09:05 UTC, leafty commented on client/src/components/icons/SearchEntityIcon.tsx
> +      width={`${size}px`}
Height should still be provided because the icon doesn't fit inside a 20x20 square:
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/a35456ec-e1f1-4ee7-afdc-f1e30f24980f)

2023-11-01 14:15 UTC, leafty approved these changes

2023-11-02 13:28 UTC, merged