tests: add tests for slow and error responses from user and statuspage
SwissDataScienceCenter/renku-ui pull request #2858
Opened 2023-10-20 13:01 UTC by ciyer

Work on #2283

2023-10-20 13:04 UTC, ciyer commented
I added the tests suggested in [#2283](https://github.com/SwissDataScienceCenter/renku-ui/issues/2283), but I still do not see the behavior described in that issue. Though I believe all those that have reported it, from looking at the code, it isn't clear how this situation could happen in the way described

I think a more likely scenario that could cause this would be an error response from the `user` endpoint, followed by a UI refresh, followed by a valid response from `user`.

2023-10-24 09:54 UTC, lorenzo-cavazzi reviewed
I suggest having a single place where we verify the maintenance messages work as expected.
Perhaps we should move the maintenance-related tests (that includes the `"display the maintenance page"` section, to be updated or merged with the new tests) to the maintenace.spec.ts file and let the home specs check only home page-specific components.

2023-10-24 09:54 UTC, lorenzo-cavazzi commented on tests/cypress/e2e/home.spec.ts
> +      .userNone("getUser", 5000);
This can probably be much lower than 5000, I'd say 1000

2023-10-25 09:30 UTC, ciyer commented
> I suggest having a single place where we verify the maintenance messages work as expected. Perhaps we should move the maintenance-related tests (that includes the `"display the maintenance page"` section, to be updated or merged with the new tests) to the maintenace.spec.ts file and let the home specs check only home page-specific components.

I moved the `display maintenance page` test to the `mainenance.spec.ts` file, but I kept the new test in the home page, since it tests that the home page, and not the mainenance page, is shown. I reduced the delay to 1s, as suggested.

2023-10-26 09:22 UTC, lorenzo-cavazzi requested changes
Lgtm!

Before merging, let's remove the comment about the #2283 issue since it's closed by this PR.

2023-10-26 09:22 UTC, lorenzo-cavazzi commented on tests/cypress/e2e/maintenance.spec.ts
> +    // ! we plan to change this behavior and ignore statuspage info when unavailable #2283
```suggestion
```
We can remove this line

2023-10-27 09:49 UTC, lorenzo-cavazzi commented
The test `display the home page even when APIs return strange responses` seems to fail consistently -- I tried it locally as well

2023-10-27 14:41 UTC, ciyer commented
> The test `display the home page even when APIs return strange responses` seems to fail consistently -- I tried it locally as well

I see that now -- it was a problem introduced as a side effect of merging changes from master. Everything should work now.

2023-10-30 08:56 UTC, lorenzo-cavazzi approved these changes
Lgtm!

2023-10-30 08:58 UTC, merged