refactor(client): make all fixtures use default options
SwissDataScienceCenter/renku-ui pull request #2864
Opened 2023-10-25 15:32 UTC by leafty

Details:

* Fixtures now have sensible defaults and callers can provide only the options they need.

2023-10-27 09:03 UTC, ciyer requested changes
This is a good change to unify the structure of the fixtures. 🎉 I have a few requests for field name changes to clarify the semantics of the field, and a suggestion for a refactoring.

2023-10-27 09:12 UTC, ciyer requested changes
Also, the `dashboard.spec.ts` fails, even locally, so I suspect an error was introduced into that test that needs to be fixed.

2023-10-27 12:52 UTC, leafty commented on tests/cypress/support/renkulab-fixtures/projects.ts
> +          path: "",
Done in [e1b88f9](https://github.com/SwissDataScienceCenter/renku-ui/pull/2864/commits/e1b88f991d0c315bcf8c3d77173fd1bc4b6bc4ad).

2023-10-27 12:52 UTC, leafty commented on tests/cypress/support/renkulab-fixtures/projects.ts
> +        path = "",
Done in [e1b88f9](https://github.com/SwissDataScienceCenter/renku-ui/pull/2864/commits/e1b88f991d0c315bcf8c3d77173fd1bc4b6bc4ad).

2023-10-27 12:52 UTC, leafty commented on tests/cypress/support/renkulab-fixtures/datasets.ts
> +        path = "",
Done in [e1b88f9](https://github.com/SwissDataScienceCenter/renku-ui/pull/2864/commits/e1b88f991d0c315bcf8c3d77173fd1bc4b6bc4ad).

2023-10-30 09:57 UTC, ciyer requested changes
One of the changes requested in an earlier review was. missed, but this otherwise looks good and is very close to approval.

2023-10-30 09:57 UTC, ciyer commented on tests/cypress/support/renkulab-fixtures/datasets.ts
> +        path = "",
It looks like this one was missed. That commit only changes `tests/cypress/support/renkulab-fixtures/projects.ts`, not this file.

2023-10-30 09:57 UTC, ciyer commented on tests/cypress/support/renkulab-fixtures/global.ts
> +        "https://*.statuspage.io/api/v2/summary.jsonr",
This is a mistake introduced by my PR, but I will fix it in #2871

2023-11-02 08:23 UTC, ciyer approved these changes
LGTM!

2023-11-02 08:24 UTC, merged