tests: fix some flakiness with e2e tests
SwissDataScienceCenter/renku-ui pull request #2872
Opened 2023-10-31 07:16 UTC by leafty

2023-10-31 09:08 UTC, ciyer approved these changes
This fixes the problems that I was seeing locally!

2023-11-01 11:03 UTC, lorenzo-cavazzi requested changes
I dislike adding a re-try strategy for local tests, but it seems effective and gives us time to improve the UI wherever needed.

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/fbea875c-bfdf-47b1-a721-80bb1965b579)

2023-11-01 11:03 UTC, lorenzo-cavazzi commented on client/src/project/Project.present.js
> +// }
```suggestion
```
Should we remove this before merging?

2023-11-01 11:43 UTC, leafty commented on client/src/project/Project.present.js
> +// }
Done in [fc2b93c](https://github.com/SwissDataScienceCenter/renku-ui/pull/2872/commits/fc2b93c4611d14f78b7f2e2a1163b05b4f447cfd).

2023-11-01 12:00 UTC, lorenzo-cavazzi approved these changes
Thank you for the joint effort on this :pray:

2023-11-01 12:22 UTC, merged