chore(client): change icons in the navbar to use Bootstrap icons
SwissDataScienceCenter/renku-ui pull request #2882
Opened 2023-11-07 14:17 UTC by leafty

See #2763.

2023-11-08 16:52 UTC, lorenzo-cavazzi requested changes
Very nice!

I added a comment on using the `Url` consistently instead of a hardcoded string for links.
Apart from that, I must say the icons look smaller compared to the previous solution. I feel adding `font-size: large` compensates well enough. What do you think?
I would also go with the `PlusLg` bootstrap icon for now, and then ask the designer for a new icon if people don't like it.

2023-11-08 16:52 UTC, lorenzo-cavazzi commented on client/src/components/navbar/AnonymousNavBar.tsx
> +                  to="/search"
Save as above (`Url.pages.search`)

2023-11-08 16:52 UTC, lorenzo-cavazzi commented on client/src/components/navbar/AnonymousNavBar.tsx
> +                  to="/sessions"
Should we use the `Url` utility instead of passing a hardcoded value?

```suggestion
                  to={Url.get(Url.pages.sessions)}
```

2023-11-08 16:52 UTC, lorenzo-cavazzi commented on client/src/components/navbar/AnonymousNavBar.tsx
> +          <Link id="link-home" to="/" className="navbar-brand me-2 pb-0 pt-0">
Same as above (`Url.pages.landing`)

2023-11-08 16:52 UTC, lorenzo-cavazzi commented on client/src/components/navbar/LoggedInNavBar.tsx
Same thing for the Urls

2023-11-08 16:52 UTC, lorenzo-cavazzi commented on client/src/components/navbar/NavBarItems.tsx
Same thing for the Urls

2023-11-09 11:09 UTC, leafty commented on client/src/components/navbar/AnonymousNavBar.tsx
> +                  to="/sessions"
will do; I initially updated only the props of the navbar components.

2023-11-09 11:12 UTC, leafty commented
> Apart from that, I must say the icons look smaller compared to the previous solution. I feel adding `font-size: large` compensates well enough. What do you think?

The bootstrap icons are actually the same size (max 16x16), but they have a significant smaller visual presence due to the very fine stroke they use. I think we can consider making them larger (e.g. 20 or 24px), but to keep the size of the navbar, I will have to tweak the margins used around the icons.

2023-11-10 10:07 UTC, lorenzo-cavazzi commented
I see. I'm inclined towards using larger icons (20px looks much better already) if that's quick enough and doesn't require too many other modifications.
We could also go through the designer and see what's the desired output considering the different style of Bootstrap's icons.

2023-11-14 12:45 UTC, leafty commented
> I see. I'm inclined towards using larger icons (20px looks much better already) if that's quick enough and doesn't require too many other modifications. We could also go through the designer and see what's the desired output considering the different style of Bootstrap's icons.

The icons are now using size 20px:
![renku-ci-ui-2882 dev renku ch_ (2)](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/60e04549-0f83-411a-9ae1-8881dfc255f1)

2023-11-14 14:31 UTC, leafty commented on client/src/components/navbar/AnonymousNavBar.tsx
> +                  to="/search"
Done in 593084e8f11e30b52aa1e460ccd8d172f91d3161.

2023-11-14 14:31 UTC, leafty commented on client/src/components/navbar/AnonymousNavBar.tsx
> +                  to="/sessions"
Done in 593084e8f11e30b52aa1e460ccd8d172f91d3161.

2023-11-14 14:32 UTC, leafty commented on client/src/components/navbar/AnonymousNavBar.tsx
> +          <Link id="link-home" to="/" className="navbar-brand me-2 pb-0 pt-0">
Done in 593084e8f11e30b52aa1e460ccd8d172f91d3161.

2023-11-14 14:32 UTC, leafty commented on client/src/components/navbar/LoggedInNavBar.tsx
Done in 593084e8f11e30b52aa1e460ccd8d172f91d3161.

2023-11-14 14:32 UTC, leafty commented on client/src/components/navbar/NavBarItems.tsx
Done in 593084e8f11e30b52aa1e460ccd8d172f91d3161.

2023-11-14 16:36 UTC, lorenzo-cavazzi submitted a review, later dismissed
Very nice! :star_struck: 

The "plus" icon is a bit thin, but I guess we can live with that for now and swap it later with a custom-made thicker version.

2023-11-15 15:41 UTC, leafty commented
Updated navbar for small viewports:

![renku-ci-ui-2882 dev renku ch_ (5)](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/ca4edb70-84d2-4a24-964c-ceb50c1b23ae)
![dev renku ch_ (3)](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/c56a867d-1e9f-478f-b604-2f49abf2e04f)

![renku-ci-ui-2882 dev renku ch_ (4)](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/3bbf2fef-08cc-4ea3-aab6-89852eb5cccf)
![dev renku ch_ (4)](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/f53c1878-1efc-43e5-92da-5413d83d30b3)

2023-11-15 15:59 UTC, lorenzo-cavazzi submitted a review, later dismissed
Fantastic! 🚀

2023-11-17 07:41 UTC, leafty commented
Design updated to use PlusCircleFill:
![renku-ci-ui-2882 dev renku ch_](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/328b1393-f7a3-4073-8610-f747e070bdaa)

2023-11-17 08:34 UTC, lorenzo-cavazzi approved these changes

2023-11-17 09:00 UTC, merged