Fix a few visual glitches
SwissDataScienceCenter/renku-ui pull request #2883
Opened 2023-11-07 14:41 UTC by lorenzo-cavazzi

There are quite a few visual glitches that piled up with time, most of them coming from updates to bootstrap defaults.

This PR addresses some of them. Here is a list to simplify the review:

* Remove badges customization
    ![01_badge](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/35ea782c-9833-499c-8e2c-34d13cf7836f)
* Update the list items defaults -- a few pages were slightly adjusted, like the commits tab:
    ![02_commits](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/32000f37-4152-4fc1-ae40-04f4d7fa5b44)
* Set transparent background on popovers:
    ![03_popovers](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/d69a01f8-58e4-4e30-846c-c84b6bc13e62)
* Set transparent background on tables:
    ![04_transparent_background](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/34e3fabf-ed26-4fbc-9cca-197bcb7f7869)
* Adjust other custom elements:
    ![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/af1cdb3a-84f7-4d71-9cb1-d3caf2e19d34)

/deploy

2023-11-07 15:35 UTC, leafty requested changes

2023-11-07 15:35 UTC, leafty commented on client/src/App.css
Good seeing a lot of global rules being removed! 👍

2023-11-07 15:35 UTC, leafty commented on client/src/components/commits/Commits.js
> +                </Clipboard>
It doesn't make sense to have a `<Clipboard>` inside a `<Button>`.
Maybe try to use `<span>` instead of `<Button>`, and add `btn` to the `<Clipboard>` classname.

```tsx
<span id={idCopyButton}>
  <Clipboard classname={cx("btn", "border")} clipboardText={props.commit.id}>
```

2023-11-07 15:35 UTC, leafty commented on client/src/components/commits/Commits.js
> +              <Button className="d-none"></Button>
Why is there a hidden button?

2023-11-07 15:35 UTC, leafty commented on client/src/dataset/Dataset.present.js
>          {dataset.published?.creator?.length >= 3 ? (
non-blocking: the logic here is weird and creates an empty card above the description.

2023-11-07 15:35 UTC, leafty commented on client/src/styles/bootstrap/_custom_bootstrap_variables.scss
> +$input-bg: #ffffff;
maybe use:
```suggestion
$input-bg: $rk-white;
```

2023-11-07 15:35 UTC, leafty commented on client/src/styles/bootstrap_ext/_badge.scss
> -  }
For contrast, this rule should stay.

2023-11-07 15:35 UTC, leafty commented on client/src/components/commits/Commits.css
Can you check the borders? They do not seem consistent:

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/30a0f4fd-1e7f-4fbf-8f0f-e32d02af652f)

The date headers should probably have borders too.

2023-11-07 16:09 UTC, lorenzo-cavazzi commented on client/src/components/commits/Commits.js
> +                </Clipboard>
I kept the buttons to avoid spending time updating the styling.
I agree this solution isn't optimal, but this tab might disappear soon so I wouldn't spend more time on it

2023-11-07 16:10 UTC, lorenzo-cavazzi commented on client/src/components/commits/Commits.js
> +              <Button className="d-none"></Button>
To use the buttons group styling. Same reason as above: the tab might disappear soon so let's just fix the visual appearance

2023-11-07 16:18 UTC, lorenzo-cavazzi commented on client/src/dataset/Dataset.present.js
>          {dataset.published?.creator?.length >= 3 ? (
I don't get empty cards, could you share an example? Or perhaps I'm missing it :thinking: 

Still, the logic is indeed weird :smile: If it's about improving what we show on the dataset page, let's keep it separate from the CSS/classes changes in this PR

2023-11-07 16:23 UTC, lorenzo-cavazzi commented
Thanks for the review! I added the style/visual changes, but I didn't update the components used for the commits since that tab is likely to disappear soon (or be re-written anyway). I agree the current solution is... non-optimal :grimacing:

2023-11-08 15:21 UTC, lorenzo-cavazzi commented on client/src/dataset/Dataset.present.js
>          {dataset.published?.creator?.length >= 3 ? (
Oh, interesting! I got contradicting outputs and, after digging a bit into this, I found out that KG occasionally return responses for non-indexed projects (i.e. when the same database has been used in another project that happens to be indexed) :exploding_head: 

Anyway, I managed to reproduce the issue
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/8c1d8a25-3c9f-4532-a393-7bd179747457)

I couldn't understand how authors/source work, but I changed it slightly. Actually, that was probably a bad decision and I should have made a separate PR (or issue) to prevent "patchwork PRs" changing random stuffs together but... it was just quicker and I couldn't resist the temptation :shrug: 
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/b8778461-00fe-4f79-a628-f425d2b622f8)

2023-11-08 15:25 UTC, lorenzo-cavazzi commented on client/src/components/commits/Commits.js
> +                </Clipboard>
Vertical alignment seems a bit off with that solution. For comparison, on the left side is the code from the PR, while on the right it's your suggestion. Mind the vertical alignment
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/2f481d5a-1b65-47b2-a00f-52cf6ae40f75).

I removed the unnecessary hidden button (see https://github.com/SwissDataScienceCenter/renku-ui/pull/2883/commits/5c9b3af87d55bbab7c7a14679df13f24b63ca425 ) since that was admittedly bad, and replaced it by playing around with the `rounded-*` classes.
I suggest to keep the button with clipboard to avoid spending more time on this -- that was already the previous solution after all.

2023-11-08 16:56 UTC, leafty approved these changes
LGTM 🚀 thanks for the changes 🙏

2023-11-09 10:13 UTC, merged