feat(client): let users pin projects to the Dashboard
SwissDataScienceCenter/renku-ui pull request #2902
Opened 2023-11-16 14:39 UTC by leafty

2023-11-22 10:06 UTC, ciyer requested changes
This looks very good for the most part, and works quite well. 🎉 I have identified a few mostly minor things that could be improved.

2023-11-22 10:06 UTC, ciyer commented on client/src/components/list/PinnedBadge.tsx
> +  return (
The visual difference between an enabled badge and a disabled one is **very** subtle. I think there needs to be a greater visual distinction.

<img width="512" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/1196411/21d88b92-fda9-4b16-bef8-1eb6e0071371">

2023-11-22 11:18 UTC, leafty commented on client/src/components/list/PinnedBadge.tsx
> +  return (
I understand, but this is using existing button styles and I am not sure I want to create yet another button just for this.

2023-11-22 11:18 UTC, leafty commented on client/src/components/list/PinnedBadge.tsx
> +      return 0;
I do not see why this logic would be gone in `App.js`. I still need to ensure that the parameter is set to a valid value before using it. I would avoid adding untyped code in `App.js` in any case.

2023-11-22 11:18 UTC, leafty commented on client/src/components/list/PinnedBadge.tsx
> +    ? "Error: could not retrieve user preferences"
I am not sure where I would move the notification that something went wrong. Is there a better place for the errors to go to?

2023-11-22 11:18 UTC, leafty commented on client/src/components/list/PinnedBadge.tsx
> +      addErrorNotification(addPinnedProjectResult.error);
I am not sure where I would move the notification that something went wrong. Is there a better place for the errors to go to?

2023-11-22 11:19 UTC, leafty commented on client/src/components/list/PinnedBadge.tsx
> +    ? "Error: could not retrieve user preferences"
I am not sure it's a better UX to silently remove a button in case of an error.

2023-11-23 08:23 UTC, ciyer commented on client/src/components/list/PinnedBadge.tsx
> +    ? "Error: could not retrieve user preferences"
As discussed, just leave this as is.

2023-11-23 08:29 UTC, ciyer commented on client/src/components/list/PinnedBadge.tsx
> +      addErrorNotification(addPinnedProjectResult.error);
As discussed, handle the case that the pinned project limit is reached without a notification, other errors that are not "expected" can trigger a notification.

2023-11-23 09:54 UTC, ciyer commented
As discussed, none of these are blockers in my opinion. If you find quick solutions, then great, if not, feel free to defer to a later PR, or ignore.

2023-11-23 09:55 UTC, leafty commented on client/src/components/list/PinnedBadge.tsx
> +      return 0;
Will refactor `params` later.

2023-11-23 10:18 UTC, leafty commented on client/src/components/list/PinnedBadge.tsx
> +  return (
Done in [d90a17b](https://github.com/SwissDataScienceCenter/renku-ui/pull/2902/commits/d90a17badfd866af0d8d227644291c71ed8e6da8).

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/14b4225f-ec17-4d51-a610-e5d4cdb665f8)

2023-11-23 10:18 UTC, leafty commented on client/src/components/list/PinnedBadge.tsx
> +      addErrorNotification(addPinnedProjectResult.error);
Done in [17b46ab](https://github.com/SwissDataScienceCenter/renku-ui/pull/2902/commits/17b46ab712ac6ff11850b3788d57e16c19689fd1).

2023-11-23 10:18 UTC, leafty commented
> As discussed, none of these are blockers in my opinion. If you find quick solutions, then great, if not, feel free to defer to a later PR, or ignore.

Comments should be addressed now.

2023-11-23 11:00 UTC, ciyer commented on client/src/components/list/PinnedBadge.tsx
> +  return (
This is a nice solution, I think. Much easier to see the difference between the two states.

2023-11-23 11:01 UTC, ciyer approved these changes
Thanks for addressing those comments. This looks very nice. 🚀

2023-11-23 14:07 UTC, merged