feat: support more cloude storage options from the backend
SwissDataScienceCenter/renku-ui pull request #2908
Opened 2023-11-20 15:06 UTC by lorenzo-cavazzi

Support Cloud Storages coming from the `GET /storage/get_storage_schema` endpoint

/deploy
fix #2900

2023-12-12 11:05 UTC, leafty reviewed
Some first notes, which may be invalid as the code is not final.

2023-12-12 13:53 UTC, lorenzo-cavazzi commented on client/src/features/project/components/ProjectSettingsCloudStorage.tsx
> -  }
Now each CloudStorageItem handles permissions. It's not particularly useful at the moment since devAccess is required to add any storage in the first place, but in the future we can extend support for per-project storage and it will be listed without any further UI change

2023-12-12 13:56 UTC, lorenzo-cavazzi commented on client/src/features/session/hooks/options/useDefaultCloudStorageOption.hook.ts
> +  support: "s3" | "none"
Ouch, I missed this. Thanks

2023-12-12 14:19 UTC, leafty commented on client/src/features/project/components/ProjectSettingsCloudStorage.tsx
> -  }
> we can extend support for per-project storage

I don't understand. The current storage service stores configuration per project. It seems counter-productive to do this change expecting some future feature which may not exist in the end. Let's modify the behaviour once we change the access model of external storage, not before.

2023-12-12 14:28 UTC, lorenzo-cavazzi commented on client/src/styles/bootstrap/_custom_bootstrap_variables.scss
> +$breadcrumb-divider: quote(">");
It looks fine to me. Using the `button` elements in the breadcrumb actually seems to break the vertical alignment by ~1 px. Not sure how to properly fix this.
It looks really minor to me, but if you have a solution I'm happy to integrate it

2023-12-12 14:41 UTC, lorenzo-cavazzi commented on client/src/features/session/components/options/SessionCloudStorageOption.tsx
> +              : "Non active for this session"}
Fair point. Not sure why I thought it would be a good idea to change it.
User: "oh, so if I click this, it will make the storage _non_ active :thinking:   :see_no_evil:

2023-12-12 16:07 UTC, lorenzo-cavazzi commented on client/src/features/project/components/ProjectSettingsCloudStorage.tsx
> -  }
At this point it's more work to revert that than to keep this as is

2023-12-13 10:00 UTC, leafty commented on client/src/features/project/components/cloudStorage/CloudStorageModal.tsx
> +  }, []); // eslint-disable-line react-hooks/exhaustive-deps
This is the source of many bugs, please respect the hook deps list provided by `eslint`. Remove here and everywhere else.

2023-12-13 10:06 UTC, leafty commented on client/src/features/project/components/cloudStorage/projectCloudStorage.constants.ts
> +export const CLOUD_STORAGE_OVERRIDE = {
Non-blocking: why is this stored on the UI? This reads like it should be provided by the storage service itself.

2023-12-13 10:26 UTC, leafty commented on client/src/utils/types/notebooksService.types.ts
These types belong in `client/src/features/session/sessions.types.ts` where other types for the `sessions` API are defined.

2023-12-13 10:26 UTC, leafty commented on client/src/features/session/hooks/options/useDefaultCloudStorageOption.hook.ts
> +  const support = !!notebooksVersion?.cloudStorageEnabled;
nitpick:
```suggestion
  const supported = !!notebooksVersion?.cloudStorageEnabled;
```

2023-12-13 10:26 UTC, leafty commented on client/src/features/session/hooks/options/useDefaultCloudStorageOption.hook.ts
> +  support: boolean
nitpick:

```suggestion
  supported: boolean
```

2023-12-13 10:26 UTC, leafty commented on client/src/features/session/components/options/SessionCloudStorageOption.tsx
> +      {storageSettingsRecommendation}
Prefer:

```suggestion
      {devAccess && (
        <div className={cx("form-text", "my-1")}>
      Cloud storage options can be adjusted from the{" "}
      <Link to={settingsStorageUrl}>Project&apos;s settings</Link>.
    </div>
      )}
```

2023-12-13 10:26 UTC, leafty commented on client/src/features/session/components/options/SessionCloudStorageOption.tsx
> +        supported: true,
This looks incorrect, I think this should probably reuse `getInitialCloudStorageItem()`:

```tsx
  const supported = !!notebooksVersion?.cloudStorageEnabled;
   const initialCloudStorage: SessionCloudStorage[] = storageForProject.map(
      getInitialCloudStorageItem(supported)
    );
```

2023-12-13 10:51 UTC, lorenzo-cavazzi commented on client/src/features/project/components/cloudStorage/projectCloudStorage.types.ts
> +  step: number;
I agree using numbers isn't really optimal, especially now that we are down to 3 steps + the advanced mode.
If you don't mind, I'll change this in a follow-up PR

2023-12-13 11:06 UTC, lorenzo-cavazzi commented on client/src/features/project/components/cloudStorage/CloudStorageModal.tsx
> +  }, []); // eslint-disable-line react-hooks/exhaustive-deps
I actually want to invoke this only when unmounting the component. I'm not 100% sure how to achieve that without the pattern I used. I'm open to suggestions

2023-12-13 11:09 UTC, lorenzo-cavazzi commented on client/src/features/project/components/cloudStorage/projectCloudStorage.constants.ts
> +export const CLOUD_STORAGE_OVERRIDE = {
Yeah in principle I agree, but during the discussion we ended up implementing this solution so that we could support fields non relevant for the backend like `position`, and to better tailor the list to the needs of the UI (more evident in `CLOUD_OPTIONS_OVERRIDE`). 
Perhaps we should review that decision; in insight, it wasn't the best one

2023-12-13 11:11 UTC, lorenzo-cavazzi commented on client/src/features/project/components/cloudStorage/CloudStorageModal.tsx
> +  }, []); // eslint-disable-line react-hooks/exhaustive-deps
P.S. I removed the other in the same file, that was an oversight

2023-12-13 11:26 UTC, lorenzo-cavazzi commented on client/src/features/session/components/options/SessionCloudStorageOption.tsx
> +        supported: true,
This shouldn't be necessary anymore cause the component isn't rendered at all when there is no support from renku-notebooks. It was useful when supporting only s3 or azure. I'm removing the "supported" variable in this case

2023-12-13 15:16 UTC, leafty reviewed
Partial review part 1.

2023-12-13 15:16 UTC, leafty commented on client/src/features/project/components/cloudStorage/CloudStorageModal.tsx
> +    setState(() => fullNewState);
```suggestion
    setState(fullNewState);
```

2023-12-13 15:16 UTC, leafty commented on client/src/features/project/components/cloudStorage/CloudStorageModal.tsx
> +    }
Same here, this should not be necessary.

2023-12-13 15:16 UTC, leafty commented on client/src/features/project/components/cloudStorage/CloudStorageModal.tsx
> +    setStorageDetails(() => fullNewDetails);
```suggestion
    setStorageDetails(fullNewDetails);
```

2023-12-13 15:16 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddCloudStorage.tsx
> +  } = useForm();
To fix: Untyped usage of `useForm()` will default values to `any` which prevents the TypeScript compiler from detecting errors such as incorrect `name` on `<input>`.

2023-12-13 16:44 UTC, lorenzo-cavazzi commented on client/src/components/errors/RtkErrorAlert.tsx
> +export function RtkOrNotebooksError({
It looks fine for errors coming from renku notebooks, and the data service has a similar response structure. I'll double check

2023-12-13 16:54 UTC, lorenzo-cavazzi commented on client/src/features/project/components/cloudStorage/CloudStorageModal.tsx
> +    }
It's not a big optimization, but without this we re-render a few additional times when not necessary (E.G. try to click on the current section on the breadcrumb navigation)

2023-12-13 17:01 UTC, lorenzo-cavazzi commented on client/src/features/project/components/cloudStorage/CloudStorageModal.tsx
> +  const [success, setSuccess] = useState(false);
The storage state contains the values required to create/edit the storage, while this is a sort of extension to the addCloud/modifyCloud mutations. I feel it would make more sense to modify the mutations to rely on the `isSuccess/isError` variables, but this way was just quicker.

2023-12-13 17:20 UTC, lorenzo-cavazzi commented
@leafty thank you for the review :pray: 
I either applied the suggestions or responded inline. I dared mark as resolved all the suggestions I just used, but feel free to un-resolve wherever you think it not fixed

2023-12-14 11:03 UTC, leafty reviewed
Part 2

2023-12-14 11:03 UTC, leafty commented on client/src/features/project/components/cloudStorage/CloudStorage.module.scss
> +}
Remove class and replace with:
```tsx
className={cx("border", "border-rk-green")}
```

2023-12-14 11:03 UTC, leafty commented on client/src/features/project/components/cloudStorage/CloudStorage.module.scss
> +}
This is never used.

2023-12-14 11:03 UTC, leafty commented on client/src/features/project/components/cloudStorage/CloudStorage.module.scss
> +  }
Remove this, as the padding is already 8px by default.

2023-12-14 11:03 UTC, leafty commented on client/src/features/project/components/cloudStorage/CloudStorage.module.scss
> +  color: $rk-green;
TODO: replace with Bootstrap's variables for list groups.

2023-12-14 12:28 UTC, leafty requested changes
Last part

2023-12-14 12:28 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +            `external_storage/${storage.schema?.toLowerCase()}`
I think this should be `storage/<name>` instead. Just using the `schema` is prone to create mounting issues when using more than one storage configuration.

2023-12-14 12:28 UTC, leafty commented on client/src/features/versions/versions.api.ts
> +        } as NotebooksVersion;
nitpick, Should not be necessary:

```suggestion
        };
```

2023-12-14 12:28 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +    trigger(field);
Use `mode: "onChange"` instead: https://www.react-hook-form.com/api/useform/#mode

2023-12-14 12:39 UTC, leafty commented
Note: TODOs are to be tracked and put on a new issue to be solved soon.

2023-12-14 14:25 UTC, lorenzo-cavazzi commented on client/src/features/project/components/cloudStorage/CloudStorageModal.tsx
> +      }
Agreed, this is definitely not the best solution.
In the meanwhile, I can swap to `isEqual` from lodash since we already use the library

2023-12-14 14:34 UTC, lorenzo-cavazzi commented on client/src/features/project/components/cloudStorage/CloudStorageModal.tsx
> +  };
😅

2023-12-14 14:40 UTC, lorenzo-cavazzi commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +    });
The drawback is that vertical alignment is a bit off with this solution

2023-12-14 14:49 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +    });
To solve it you can add `align-items-center` to the parent => `<Breadcrumb className="align-items-center" data-cy="cloud-storage-edit-navigation">{items}</Breadcrumb>`

2023-12-14 15:40 UTC, lorenzo-cavazzi commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +            `external_storage/${storage.schema?.toLowerCase()}`
True, otoh the name is usually empty the first time you see this page.
I adopted an alternative solution: I update the mount point when editing the name as long as the mountPoint input is not dirty

2023-12-15 08:29 UTC, leafty commented
> The only bit I didn't change as suggested is the logic on running `reset` when unmounting the component. I tried to follow the suggestion here [#2908 (comment)](https://github.com/SwissDataScienceCenter/renku-ui/pull/2908#discussion_r1426475881) but I always end up in a re-render loop and I'm not sure how to avoid that. If you find an alternative solution, I'm happy to integrate it in the code

This indicates that state handling has some issues, and will need to be cleaned up.

2023-12-15 09:43 UTC, leafty reviewed
Some remarks about the "read-only" option.

2023-12-15 09:43 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +      <div className="mb-3">
Last item, doesn't need the margin after.

```suggestion
      <div>
```

2023-12-15 09:43 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +            <WarnAlert>
```suggestion
            <WarnAlert dismissible={false}>
```

2023-12-15 09:43 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +        </Label>
The label should be found after the check box.

2023-12-15 09:43 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +              id="readOnly"
The label is broken:
```suggestion
              id="add-storage-name"
```

Clicking the label should check/uncheck the option.

2023-12-15 11:38 UTC, lorenzo-cavazzi commented
> This indicates that state handling has some issues, and will need to be cleaned up.

Do you mind if I add also [#2908 (comment)](https://github.com/SwissDataScienceCenter/renku-ui/pull/2908#discussion_r1426475881) to the cleanup issue? I'd like to merge this PR soon and tag, and I can't find an easy solution to change the code and keep the same functionality

2023-12-15 13:44 UTC, leafty commented
> @leafty Do you mind if I add also [#2908 (comment)](https://github.com/SwissDataScienceCenter/renku-ui/pull/2908#discussion_r1426475881) to the cleanup issue? I'd like to merge this PR soon and tag, and I can't find an easy solution to change the code and keep the same functionality

No. This is to be cleaned up with moving state to an RTK slice.

2023-12-15 13:51 UTC, leafty approved these changes

2023-12-15 13:57 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +        <Label className="form-label" for="readOnly">
The label should still be on the right of the check box.

2023-12-19 09:18 UTC, merged