[ShapeUp] improve UX when adding/editing storage
SwissDataScienceCenter/renku-ui pull request #2962
Opened 2024-01-10 12:56 UTC by lorenzo-cavazzi

This PR fixes a few issues when adding/editing storage:
- Prevents a bunch of default values to be set automatically, especially when many advanced options exist.
- Correct use of placeholders for default values and examples.
- Remove values correctly when editing an existing storage.
- Handles non-stringy values correctly when listing the storage options in the storage list.
- Use `<datalist>` to pick values from the examples list.
    - Mind that examples from the backend are not 100% reliable; we can't use a `<select>` here, and I would rather keep a simple solution than mess up with autocomplete examples and "use-react-form." Support for the datalist tag is pretty good on Firefox, while the UX on Chrome is still not that good, especially for longer lists.

/deploy renku=rclone-sessions-acceptance-tests renku-notebooks=rclone-csi amalthea=pv-rbac renku-data-services=fix-storage-webdav extra-values=notebooks.cloudstorage.enabled=true,notebooks.cloudstorage.storageClass=csi-rclone-test,notebooks.cloudstorage.installRCloneCSI=false

2024-01-11 10:25 UTC, leafty requested changes

2024-01-11 10:25 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +  };
Prefer `useCallback()` version:

```suggestion
  const toggleTruncate = useCallback(() => {
    setIsTruncated((isTruncated) => !isTruncated);
  }, []);
```

2024-01-11 10:25 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +        className={cx("overflow-hidden", "local-style")}
What's `"local-style"`?

2024-01-11 10:25 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
>      options.map((o) => {
This is difficult to read, consider moving this to components (e.g. `<CheckboxOptionItem>`, `<PasswordOptionItem>`, `<DropdownOptionItem>`, etc.).

2024-01-11 10:25 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
>            {inputType === "checkbox" ? (
Checkboxes should be placed to the left of their label, not to the right.

2024-01-11 10:25 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +            {/* {o.help} */}
```suggestion
```

2024-01-11 10:25 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +      <Label className="form-label" for="add-storage-name">
Wrong `for=` here.

2024-01-11 10:25 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +function OptionDataList({ examples, listId }: OptionDataListProps) {
Note: the same functionality can be achieved with `react-autosuggest`.

2024-01-12 10:08 UTC, lorenzo-cavazzi commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +        className={cx("overflow-hidden", "local-style")}
Ouch, that's a leftover from a previous test

2024-01-12 11:38 UTC, lorenzo-cavazzi commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
>      options.map((o) => {
That's a good point; I split that long chunk of code into multiple components

2024-01-12 11:46 UTC, lorenzo-cavazzi commented
@leafty thank you for the review. I addressed your comments in ea48f28c400cfc9dee8614c01df04e39ca941646

There are a couple of additional commits that add minimal changes:
- Hide a couple of storage services that we don't want to support in the UI, at least initially.
- Restore the correct tag when invoking renku actions

2024-01-15 08:21 UTC, leafty approved these changes
LGTM :100: just some small things

2024-01-15 08:21 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +  }
```suggestion
  const additionalProps: Record<string, string> = {
    ...(inputType === "dropdown" ? { list: `${option.name}__list` } : {}),
  };
```

2024-01-15 09:45 UTC, lorenzo-cavazzi commented
@leafty fixes from the last review are in this commit https://github.com/SwissDataScienceCenter/renku-ui/pull/2962/commits/0a995c9717ac8a0de739a85d72fdac53d7e7bfbb

2024-01-15 09:47 UTC, leafty commented on client/src/features/project/components/cloudStorage/AddOrEditCloudStorage.tsx
> +  control: Control<FieldValues, any>; // eslint-disable-line @typescript-eslint/no-explicit-any
I think we can force this to be `void` if we call `useForm<Values, void>({<defaultValues>})` when using `react-hook-form`. The `context: TContext` field is used only if we use a third-party library for field validation.

`unknown` can work too I think. We don't need to address the use of `any` in this PR anyway.

2024-01-15 09:48 UTC, leafty approved these changes

2024-01-15 10:21 UTC, merged