[ShapeUp] Search and Discovery 1.0
SwissDataScienceCenter/renku-ui pull request #3032
Opened 2024-02-13 13:51 UTC by lorenzo-cavazzi

Feature branch for Search and Discovery 1.0
Pitch: https://www.notion.so/Renku-1-0-Project-and-User-Search-Service-e3df82dab0734f91bb8dc128f5e3aa54
Build page: https://www.notion.so/Renku-1-0-Search-Discovery-Services-Build-Team-cc4782794e084adca8fe9c36571d7b99

/deploy #notest

2024-03-15 15:23 UTC, andre-code commented
Items for review:
- Searching by Query Type, Visibility, and Creation Date for authenticated users
![search](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/20a81c04-b6ce-491a-ad4c-30fbd0af10c8)


- Searching by Query Type and Creation Date for non-authenticated users
- Sorting by Score, Creation Date, and Name
- Filtering by user ID
![search by user](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/314befe5-6261-499b-8b9b-252f856dd6b2)


On hold to review:
- Search by Role, awaiting implementation in the search service

2024-03-20 08:03 UTC, leafty commented on client/run-telepresence.sh
Minor comment: we should undo the changes in the telepresence scripts. See https://github.com/SwissDataScienceCenter/renku-ui/pull/3047.

2024-03-20 08:04 UTC, leafty commented on client/src/features/rootV2/NavbarV2.tsx
> +              Search v2
```suggestion
              Search
```

2024-03-20 08:04 UTC, leafty commented on client/src/features/rootV2/NavbarV2.tsx
> +              Projects v2
```suggestion
              Projects
```

2024-03-20 08:38 UTC, ciyer requested changes
Overall looks very good! 🚀 I have two minor change requests which should be easy to implement.

2024-03-20 08:38 UTC, ciyer commented on client/src/features/searchV2/components/SearchV2Results.tsx
> +    const fakeId = simpleHash(Math.random().toString());
I'm not sure this is a good idea. I think it would be better to use the index in the collection as the key (since this should not collide with the entity ids, which have a different structure).

2024-03-21 08:56 UTC, ciyer commented on client/src/utils/helpers/url/Url.js
> +    v2Users: {
As discussed in the stand up, let us set this change aside, since projects is also done this way and decide what to do in a later PR.

2024-03-21 09:10 UTC, leafty commented on client/src/utils/helpers/url/Url.js
> +    v2Users: {
Anyway, I think we should remove the `Url.js` file at some point. See https://github.com/SwissDataScienceCenter/renku-ui/issues/3052.

2024-03-22 09:16 UTC, andre-code commented on client/src/features/searchV2/components/SearchV2Results.tsx
> +    const fakeId = simpleHash(Math.random().toString());
sure, I have modified the component key to use the index instead

2024-03-22 13:21 UTC, ciyer approved these changes
LGTM! 🚀

2024-03-26 11:45 UTC, ciyer approved these changes
Tested the new changes, and everything works for me! 🚀

2024-03-26 12:03 UTC, merged