Associate projects to namespaces
SwissDataScienceCenter/renku-ui pull request #3064
Opened 2024-03-08 15:46 UTC by ciyer

Changes that associate projects to namespaces.

2024-03-11 09:10 UTC, leafty requested changes
Code looks good.

After discussing with @Panaetius to coordinate on code naming for Renku 2.0, we should stick to `ProjectV2`, `SessionV2`, etc. naming to indicate Renku 2.0. This means things like `v2Group` should be renamed to `GroupV2`, etc.

Some other minor comments also.

2024-03-11 09:10 UTC, leafty commented on client/src/features/projectsV2/fields/ProjectNamespaceFormField.tsx
> +}
This interface already exists, it should be imported instead of copy-pasted.

2024-03-11 09:10 UTC, leafty commented on client/src/features/projectsV2/fields/ProjectNamespaceFormField.tsx
> +import styles from "./ProjectNamespaceFormField.module.scss";
nitpick: Import formatting

2024-03-14 15:35 UTC, ciyer commented on tests/cypress/support/commands/react-select.ts
> +  // @ts-ignore
I have removed this, though I do not follow why leaving this in is harmful.

2024-03-26 12:21 UTC, leafty approved these changes
Some minor comments which can be addressed or moved into issues.

2024-03-26 12:21 UTC, leafty commented on client/src/features/projectsV2/show/groupEditForms.tsx
> +import { Redirect } from "react-router-dom";
non-blocking (make a new issue): use `navigate` from the new `react-router` API since this already lives there.

2024-03-26 12:21 UTC, leafty commented on client/src/utils/helpers/url/Url.js
> +    groupV2s: {
```suggestion
    groupsV2: {
```

2024-03-28 09:52 UTC, merged