feat: test styles for Renku 2.0
SwissDataScienceCenter/renku-ui pull request #3094
Opened 2024-04-05 11:49 UTC by andre-code

Draft styles for Renku 2.0 and current Renku

2024-04-08 09:42 UTC, lorenzo-cavazzi requested changes
See inline

2024-04-08 09:42 UTC, lorenzo-cavazzi commented on client/src/features/rootV2/StylesV2.tsx
> +const StylesV2 = () => <></>;
Is this file just to import files? This shouldn't be necessary, you can import the style directly on the component where you need it

2024-04-08 09:42 UTC, lorenzo-cavazzi commented on client/src/features/rootV2/LazyRootV2.tsx
>    );
What about just importing? Something like this.
```suggestion
export default function LazyRootV2() {
  useEffect(() => {
    import("../../styles/indexV2.scss");
  }, []);
  return (
    <Suspense fallback={<PageLoader />}>
      <RootV2 />
    </Suspense>
  );
```

2024-04-08 09:42 UTC, lorenzo-cavazzi commented on client/src/utils/customHooks/ReloadOnV2Navigation.hook.ts
> +      window.location.reload();
It would be great to re-assign the SCSS variables instead; not sure what's the best method but it's a matter of re-executing the code in "styles/bootstrap/_custom_bootstrap_variables.scss". Re-importing index.scss won't work just because it's cached, but there might be a workaround.

P.S. the function would need to work slightly different cause the variables should be re-defined before rendering the components. You can see what I mean by swapping this with something like `import("../../styles/indexV1.scss");` where `indexV1.scss` is a copy of `index.scss` and trying to move around. The first page will _usually_ render with the previous colors, and all the others will have the correct colors again

2024-04-16 13:37 UTC, leafty commented on client/src/styles/bootstrap/_custom_bootstrap_variables2.0.scss
> +$enable-rounded: false;
Note: I think we should set this to `true`. Having this set to `false` while we actually use rounded corners breaks many components (e.g. input groups where we have to manually set which corners are rounded).

2024-04-22 06:44 UTC, andre-code commented on client/src/styles/bootstrap/_custom_bootstrap_variables2.0.scss
> +$enable-rounded: false;
Agree, I changed this in the PR https://github.com/SwissDataScienceCenter/renku-ui/pull/3104

2024-04-22 06:46 UTC, andre-code commented on client/src/features/rootV2/LazyRootV2.tsx
>    );
Thank you @lorenzo-cavazzi . The strategy for managing styles has changed, so this code is no longer needed.

2024-04-22 07:23 UTC, leafty approved these changes

2024-04-22 07:59 UTC, merged