[ShapeUp] feat: add secrets page
SwissDataScienceCenter/renku-ui pull request #3101
Opened 2024-04-08 16:06 UTC by lorenzo-cavazzi

Secrets in the UI -- feature branch

/deploy

fix #3100

2024-05-13 09:44 UTC, ciyer requested changes
Looks very good and works well! I have a small suggestion to turn off spellcheck in the secrets input.

2024-05-13 09:44 UTC, ciyer commented on client/src/features/secrets/SecretNew.tsx
> +                  type="textarea"
```suggestion
                  id="new-secret-value"
                  spellCheck="false"
                  type="textarea"
```

This field should probably not be spellchecked.

<img width="434" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/1196411/aae80f07-06b2-460f-815c-ae8bdd5fe9fe">

2024-05-13 09:44 UTC, ciyer commented on client/src/features/secrets/SecretEdit.tsx
> +                      type="textarea"
```suggestion
                      id="edit-secret-value"
                      spellCheck="false"
                      type="textarea"
```

2024-05-13 12:23 UTC, lorenzo-cavazzi commented
@ciyer  I added your suggestions to the code, although not all browsers consider that option
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/403141c2-5177-4297-ac54-42ec0263b9a1)

2024-05-14 14:30 UTC, ciyer approved these changes
LGTM!

2024-05-14 14:44 UTC, leafty commented
> @ciyer I added your suggestions to the code, although not all browsers consider that option

Note: It looks like it's added from a chrome extension, not the base browser itself.

2024-05-14 15:00 UTC, merged

2024-05-14 15:07 UTC, lorenzo-cavazzi commented
> Note: It looks like it's added from a chrome extension, not the base browser itself.

@leafty That's actually the Firefox browser spellcheck.

On top of that, I also have a browser extension that would take priority and ofc ignore the setting as well :laughing: 

The additional icon on the right side of the field was misleading, it was temporarily off. It shows slightly differently when it's enabled on the page and it finds errors.

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/9f864119-28f6-418e-9660-7a4634673c87)