feat(client): use namespace/slug to identify projects (#3096)
SwissDataScienceCenter/renku-ui pull request #3103
Opened 2024-04-11 07:50 UTC by ciyer

* Changes to use namespace/slug in the URL for the project page (instead of project Id)
* Minor changes like rename `v2Projects` to `projectV2` and use Navigate instead of Redirect

Fix #3096 

/deploy renku-data-services=main

2024-04-15 08:07 UTC, leafty requested changes
Code looks good :clap: 

The Navbar code needs to have one line added to fix the session page with the new routing (see screenshot).
Add a new exception here: https://github.com/SwissDataScienceCenter/renku-ui/blob/15dd06021e453a82dac81c4953d0eb39a15c5c18/client/src/landing/NavBar.jsx#L66.

![renku-ci-ui-3103 dev renku ch_v2_projects_flora thiebaut_flora-test_sessions_show_renku-2-451b10d8ec2c12941906a86dd7ec6dd8](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/f5257a75-b6a7-4c7f-bcce-6e17d4eba4b9)

2024-04-16 08:34 UTC, ciyer commented
> The Navbar code needs to have one line added to fix the session page with the new routing (see screenshot). Add a new exception here:
> 
> https://github.com/SwissDataScienceCenter/renku-ui/blob/15dd06021e453a82dac81c4953d0eb39a15c5c18/client/src/landing/NavBar.jsx#L66


Thanks for the review! I felt that something wasn't quite right, but I couldn't put my finger on what it was. I have made the changes necessary to hide navigation in the session view (c403472a8d32f5bd15de7a8411eaae3854d3f212).

2024-04-16 09:03 UTC, leafty requested changes
I noticed the same issue exists for the footer 😅 . Should be good to go once fixed.

2024-04-16 09:13 UTC, ciyer commented
> I noticed the same issue exists for the footer 😅 . Should be good to go once fixed.

Yes, you are right! Fixed in 51aa67c9d86fbe7c7c9cbfe91854b01cc4af703c

2024-04-16 09:25 UTC, leafty approved these changes

2024-04-17 06:49 UTC, merged