feat(client): Add structure project page
SwissDataScienceCenter/renku-ui pull request #3104
Opened 2024-04-11 08:24 UTC by andre-code

This PR Includes:

Header

- Show preview image
- Show title, description
- Display "add description" link that redirects to project settings
- Show "create session" button; it includes a modal but no styles for the create session modal, the button is visible only when the project hasn't created a session yet
- Show dots menu, including delete project modal with styles

Side Menu

- Display items with styles
- Display project info item when on mobile

Project Info
- Display project namespace, visibility, creation date
![Screenshot 2024-04-25 at 09 27 38](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/565bd85f-0988-4247-b350-8ef009ee3f32)
![Screenshot 2024-04-25 at 09 25 41](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/8f21e874-d4c4-4339-8fb0-9250d9ebbea3)

Note: Pending display of members and keywords, they will be included in another PR.
- Project Overview will be included in other PR

/deploy renku=release-0.52.x renku-data-services=main

2024-04-23 09:07 UTC, leafty commented
@andre-code can you please fix the merge conflict and provide screenshots in the PR description?

I am not sure if what I am seeing corresponds to the intended state:
![Screenshot 2024-04-23 at 11 06 04](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/e18939d5-c5d4-4c32-b1fa-53538389f2f8)
The overview is empty even after adding a session.

2024-04-25 08:36 UTC, leafty reviewed
Component code looks good, styles will have to be discussed as they introduce deviations from the Bootstrap system.

Some visual issues:

Top corners on the dropdown account menu get squared on hover:
![Screenshot 2024-04-25 at 10 01 23](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/3400620f-8c3c-47db-a070-5eeb773fa248)
![Screenshot 2024-04-25 at 10 30 51](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/ccdcbccf-ea1b-40ec-9cc6-d659381854bf)

Three dots button gets white:
![Screenshot 2024-04-25 at 10 00 02](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/0131c33c-b62a-461d-bcd8-ddfa6a420189)

The issue appears when the user navigates to v2 then v1 then v2 again. This is due to the use of the `cssModule` property. I can suggest a fix later.

2024-04-25 08:36 UTC, leafty commented on client/src/components/buttons/Button.tsx
> +  title: string;
Change this to support any type of tooltip content:

```suggestion
  tooltip: ReactNode;
```

This works with text or react components without any effort.

2024-04-25 08:36 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContainer/ProjectPageContainer.tsx
> +              <Link to={Url.get(Url.pages.v2Projects.list)}>
`react-router@v6` recommends developers to use relative routing for links:

```suggestion
              <Link to="..">
```

2024-04-25 08:36 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContainer/ProjectPageContainer.tsx
> +      <Col sm={12} lg={12} className={styles.HeaderContainer}>
```suggestion
      <Col sm={12} className={styles.HeaderContainer}>
```
`lg={12}` does nothing here.

2024-04-25 08:36 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContainer/ProjectPageContainer.tsx
> +    if (isErrorResponse(error)) {
I think this should be filtered to only `404` responses.

2024-04-25 08:36 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContainer/ProjectPageContainer.tsx
> +          <div>Could not retrieve project</div>
In this case we should use the RtkError component to show the error.

2024-04-25 08:36 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageNav/ProjectPageNav.tsx
> +    <Nav justified={true} className={styles.ProjectPageNav}>
```suggestion
    <Nav justified className={styles.ProjectPageNav}>
```

2024-04-25 08:36 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageNav/ProjectPageNav.tsx
> +            : ""
```suggestion
          selectedContent === ProjectPageContentType.Overview
            && styles.ProjectPageNavItemActive
```

2024-04-25 08:36 UTC, leafty commented on client/src/styles/components/_custom_buttons.module.scss
This and the two other modules are not intended to be part of the initial bootstrap stack (`index.scss`), so they should be placed in another location.

2024-04-26 10:03 UTC, leafty commented
@andre-code See [this commit](https://github.com/SwissDataScienceCenter/renku-ui/pull/3114/commits/4c7cf2e732eee3ee663132debdb4d1c3bbad0679) for a fix on the three dots button going white.

2024-04-29 06:54 UTC, andre-code commented
@leafty, thanks for your review. I've incorporated your suggestions and revised the CSS styles to utilize more Bootstrap components and classes.

2024-04-29 07:44 UTC, leafty reviewed
(Partial review) some comments.

2024-04-29 07:44 UTC, leafty commented on client/src/components/buttons/Buttons.module.scss
non-blocking: I think it would be nicer to use the bootstrap CSS variables to achieve this. In some cases this may be broken because of our continued use of bootstrap anti-patterns in our `index.scss`.

2024-04-29 07:44 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContainer/ProjectPageContainer.module.scss
> +}
Alternatively:

```suggestion
.HeaderContainer {
  background-color: var(--#{$prefix}white);
  
  @include media-breakpoint-up(lg) {
    & {
      background-color: transparent;
    }
  }
}

.NavContainer {
  background-color: var(--bs-gray-200);
  
  @include media-breakpoint-up(lg) {
    & {
      background-color: transparent;
    }
  }
}
```

2024-04-29 07:44 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/ProjectInformation/ProjectInformation.module.scss
> +  background-color: #6c757d;
Can this be defined somewhere and re-used as a CSS or SASS variable?

2024-04-29 07:44 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageNav/ProjectPageNav.module.scss
> +}
```suggestion
.ProjectPageNavItem a {
  color: var(--bs-rk-text);
  
  &:hover {
    text-decoration: underline;
    text-underline-offset: 5px;
  }
}
```

2024-04-29 08:22 UTC, leafty requested changes
The navbar component needs to be simplified: it does not need to use the page content type argument to properly render `active` links.

See code suggestions to make this work and reduce the amount of code.

2024-04-29 08:22 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContainer/ProjectPageContainer.tsx
> +        ></ProjectPageNav>
This can be simplified to:

```suggestion
        <ProjectPageNav namespace={namespace} slug={slug} />
```

2024-04-29 08:22 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageNav/ProjectPageNav.tsx
> +}
The content page type argument is not needed to render `active` links.

```suggestion
import cx from "classnames";
import { EyeFill, Folder2Open, PencilSquare } from "react-bootstrap-icons";
import { Nav, NavItem } from "reactstrap";

import RenkuNavLinkV2 from "../../../components/RenkuNavLinkV2.tsx";
import { Url } from "../../../utils/helpers/url";

import styles from "./ProjectPageNav.module.scss";

export default function ProjectPageNav({
  namespace,
  slug,
}: {
  namespace: string | undefined;
  slug: string | undefined;
}) {
  const projectUrl = Url.get(Url.pages.projectV2.show, { namespace, slug });
  const projectSettingsUrl = Url.get(Url.pages.projectV2.settings, {
    namespace,
    slug,
  });
  const projectInfoUrl = Url.get(Url.pages.projectV2.projectInfo, {
    namespace,
    slug,
  });

  return (
    <Nav justified className={cx("d-flex", "flex-row", "flex-lg-column")}>
      <NavItem className={cx("mb-0", "mb-lg-3", "py-3", "py-lg-0", "d-flex")}>
        <RenkuNavLinkV2
          end
          to={projectUrl}
          title="Overview"
          className={cx(
            "p-0",
            "mb-1",
            "text-center",
            "text-lg-start",
            "d-flex",
            "flex-column",
            "flex-lg-row",
            "align-items-center",
            "align-items-lg-start",
            "gap-2",
            styles.navLink
          )}
        >
          <EyeFill className={cx("d-block", "d-lg-none")} />
          Overview
        </RenkuNavLinkV2>
      </NavItem>
      <NavItem
        className={cx(
          "d-inline",
          "d-lg-none",
          "mb-0",
          "mb-lg-3",
          "py-3",
          "py-lg-0"
        )}
      >
        <RenkuNavLinkV2
          end
          to={projectInfoUrl}
          title="Project Information"
          className={cx(
            "p-0",
            "mb-1",
            "text-center",
            "text-lg-start",
            "d-flex",
            "flex-column",
            "flex-lg-row",
            "align-items-center",
            "align-items-lg-start",
            "gap-2",
            styles.navLink
          )}
        >
          <Folder2Open className={cx("d-block", "d-lg-none")} />
          Project Info
        </RenkuNavLinkV2>
      </NavItem>
      <NavItem className={cx("mb-0", "mb-lg-3", "py-3", "py-lg-0")}>
        <RenkuNavLinkV2
          end
          to={projectSettingsUrl}
          title="Settings"
          className={cx(
            "p-0",
            "mb-1",
            "text-center",
            "text-lg-start",
            "d-flex",
            "flex-column",
            "flex-lg-row",
            "align-items-center",
            "align-items-lg-start",
            "gap-2",
            styles.navLink
          )}
        >
          <PencilSquare className={cx("d-block", "d-lg-none")} />
          Settings
        </RenkuNavLinkV2>
      </NavItem>
    </Nav>
  );
}
```

2024-04-29 08:22 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageNav/ProjectPageNav.module.scss
> +}
The styles are applied at the wrong level here, they need to be applied to the `a.nav-link` component.

```suggestion
.navLink {
  color: var(--bs-rk-text);

  &:hover {
    text-decoration: underline;
    text-underline-offset: 5px;
  }

  &:global(.active) {
    font-weight: bold;
    text-decoration: underline;
    text-underline-offset: 5px;
    padding: 0;
    margin-bottom: 0;
    color: var(--bs-rk-text);
  }

  @include media-breakpoint-up(lg) {
    & {
      color: var(--bs-rk-text-light);

      &:hover {
        color: var(--bs-rk-text);
      }
    }

    &:global(.active) {
      color: var(--bs-rk-text);
    }
  }
}
```

2024-04-29 08:23 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageNav/ProjectPageNav.module.scss
> +}
Resolving because of the later comment.

2024-04-29 11:48 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/ProjectPageContent.tsx
> +  const isSettingsPage = window.location.pathname.endsWith("/settings");
I don't think this a clean way to handle routing. The original implementation was fine, the review only mentioned the nav components.

2024-05-02 08:48 UTC, leafty approved these changes

2024-05-02 11:33 UTC, merged