[ShapeUp] Renku V2 Project Page
SwissDataScienceCenter/renku-ui pull request #3108
Opened 2024-04-22 08:01 UTC by andre-code

[WIP]

/deploy

2024-05-21 07:25 UTC, leafty requested changes
This is mostly ready :clap: , some comments below.

The **[design]** items are non-blocking but need to be raised with design and fixed shortly.

2024-05-21 07:25 UTC, leafty commented on client/src/features/sessionsV2/components/SessionStatus/SessionStatus.tsx
> +        <ExclamationCircleFill className="text-warning" size={16} />
For all bootstrap icons, use class `"bi"` to align them with the surrounding text. Also, you can handle the margin here:

```suggestion
        <ExclamationCircleFill className={cx("bi", "me-1", "text-warning")}  size={16} />
```

2024-05-21 07:25 UTC, leafty commented on client/src/features/sessionsV2/components/SessionStatus/SessionStatus.tsx
> +        <span className="text-warning ml-2">Starting Session</span>
Note: class `ml-2` does not exist. Use `ms-1`, `me-1`, etc.

2024-05-21 07:25 UTC, leafty commented on client/src/styles/icons/sessions.svg
[design] same viewbox comment here

2024-05-21 10:25 UTC, andre-code commented
Thanks, @leafty. I've included your code suggestions in the latest commit.

2024-05-21 11:44 UTC, leafty reviewed
Should be good after this.

2024-05-21 11:44 UTC, leafty commented on client/src/components/buttons/Button.tsx
> +        className={cx(props.className || "", classes, "rounded-end-pill")}
why have `|| ""`?

```suggestion
        className={cx(props.className, classes, "rounded-end-pill")}
```

2024-05-21 11:44 UTC, leafty commented on client/src/components/buttons/Button.tsx
> +          {text} <ArrowRight />
This probably looks better:

```suggestion
          {text}
          <ArrowRight className={cx("bi", "ms-1")} />
```

2024-05-21 14:13 UTC, leafty approved these changes
LGTM :rocket: :clap:

2024-05-22 08:36 UTC, leafty approved these changes

2024-05-22 09:39 UTC, merged