feat: project page overview V2 (sessions and code repositories)
SwissDataScienceCenter/renku-ui pull request #3117
Opened 2024-05-02 11:49 UTC by andre-code

PR to add project overview content. It includes:

Display session and code repositories.
Display session launcher info in side panel.
Add new session (custom image/existing environment).
Link existing code repository (Renku repo only).
Delete session launcher.
Remove code repository.
Edit session launcher.

![project overview](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/568b6279-5b94-4314-9f94-024bd8a6076c)

/deploy renku-data-services=main

2024-05-02 14:40 UTC, leafty requested changes
Code mostly looks OK 👏 

One big issue is the display of session environments
![Screenshot 2024-05-02 at 16 27 26](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/c38d387c-717f-4a01-bf53-d63c990904e3)

1. The margins between items is much larger than the margins with other components. This breaks the flow of information within the form. The margin inside the same form control should be smaller than the gap between form controls.
2. The border effects create layout shifts, see comment in code.

2024-05-02 14:40 UTC, leafty commented on client/src/components/buttons/Button.tsx
> +  const ref = useRef(null);
`ref` is never used, so the tooltip will no work.

2024-05-02 14:40 UTC, leafty commented on client/src/components/buttons/Button.tsx
> +        onClick={() => handler()}
```suggestion
        onClick={handler}
```

2024-05-02 14:40 UTC, leafty commented on client/src/components/icons/EnvironmentIcon.tsx
> + * Copyright 2023 - Swiss Data Science Center (SDSC)
```suggestion
 * Copyright 2024 - Swiss Data Science Center (SDSC)
```

2024-05-02 14:40 UTC, leafty commented on client/src/components/icons/AlertIcon.tsx
> + * Copyright 2023 - Swiss Data Science Center (SDSC)
```suggestion
 * Copyright 2024 - Swiss Data Science Center (SDSC)
```

2024-05-02 14:40 UTC, leafty commented on client/src/components/icons/RenkuIcon.tsx
> + * Copyright 2023 - Swiss Data Science Center (SDSC)
```suggestion
 * Copyright 2024 - Swiss Data Science Center (SDSC)
```

2024-05-02 14:40 UTC, leafty commented on client/src/features/sessionsV2/components/SessionModals/AddSession.tsx
> +    <Modal
This modal is not centered

2024-05-02 14:40 UTC, leafty commented on client/src/styles/assets/chevron-up.svg
There is already a chevron in bootstrap. Why is a new one needed?

2024-05-02 14:40 UTC, leafty commented on client/src/styles/bootstrap/_custom_bootstrap_variables.scss
> +$dropdown-link-hover-bg: #e9ecef;
as a variable?

2024-05-02 14:40 UTC, leafty commented on client/src/styles/bootstrap/_custom_bootstrap_variables.scss
> +$rk-dropdown-options-margin: 5px 0;
An odd value is weird here. Is `4px` or `6px` not acceptable?

2024-05-02 14:40 UTC, leafty commented on client/src/styles/bootstrap/_custom_bootstrap_variables.scss
> +$dropdown-item-padding-y: 15px;
Odd value here too.

2024-05-02 14:40 UTC, leafty commented on client/src/styles/bootstrap/_custom_bootstrap_variables2.0.scss
> +// Modal stylesF.alert-warning
?

2024-05-02 14:40 UTC, leafty commented on client/src/styles/bootstrap/_custom_bootstrap_variables2.0.scss
> +$rk-gray-600: #6c757d;
Where and how are all these colors defined?

2024-05-02 14:40 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourcesBox.tsx
> +      <Modal isOpen={isOpen} toggle={toggle}>
Modal is not centered.

2024-05-02 14:40 UTC, leafty commented on client/src/features/sessionsV2/SessionLauncherFormContent.tsx
> +                ? "border border-rk-green border-3 rounded"
The `border-3` here creates layout shifts when we select an item. The same issue happens on hover because of the `border` added when hovering.

To achieve a proper hover effect, the unselected items need to have a transparent border.

To achieve the proper select border is more complex. One possibility is to use an inner shadow, another one is to add a transparent 2px border which gets green on select.

2024-05-06 07:53 UTC, andre-code commented on client/src/styles/bootstrap/_custom_bootstrap_variables2.0.scss
> +$rk-gray-600: #6c757d;
Here you can find the new palette color definition: [link](https://www.figma.com/file/2vGPq24rAU15EydWpj94cf/High-fidelity-design?type=design&node-id=4-10071&mode=design)

2024-05-06 14:56 UTC, leafty requested changes
There is still a layout shift on the environment items, see below.

The dropdown menus are broken in Renku 1.0 and 2.0; rounded corners become square on hover. Also, the divider looks wrong, being thicker than the border.
![Screenshot 2024-05-06 at 13 59 24](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/3c9f49f3-69f3-410f-88d7-342d329c99e8)
![Screenshot 2024-05-06 at 14 00 04](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/ddc1854c-01d4-4ddf-bfc1-641559d692e8)

I feel concerned by the fact that this PR increases the complexity of the bootstrap setup which will likely make cleaning it up harder to do in the future.

2024-05-06 14:56 UTC, leafty commented on client/src/styles/bootstrap/_custom_bootstrap_variables2.0.scss
> +  "rk-text-warning": $rk-text-warning,
We should not add all these colors here. This creates a lot of new CSS classes from Bootstrap which we are unlikely to use.

2024-05-06 14:56 UTC, leafty commented on client/src/features/sessionsV2/SessionLauncherFormContent.tsx
> +import { WarnAlert } from "../../components/Alert.jsx";
import order

2024-05-06 14:56 UTC, leafty commented on client/src/features/sessionsV2/SessionLauncherFormContent.tsx
> +                ? "border rounded border-rk-green bg-rk-green-50 border-2"
This still creates a layout shift when selecting or de-selecting items.

2024-05-08 07:58 UTC, leafty approved these changes
LGTM 👏

2024-05-15 08:16 UTC, leafty reviewed
I just noticed that there is no option to change the URL of a repository. Is this intentional?

2024-05-15 12:16 UTC, andre-code commented
> I just noticed that there is no option to change the URL of a repository. Is this intentional?

Yes, the options so far are to add or remove repositories.

2024-05-15 12:41 UTC, leafty commented
> > I just noticed that there is no option to change the URL of a repository. Is this intentional?
> 
> Yes, the options so far are to add or remove repositories.

The old view would let users edit the URL which is useful if there is a typo. Can it be added back here?

2024-05-15 12:47 UTC, andre-code commented
> > > I just noticed that there is no option to change the URL of a repository. Is this intentional?
> > 
> > 
> > Yes, the options so far are to add or remove repositories.
> 
> The old view would let users edit the URL which is useful if there is a typo. Can it be added back here?

Sure

2024-05-17 06:48 UTC, merged