UI changes for auth
SwissDataScienceCenter/renku-ui pull request #3118
Opened 2024-05-03 12:38 UTC by ciyer

WIP

2024-05-23 14:50 UTC, lorenzo-cavazzi requested changes
I'm reviewing the code right now. As an early comment, I believe the "Keywords" section got accidentally duplicated while merging/rebasing the code.
I'll follow up soon with the full review

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/018ea2c3-6848-44ac-b66b-3bd62329d646)

2024-05-23 15:25 UTC, lorenzo-cavazzi requested changes
Very nice addition! :rocket: 

Since most of the code was already reviewed separately, I did only a quick pass and everything looks reasonable!
I added a couple of inline comments, very minor changes.

While testing, I noticed the visibility is listed twice on the General Settings tab, and with different formats. Perhaps something mixed up while rebasing?

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/398a9f9b-2f52-4e3e-a1cd-7e8821653b78)

2024-05-23 15:25 UTC, lorenzo-cavazzi commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/RepositoriesBox.tsx
> +          disabled={null}
Should the `AccessGuard` component make this property optional instead of passing `null` here?

2024-05-23 15:25 UTC, lorenzo-cavazzi commented on client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourcesBox.tsx
> +          disabled={null}
Some as above

2024-05-23 15:25 UTC, lorenzo-cavazzi commented on client/src/features/ProjectPageV2/ProjectPageContent/ProjectInformation/ProjectInformation.tsx
> +            disabled={null}
Same here

2024-05-23 15:25 UTC, lorenzo-cavazzi commented on client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectSettings.tsx
> +        disabled={null}
Same here

2024-05-23 15:25 UTC, lorenzo-cavazzi commented on client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectSettings.tsx
> +        disabled={null}
Same here

2024-05-23 15:25 UTC, lorenzo-cavazzi commented on client/src/features/ProjectPageV2/ProjectPageContent/Settings/ProjectSettings.tsx
> +        disabled={null}
Please also check the other occurences. I realize now there are some :grin:

2024-05-23 15:25 UTC, lorenzo-cavazzi commented on tests/cypress/e2e/projectV2.spec.ts
> +    // cy.contains("https://domain.name/repo3.git").should("be.visible");
Should this be removed?

2024-05-23 15:27 UTC, lorenzo-cavazzi reviewed
Here are a few additional comments that can be addressed in separate issues as cooldown activities -- some of them are actually improvements, perhaps not even envisioned in the current build.

* Users can now demote themselves from the `Owner` role to something with less permissions. It would be nice to prevent demoting the last owner; otherwise, projects would un-deletable.
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/8f38378f-dae1-48fd-9695-60c7f3a1de44)

* I suggest making users always able to remove themselves from a project they don't own. Otherwise, they could have a role assigned by someone else and be stuck with that project (sounds bad for spamming unwanted content). Here is an example: I can't remove my user from there: https://renku-ci-ui-3118.dev.renku.ch/v2/projects/lorenzo.cavazzi.tech/test-creation

* (cosmetic) The content spacing is a little off; the outer box is in line with the other components, but the internal content adds further spacing. I suggest removing that and adding just the bottom margin to the different sections (or top margins, or using the `gap` logic; whatever solution makes the most sense here). I assume this was evident only after merging the other Project 2.0 changes at the last moment :grin: Not a big deal tbh 
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/c744c5e7-69ac-4cdb-af58-d7af590b7c14)

2024-05-23 15:31 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/RepositoriesBox.tsx
> +          disabled={null}
I personally think that it's a good interface to explicitly require a component to be passed, even if it is `null`.

2024-05-23 15:31 UTC, ciyer commented
> I'm reviewing the code right now. As an early comment, I believe the "Keywords" section got accidentally duplicated while merging/rebasing the code. I'll follow up soon with the full review

Great catch! Just fixed this.

2024-05-23 15:34 UTC, ciyer commented
> While testing, I noticed the visibility is listed twice on the General Settings tab, and with different formats. Perhaps something mixed up while rebasing?

Yes, looks like this happened in the rebase. I have fixed this.

2024-05-23 15:37 UTC, ciyer commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/RepositoriesBox.tsx
> +          disabled={null}
I suggest leaving this as it is for the moment; if there is a reason to apply a default, we can easily do this in the future.

2024-05-23 15:45 UTC, ciyer commented
> * Users can now demote themselves from the `Owner` role to something with less permissions. It would be nice to prevent demoting the last owner; otherwise, projects would un-deletable.
> * I suggest making users always able to remove themselves from a project they don't own. Otherwise, they could have a role assigned by someone else and be stuck with that project (sounds bad for spamming unwanted content). Here is an example: I can't remove my user from there: https://renku-ci-ui-3118.dev.renku.ch/v2/projects/lorenzo.cavazzi.tech/test-creation

I agree that these are both problems, but I think they need to be fixed in the backend first. The UI should allow any change that is allowed by the backend and should generally prevent the user from making changes that are not allowed by the backend as a UX convenience. 

> * (cosmetic) The content spacing is a little off; the outer box is in line with the other components, but the internal content adds further spacing. I suggest removing that and adding just the bottom margin to the different sections (or top margins, or using the `gap` logic; whatever solution makes the most sense here). I assume this was evident only after merging the other Project 2.0 changes at the last moment 😁 Not a big deal tbh

Yes, this is a good point. I will try to make those cosmetic fixes quickly.

2024-05-23 16:10 UTC, lorenzo-cavazzi commented
> I agree that these are both problems, but I think they need to be fixed in the backend first. The UI should allow any change that is allowed by the backend and should generally prevent the user from making changes that are not allowed by the backend as a UX convenience.

I agree the backend should catch up by disallowing unwanted actions, but I don't think this excuses us from making a better UX.
Ofc the backend should support the actions (E.G. no point in adding a UX to let users remove themselves from a project if the backend errors), but I don't see a negative point in preventing a downgrade of the last Owner even if doing it from the backend API works.

2024-05-23 16:16 UTC, ciyer commented on tests/cypress/e2e/projectV2.spec.ts
> +    // cy.contains("https://domain.name/repo3.git").should("be.visible");
I fixed the implementation of this test.

2024-05-23 18:00 UTC, leafty commented
> > I agree that these are both problems, but I think they need to be fixed in the backend first. The UI should allow any change that is allowed by the backend and should generally prevent the user from making changes that are not allowed by the backend as a UX convenience.
> 
> I agree the backend should catch up by disallowing unwanted actions, but I don't think this excuses us from giving users a better UX. Ofc the backend should support the actions (E.G. no point in adding a UX to let users remove themselves from a project if the backend errors), but I don't see a negative point in preventing a downgrade of the last Owner even if doing it from the backend API works.

I think you are missing the point: we should not hide the bug in the UI because doing so may hide the existence of the bug from the backend maintainers. The backen

2024-05-24 09:32 UTC, andre-code submitted a review, later dismissed
Great feature! Is it possible to display the member names in the project information? Currently, it only shows the number of members, not their names.

![Screenshot 2024-05-24 at 11 31 52](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/b8e655a1-472e-40c9-94f3-2aac944af1b2)

2024-05-24 12:16 UTC, ciyer commented
> Great feature! Is it possible to display the member names in the project information? Currently, it only shows the number of members, not their names.

Sure, I will make a PR to address this.

2024-05-24 12:17 UTC, leafty approved these changes
LGTM

2024-05-24 12:39 UTC, leafty approved these changes

2024-05-24 13:07 UTC, merged

2024-05-27 11:55 UTC, lorenzo-cavazzi commented
> I think you are missing the point: we should not hide the bug in the UI because doing so may hide the existence of the bug from the backend maintainers. The backend needs to have the bug filed before we hide the bug.

I totally get that point :smile:  and it still sounds poor to me.
I don't understand how implementing a poor UX can be the best solution here, especially when the reasoning behind is that the backend allows for it. In this case, it also allows for a better solution -- we don't _need_ any change for that.
I think creating an issue in the backend and communicating with the developers is a much better solution to get the bug addressed than letting users fall for it in the UI.

2024-05-27 12:10 UTC, leafty commented
I have filed an issue at last https://github.com/SwissDataScienceCenter/renku-data-services/issues/227