feat: add data sources in project page v2
SwissDataScienceCenter/renku-ui pull request #3120
Opened 2024-05-06 13:53 UTC by andre-code

PR to include adding/modifying/deleting/viewing details of data sources.

![data source](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/03d67a59-fc0c-4032-b847-9a9682bae005)

/deploy

2024-05-08 13:12 UTC, leafty requested changes
Code looks OK. :raised_hands: 

Can you do a contrast check here. The labels do not seem to have enough contrast here.
![Screenshot from 2024-05-08 15-08-45](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/d71de52c-9d42-4a1b-a159-12ec89a18312)

Comment: we have so much space here, why do we not have the actions directly available as buttons? It feels annoying to do two clicks.
![Screenshot from 2024-05-08 15-08-57](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/ba53ac5b-f376-4cd1-af89-6c38098ed650)

2024-05-08 13:12 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourceDisplay.tsx
> +  };
```suggestion
  const toggleDetails = useCallback(() => {
    setToggleView((open: boolean) => !open);
  }, []);
```

2024-05-08 13:12 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourceDisplay.tsx
> +      onClick={() => toggleDetails()}
```suggestion
      onClick={toggleDetails}
```

2024-05-08 13:12 UTC, leafty commented on client/src/features/projectsV2/api/projectV2.enhanced-api.ts
> +    "Storages",
```suggestion
    "Storage",
```

2024-05-08 13:12 UTC, leafty commented on client/src/features/projectsV2/api/storages.api-config.ts
`storage` API. "Storages" is not an English word.

2024-05-08 13:12 UTC, leafty commented on client/.eslintrc.json
> +          "storages",
"storages" is not proper English.

```suggestion
```

2024-05-08 13:12 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourceDisplay.tsx
> +            <Pencil /> Edit data sources
```suggestion
            <Pencil /> Edit data source
```

2024-05-10 09:06 UTC, andre-code commented on client/src/features/projectsV2/api/storages.api-config.ts
Even though 'storages' isn't used much, it's still proper English. In our data services API, we refer to the storage as 'storages'. So, for now, I'll stick with that name to keep things consistent

2024-05-10 09:11 UTC, andre-code commented
> Code looks OK. 🙌
> 
> Can you do a contrast check here. The labels do not seem to have enough contrast here. ![Screenshot from 2024-05-08 15-08-45](https://private-user-images.githubusercontent.com/951086/328900089-d71de52c-9d42-4a1b-a159-12ec89a18312.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzIxMDgsIm5iZiI6MTcxNTMzMTgwOCwicGF0aCI6Ii85NTEwODYvMzI4OTAwMDg5LWQ3MWRlNTJjLTlkNDItNGExYi1hMTU5LTEyZWM4OWExODMxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwOTAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTMwMjZiNjNmNzRmOGU1OTBjY2JlN2Y5MGE2ZWI2NTM4NTFkY2NkNTQ0ZjYyYzkxYmNhN2MyODQ4NzE3YWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rhNVOLgcywB2FhYY-0PnzDzKk0QnICQuLVJWO3FVx4Q)
> 
> Comment: we have so much space here, why do we not have the actions directly available as buttons? It feels annoying to do two clicks. ![Screenshot from 2024-05-08 15-08-57](https://private-user-images.githubusercontent.com/951086/328900103-ba53ac5b-f376-4cd1-af89-6c38098ed650.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzIxMDgsIm5iZiI6MTcxNTMzMTgwOCwicGF0aCI6Ii85NTEwODYvMzI4OTAwMTAzLWJhNTNhYzViLWYzNzYtNGNkMS1hZjg5LTZjMzgwOThlZDY1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwOTAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTkzNmI2ODIyYmVkYjVjN2Q2Y2RkNTZkYjczODY5NTk0MWNkZjYxNmI5MjJiMTVkMmZiMmU4ODkxYzkxM2M2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x3rFMdsHia_YS2yOqanjvbszDBNgXCX34xUa8M0OXYg)

Big thanks @leafty for reviewing the code! 🙌 I'll definitely bring up your point about the two clicks needed to remove or update the data source with Jimena. Maybe she can take it into account for the new redesign of Renku 2.0. For now, I think it's crucial to maintain consistency in how we interact with the session launcher and data sources in the side panel. Having uniform styles for those actions.

2024-05-10 10:11 UTC, leafty commented on client/src/features/projectsV2/api/storages.api-config.ts
This comment still stand:
1. The RTK query tag types need to be updated to `"Storage"` (see "Project", "Namespace" above)
2. The file name and the API name need to be updated t `storage-api` or similar ("The storage API").

2024-05-10 10:11 UTC, leafty commented on client/.eslintrc.json
> +          "storages",
Can be added.

2024-05-14 07:18 UTC, leafty approved these changes
LGTM 👏

2024-05-14 07:18 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/RepositoriesBox.tsx
> +            showMenu={true}
nitpick

```suggestion
            showMenu
```

2024-05-17 07:30 UTC, merged