feat: indicate repository permissions
SwissDataScienceCenter/renku-ui pull request #3136
Opened 2024-05-21 12:19 UTC by leafty

WIP

/deploy renku=release-0.52.x renku-data-services=leafty/build-add-connected-services-repo-permissions

2024-06-20 15:13 UTC, lorenzo-cavazzi requested changes
Nice feature! :rocket: 

The code looks good! I added a couple of inline comments, just minor changes to add a few more interactions to the UX.

P.S. Including minimal cypress tests to cover the new code would be great.

2024-06-20 15:13 UTC, lorenzo-cavazzi commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +              {provider.display_name}.
Same thing as above (link to connected-services)

2024-06-20 15:13 UTC, lorenzo-cavazzi commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +              repositories.
This sounds a little repetitive for anonymous users since we already say "You are not allowed to push on this repository."

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/c2d6534b-f420-41ed-bacb-508d748bd79d)

What about something like "You need to log in to perform pushes on git repositories" with a link to the log in page on the `log in` text?

2024-06-21 09:21 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +            <YesBadge />
I think I would like to make this change as part of a PR which improves the UX around GitHub using feedback from product. Using `https://github.com/apps/renkulab-io/installations/select_target` only works for `renkulab.io` and not other RenkuLab deployments.

2024-06-21 11:15 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +              {provider.display_name}.
Done in d5c628a76daa5b591d7d81c2396d6e3caf38f0a9.

2024-06-21 11:15 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +              {provider.display_name}.
Done in d5c628a76daa5b591d7d81c2396d6e3caf38f0a9.

2024-06-21 11:15 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +              repositories.
Done in d5c628a76daa5b591d7d81c2396d6e3caf38f0a9.

2024-06-24 07:27 UTC, lorenzo-cavazzi commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +            <YesBadge />
Fair point, although `renkulab.io` might already be enough for this beta phase and give a useful tip. Not a blocker for the PR.

Could you open an issue for the push problem (no need to mention this silly workaround) to work on that in a future cooldown phase? Thanks
P.S. Here is a screenshot to better visualize the issue if you want to include it
![Screenshot_20240620_155229](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/5b1e7343-527f-42ac-a778-478cf18015d6)

2024-06-24 07:28 UTC, lorenzo-cavazzi approved these changes
Great addition to the project page :rocket:

2024-06-24 07:32 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +            <YesBadge />
Here -> https://github.com/SwissDataScienceCenter/renku-ui/issues/3216

2024-06-24 09:01 UTC, merged