test(e2e): add project page tests
SwissDataScienceCenter/renku-ui pull request #3142
Opened 2024-05-24 08:56 UTC by andre-code

PR to add e2e project page test.

/deploy renku=release-0.52.x

2024-05-24 12:06 UTC, ciyer approved these changes
This is great! For the repository test, there is one that overlaps in https://github.com/SwissDataScienceCenter/renku-ui/pull/3118, and I think it would make sense to consolidate the tests here with those in the `projectsV2.spec.ts`, but I think those issues can be handled later -- having these tests would already be helpful.

2024-05-27 10:28 UTC, lorenzo-cavazzi requested changes
Great to have tests covering the latest features :raised_hands: 

I added a few inline comments, only minor improvements.

Good point from @ciyer .
It would be nice to either have a better distinction for content in the projectV2 and projectPageV2 files, or to have all the content in one single file.

2024-05-27 10:28 UTC, lorenzo-cavazzi commented on client/src/components/buttons/Button.tsx
> +        data-cy="plus-button"
This component already has another `data-cy` property. We could fall back to `"plus-button"` whenever `{dataCy}` isn't provided.

2024-05-27 10:28 UTC, lorenzo-cavazzi commented on client/src/features/sessionsV2/StartSessionButton.tsx
> +      data-cy="session-btn"
I would add `start` to avoid it being too generic.
Also, you used `-button` in most other properties except the sessions components; let's keep it consistent.

```suggestion
      data-cy="start-session-button"
```

2024-05-27 10:28 UTC, lorenzo-cavazzi commented on client/src/features/sessionsV2/UpdateSessionLauncherModal.tsx
> +          data-cy="edit-session-btn"
```suggestion
          data-cy="edit-session-button"
```

2024-05-27 10:28 UTC, lorenzo-cavazzi commented on client/src/features/sessionsV2/components/SessionModals/AddSession.tsx
> +            data-cy="add-launcher-custom-btn"
```suggestion
            data-cy="add-launcher-custom-button"
```

2024-05-27 10:28 UTC, lorenzo-cavazzi commented on client/src/features/sessionsV2/components/SessionModals/AddSession.tsx
> +          data-cy="add-session-launcher-btn"
```suggestion
          data-cy="add-session-launcher-button"
```

2024-05-27 10:28 UTC, lorenzo-cavazzi commented on tests/cypress/fixtures/cloudStorage/storage-schema-s3.json
Optional: this is a very long file. Since the tests only set up the `giab` storage, should we strip out parts of the response and keep only what is necessary?

2024-05-27 10:28 UTC, lorenzo-cavazzi commented on tests/cypress/support/renkulab-fixtures/newSession.ts
> +      const response = { fixture, delay: 2000, statusCode: 201 };
You added a bunch of `delay` in the responses. Any specific reason for that? If yes, please add an inline comment about why they should be delayed.
Otherwise, I suggest removing them. Mind that we have many local Cypress tests that execute quickly and still take 10 minutes in total. We don't  want to slow them down any further

2024-06-06 13:56 UTC, andre-code commented on tests/cypress/support/renkulab-fixtures/newSession.ts
> +      const response = { fixture, delay: 2000, statusCode: 201 };
no needed it anymore. So I removed it

2024-06-06 14:25 UTC, andre-code commented
> Great to have tests covering the latest features 🙌
> 
> I added a few inline comments, only minor improvements.
> 
> Good point from @ciyer . It would be nice to either have a better distinction for content in the projectV2 and projectPageV2 files, or to have all the content in one single file.

Good point. I renamed the file and moved the project info check to the projectV2 file to clarify the responsibility of the test in each file.

2024-06-07 13:30 UTC, ciyer requested changes
I think this is almost ready to merge! 

Only one question -- shouldn't `tests/cypress/e2e/projectV2setup.ts` be `tests/cypress/e2e/projectV2setup.spec.ts`

2024-06-07 13:48 UTC, ciyer approved these changes
LGTM! 🎉

2024-06-13 07:22 UTC, ciyer approved these changes
🎉

2024-06-13 07:26 UTC, merged