refactor(client): some migration step for `react-router@v6`
SwissDataScienceCenter/renku-ui pull request #3151
Opened 2024-05-28 12:38 UTC by leafty

Setup CompatRoute for some top-level routes.

Setup CompatRoute for:
* `/search`

See:
* #3028
* #3041

/deploy #notest renku=master

2024-05-29 12:18 UTC, lorenzo-cavazzi requested changes
Lgtm! Just need to drop an unused variable

2024-05-29 12:18 UTC, lorenzo-cavazzi commented on client/src/features/inactiveKgProjects/InactiveKgProjects.tsx
> +
```suggestion
```

2024-05-29 12:18 UTC, lorenzo-cavazzi commented on client/src/project/new/ProjectNew.test.jsx
Remove `const fakeLocation = { pathname: "" };`
P.S. I hate GitHub doesn't let me add suggestions since the code wasn't modified in the PR

2024-05-29 14:07 UTC, leafty commented on client/src/project/new/ProjectNew.test.jsx
Done in 33b342228c49453e9502b8e459e4cde1a1b4156a.

2024-05-30 11:08 UTC, lorenzo-cavazzi approved these changes

2024-05-30 11:29 UTC, merged