Convert font-awesome icons to bootstrap icons
SwissDataScienceCenter/renku-ui pull request #3173
Opened 2024-06-03 08:26 UTC by ciyer

* refactor: remove unused components

/deploy

2024-06-03 11:29 UTC, leafty reviewed
Thanks for the fix.

I think that we agreed that we should pick the `"fill"` variants of icons when they are available:
* `FileEarmark` -> `FileEarmarkFill`
* `Diagram2` -> `Diagram2Fill`

(@lorenzo-cavazzi for the fill icons)

2024-06-03 11:29 UTC, leafty commented on client/src/components/Avatar.jsx
praise: nice! 👏

2024-06-03 11:30 UTC, leafty commented on client/src/components/FileExplorer.tsx
> +        <FolderFill className="link-primary" />
In almost all cases, bootstrap icons need to have the `"bi"` (bootstrap icon) class added so that they align with the surrounding text.

Without `bi`:
![Screenshot 2024-06-03 at 13 25 59](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/f5ff26e9-1935-4341-a600-995b80e14a06)

WIth `bi`:
![Screenshot 2024-06-03 at 13 25 54](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/60205302-f769-464a-9997-1459daf954b2)

Here and everywhere else:
```suggestion
        <FolderFill className={cx("bi", "link-primary")} />
```

2024-06-03 13:56 UTC, leafty requested changes
This should be good to go after switching to filled icons and fixing the `"bi"` class name. :rocket:

2024-06-04 11:14 UTC, ciyer commented
> I think that we agreed that we should pick the `"fill"` variants of icons when they are available:
> 
> * `FileEarmark` -> `FileEarmarkFill`
> * `Diagram2` -> `Diagram2Fill`

Resolved in 06878da8797b1e8e1c3623bc55fd7c2daa931d32

2024-06-04 11:19 UTC, leafty approved these changes
Great, thanks!

2024-06-04 13:38 UTC, merged