docs: update contribution guidelines
SwissDataScienceCenter/renku-ui pull request #3186
Opened 2024-06-06 13:24 UTC by lorenzo-cavazzi

From our offline discussion earlier today:

* Refresh the Contribute section in the Readme file to include details on commits and releases.
* Deprecate the Changelog file and point to the GitHub Releases page instead.

2024-06-06 14:26 UTC, leafty requested changes
Thanks! Some comments below.

2024-06-06 14:26 UTC, leafty commented on README.md
> +sense to do so. In that case, you can rebase the commits in the PR before merging.
> You should still keep separate commits whenever it makes
sense to do so. In that case, you can rebase the commits in the PR before merging.

I don't really see a case for this. If a PR is too large, it should be split into logical parts. A PR should be of one type only (e.g. feat, fix, refactor, etc.).

2024-06-06 14:26 UTC, leafty commented on README.md
> +- If the release includes only bug fixes or minor changes (i.e. no `feat` nor `perf`
why `perf`? `perf` should not affect features

2024-06-19 07:53 UTC, lorenzo-cavazzi commented on README.md
> +- If the release includes only bug fixes or minor changes (i.e. no `feat` nor `perf`
You are right, I removed `perf`

2024-06-19 07:57 UTC, lorenzo-cavazzi commented on README.md
> +sense to do so. In that case, you can rebase the commits in the PR before merging.
That's useful in some cases -- E.G. feature branches adding incremental changes.
It's not that common tho; I rephrased the sentence to make it more obvious it's an exception and having multiple PRs is best when commits are logically separate.

2024-06-19 07:59 UTC, leafty approved these changes

2024-06-19 08:16 UTC, merged