feat: add user and group pages in Renku 2.0
SwissDataScienceCenter/renku-ui pull request #3198
Opened 2024-06-10 12:15 UTC by leafty

Closes #3197.

Feature branch.

WIP.

2024-07-08 18:51 UTC, ciyer requested changes
This looks very good! 🎉 I have a few minor wording suggestions and a question about a change (or lack thereof) in the e2e test data, but that is all.

2024-07-08 18:51 UTC, ciyer commented on tests/cypress/fixtures/projectV2/update-projectV2-one-repository.json
> +  "namespace": "user1-uuid",
**question** is this the right value after the changes that have been made (since the id was changed elsewhere).

2024-07-08 18:51 UTC, ciyer commented on client/src/features/projectsV2/list/ProjectV2List.tsx
> +        emptyListElement={<p>There is no visible project.</p>}
```suggestion
        emptyListElement={<p>There are no visible projects.</p>}
```

2024-07-08 18:51 UTC, ciyer commented on client/src/features/groupsV2/show/GroupV2Show.tsx
> +            <p>The group {group.name} has no visible project.</p>
**suggestion** This is a good idea, but in practice, might not work out well depending on the name of the group. In the screenshot, it took me a minute to understand what this message was communicating.

<img width="611" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/1196411/eb1ea244-43bd-42d8-b71b-4b112ac9d471">

I think something simpler would be easier to understand:

```suggestion
            <p>No visible projects.</p>
```

2024-07-08 18:51 UTC, ciyer commented on client/src/features/usersV2/show/UserShow.tsx
> +            <p>{name ?? username} has no visible personal project.</p>
```suggestion
            <p>{name ?? username} has no visible personal projects.</p>
```

2024-07-09 08:53 UTC, leafty commented on tests/cypress/fixtures/projectV2/update-projectV2-one-repository.json
> +  "namespace": "user1-uuid",
Yes, this one is correct here, this fixture is used in a test adding a repo to a project and this is the correct namespace.

2024-07-09 14:09 UTC, ciyer approved these changes
🎉

2024-07-10 07:31 UTC, merged