Design changes for Renku 2.0
SwissDataScienceCenter/renku-ui pull request #3214
Opened 2024-06-19 15:04 UTC by lorenzo-cavazzi

WIP - design changes

[Notion page reference](https://www.notion.so/renku/Renku-2-0-Identity-UI-Library-Pitch-8dae80a9a7684767ab5424b6f58dbd4d?pvs=31)

/deploy

2024-07-22 09:47 UTC, leafty reviewed
Some early comments about bootstrap icons and overrides.

2024-07-22 09:47 UTC, leafty commented on client/src/styles/renku_bootstrap_customization.scss
> +}
Use `$headings-font-weight: 600;` instead.

2024-07-22 09:47 UTC, leafty commented on client/src/styles/renku_bootstrap_customization.scss
> +}
Do not override the default behavior! Create a new class, e.g. `.list-group-item-action-extended` for which the styles apply. As is, this breaks the behavior of regular flush list groups!

2024-07-22 09:47 UTC, leafty commented on client/src/styles/renku_bootstrap_customization.scss
> +}
Same comment here, do not override the default bootstrap behavior! This will most likely break standard bootstrap components.

2024-07-22 13:34 UTC, leafty reviewed
More comments.

2024-07-22 13:34 UTC, leafty commented on client/src/components/ExternalLinks.tsx
Note: we should probably deprecate this component and use a simpler one (with the icon always on the right and idiomatic props).

2024-07-22 13:34 UTC, leafty commented on client/src/components/Logs.tsx
> +      <div className="text-nowrap mb-3">
```suggestion
      <div className={cx("text-nowrap","mb-3")}>
```

2024-07-22 13:34 UTC, leafty commented on client/src/components/Logs.tsx
> +      <FileEarmarkArrowDown className={cx("me-2", "text-icon")} />
We should settle on `me-1` and `ms-1` for icons. This will make it consistent across all uses of icons next to text.

```suggestion
      <FileEarmarkArrowDown className={cx("me-1", "text-icon")} />
```

2024-07-22 13:34 UTC, leafty commented on client/src/components/Logs.tsx
> +                  style={{ whiteSpace: "pre-line" }}
What is the reason for the `pre-line` styling? Log contents should not be changed for presentation.

2024-07-22 13:34 UTC, leafty commented on client/src/components/Logs.tsx
> +          <ArrowRepeat className={cx("me-2", "text-icon")} /> Refresh logs
```suggestion
          <ArrowRepeat className={cx("me-1", "text-icon")} />Refresh logs
```

2024-07-22 13:34 UTC, leafty commented on client/src/components/Logs.tsx
> +      className="modal-dynamic-width"
Note: `.modal-dynamic-width` should be deprecated.

2024-07-22 13:34 UTC, leafty commented on client/src/components/buttons/Button.tsx
> +  children?:
??? `ReactNode` should be sufficient.

2024-07-22 13:34 UTC, leafty commented on client/src/components/buttons/Button.tsx
> +  preventPropagation?: boolean;
This prop should not be needed (if it is, the code is buggy).

2024-07-22 13:34 UTC, leafty commented on client/src/components/buttons/Button.tsx
> +type BButtonWithMenuV2Props = {
```suggestion
interface ButtonWithMenuV2Props {
```

2024-07-22 13:34 UTC, leafty commented on client/src/components/buttons/Button.tsx
> +export function ButtonWithMenuV2(props: BButtonWithMenuV2Props) {
Prefer `props` deconstruction (and potentially, default assignments too) here.

2024-07-22 13:34 UTC, leafty commented on client/src/error-boundary/ErrorBoundary.tsx
> +      <style type="text/css">{v2Styles}</style>
Remove this line, use `Helmet` for this. Also, this probably breaks styles until reload, so I would NOT use it at all.

2024-07-22 13:34 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourcesBox.tsx
> +              <Database className={cx("me-2", "small", "text-icon")} />
Note: `small` does not do anything when combined with `text-icon` or `bi`.

2024-07-22 14:10 UTC, lorenzo-cavazzi commented on client/public/static/public/img/logo-yellow.svg
Good catch! I'm not sure how it ended up being committed. I'll revert it

2024-07-22 14:10 UTC, lorenzo-cavazzi commented on client/src/styles/renku_bootstrap_customization.scss
> +@import "~bootstrap/scss/variables-dark";
Bootstrap suggests adding imports in a specific order to simplify overwriting variables ([reference](https://getbootstrap.com/docs/5.3/customize/sass/)).
E.G. if you import the variables before changing the `$primary` color, it won't be picked by all components ([reference](https://getbootstrap.com/docs/5.3/customize/sass/#variable-defaults)).

2024-07-22 14:17 UTC, lorenzo-cavazzi commented on client/src/styles/renku_bootstrap_customization.scss
I see your point. Otoh, if we keep them in one place, it helps not to lose track of the changes targeting a single component.

E.G. for the Nav Tabs, not all the desired customization can be done through the Bootstrap variables. I used variables wherever possible and modified the bottom border by overwriting the classes. Having the following block in one place...

```
// Adjust nav tabs
$nav-tabs-link-active-bg: transparent;
$nav-tabs-link-hover-border-color: transparent;
$nav-tabs-link-active-color: $primary;
$nav-link-color: $body-color;
$nav-link-transition: none;
.nav-tabs .nav-link {
  border: 0 !important;
  border-bottom: 2px solid transparent !important;
}
.nav-tabs .nav-link.active {
  border-bottom: 2px solid $nav-tabs-link-active-color !important;
}
```

... seems better than having it scattered into different files.

What do you think?

2024-07-22 14:19 UTC, leafty commented on client/src/styles/renku_bootstrap_customization.scss
> +@import "~bootstrap/scss/variables-dark";
In that case we should follow the docs:
```
// 1. Include functions first (so you can manipulate colors, SVGs, calc, etc)
@import "../node_modules/bootstrap/scss/functions";

// 2. Include any default variable overrides here

// 3. Include remainder of required Bootstrap stylesheets (including any separate color mode stylesheets)
@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/variables-dark";

// 4. Include any default map overrides here
```

So `functions` import at the top, then variable definitions, then `variables, variables-dark` imports, then map overrides.

2024-07-22 14:30 UTC, lorenzo-cavazzi commented on client/src/styles/renku_additional_classes.scss
> +}
> Why introduce a new class?

You mean, why `text-icon` instead of `bi`? I'm having difficulty finding the exact reference, but while reading through the customization guidelines, I read it's best to qualify the names following the other Bootstrap classes. Since there are many `text-*` classes to position the text, I think following the same approach might be good and easier to remember than `bi`.

> Why is the code not including `fill: currentcolor;`?

The icons from Bootstrap Icons already pick the fill color correctly without forcing that property. We dropped most of the custom icons using `fill` improperly; for the ones using it, we very likely do not want to override the color (E.G. the green frog with yellow eyes)

> Utility classes should NOT restrict the tag they apply to

That's a good point! I'll remove it

2024-07-22 14:34 UTC, lorenzo-cavazzi commented on client/src/styles/renku_bootstrap_customization.scss
> +}
That changes _all_ headers.
It would be best to keep the consistency, but there was a lengthy discussion with the design team about the specific sizing of the card header elements and I hope not to have it again -- this feels like a relatively minor deviation anyway

2024-07-22 14:40 UTC, lorenzo-cavazzi commented on client/src/styles/renku_bootstrap_customization.scss
> +}
Could you expand on this? Why is this broken?

We should not use a different on-hover style for flush style list groups. I don't understand why adding a new class instead of overriding is best here, but I'm open to a longer explanation.

2024-07-22 14:42 UTC, lorenzo-cavazzi commented on client/src/styles/renku_bootstrap_customization.scss
> +}
We use extensively the flush variation of the group item list element. It would be great to have the possibility to change padding only for the flush variation, but we can't. What's wrong with overriding the classes here?

2024-07-22 14:50 UTC, lorenzo-cavazzi commented on client/src/components/Alert.jsx
Yeah, we should do that. Do you mind if I do that in separate PR?

2024-07-22 14:53 UTC, leafty commented on client/src/styles/renku_bootstrap_customization.scss
> +}
This is what happens when a standard `list-group-flush` is used:
![Screenshot 2024-07-22 at 16 51 37](https://github.com/user-attachments/assets/9771b864-c35d-4829-8aec-469b408abd5d)

As you can see, the styling from the cards used in the Dashboard pollute the global scope for flush lists. A specific SCSS module for list groups inside cards should be created to avoid polluting the global scope.

2024-07-22 14:56 UTC, lorenzo-cavazzi commented on client/src/components/Logs.tsx
> +      <FileEarmarkArrowDown className={cx("me-2", "text-icon")} />
I actually changed all the occurrences I found in 2.0 components to `me-2` or `ms-2` for consistency :facepalm: 
I'm not sure which looks best -- `2` feels better on headers and `1` on buttons or links.
I'm ok with both solutions, but changing it to `1` is quite some work. Should we quickly touch base with the whole team in the next standup and do it in the next round? I also have a different proposal to prevent accidentally showing additional margins on smaller window widths.

2024-07-22 14:59 UTC, lorenzo-cavazzi commented on client/src/components/Logs.tsx
> +                  style={{ whiteSpace: "pre-line" }}
I agree with you. In this specific case, I just re-applied the relevant style from all the classes I dropped. Removing it resulted in much harder-to-read content.

2024-07-22 15:10 UTC, lorenzo-cavazzi commented on client/src/components/buttons/Button.tsx
> +  preventPropagation?: boolean;
We use that for quick actions on the group list elements we have in many places (projects, sessions, groups, data sources, ...). The whole item is a link to a location. Still, the quick-action button offers a way to do something else (E.G. opening a session or stopping it without going to the corresponding project page and opening the session details).

This seems reasonable to me, but I'm open to different solutions

![image](https://github.com/user-attachments/assets/3a01b065-2d2b-494b-aaba-38fa5a764749)

2024-07-22 15:15 UTC, lorenzo-cavazzi commented on client/src/error-boundary/ErrorBoundary.tsx
> +      <style type="text/css">{v2Styles}</style>
That's a good suggestion! Done.
I agree it's not the cleanest solution, but we will drop the old v1 styling in the (not so near :unamused: ) future. Do you have any suggestions for alternative ways of having the two styles co-exist?

2024-07-22 15:18 UTC, lorenzo-cavazzi commented on client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourcesBox.tsx
> +              <Database className={cx("me-2", "small", "text-icon")} />
`small` changes the font size; it seems effective here.
The design team felt the icons were too big on the card headers on the project page

![image](https://github.com/user-attachments/assets/cedb3892-4a77-4cfc-b66a-e62bae7da7cd)

2024-07-22 15:26 UTC, lorenzo-cavazzi commented on client/src/styles/renku_bootstrap_customization.scss
> +}
I see. I reasoned that the flush variation is made _specifically_ for working with parent components ([Bootstrap docs](https://getbootstrap.com/docs/5.3/components/list-group/#flush)); it looks visually off anyway when used anywhere else.

But I see how polluting the global scope is bad and playing with negative margins is a double-edged sword (note that Bootstrap itself uses that mechanism for rows/columns).
If you feel the current solution isn't acceptable, I can make another class as in your previous suggestion

2024-07-22 15:40 UTC, lorenzo-cavazzi commented
@leafty Thank you for the review! For every suggestion, I either applied it or added questions/considerations inline.

2024-07-23 11:15 UTC, lorenzo-cavazzi commented on client/src/components/buttons/Button.tsx
> +  preventPropagation?: boolean;
As we discussed offline, we should address this as soon as possible.
I made a separate issue for making a component that simplifies avoiding nesting without forcing re-implementing ad-hoc solutions
https://github.com/SwissDataScienceCenter/renku-ui/issues/3250

2024-07-23 11:27 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourcesBox.tsx
> +              <Database className={cx("me-2", "small", "text-icon")} />
OK, I see.

So some design notes here:
1. The icons are designed to be `1em` when used next to text content (that is being the same size as the surrounding text). Breaking this rule breaks vertical alignment of the icons. In the project page the icons are not nicely aligned with the section titles because of this. I suggest we remove the `small` CSS class. It should not be used for icons.
2. The `h4` title here and elsewhere should not be flex elements (because that doesn't change alignment).

```tsx
<h4 className={cx("mb-0", "me-2")}>
```

2024-07-23 11:56 UTC, lorenzo-cavazzi commented on client/src/styles/renku_additional_classes.scss
> +}
After the offline discussion, I removed `text-icon` as suggested.

P.S. Mind that I still haven't added `fill: currentcolor` since it's already embedded in the bootstrap icons.

2024-07-23 11:59 UTC, lorenzo-cavazzi commented on client/src/components/Logs.tsx
> +      <FileEarmarkArrowDown className={cx("me-2", "text-icon")} />
I changed it to always use a space of `1` to maintain consistency everywhere.
I think using whitespaces would be best, but I don't want to include that here -- we can discuss it and see if it makes sense to create a separate issue

2024-07-23 11:59 UTC, leafty commented on client/src/components/Alert.jsx
> +      success: <CheckCircleFill className={cx(bi, "text-success")} />,
```suggestion
      danger: <ExclamationTriangleFill className={cx("bi", "text-danger")} />,
      info: <InfoCircleFill className={cx("bi", "text-info")} />,
      warning: <ExclamationTriangleFill className={cx("bi", "text-warning")} />,
      success: <CheckCircleFill className={cx("bi", "text-success")} />,
```

2024-07-23 12:05 UTC, lorenzo-cavazzi commented on client/src/components/Alert.jsx
> +      success: <CheckCircleFill className={cx(bi, "text-success")} />,
:pray:

2024-07-23 14:22 UTC, lorenzo-cavazzi commented on client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourcesBox.tsx
> +              <Database className={cx("me-2", "small", "text-icon")} />
1. I see your point; there was a somewhat lengthy discussion with the design team about this, but the alignment looks a little off. I have removed the `small` modifier and I will run this through the design team again :crossed_fingers: 
2. Done

2024-07-23 14:26 UTC, leafty reviewed
Some comments.

Progress: 34/141 files viewed.

2024-07-23 14:26 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +  // );
Why is this removed? Can't it work as is?

2024-07-23 14:26 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +    <CircleFill className={cx("me-1", "bi")} />
Remove all the ternaries here.

2024-07-23 14:26 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +    <Loader className="me-1" inline size={16} />
Should the size be smaller here? This should correspond to the font size.

2024-07-23 14:26 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +    ? ""
```suggestion
    ? null
```

(see below)

2024-07-23 14:26 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +      <span className="fw-normal">{badgeText}</span>
Avoid rendering empty nodes:

```suggestion
      {badgeText && (<span className="fw-normal">{badgeText}</span>)}
```

2024-07-23 14:26 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +  const canonicalUrl = useMemo(() => {
Use the `safeNewUrl` method instead.

```tsx
const canonicalUrl = useMemo(
    () => safeNewUrl(canonicalUrlStr),
    [canonicalUrlStr]
  );
```

2024-07-23 14:26 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourceDisplay.tsx
> +  ) : null;
Avoid rendering the space `" "` when this is `null`:

```suggestion
  const storageType = storageSensitive?.storage_type ? (
    <>
      {" "}
      <span className="fst-italic" data-cy="data-storage-type">
        (type: {storageSensitive.storage_type})
      </span>
    </>
  ) : null;
```

2024-07-23 14:26 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourceDisplay.tsx
> +              {storageName} {storageType}
```suggestion
              {storageName}{storageType}
```

2024-07-23 14:32 UTC, leafty commented on client/src/styles/renku_bootstrap_customization.scss
> +}
These adjustments make the flush list work only inside components which use `x` padding with a value of `$spacer`. Other values (e.g. `mx-4`) would also break.

For this reason, I think we could restrict these changes to the flush list to be only for flush lists found inside cards.

2024-07-23 14:35 UTC, lorenzo-cavazzi commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +  // );
Product/design teams discussed a common solution for showing the source of both code repositories and data sources in a similar way. This (or some variation) will be back in the next PR further changing the design.

2024-07-23 14:39 UTC, lorenzo-cavazzi commented on client/src/features/ProjectPageV2/ProjectPageContent/CodeRepositories/CodeRepositoryDisplay.tsx
> +    <Loader className="me-1" inline size={16} />
Ah yes! It should be `12` in the badges. Good catch!

2024-07-24 07:27 UTC, leafty reviewed
More comments.

Progress: 85/143 files viewed.

2024-07-24 07:27 UTC, leafty commented on client/src/features/projectsV2/fields/AddEntityMemberLookupForm.tsx
> +        >
Why assign an `onClick` if this button is disabled?

2024-07-24 07:27 UTC, leafty commented on client/src/features/projectsV2/fields/ProjectVisibilityFormField.tsx
> +                Private <Lock className="bi" />
```suggestion
                Private
                <Lock className={cx("bi", "ms-1")} />
```

Also, why is the icon after the text? Usual placement is before the text for most icons.

2024-07-24 07:27 UTC, leafty commented on client/src/features/projectsV2/list/ProjectV2ListDisplay.tsx
> +              }}
We should define re-usable classes or components for this.

2024-07-24 07:27 UTC, leafty commented on client/src/features/projectsV2/new/ProjectV2FormSubmitGroup.tsx
> +            Set visibility <ArrowRight />
```suggestion
            Set visibility
            <ArrowRight classname="ms-1" />
```

2024-07-24 07:27 UTC, leafty commented on client/src/features/projectsV2/new/ProjectV2New.tsx
> +        access them. <WipBadge />
```suggestion
        access them.<WipBadge classname="ms-1" />
```

2024-07-24 07:27 UTC, leafty commented on client/src/features/projectsV2/new/ProjectV2NewForm.tsx
> +            <PlusLg className="bi" /> Add repository
```suggestion
            <PlusLg className={cx("bi", "me-1")} />Add repository
```

2024-07-24 07:27 UTC, leafty commented on client/src/features/projectsV2/show/GroupSimple.types.tsx
> +export type GroupSimple = {
Why does this type exist? Can't we use something generated from the API?

2024-07-24 07:27 UTC, leafty commented on client/src/features/projectsV2/show/GroupSimple.tsx
> +export default function GroupSimple({
Invalid component name. It cannot use the same name as the type.

2024-07-24 07:27 UTC, leafty commented on client/src/features/projectsV2/show/GroupSimple.tsx
> +  className?: string | string[];
Only string here for convention.
```suggestion
  className?: string;
```

2024-07-24 07:27 UTC, leafty commented on client/src/features/projectsV2/show/GroupSimple.tsx
> +      )}
Do not nest `cx` calls!

```suggestion
      className={cx(
        element === "card-body" && ["d-flex", "flex-column", "flex-grow-1"]
      )}
```

2024-07-24 07:27 UTC, leafty commented on client/src/features/projectsV2/show/GroupSimple.tsx
> +      : "";
Do not nest `cx` call here too.

```suggestion
  const elementClasses =
    element === "card-body"
      ? ["card-body", "d-flex"]
      : element === "list-item"
      ? ["list-group-item", "list-group-item-action"]
      : [];
```

2024-07-24 07:27 UTC, leafty commented on client/src/features/projectsV2/show/ProjectSimple.tsx
> +export default function ProjectSimple({
The name is a bit confusing. Where is this component supposed to be used? Prefer `ProjectShortHandDisplay` or `ProjectDisplaySmall` or similar.

2024-07-24 07:27 UTC, leafty commented on client/src/features/searchV2/components/SearchV2Results.tsx
> +  entityType?: "Project" | "Group" | "User";
This should be imported from the search API, not hard-coded.

2024-07-24 07:27 UTC, leafty commented on client/src/features/searchV2/components/SearchV2Results.tsx
> +  nameUrl: string;
```suggestion
  entityUrl: string;
```

as it is more informative.

2024-07-24 08:42 UTC, leafty reviewed
More comments.

Progress: 121/143 files viewed.

2024-07-24 08:42 UTC, leafty commented on client/src/features/sessionsV2/SessionLauncherForm.module.scss
> +// }
Leftover?

2024-07-24 08:42 UTC, leafty commented on client/src/features/sessionsV2/SessionList/SessionItem.tsx
> +      onClick={() => toggleSessionDetails()}
```suggestion
      onClick={toggleSessionDetails}
```

2024-07-24 08:42 UTC, leafty commented on client/src/features/sessionsV2/SessionView/SessionView.tsx
> +  contentDescription: React.ReactNode;
I prefer:

```suggestion
  contentDescription: ReactNode;
```

It's shorter and forces to import from `react`, instead of relying on an ambient import.

2024-07-24 08:42 UTC, leafty commented on client/src/features/usersV2/show/UserShow.tsx
> +        <h4>Personal Projects</h4>
Note: this should probably still be an `h2`. Semantically, it's better to avoid gaps in `hx` uses in a web page.

2024-07-24 11:46 UTC, leafty commented on tests/cypress/e2e/dashboard.spec.ts
> +  // // });
?

2024-07-24 11:46 UTC, leafty commented on client/src/storybook/bootstrap/Accordion.stories.tsx
Do we use Accordion?

2024-07-24 12:25 UTC, lorenzo-cavazzi commented on client/src/features/projectsV2/fields/ProjectVisibilityFormField.tsx
> +                Private <Lock className="bi" />
Fair point. Swapped and adjusted for both the Private and Public options

2024-07-24 12:40 UTC, lorenzo-cavazzi commented on client/src/features/projectsV2/list/ProjectV2ListDisplay.tsx
> +              }}
Good idea. Added here https://github.com/SwissDataScienceCenter/renku-ui/pull/3214/commits/14ba91b22919d9c30234e0ca755cbc2a2e6d81fe

2024-07-24 13:09 UTC, lorenzo-cavazzi commented on client/src/features/usersV2/show/UserShow.tsx
> +        <h4>Personal Projects</h4>
That's an interesting point. We ended up mainly using h2, h4 and h5. I'm wondering if we should adjust the default header sizing instead to let developers pick headers more intuitively.

2024-07-24 13:15 UTC, leafty commented on client/src/components/Logs.tsx
> +                  style={{ whiteSpace: "pre-line" }}
Tested: just use the `text-wrap` class from bootstrap to enable text wrapping in the `<pre>` tag.

2024-07-24 13:34 UTC, lorenzo-cavazzi commented on client/src/components/Logs.tsx
> +                  style={{ whiteSpace: "pre-line" }}
`text-wrap` seems to have a very different effect. Comper `white-space: pre-line` on the left with `text-wrap` on the right.

![image](https://github.com/user-attachments/assets/4bab677a-d732-45b0-a17b-f92462f140b5)

The best thing would be to improve the backend response; currently, it returns a very long string.
Since `white-space: pre-line` seems to work well enough as a workaround, I would leave this as is since the scope of this redesign effort is already quite broad.

2024-07-25 12:13 UTC, andre-code reviewed
Great to see those changes in place. I appreciate the tremendous effort put into redesigning the app. This is a big PR with many things to consider, and so far, the results are amazing 🤩 👏 💪. Along with the minor comments I've left in the code, I found a few additional issues that would be great to address here or in the next phase of the redesign:

1. Missing top padding in the "Add Data Source" confirmation modal and the "Remove Code Repository" modal.
![Screenshot 2024-07-25 at 09 23 07](https://github.com/user-attachments/assets/1d481b80-cadb-4795-ad84-db2d45310d98)
![Screenshot 2024-07-25 at 09 24 27](https://github.com/user-attachments/assets/c6e3f6d5-609d-4441-aa4d-c7f8cbe7d61a)

2. The text buttons combine uppercase and lowercase words. Please standardize them so only the first letter is uppercase.

![Screenshot 2024-07-25 at 09 25 14](https://github.com/user-attachments/assets/2ea8f8c9-d0bc-46d6-80b9-12a30b11bd04)


3. Consider adjusting the off-canvas size for the session view. This off-canvas displays a lot of information, and the reduced size makes it look disorganized and overwhelming.

![Screenshot 2024-07-25 at 09 26 04](https://github.com/user-attachments/assets/e6b6233d-0033-44a2-8927-6847474cc742)

4. In the session off-canvas, consider including the code repository permission information, as the badge alone is not enough to understand the status.
![Screenshot 2024-07-25 at 09 26 49](https://github.com/user-attachments/assets/100d72b1-b926-45c5-82e6-b0c552fc217d)


5. Why does this menu have a dark background?
![Screenshot 2024-07-25 at 09 27 40](https://github.com/user-attachments/assets/d5923f2e-97b1-4f32-b0d1-93e351d4a344)


6. Consider redesigning this; it doesn't look right to display a card inside this list.
![Screenshot 2024-07-25 at 10 36 15](https://github.com/user-attachments/assets/9aa9aed9-be75-4adc-ba6c-4825a1f5bff1)


7. This modal shows a lot of information. Consider using shorter texts and making the buttons larger to avoid overwhelming the user when selecting an option. Using button-lg makes a big difference.
![Screenshot 2024-07-25 at 11 15 38](https://github.com/user-attachments/assets/50194928-5f5b-41df-ac15-9b07bdff8bd6)
![Screenshot 2024-07-25 at 11 15 23](https://github.com/user-attachments/assets/f201b907-26ea-4de8-956a-8d238366adeb)


8. Don’t forget to standardize the use of the user avatar on all pages where the user name is included.
![Screenshot 2024-07-25 at 11 16 43](https://github.com/user-attachments/assets/01db578a-b794-4e64-b0d2-7c5ff1ccf34f)


9. I mentioned this in a previous meeting, but as a reminder, please redesign the filter form. Using cards as the result format so far doesn’t help differentiate one component from another.
![Screenshot 2024-07-25 at 11 17 08](https://github.com/user-attachments/assets/f5779cd5-6e48-4efc-b6bc-63012722201a)


10. The buttons here are not using the primary and outline buttons as the rest of the app does.
![Screenshot 2024-07-25 at 11 22 13](https://github.com/user-attachments/assets/88614590-631f-4617-8eb2-26f71910f353)

![Screenshot 2024-07-25 at 11 22 26](https://github.com/user-attachments/assets/97ee480f-4951-46ce-882c-7f7044edf1f9)


11. Consider removing or moving inside the card the short text "You are currently starting a session...", "You are currently running a session...", "No session is running from...". This text explains the current session status, but being placed just below the title can be mistaken for a label.
![Screenshot 2024-07-25 at 13 09 46](https://github.com/user-attachments/assets/be5c0cb4-ed37-4322-91ba-64a2b51a6201)

![Screenshot 2024-07-25 at 13 09 55](https://github.com/user-attachments/assets/df7dacc6-f213-4500-a38d-a9bb263305cc)
![Screenshot 2024-07-25 at 13 10 03](https://github.com/user-attachments/assets/7409282f-1687-479a-af00-c96e7014c6a9)

2024-07-25 14:39 UTC, lorenzo-cavazzi commented on client/src/components/ExternalLinks.tsx
Good point!
Here is an issue for doing that -- feel free to add to it https://github.com/SwissDataScienceCenter/renku-ui/issues/3255

2024-07-25 14:46 UTC, lorenzo-cavazzi commented on client/src/features/usersV2/show/UserShow.tsx
> +        <h4>Personal Projects</h4>
Here is the issue for that https://github.com/SwissDataScienceCenter/renku-ui/issues/3256
I'll be sure to address it in the 2nd round of the design changes

2024-07-29 09:45 UTC, lorenzo-cavazzi commented on client/src/components/entities/VisibilityIcon.tsx
> +          "card-visibility-icon",
In places where we use v1 components for v2 content, I've left the v1 classes wherever useful for the v1 pages since they do not affect v2 pages. I would keep it consistent if you don't mind (most v1 components don't actually support `className`).

2024-07-29 09:47 UTC, lorenzo-cavazzi commented on client/src/components/Alert.jsx
> +      danger: <ExclamationTriangleFill className={cx("bi", "text-danger")} />,
That's a good point! I'll bring this up with the designer since this changes the visualization quite a lot when it comes to alerts.

2024-07-29 09:54 UTC, lorenzo-cavazzi commented
@andre-code thank you for your review!

For all your comments, I've either 1) addressed it or 2) added it to the second round of design changes or 3) added an inline comment (below this message for non-inline comments). Please give it a look.

--------

1, 2: Done

3. > Consider adjusting the off-canvas size for the session view [...]

Currently, all the off-canvas elements have the same width. Making it larger for sessions won't help much -- we have a lot of vertical content, but expanding horizontally won't fit more elements and users will need to scroll anyway. For this reason, I prefer to keep it consistent with all the other off-canvas. We can revise this later if we wish to re-think how we display the content there.

4. > In the session off-canvas, consider including the code repository permission information [...]

The space there seems a little limited to add more info. We could think about opening the Code repositories off-canvas on click. If we do that, we should add the same interaction for the other elements on the page (data source, launcher, ...). I would rather discuss this change with the product team since it will require a bit of work.

5: That's planned for the second round of design changes.

6, 7, 8, 9: Good point! I'll check into those with Jimena during the second round of design changes. Thank you for bringing those up!

10. Done

11. I would rather rework both the "Launched Sessions" and "Session Environment" sections separately; I agree the current output might be a little confusing to the users, but the restyle PR might not be the best place to change the content there.

2024-07-29 14:07 UTC, leafty requested changes
Some thing I noted from the deployment:

1. The icon used in the new Alert components should be aligned to the top. If the content of the alert is large, then the icon floats too much in the middle
![Screenshot 2024-07-29 at 16 00 53](https://github.com/user-attachments/assets/eaf499ec-03b8-4d15-982c-4c2c064826a1)
![Screenshot 2024-07-29 at 15 59 59](https://github.com/user-attachments/assets/c45023bd-6b3d-4ec6-a463-8a6bd7475372)

2. The small avatar should be used for project members:
![Screenshot 2024-07-29 at 16 04 13](https://github.com/user-attachments/assets/5d4c57bf-2ec8-4166-8f50-63037ab08971)


Otherwise the changes look good, and any more adjustment can be done later.

2024-07-29 15:40 UTC, lorenzo-cavazzi commented
@leafty 
For the avatar, there was a discussion and we postponed the decision to the second iteration. I think we should leave this as is since we will address it soon; the alternative would be temporarily removing the avatar also from the other places.

For the alerts, we considered that the content is unlikely to be very long. In principle, I agree with your comment and I will bring this up again, but I would rather address this later since the topic has been discussed already and there are a few other details we would like to address for the alerts (E.G. using non-filled icons and match the color we use for the text)

2024-07-30 08:54 UTC, leafty approved these changes

2024-07-30 09:05 UTC, merged