Allow remembering storage credentials as secrets
SwissDataScienceCenter/renku-ui pull request #3224
Opened 2024-06-27 00:41 UTC by ciyer

2024-07-04 20:03 UTC, andre-code requested changes
Great to see the code in action! It's mostly looking good, but a few issues need addressing:

- Adding a new general secret key doesn't work; it errors out asking for the kind of secret.
<img width="493" alt="Screenshot 2024-07-04 at 21 59 50" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/4dc1e60f-f0cf-4ef9-b1bd-d495bd5061a2">
- When launching a session with more than 1 data sources, it only send in the `cloudstorage` array the last data source in the list.
- UX Issue: If a data source has multiple secret keys, and some are already stored, it still asks for all keys again. It should only request the missing keys. What do you think?
- UX Issue: When launching a session with multiple data sources, the "continue" or "skip" functionality isn't clear. Will it skip the problematic data source or try to use it anyway? Adding a clarification to the message like "The data source could not be mounted. Please retry with different credentials, or skip." might help.

✨ It'd be great if the data source view showed which credentials already have a secret value stored and linked to the secret page if accessible. This helps users know where to find and manage them. Makes sense? I see there's already an endpoint to check that 🙂

2024-07-05 19:16 UTC, ciyer commented
> Great to see the code in action! It's mostly looking good, but a few issues need addressing:
> 
> * Adding a new general secret key doesn't work; it errors out asking for the kind of secret.

Good catch! I have fixed this in 940a4c77d656755ae71f8cb4801232a7e9142c67.

> * When launching a session with more than 1 data sources, it only send in the `cloudstorage` array the last data source in the list.

Can you elaborate on this? I just tested a project with multiple data sources and it worked as expected.

> * UX Issue: If a data source has multiple secret keys, and some are already stored, it still asks for all keys again. It should only request the missing keys. What do you think?

I agree that the UX in this case could be improved, but I will fix it in #3229, where I am modifying the dialog to allow display of stored secrets. 

> * UX Issue: When launching a session with multiple data sources, the "continue" or "skip" functionality isn't clear. Will it skip the problematic data source or try to use it anyway? Adding a clarification to the message like "The data source could not be mounted. Please retry with different credentials, or skip." might help.

I do not follow. This is what I see right now:

<img width="845" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/1196411/ce095a94-bfdb-480e-8c51-9d2ab19f6ff1">

Do you think a different message should be shown?

> ✨ It'd be great if the data source view showed which credentials already have a secret value stored and linked to the secret page if accessible. This helps users know where to find and manage them. Makes sense? I see there's already an endpoint to check that 🙂

Agreed! That is what is being done in #3229.

2024-07-05 19:23 UTC, ciyer commented on client/src/features/project/utils/projectCloudStorage.utils.ts
> +  // which should be ok, but isn't; so keep in the sensitive fields.
I think the commented-out code represents how it *should* behave, but the backend to support that way has not yet been implemented, so I do not want to activate that code yet. I can change the comment if you think it would be helpful, but I expect that this will all be resolved before this is merged to main (this PR targets a feature branch).

2024-07-08 20:58 UTC, andre-code commented
Thanks for fixing the issues.

Regarding the cases where not all data sources are being sent, I'm also confused. In this example, the launcher asked for keys of the datasources giab and giab2. It couldn't connect in both cases, but it sent only one of the data sources. Please check the payload; it should send none since it couldn't connect with any of the data sources, and the user selected the skip option in both cases. Or should it send both even if it didn't connect?

Additionally, I think we should extend the message to explain what "skip" means: does it skip the connection attempt and continue trying to mount the data source, or does it not attempt mount the data source at all?

![launch with storage 2](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/50367696-772f-4b8e-95a0-be31066d7992)

2024-07-08 22:34 UTC, ciyer commented
> Thanks for fixing the issues.
> 
> Regarding the cases where not all data sources are being sent, I'm also confused. In this example, the launcher asked for keys of the datasources giab and giab2. It couldn't connect in both cases, but it sent only one of the data sources. Please check the payload; it should send none since it couldn't connect with any of the data sources, and the user selected the skip option in both cases. Or should it send both even if it didn't connect?
> 
> Additionally, I think we should extend the message to explain what "skip" means: does it skip the connection attempt and continue trying to mount the data source, or does it not attempt mount the data source at all?
> 
> I hope it clarifies a bit better ✨

Yes, thanks for the clarification! This has prompted me to think a bit more about how this should work. I have decided that the skip button should skip the test, but still try to mount the cloud storage at startup time. The reason for this is that the logic for the test is not exactly the same as what happens when the session starts, and there are situations where the test fails, but the storage would still mount.

Given that, I have adapted the user feedback.

1. Check the connection, but get a failure
<img width="403" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/1196411/5d8a8c89-bab4-4b48-8894-589497358fbf">

<img width="403" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/1196411/6f7395f3-4a4c-4e0f-a81c-87e31c51186b">


2. Skip the test without checking the connection

<img width="403" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/1196411/3f114058-a65e-4ca9-9b6a-9cf69130fa27">

Given that, all the data sources should be sent to the backend, which should try to mount them at session start.

2024-07-09 21:37 UTC, andre-code approved these changes
🚀

2024-07-10 15:12 UTC, merged