Allow editing of cloud storage secret credentials
SwissDataScienceCenter/renku-ui pull request #3229
Opened 2024-07-03 21:53 UTC by ciyer

2024-07-12 11:32 UTC, leafty commented
Should the user be given a "Save anyway" option?

![Screenshot 2024-07-12 at 13 31 53](https://github.com/user-attachments/assets/73ef51e6-a8b7-4cbd-8ea5-b2bb63360263)

2024-07-12 11:54 UTC, leafty reviewed
some early comments

2024-07-12 11:54 UTC, leafty commented on client/src/features/sessionsV2/SessionStartCloudStorageSecretsModal.tsx
> +              <div>&nbsp;</div>
This existed before this PR, but what?!? This case needs to be removed and no content generated in this case.

2024-07-12 11:54 UTC, leafty commented on client/src/features/sessionsV2/SessionStartCloudStorageSecretsModal.tsx
> +  context = "session",
non-blocking, create a new issue for this: Adding this attribute starts a slippery slope which leads to spaghetti code later on. This component needs to be split into reusable parts so that each case can be defined cleanly as separate components.

Also, this component is now a misnomer, as it is not exclusively used during session start.

2024-07-12 11:54 UTC, leafty commented on client/src/features/sessionsV2/SessionStartCloudStorageSecretsModal.tsx
> +            <ChevronRight className="bi" />
```suggestion
            {context === "session" ? "Continue" : "Test and Save"}
            <ChevronRight className={cx("bi", "ms-1")} />
```

2024-07-12 11:54 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/DataSources/useDataSourceConfiguration.hook.ts
> +interface StartSessionFromLauncherProps {
Misnamed arguments.

```suggestion
interface UseDataSourceConfigurationArgs {
```

2024-07-12 11:54 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourceDisplay.tsx
> +            <Lock /> Update Credentials
```suggestion
            <Lock className={cx("bi", "ms-1")} />
            Update Credentials
```

2024-07-12 11:54 UTC, leafty commented on client/src/features/sessionsV2/SessionStartCloudStorageSecretsModal.tsx
> +            mount
typo?

```suggestion
            to mount
```

2024-07-12 17:22 UTC, ciyer commented on client/src/features/sessionsV2/SessionStartCloudStorageSecretsModal.tsx
> +  context = "session",
I've renamed the component and, though it could still be improved, restructured the code to make it easier to follow in situations where different content is shown based on which context the component is used.

2024-07-15 13:07 UTC, leafty commented
> > Should the user be given a "Save anyway" option?
> 
> I thought about this, and I'm not sure it is a good idea. The problem is that there is no feedback given if the storage fails to mount. Because of that, it would be easy to set up a cloud storage where the credentials do not work and not see the fact that the credentials are wrong anymore.

After trying to use credentials, it seems that you can save the credentials anyway during the start session flow. It seems inconsistent to allow saving failing credentials there but not from the data connector edit form.

2024-07-15 13:12 UTC, leafty requested changes
It seems that updating credentials is not possible from the data storage panel:

![Screenshot 2024-07-15 at 15 10 28](https://github.com/user-attachments/assets/a488ba97-c16d-4ca9-8648-0203c30de07c)

2024-07-15 13:14 UTC, leafty reviewed
Code looks OK otherwise.

2024-07-15 16:15 UTC, ciyer commented
> It seems that updating credentials is not possible from the data storage panel:

It is a two step process. You need to clear first, then you can set. This is not ideal and should be improved in follow up work on this issue, but it was ok'd by prod as a shortcut to get this feature to users sooner rather than later.

2024-07-16 09:11 UTC, leafty approved these changes
Can be merged in the feature branch :+1:

2024-08-06 08:43 UTC, merged