feat: reflect Renku 2.0 search in the URL
SwissDataScienceCenter/renku-ui pull request #3245
Opened 2024-07-18 08:57 UTC by leafty

Closes #3157.

The search page in Renku 2.0 has been reworked to make the search query and search options be reflected in the browser's URL.

/deploy

2024-08-05 11:53 UTC, andre-code reviewed
Excellent work, @leafty! 👏 The code functions as intended and is very clear and clean. I have only a few minor suggestions.

2024-08-06 07:18 UTC, leafty commented on client/src/features/searchV2/components/SearchV2DateFilters.tsx
> +            <label className={cx("px-2", "author-label")}>From:</label>
Removed

2024-08-06 10:49 UTC, andre-code submitted a review, later dismissed
🚀 LGTM

2024-08-06 11:28 UTC, lorenzo-cavazzi commented
I'm finishing a review on this, hold on a few minutes :pray: 
Sorry for the delay

2024-08-06 11:50 UTC, lorenzo-cavazzi requested changes
Great work! Just a few comments before merging (see inline).

* Nitpick: when clicking on the filters, the line `<n> results for <filters>` immediately shows the new selection for the filters, but the number is updated later, when the API response arrives (I hope it's visible on the low-quality video). That's not a big deal, but it would be nice to either update them at the same time (it's fine if it's a little delayed) or show a loader instead of the number while waiting for the API response
![Peek 2024-08-06 11-13](https://github.com/user-attachments/assets/c4058a46-376e-4d64-9541-09a32f73210d)
* The application seems to refresh entirely when changing the search parameters (see video where re-drawn components flash). I assume there aren't other ways since we are changing the URL but the WebSocket channel gets re-created every time. I'm wondering if there is any way to address this.
![Peek 2024-08-06 13-44](https://github.com/user-attachments/assets/846ae323-6c46-4800-b330-e0d42afd3cb6)

2024-08-06 13:21 UTC, leafty commented on client/src/features/searchV2/components/SearchV2DateFilters.tsx
> +            <label className="px-2">From:</label>
This is keeping code you originally wrote for date filters -> https://github.com/SwissDataScienceCenter/renku-ui/commit/302737fe6297303aa831d06a2dec31416133126e#diff-2fd2bbc01a81ab8190494a0f096c095ce1c17bf250f42c692f4d6bb099dd149f. 🤷‍♀️

2024-08-06 13:37 UTC, lorenzo-cavazzi commented on client/src/features/searchV2/components/SearchV2DateFilters.tsx
> +            <label className="px-2">From:</label>
Ouch! Do you mind removing the class in both places? I didn't do that when updating the design :sweat:

2024-08-07 13:08 UTC, leafty commented
> * Nitpick: when clicking on the filters, the line `<n> results for <filters>` immediately shows the new selection for the filters, but the number is updated later, when the API response arrives (I hope it's visible on the low-quality video). That's not a big deal, but it would be nice to either update them at the same time (it's fine if it's a little delayed) or show a loader instead of the number while waiting for the API response

Done

> * The application seems to refresh entirely when changing the search parameters (see video where re-drawn components flash). I assume there aren't other ways since we are changing the URL but the WebSocket channel gets re-created every time. I'm wondering if there is any way to address this.

Nothing we can do until we refactor how the app is bootstrapped (`src/index`, `src/App`).

2024-08-07 14:03 UTC, lorenzo-cavazzi approved these changes
Lgtm! :rocket:

2024-08-07 14:40 UTC, merged