feat: add playful 404 and error pages
SwissDataScienceCenter/renku-ui pull request #3248
Opened 2024-07-19 12:07 UTC by andre-code

Playful 404 and error pages

fix #3235 

/deploy

2024-07-29 13:24 UTC, lorenzo-cavazzi reviewed
This looks nice!
A couple of comments before digging deep into the code:

* Some content is flashing on the top left when opening a link like the following (see gif)
https://renku-ci-ui-3248.dev.renku.ch/projects/fakename
![Peek 2024-07-29 14-55](https://github.com/user-attachments/assets/fb4b9a57-62da-452d-b1c4-91a74b65d91f)

* The Error page is blank, except for the footer. I would suggest removing it so that we minimize the probably of crashing the error page itself.
The content is also centered vertically, while it's not for the other error pages; I suggest keeping it consistent, adding only some margin on top
![image](https://github.com/user-attachments/assets/73db8746-3992-4801-8a42-daf8771e0ec5)

* The custom CSS classes should be limited to the bare minimum and avoided wherever unnecessary. E.G. We can use the bootstrap `w-100` instead of `width: 100%;`

2024-07-29 13:25 UTC, lorenzo-cavazzi commented
P.S. Sorry I missed that this PR was still a draft :facepalm: 
I hope the comments help anyway

2024-07-30 14:42 UTC, andre-code commented
Thanks, @lorenzo-cavazzi, for your helpful suggestions.

Regarding the flashing information, I'm unsure how to address it. The info is the loading message indicating what is being searched for, but since, in the best case, this query is resolved quickly, it shows our 'not found' page in seconds. There isn't enough time to read the loading message. 

So, I am not sure whether to delay the query response or leave it as it is. Do you have a suggestion for this case?
I've already included your other suggestions in the latest commit.

2024-08-13 12:25 UTC, lorenzo-cavazzi requested changes
Great to see these components being standardized! :raised_hands: 

I noticed a few sub-optimal solutions (see inline comments -- and please feel free to justify your changes if you feel I missed the reason).
Even tho they mostly do not impact the users, we should try to avoid bad patterns we used in the past (like prop drilling, inconsistent spaces, unnecessary abstraction layers) so that it's easier to maintain the code in the long term :slightly_smiling_face:

2024-08-13 12:25 UTC, lorenzo-cavazzi commented on client/src/features/projectsV2/notFound/ProjectNotFound.tsx
> +          <Col className={cx("p-4", "mt-5")}>
There is an interesting combination of classes here :smile: 

* The custom style interferes with automatic margins forcing the content to a specific width so that on larger screens there is an additional white space on the right.
![image](https://github.com/user-attachments/assets/1f967828-587d-4527-ae0e-aabbc6c6857e)
I suggest dropping that div entirely, together with the fixed width, and let `m-auto` do its job.
What's the reason for the fixed width? If you wish to avoid wrapping, you could use `text-nowrap`.
* There is an additional "row-col" layer that feels unnecessary here. Perhaps that's a leftover after trying a multi-column layout?
* There are multiple classes that are adding space to the top. The final result is a space between the top border and the first component that is a combination of `mt-5` + `p-4` + `mt-3`, ending up with a semi-random number of pixels. I suggest avoiding this pattern because it makes keeping spacing consistent throughout the application much harder.
In this case, you could remove the classes from the children components and let the topmost component handle also the space on top.

2024-08-13 12:25 UTC, lorenzo-cavazzi commented on client/src/features/projectsV2/notFound/ProjectNotFound.tsx
> +          <Col className={cx("p-4", "mt-5")}>
Please double-check the other pages that implement a similar pattern. This is used in several places in this PR

2024-10-11 15:17 UTC, andre-code commented
Thanks @lorenzo-cavazzi for your review! I've applied your suggestions and also included the styles for non-authenticated users in v2 when want to create a project or group.

2024-10-15 07:25 UTC, lorenzo-cavazzi commented
@andre-code looks good now! There is something off with "oops" images used for the error pages. In my case, they don't show up.

![Screenshot_20241015_091835](https://github.com/user-attachments/assets/312d9cdc-5007-45f9-8665-843241c2ceda)

It's probably just something with the `svg` attributes cause I see the image in my file explorer, but when I try to open it with Firefox it doesn't show up and I see the following message:

> `This XML file does not appear to have any style information associated with it.

2024-10-15 07:38 UTC, leafty requested changes

2024-10-15 07:38 UTC, leafty commented on client/src/error-boundary/ErrorBoundary.tsx
> +const ErrorPage = () => {
Use the `function` coding style here.

2024-10-15 07:38 UTC, leafty commented on client/src/error-boundary/ErrorBoundary.tsx
> +    <Sentry.ErrorBoundary onError={onError} fallback={fallbackErrorPage}>
I'm not sure I get why you cannot just use `ErrorPage` here.

2024-10-15 09:52 UTC, leafty approved these changes

2024-10-15 12:21 UTC, lorenzo-cavazzi approved these changes
Lgtm :rocket:

2024-10-15 12:25 UTC, merged