[WIP] feat: fix small issues v2
SwissDataScienceCenter/renku-ui pull request #3258
Opened 2024-07-29 12:40 UTC by andre-code

PR to address small issues in Renku v2

Issues:
- Display Launcher names in session page
- Typo: in the data sources three dots, incorrect plural for 'Remove data sources' 
- Copy Text Inconsistencies: referring to stopping/deleting sessions 
- When I go to Resources in a Renku 2.0 session, I see the cheat sheet for the Renku CLI (this should be removed)

/deploy

2024-08-13 09:31 UTC, lorenzo-cavazzi requested changes
Nice changes!

The code looks overall good, but there are a few details that require adjustments before merging -- see inline comments.

2024-08-13 09:31 UTC, lorenzo-cavazzi commented on client/src/features/sessionsV2/ShowSessionPage.tsx
> +  if (launchersError || !launcher) return <i>Session not accessible</i>;
This can also be improved
![image](https://github.com/user-attachments/assets/76656561-1be9-4eea-a7ec-67319962f31f)

I suggest putting it into a text element (like a `<p>`) styling it to have no bottom margin, white text color, and italics. Optional: add a warning icon at the beginning of the text.

2024-08-13 09:31 UTC, lorenzo-cavazzi commented on client/src/features/sessionsV2/ShowSessionPage.tsx
> +      <ModalBody>
The spacing is a little messed up here: you always add the class `mb-2` to the divs, but sometimes they contain a single `p` child with a bigger bottom margin (equivalent to `mb-3`) making the class useless, while in other cases the margin is applied but other components add additional vertical margins (see `CommandCopy`).

I suggest:
* Remove the margins within the child components. Depending on the case, you might drop the `div` entirely leaving a `p className="mb-0"`, or drop the `mb-2` on the div, or use properties to remove the margins like in `<CommandCopy noMargin ... />`.
* Handle the spacing between the children at the parent component by adding `d-flex, flex-column, gap-3`

2024-08-20 08:53 UTC, andre-code commented
Thank you, @lorenzo-cavazzi, for your review and suggestions. I've applied those changes in the latest commit. They make a lot of sense!

2024-08-21 10:37 UTC, lorenzo-cavazzi requested changes
Looks nice! Just a tiny detail before merging

2024-08-21 10:37 UTC, lorenzo-cavazzi commented on client/src/features/sessionsV2/ShowSessionPage.tsx
> +            )}
No need to add additional space on the bottom since the spacing is already handled by the parent component with `gap-3`

```suggestion
            className={cx(
              "d-block",
              "d-lg-flex",
              "gap-2",
              "align-items-center"
            )}
```

2024-08-23 09:35 UTC, andre-code commented on client/src/features/sessionsV2/ShowSessionPage.tsx
> +            )}
thanks @lorenzo-cavazzi I have removed the unnecessary style

2024-08-23 12:47 UTC, lorenzo-cavazzi approved these changes
:rocket:

2024-08-26 12:10 UTC, merged