design - search page
SwissDataScienceCenter/renku-ui pull request #3261
Opened 2024-07-30 12:53 UTC by lorenzo-cavazzi

Rework the design on the search page

/deploy #notest

2024-08-09 15:13 UTC, lorenzo-cavazzi commented
Reminder to self: this is still missing the entity icons on the search cards

![image](https://github.com/user-attachments/assets/91148ad8-fe00-4000-94e1-36cf821ab190)

2024-08-21 07:02 UTC, ciyer requested changes
There is a problem with the deployment, so I could not try it out in a running environment but played with it in cypress, and I think it looks very good!

I have one minor suggestion for clearer separation of branches in the code, but that is all.

2024-08-21 07:02 UTC, ciyer commented on client/src/features/searchV2/components/SearchV2Results.tsx
>      );
Suggestion:
```
    return query == null ? (
      <p>No results</p>
    ) : (
      <>
        <p>
          No results for <span className="fw-bold">{`"${query}"`}</span>
        </p>
        <p>You can try another search, or change some filters.</p>
      </>
    );
```

2024-08-21 10:42 UTC, lorenzo-cavazzi commented
@ciyer thank you for the review! I re-deployed and it should now be accessible

2024-08-21 11:38 UTC, ciyer approved these changes
👍

2024-08-21 12:05 UTC, merged