design - add navy theme for main navbar and footbar
SwissDataScienceCenter/renku-ui pull request #3262
Opened 2024-07-30 15:30 UTC by lorenzo-cavazzi

Consistent Navy colors for dropdowns on main navbar and footer

/deploy #notest

2024-08-08 08:48 UTC, lorenzo-cavazzi commented
![image](https://github.com/user-attachments/assets/27ab3ca1-b1ae-4617-9e33-781230a13747)

2024-08-09 07:22 UTC, leafty requested changes
Nice :+1:

Some details to change here :point_down:

2024-08-09 07:22 UTC, leafty commented on client/src/styles/renku_navy_theme.scss
> +[data-bs-theme="navy"] {
We can use the `color-mode` mixin from bootstrap here:

```suggestion
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/mixins";

@include color-mode(navy) {
```

2024-08-09 07:22 UTC, leafty commented on client/src/styles/renku_navy_theme.scss
> +  }
* We should only include variables in this file (remove `color` and `background-color`.
* We can use `body-color` and `body-bg` instead (see also classes on navbars).
* Use `$prefix`.

```suggestion
  --#{$prefix}body-color: var(--#{$prefix}white);
  --#{$prefix}body-color-rgb: #{to-rgb($white)};
  --#{$prefix}body-bg: var(--#{$prefix}navy);
  --#{$prefix}body-bg-rgb: #{to-rgb($navy)};

  .navbar {
    --#{$prefix}navbar-color: var(--#{$prefix}gray-400);
    --#{$prefix}navbar-active-color: var(--#{$prefix}white);
    --#{$prefix}navbar-hover-color: var(--#{$prefix}white);
  }

  .dropdown-menu {
    --#{$prefix}dropdown-border-color: var(--#{$prefix}gray-800);
    --#{$prefix}dropdown-divider-bg: var(--#{$prefix}gray-800);

    --#{$prefix}dropdown-bg: var(--#{$prefix}navy);
    --#{$prefix}dropdown-link-color: var(--#{$prefix}gray-400);

    --#{$prefix}dropdown-link-hover-color: var(--#{$prefix}white);
    --#{$prefix}dropdown-link-hover-bg: var(--#{$prefix}gray-800);

    --#{$prefix}dropdown-link-active-color: var(--#{$prefix}white);
    --#{$prefix}dropdown-link-active-bg: var(--#{$prefix}navy);

    --#{$prefix}dropdown-link-disabled-color: var(--#{$prefix}gray-600);
  }
```

2024-08-09 07:22 UTC, leafty commented on client/src/features/rootV2/NavbarV2.tsx
> +      <header className="navbar-expand-lg" data-bs-theme="navy">
To make the `color` and `bg` work:

```suggestion
      <header
        className={cx("navbar-expand-lg", "text-body", "bg-body")}
        data-bs-theme="navy"
      >
```

2024-08-09 07:22 UTC, leafty commented on client/src/landing/NavBar.jsx
> +    <footer data-bs-theme="navy">
```suggestion
     <footer className={cx("text-body", "bg-body")} data-bs-theme="navy">
```

2024-08-09 07:22 UTC, leafty commented on client/src/landing/NavBar.jsx
> +          location.pathname.startsWith("/v2") ? "" : "bg-primary"
```suggestion
          !location.pathname.startsWith("/v2") && "bg-primary"
```

2024-08-09 15:08 UTC, lorenzo-cavazzi commented on client/src/features/rootV2/NavbarV2.tsx
> +      <header className="navbar-expand-lg" data-bs-theme="navy">
Ha, thanks!
I initially tried with the variables for text color and background color but it didn't work because of this. And I went for a quicker shortcut instead... :roll_eyes:

2024-08-09 15:11 UTC, lorenzo-cavazzi commented
@leafty Thank you for taking the time to suggest a better solution than overwriting `color` and `background-color`. Using the corresponding variables looks cleaner :+1:

2024-08-12 08:02 UTC, andre-code reviewed
Very nice change ✨

I noticed that the text color in the footer is not consistent in v1 and v2.

Here the copyright notice is white. 
![Screenshot 2024-08-12 at 09 55 34](https://github.com/user-attachments/assets/90621ee4-4ada-4671-942a-2e5ec23470d3)

It is clearer here that the copyright text color is not correct.
![Screenshot 2024-08-12 at 09 55 49](https://github.com/user-attachments/assets/bd341bc0-f051-4570-9aeb-11fc88f69cc3)

2024-08-13 06:59 UTC, lorenzo-cavazzi commented
@andre-code thank you for spotting that :pray:  Fixed

2024-08-13 12:44 UTC, andre-code approved these changes
🚀 lgtm ✨

2024-08-15 08:51 UTC, leafty approved these changes

2024-08-15 08:53 UTC, merged