feat: dashboard renku 2.0
SwissDataScienceCenter/renku-ui pull request #3289
Opened 2024-08-29 12:57 UTC by andre-code

/deploy renku=search-update-0.5 renku-data-services=main

2024-10-04 08:37 UTC, leafty requested changes
This looks good 👏 

Some comments below.

2024-10-04 08:37 UTC, leafty commented on client/src/features/dashboardV2/Dashboard.module.scss
This file does not seem to be used. If this is the case it can be removed from the PR.

2024-10-04 08:37 UTC, leafty commented on client/src/features/dashboardV2/DashboardV2.tsx
> +            <h6>Do not do any important work in the Renku 2.0 beta preview!</h6>
Use `<p>` with a classname to set the font size and possibly other classnames for `margin-bottom` and `line-height` here. Or you can use the `.h6` classname for the same visual effect. It is not semantically correct to use `hx` tags for content which is not a title. And also, we should avoid gaps and have a correct title hierarchy:

```
h1
  h2
    h3
    h3
  h2
  h2
```

2024-10-04 08:37 UTC, leafty commented on client/src/features/projectsV2/api/projectV2.enhanced-api.ts
> +          direct_member: queryArg["direct_member"],
Unless this breaks:

```suggestion
          direct_member: queryArg.direct_member,
```

2024-10-04 08:37 UTC, leafty commented on client/src/features/projectsV2/show/GroupShortHandDisplay.tsx
> +        <h6 className={cx("m-0", "fw-bold", "text-truncate")}>{group.name}</h6>
Use the proper `hx` here, I doubt it 6 levels deep. Otherwise just use `<div>` or `<p>` with the `.h6` classname.

2024-10-04 08:37 UTC, leafty commented on client/src/features/projectsV2/show/ProjectShortHandDisplay.tsx
> +        </h6>
Same comment about `h6`.

2024-10-07 09:22 UTC, andre-code commented
Thanks @leafty, this ready for your review 🙌

2024-10-07 11:18 UTC, leafty approved these changes
LGTM Great! 🎉

2024-10-07 13:42 UTC, merged