feat: use data-service sessions endpoint
SwissDataScienceCenter/renku-ui pull request #3296
Opened 2024-09-02 15:16 UTC by andre-code

PR to use data-service `/sessions/*` endpoint in Renku V2.

### What's Included
- Launch sessions with a custom or global environment
- Open sessions in the session view
- See the current session state
- Start, resume, hibernate, and shut down a session

### What's Not Included ‼️
- Automatic injection of saved cloud storage secrets
- Displaying an error message when a session has an error

### Pending 
- [ ] Update e2e tests

/deploy renku=feat-jupyter-free-sessions renku-data-services=release-amaltheas-migration amalthea-sessions=main renku-notebooks=master renku-gateway=1.1.0 extra-values=amalthea-sessions.deployCrd=false

2024-10-16 08:59 UTC, leafty reviewed
General note: please use the `function` style for components.

A first batch of comments below:

2024-10-16 08:59 UTC, leafty commented on client/src/components/LogsV2.tsx
> +export const EnvironmentLogsV2 = ({ name }: EnvironmentLogsPropsV2) => {
`function` style -> https://github.com/SwissDataScienceCenter/renku-ui/blob/main/CODING_GUIDELINES.md#r004-include-a-default-export-when-appropriate

2024-10-16 08:59 UTC, leafty commented on client/src/components/LogsV2.tsx
> +  );
Why is this split into another component here? This code can be in the previous component and that saves all the `interface` and `const =` lines of code.

2024-10-16 08:59 UTC, leafty commented on client/src/features/admin/AddSessionEnvironmentButton.tsx
> +          default_url: data.default_url?.trim() ? data.default_url : undefined,
For here and everywhere else: should we instead have this?

```suggestion
          default_url: data.default_url?.trim() || undefined,
```

Otherwise we send `untrimmed` strings to the API.

This can be added to a new issue to do later.

2024-10-16 08:59 UTC, leafty commented on client/src/features/sessionsV2/PauseOrDeleteSessionModal.tsx
> +          session?.status?.will_hibernate_at?.length > 0 && (
No need for a length check on strings:

```suggestion
        {session?.status?.will_hibernate_at && (
```

2024-10-16 08:59 UTC, leafty commented on client/src/features/sessionsV2/PauseOrDeleteSessionModal.tsx
> +              {hibernationThreshold} of inactivity.
This is not an accurate text copy because `session?.status?.will_hibernate_at` refers to this specific session. Also the text refers to `"DELETE"` while the threshold is for `"PAUSE"`.

2024-10-16 08:59 UTC, leafty commented on client/src/features/sessionsV2/PauseOrDeleteSessionModal.tsx
> +    : 0;
To make things correct, it is preferable to use `<TimeCaption>` instead of computing this. `<TimeCaption>` supports passing class names and the `noCaption` attribute to not have the `time-caption` class.

2024-10-16 08:59 UTC, leafty commented on client/src/features/sessionsV2/session.utils.ts
> +      return `https://${url}`;
What if this is not a valid URL?

2024-10-16 08:59 UTC, leafty commented on client/src/features/sessionsV2/SessionShowPage/SessionIframe.tsx
> +export default function SessionIframe({
New issue: re-factor into existing `<SessionJupyter>` component.

2024-10-16 08:59 UTC, leafty commented on client/src/features/sessionsV2/SessionShowPage/ShowSessionPage.tsx
> +    skip: false,
?

2024-10-16 09:57 UTC, ciyer requested changes
Looks very good! I have some small code suggestions and a question about intent, but those are all quite minor. 

We discussed the use of anonymous vs. named functions for the components, and it looks like the project session test is failing, but I'm assuming you are already work on those.

2024-10-16 09:57 UTC, ciyer commented on client/src/features/sessionsV2/components/SessionButton/ActiveSessionButton.tsx
> +      .find((c) => `${c.id}` == resource_class_id);
I think this would be more idiomatic.

```suggestion
      .find((c) => ""+ c.id == resource_class_id);
```

2024-10-16 09:57 UTC, ciyer commented on client/src/features/sessionsV2/components/SessionButton/ActiveSessionButton.tsx
> +                resource_class_id === `${currentSessionClass?.id}`)
Since this logic is used in a couple of places:

```suggestion
resourceClassMatchesCurrent(resource_class_id, currentSessionClass)
```

```
function resourceClassMatchesCurrent(resourceClassId: string | undefined, currentSessionClass: string) {
    return (resourceClassId != null && resourceClassId === ""+currentSessionClass.id)
}
```

2024-10-16 09:57 UTC, ciyer commented on client/src/features/sessionsV2/components/SessionButton/ActiveSessionButton.tsx
> +              resource_class_id === `${currentSessionClass?.id}`)
```suggestion
resourceClassMatchesCurrent(resource_class_id, currentSessionClass)
```

2024-10-16 09:57 UTC, ciyer commented on client/src/features/sessionsV2/sessionsV2.api.ts
> +              ...result.map(({ name }) => ({
Question: `name` is used here, but `id` below. Is that correct?

2024-10-16 10:06 UTC, leafty commented on client/src/features/sessionsV2/components/SessionButton/ActiveSessionButton.tsx
> +      .find((c) => `${c.id}` == resource_class_id);
This is a javascript "hack" and should not be used. It uses type coercion so this makes code look weird (see things like `"1"+1 == 11`, etc. `${c.id}` is a valid way to convert a `number` to a `string`.

2024-10-16 12:37 UTC, leafty commented on client/src/features/sessionsV2/sessionsV2.api.ts
> +              ...result.map(({ name }) => ({
The `name` field is the identifier. Maybe that should be changed in the API?

2024-10-16 13:03 UTC, leafty commented on client/src/features/sessionsV2/components/SessionButton/ActiveSessionButton.tsx
> +                resource_class_id === `${currentSessionClass?.id}`)
why not just?
```
resource_class_id === `${currentSessionClass?.id}
```

This is all that's needed here (`resource_class_id` cannot be null-ish and equal a string).

2024-10-17 08:35 UTC, andre-code commented on client/src/features/sessionsV2/SessionShowPage/SessionIframe.tsx
> +export default function SessionIframe({
https://github.com/SwissDataScienceCenter/renku-ui/issues/3366

2024-10-17 11:50 UTC, andre-code commented on client/src/features/sessionsV2/sessionsV2.api.ts
> +              ...result.map(({ name }) => ({
Yes, the change has been requested. I will implement this in a future PR once the updates are made in the API.

2024-10-18 08:04 UTC, leafty reviewed
Should be good to go after these comments.

2024-10-18 08:04 UTC, leafty commented on client/src/features/admin/UpdateSessionEnvironmentButton.tsx
> +          default_url: data.default_url?.trim() ? data.default_url : "",
It seems this can be done here as well:
```suggestion
          default_url: data.default_url?.trim() || "",
```

2024-10-18 08:04 UTC, leafty commented on client/src/features/dashboardV2/DashboardV2Sessions.tsx
> +import "../../notebooks/Notebooks.css";
Can you keep the CSS imports as the last ones? They semantically different from the other ones, so we should make them stand out. Also keep the associated comment.

2024-10-18 08:50 UTC, leafty commented on client/src/features/dashboardV2/DashboardV2Sessions.tsx
> -// Required for logs formatting
Can you keep this comment here? Otherwise there is no indication that removing the `.css` import would break something.

2024-10-18 09:22 UTC, leafty approved these changes

2024-10-18 14:03 UTC, merged