wip: initial support for data connectors
SwissDataScienceCenter/renku-ui pull request #3315
Opened 2024-09-12 15:09 UTC by ciyer

2024-09-24 09:35 UTC, leafty commented on client/src/features/projectsV2/api/projectV2.enhanced-api.ts
We should not inject into the `projectV2` API. In fact, the PR which updates the API files does split each API cleanly so that each one is handled separately. See: https://github.com/SwissDataScienceCenter/renku-ui/pull/3299.

2024-09-24 11:28 UTC, leafty requested changes
Thanks!

Some first comments here.

2024-09-24 11:28 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourceModal.tsx
It seems that some renaming got reverted here. Names should probably stick to "DataConnector" and the like.

2024-09-24 11:28 UTC, leafty commented on client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx
> +function DataConnectorDeleteModal({
Maybe we can also ask the user to type the slug for deletion? This is what we ask users to do when deleting a project.

2024-09-24 11:28 UTC, leafty commented on client/src/features/dataConnectorsV2/components/DataConnectorModal/DataConnectorModalBody.tsx
> +        <Controller
Why not use the same control as the one used for project creation and edit here?

https://github.com/SwissDataScienceCenter/renku-ui/blob/2945fb9cd21693b3dc52e816ca19a682482412e5/client/src/features/projectsV2/fields/ProjectNamespaceFormField.tsx#L200

2024-09-24 11:28 UTC, leafty commented on client/src/features/dataConnectorsV2/components/DataConnectorModal/index.tsx
> +  }, []); // eslint-disable-line react-hooks/exhaustive-deps
Do not ignore the rules of hooks. Ignoring them produces bugs.

2024-09-24 11:28 UTC, leafty commented on client/src/features/dataConnectorsV2/components/dataConnector.utils.ts
> +export const EMPTY_DATA_CONNECTOR_FLAT: DataConnectorFlat = {
Is there really a need for this? `react-hook-form` can handle nested values afaik.

2024-09-24 11:28 UTC, leafty commented on client/src/features/usersV2/show/UserShow.tsx
> +            <DataConnectorsBox
As a note, it is very difficult for users to access this page (there is no top-level navigation link for it). Which means it is very difficult to create personal data connectors if we do not have a top-level create menu.

2024-09-24 11:28 UTC, leafty commented on client/src/features/usersV2/show/UserShow.tsx
> +// TODO: Add data connectors
```suggestion
```

2024-09-25 08:30 UTC, ciyer commented on client/src/features/ProjectPageV2/ProjectPageContent/DataSources/DataSourceModal.tsx
I reintroduced a DataSourceModal for use on the V2 project pages. This is temporary, until project gets converted to use data connectors, but it is a helpful intermediate step to limit where code changes need to be made.

2024-09-25 08:33 UTC, ciyer commented on client/src/features/dataConnectorsV2/components/dataConnector.utils.ts
> +export const EMPTY_DATA_CONNECTOR_FLAT: DataConnectorFlat = {
This whole structure is there to maximize compatibility with the existing components for CloudStorage. I agree that the code structure would be better if this were implemented in a "data-connector-native" way, but that would require re-writing further existing components.

2024-09-25 08:35 UTC, leafty reviewed
Looks good, should be good to go with issues fixed.

2024-09-25 10:10 UTC, ciyer commented on tests/cypress/e2e/groupV2.spec.ts
> +});
Good catch -- that was accidentally copied. Fixed in 5e0760d2e05e242567d6259fd3d2ed4a51beb665.

2024-09-25 10:10 UTC, ciyer commented on client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx
> +function DataConnectorDeleteModal({
Fixed in 0e58bbb27f44b337c8c3166fe1ee24301b5fdadc.

2024-09-25 10:13 UTC, ciyer commented on client/src/features/dataConnectorsV2/components/DataConnectorModal/index.tsx
> +  }, []); // eslint-disable-line react-hooks/exhaustive-deps
Fixed in e876667a16af6ef150c0499f9a75f949402f845e

2024-09-25 11:09 UTC, leafty commented on client/src/features/dataConnectorsV2/components/DataConnectorModal/index.tsx
> +  }, []); // eslint-disable-line react-hooks/exhaustive-deps
So, this hooks makes the whole form buggy (cannot hit "Test connection"). I wonder why it is needed at all when `reset()` is called when closing the modal with `toggle()`. The whole state in the component is spaghetti code and should use a single source of truth in redux. Note that this does not need to happen in this PR, but the original quality of this code is not up to the standards we should have.

2024-09-25 11:10 UTC, leafty commented on client/src/features/dataConnectorsV2/components/DataConnectorModal/index.tsx
> +  }, []); // eslint-disable-line react-hooks/exhaustive-deps
https://github.com/SwissDataScienceCenter/renku-ui/issues/2945 for reference.

2024-09-26 14:36 UTC, ciyer commented on client/src/features/projectsV2/api/projectV2.enhanced-api.ts
Fixed in 657286918dee44b94072f6f81921c43f783ad0b8

2024-09-30 08:12 UTC, leafty approved these changes

2024-09-30 08:15 UTC, merged