feat: handle connected services in the admin panel
SwissDataScienceCenter/renku-ui pull request #3329
Opened 2024-09-25 15:12 UTC by lorenzo-cavazzi

Handle connected services in the admin panel.

![image](https://github.com/user-attachments/assets/5447ed7f-c551-4e78-88ab-49a2ce4c73f5)

/deploy #notest

2024-09-26 07:58 UTC, leafty reviewed
Some comments about the API.

2024-09-26 07:58 UTC, leafty commented on client/src/features/connectedServices/connectedServices.api.ts
> +            use_pkce: false,
why? this is a genuine setting, even if we (RenkuLab) do not use it. GitLab is compatible with PKCE and the backend works if enabled.

2024-09-26 07:58 UTC, leafty commented on client/src/features/admin/AddConnectedServiceButton.tsx
> +            <Input
Make this a dropdown or a radio select, or any input which only allows the valid values (see api spec).

2024-09-26 07:58 UTC, leafty commented on client/src/features/admin/AddConnectedServiceButton.tsx
> +          rules={{ required: true }}
Client secret is NOT required. GitLab clients can be configured without a secret and PKCE (though for server deployments, the standard is to use a secret).

2024-09-26 07:58 UTC, leafty commented on client/src/features/admin/AddConnectedServiceButton.tsx
> +          rules={{ required: true }}
Scope is NOT required. GitHub does not use OAuth2 scopes, but instead has fine-grained permissions defined on their backend, which means that the scope is `""` for GitHub clients.

See response from renkulab.io:
```json
{
    "id": "github.com",
    "kind": "github",
    "client_id": "",
    "client_secret": "",
    "display_name": "GitHub.com",
    "scope": "",
    "url": "https://github.com",
    "use_pkce": false
}
```

2024-09-27 08:56 UTC, lorenzo-cavazzi commented on client/src/features/admin/AddConnectedServiceButton.tsx
> +            <Input
I wonder if we should use an input with a `datalist` instead. That way, users will still be presented with the supported options but can write any other text. If we add support for anything else, it wouldn't require updating the UI right away.

![Screenshot_20240927_105326](https://github.com/user-attachments/assets/82c62795-5f68-4242-8ac4-112ff873314d)

2024-09-27 09:11 UTC, leafty commented on client/src/features/admin/AddConnectedServiceButton.tsx
> +            <Input
No, this is a bad solution; it just makes errors very likely to happen. Updating the UI should be just re-running code generation on the newer spec, so very low effort.

2024-09-27 09:17 UTC, lorenzo-cavazzi commented on client/src/features/admin/AddConnectedServiceButton.tsx
> +          rules={{ required: true }}
Actually, scope is required from the backend. If I don't add it, I get the following error (see screenshot)

From your explanation, I assume I should allow users to leave this empty and pass `""` to the backend.

![Screenshot_20240927_111420](https://github.com/user-attachments/assets/3a079cff-34ba-4fac-89c9-5bf58a456a38)

2024-09-27 09:23 UTC, leafty commented on client/src/features/admin/AddConnectedServiceButton.tsx
> +          rules={{ required: true }}
Yes, it needs to be empty. `required` on `react-hook-form` wants a non-empty value.

2024-09-27 09:53 UTC, lorenzo-cavazzi commented on client/src/features/admin/AddConnectedServiceButton.tsx
> +            <Input
> it just makes errors very likely to happen

How so? If you type anything unsupported, you immediately get a clear error and need to fix it before you can add a service.

Anyway, I'm not particularly attached to any solution here. I can change it to a dropdown menu later.

2024-09-27 13:14 UTC, lorenzo-cavazzi commented
@leafty Thank you for the early review. I incorporated your suggestions and finished the PR.

P.S. Sorry for rebasing; I changed the target branch to `main` and the history was :face_with_spiral_eyes:

2024-09-30 12:51 UTC, leafty requested changes

2024-10-02 14:24 UTC, lorenzo-cavazzi commented
@leafty Thank you for the review. I applied your suggestions and fixed the problem with the client secret

2024-10-03 07:38 UTC, leafty requested changes
Code looks good, there is one change to do, see below:

2024-10-03 07:38 UTC, leafty commented on client/src/features/admin/UpdateConnectedServiceButton.tsx
> +  }, [result.isSuccess, toggle]);
You should also reset the form here. Otherwise the `client secret` field is still populated when opening the form again.

2024-10-03 08:31 UTC, lorenzo-cavazzi commented on client/src/features/admin/UpdateConnectedServiceButton.tsx
> +  }, [result.isSuccess, toggle]);
That shouldn't be necessary. After adding a new service, this invokes `toggle()` so that the other `useEffect` will trigger and invoke `result.reset()`. I tried a few combinations to test this.

I can still add a reset here to be safe if you think there are cases that I might be missing.

2024-10-03 08:37 UTC, leafty commented on client/src/features/admin/UpdateConnectedServiceButton.tsx
> +  }, [result.isSuccess, toggle]);
Yes, add a form `reset()` in the `useEffect()` just below then 😄 . The `result.reset()` is for RTK Query. You also need to reset the form at the same time when you do a `result.reset()` in almost all cases.

2024-10-03 08:52 UTC, leafty commented on client/src/features/admin/ConnectedServiceFormContent.tsx
> +            <Input
Also, this field could be of type `password` with the button to toggle it to `text` like we have for some other hidden values. You can push that to a new issue if you like.

2024-10-03 09:02 UTC, lorenzo-cavazzi commented on client/src/features/admin/ConnectedServiceFormContent.tsx
> +            <Input
That makes sense; I was undecided whether to use text or password here, but since you also mentioned this I'll switch to `password` -- no need for another PR :slightly_smiling_face:

2024-10-03 09:13 UTC, lorenzo-cavazzi commented on client/src/features/admin/UpdateConnectedServiceButton.tsx
> +  }, [result.isSuccess, toggle]);
Oh sorry, I wrote `result.reset()` but I meant `reset()` from the other `useEffect`. When you open the new modal, the previous `client_secret` isn't there.

Anyway, adding a `reset()` here still makes the code more readable (and it makes sense to reset immediately after the successful action) so I added it in d640d8321630d9db9481f20da603778b80714d85.

2024-10-03 09:13 UTC, lorenzo-cavazzi commented on client/src/features/admin/ConnectedServiceFormContent.tsx
> +            <Input
Done in https://github.com/SwissDataScienceCenter/renku-ui/pull/3329/commits/ae3689871eb92bf0e48f789571c56d3a814f5def

2024-10-03 09:26 UTC, leafty commented
> I noticed that IDs with spaces are accepted, but editing/deleting those services triggers errors. Any idea what could be wrong? P.S: I added a disabled input to show the ID in the "update" modal.

This is a bug with the backend, I will have to fix it.

2024-10-03 09:27 UTC, leafty approved these changes
LGTM Thanks

2024-10-03 09:38 UTC, merged