wip: set/edit secrets for data connectors
SwissDataScienceCenter/renku-ui pull request #3330
Opened 2024-09-27 09:18 UTC by ciyer

/deploy renku-data-services=leafty/feat-namespaced-data-connectors-5

2024-10-01 12:38 UTC, leafty requested changes
Code mostly looks good and it seems to work. Some comments below:

2024-10-01 12:38 UTC, leafty commented on client/src/features/projectsV2/api/data-connectors.enhanced-api.ts
> +        }
Maybe you can use `Promise.all()` or `Promise.allSettled()` to have the requests go in parallel? The current loop does them in sequence.

2024-10-01 12:38 UTC, leafty commented on tests/cypress/e2e/groupV2DataSourceCredentials.spec.ts
> +  //   it("edit a data source with credentials", () => {
What is the intention with the commented out tests?

2024-10-02 08:27 UTC, ciyer commented on tests/cypress/e2e/groupV2DataSourceCredentials.spec.ts
> +  //   it("edit a data source with credentials", () => {
I have cleaned up the test file in 6ce632ea6c73ac77e31375052c8bae442ca79c96.

2024-10-03 07:40 UTC, leafty approved these changes
Nice!

2024-10-03 07:52 UTC, merged