Some minor improvements to data connectors
SwissDataScienceCenter/renku-ui pull request #3368
Opened 2024-10-17 14:09 UTC by ciyer

* minor: cosmetic improvements to data connector view 
![image](https://github.com/user-attachments/assets/61d0a84d-8cf6-4f21-b6ae-083e91133822)

* minor: show the avatar and icon for the data connector owner 
![image](https://github.com/user-attachments/assets/602d26d9-0ce1-4f66-a683-b2eedb6fc346)

2024-10-18 08:48 UTC, leafty commented
Note: @ciyer should we also add the `<PermissionGuard>` component to the various `edit` buttons in this PR as well.

Currently, users without permissions can attempt to edit or delete a data connector but will not succeed:
![Screenshot 2024-10-18 at 10 46 56](https://github.com/user-attachments/assets/861be097-3d56-4993-8060-1c9b61d16f73)
Trying to delete a data connector without the relevant permissions will also fail without any feedback in the UI (I guess no `error` handling).

2024-10-18 08:59 UTC, andre-code commented
In the file /ProjectConnectDataConnectorsModal.tsx, there's a typo error.
The phrase "The the" should be corrected.

`The the info sidebar for a data connector shows the identifier.`

2024-10-25 11:13 UTC, leafty commented
Question about this :point_down: 

<img width="496" alt="image" src="https://github.com/user-attachments/assets/f5eea6e8-3722-4a37-87dd-2c89bf79fd2b">

Are the colors coming from the design team? It looks weird to me that the chip with the `success` color would use black text when the chip with the Renku green would use white text. See also the buttons with Renku green using white text.

2024-10-25 11:33 UTC, leafty requested changes
Some comments below:

2024-10-25 11:33 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx
> +              : "Please provide an identifier (namespace/group) for the data connector"}
What is meant by "(namespace/group)"?

2024-10-25 11:33 UTC, leafty commented on client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx
> +  });
Why load group permissions here? You should load the data connector's permissions for these actions.

2024-10-25 11:33 UTC, leafty commented on client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx
> +            disabled={
From discussions with the product team, we should not show an action if it is not available due to permissions.

2024-10-25 11:33 UTC, leafty commented on client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx
> +                    Deleting data connector
nitpick: do not change the button text (layout shift)

2024-10-25 11:33 UTC, leafty commented on client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx
> +        ) : permissions == null || permissions["delete"] != true ? (
Why do this when the `<PermissionsGuard` component is made for this situation?

2024-10-25 11:33 UTC, leafty commented on client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx
> +                {permissions == null || permissions["write"] != true ? (
Same comment here: use the PermissionsGuard component.

2024-10-25 11:33 UTC, leafty commented on client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx
> +                disabled={
Use `null` here.

2024-10-25 11:33 UTC, leafty commented on client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx
> +                        Unlinking data connector
same nitpick about not doing layout shifts

2024-10-25 11:33 UTC, leafty commented on client/src/features/dataConnectorsV2/components/DataConnectorModal/index.tsx
> +    );
Use the DC permissions hook.

2024-10-25 11:33 UTC, leafty commented on client/src/features/dataConnectorsV2/components/DataConnectorModal/index.tsx
> +      (permissions == null || permissions["write"] != true) ? (
Use `PermissionsGuard` here.

2024-10-25 11:33 UTC, leafty commented on client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx
> +
Why do this and not use the `RtkOrNotebooksError` component to display the error? This would avoid introducing new error handling code.

2024-10-25 13:08 UTC, ciyer commented on client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx
> +              : "Please provide an identifier (namespace/group) for the data connector"}
Fixed in 4adbc68fc588ef33b6ed88ae54ba3a6f65abd298

2024-10-25 13:10 UTC, ciyer commented on client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx
> +  });
Fixed in 19b985be147ad08d900186d411a12af6c089f206

2024-10-25 13:11 UTC, ciyer commented on client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx
> +            disabled={
Fixed in 57c21a76902fabeecc71eca7f3b97092269380f7

2024-10-25 13:11 UTC, ciyer commented on client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx
> +                    Deleting data connector
Fixed in 57c21a76902fabeecc71eca7f3b97092269380f7

2024-10-25 13:12 UTC, ciyer commented on client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx
> +        ) : permissions == null || permissions["delete"] != true ? (
Fixed in 1ad1c96783c89892578354d5e66dff7345cd4432

2024-10-25 13:13 UTC, ciyer commented on client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx
> +                disabled={
Fixed in 57c21a76902fabeecc71eca7f3b97092269380f7

2024-10-25 13:13 UTC, ciyer commented on client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx
> +                        Unlinking data connector
Fixed in 57c21a76902fabeecc71eca7f3b97092269380f7

2024-10-25 13:14 UTC, ciyer commented on client/src/features/dataConnectorsV2/components/DataConnectorModal/index.tsx
> +      (permissions == null || permissions["write"] != true) ? (
Fixed in 535cb64a775a3d0e9a6e4e90dac4712a6dc5e34f

2024-10-25 13:15 UTC, ciyer commented on client/src/features/dataConnectorsV2/components/DataConnectorModal/index.tsx
> +    );
Fixed in 19b985be147ad08d900186d411a12af6c089f206

2024-10-25 13:16 UTC, ciyer commented on client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx
> +
Fixed in 28c711416cb2fea48c45e7733bfd8b34b1b8ddc7

2024-10-28 08:12 UTC, leafty approved these changes
Thanks! 👏

2024-10-28 08:28 UTC, merged