fix: update project and group membership settings
SwissDataScienceCenter/renku-ui pull request #3374
Opened 2024-10-22 08:26 UTC by leafty

On project settings:
* Do not show the member controls when the user does not have sufficient permissions
    ![Screenshot from 2024-10-22 14-57-53](https://github.com/user-attachments/assets/7512c00e-4dbc-4092-842e-8a9c8c01c506)

On group settings:
* Use similar controls for group members as what is used for project members
    ![Screenshot from 2024-10-22 15-01-51](https://github.com/user-attachments/assets/21c83e26-1d6f-4622-80ea-6fbc4f3e287f)

/deploy renku=release-0.59.0

2024-10-22 12:59 UTC, leafty commented
(WIP description)

On project settings:
* Do not show the member controls when the user does not have sufficient permissions
    ![Screenshot from 2024-10-22 14-57-53](https://github.com/user-attachments/assets/7512c00e-4dbc-4092-842e-8a9c8c01c506)

On group settings:
* Use similar controls for members as what is used for project members

2024-10-23 15:22 UTC, lorenzo-cavazzi requested changes
The code looks good overall! Just a couple of visual details to adjust (see inline).

One nitpick detail: when changing the access level, on the group page the Change button is disabled until you pick a different access level. On the project page, it's always enabled (see screenshot). It's just a detail, but perhaps you can update the project page too
![Screenshot_20241023_171902](https://github.com/user-attachments/assets/e430f665-4b2a-4f65-9602-c2f337e0ce7c)

2024-10-23 15:22 UTC, lorenzo-cavazzi commented on client/src/features/groupsV2/fields/EditGroupMemberModal.tsx
> +      <ModalBody className="pb-0">
The bottom padding is removed here and added in the nested div. I'd suggest removing both

```suggestion
      <ModalBody>
```

2024-10-23 15:22 UTC, lorenzo-cavazzi commented on client/src/features/groupsV2/fields/EditGroupMemberModal.tsx
> +            className={cx("align-items-baseline", "d-flex", "flex-row", "mb-3")}
```suggestion
            className={cx("align-items-baseline", "d-flex", "flex-row")}
```

2024-10-23 15:22 UTC, lorenzo-cavazzi commented on client/src/features/groupsV2/fields/AddGroupMemberModal.tsx
Nitpick: can you remove the `mb-3` at line 155? Just to keep the visualization consistent with the Edit modal where you adjusted bottom spacing

2024-10-23 15:22 UTC, lorenzo-cavazzi commented on client/src/features/groupsV2/fields/RemoveGroupMemberModal.tsx
> +          className={cx("align-items-baseline", "d-flex", "flex-row", "mb-3")}
```suggestion
          className={cx("align-items-baseline", "d-flex", "flex-row")}
```

2024-10-23 15:22 UTC, lorenzo-cavazzi commented on client/src/features/groupsV2/fields/RemoveGroupMemberModal.tsx
> +          </Label>
Why a `Label` here? It also adds unnecessary spacing.
I'd suggest using a `<p className="mb-0">` 

```suggestion
          <p className="mb-0">
            Remove <ProjectMemberDisplay member={member} nameInBold={true} />{" "}
            from group?
          </p>
```

2024-10-23 15:22 UTC, lorenzo-cavazzi commented on client/src/features/groupsV2/fields/RemoveGroupMemberModal.tsx
> +        <Button className="btn-outline-rk-green" onClick={toggle}>
```suggestion
        <Button color="outline-primary" onClick={toggle}>
```

2024-10-23 15:22 UTC, lorenzo-cavazzi commented on client/src/features/groupsV2/settings/GroupSettingsMembers.tsx
> +        </ListGroup> */}
Leftover?

```suggestion
```

2024-10-24 08:41 UTC, leafty commented on client/src/features/groupsV2/fields/EditGroupMemberModal.tsx
> +      <ModalBody className="pb-0">
Question about these style adjustments: should these be updated on the `Project` components too? The modals where adapted from the `Project` case.

2024-10-24 08:43 UTC, leafty commented on client/src/features/groupsV2/fields/RemoveGroupMemberModal.tsx
> +          </Label>
This was taken from the `Project` version.

2024-10-24 08:46 UTC, lorenzo-cavazzi commented on client/src/features/groupsV2/fields/EditGroupMemberModal.tsx
> +      <ModalBody className="pb-0">
Keeping them consistent would be great if you don't mind touching that code too.

2024-10-24 08:50 UTC, lorenzo-cavazzi commented
> Question about these style adjustments: should these be updated on the `Project` components too? The modals where adapted from the `Project` case.

It's great if you want to fix those too, to keep them all consistent, although I don't want to force you to inflate the PR with changes on other components.

2024-10-24 15:22 UTC, lorenzo-cavazzi approved these changes
Lgtm :rocket:

2024-10-25 06:43 UTC, merged