feat: add new dashboard layout
SwissDataScienceCenter/renku-ui pull request #3407
Opened 2024-11-22 10:26 UTC by andre-code

PR to add new dashboard layout

/deploy renku=release-0.61.0

2024-12-09 11:01 UTC, leafty commented on client/public/dashboardHeader1080x280.png
Why do we have all of these assets? Can't we use a single SVG file for this?

2024-12-09 12:15 UTC, leafty commented on client/src/features/dashboardV2/DashboardV2.tsx
> +        </p>
Why make every element a link here? This feels confusing to me, as they all go to the same location.

![Screenshot 2024-12-09 at 13 12 35](https://github.com/user-attachments/assets/7ed5695b-5b6d-444f-8918-976988ffed16)

It seems wrong to allow this to happen (green text in the avatar):
![Screenshot 2024-12-09 at 13 13 00](https://github.com/user-attachments/assets/8e0e6079-2d3d-4be4-8d2d-c52746902c29)

I would suggest to keep only one link on the `@username` element and use the `stretch-link` utility to make the whole card clickable. See: https://getbootstrap.com/docs/5.3/helpers/stretched-link/.

2024-12-10 08:18 UTC, andre-code commented on client/src/features/sessionsV2/sessionsV2.api.ts
we can create an issue for this

2024-12-11 07:39 UTC, andre-code commented
Thanks @leafty for the review! I’ve made the changes you suggested and added the slug to the project list on the dashboard.

2024-12-11 09:09 UTC, leafty reviewed
There are some issues which need to be resolved:
1. Footer card consistency (see comments below)
2. Some small SCSS / bootstrap classnames changes (see comments below)
3. Avatars not using proper initials (see here)

You do not need to resolve the issues about the cover image on the Dashboard, but we probably need to have a technical discussion about this.

The avatars are not correct on the Dashboard page:
![Screenshot From 2024-12-11 09-24-12](https://github.com/user-attachments/assets/b3ace798-1831-4ba8-bf75-9b05a9556164)

See the correct versions here:
![Screenshot From 2024-12-11 09-24-20](https://github.com/user-attachments/assets/ecab75ce-69d7-4639-b147-40e7e177588e)
![Screenshot From 2024-12-11 09-24-27](https://github.com/user-attachments/assets/4d8034ac-2152-4bba-be61-a1c81e3e257c)

I have to say that part of the issue is that the Avatar component should be updated and handle rendering initials based on the entity type (user or group) so that mistakes are not common.

2024-12-11 09:09 UTC, leafty commented on client/src/features/dashboardV2/DashboardV2.tsx
> +          srcSet="/dashboardHeader750x200.png"
There is an issue with the perceived luminance of this image:

![Screenshot From 2024-12-11 09-31-56](https://github.com/user-attachments/assets/1830d973-2627-4df4-bfa0-0a1fe5006e8f)

The tree foilage looks much darker with this image compared to the other ones.

(This may be due to a [Moiré effect](https://en.wikipedia.org/wiki/Moir%C3%A9_pattern) because of the dots)

2024-12-11 09:09 UTC, leafty commented on client/src/features/sessionsV2/sessionsV2.api.ts
> +      },
Do you need to override the query?

2024-12-12 08:22 UTC, andre-code commented
Thanks @leafty  for your review, the reason for calculating the avatar based on the slug/username instead of the initials is to ensure consistency across the app.

Right now, we fetch the list of projects and data connector and get the namespace slug, but not the namespace name. This can result in situations where, for example, a group named Potato shows initials "PO" on the dashboard, but a project under the namespace displays initials "SP" instead.

This approach is temporary. Once the projects API includes the namespace name, we can switch to using the initials derived from the name to create the avatar instead of relying on the slug.

2024-12-12 08:28 UTC, leafty commented
> Thanks @leafty for your review, the reason for calculating the avatar based on the slug/username instead of the initials is to ensure consistency across the app.
> 
> Right now, we fetch the list of projects and data connector and get the namespace slug, but not the namespace name. This can result in situations where, for example, a group named Potato shows initials "PO" on the dashboard, but a project under the namespace displays initials "SP" instead.
> 
> This approach is temporary. Once the projects API includes the namespace name, we can switch to using the initials derived from the name to create the avatar instead of relying on the slug.

I will make a PR to have the avatar component fetch the required data if needed. I don't think we need to update the API.

2024-12-12 08:31 UTC, leafty commented
> Thanks @leafty for your review, the reason for calculating the avatar based on the slug/username instead of the initials is to ensure consistency across the app.

Also, this is wrong, since the existing pages use the initials (which is much more appropriate) than the namespace slug.

2024-12-12 09:42 UTC, andre-code commented on client/src/features/sessionsV2/sessionsV2.api.ts
> +      },
Could you provide more details or clarify this comment?

2024-12-12 10:07 UTC, andre-code commented
> > Thanks @leafty for your review, the reason for calculating the avatar based on the slug/username instead of the initials is to ensure consistency across the app.
> 
> Also, this is wrong, since the existing pages use the initials (which is much more appropriate) than the namespace slug.


I understand the confusion. The changes required for the group and user pages are addressed in the other PRs. Here, you’ll see the avatar functioning consistently across all pages. https://renku-ci-ui-3433.dev.renku.ch/

2024-12-12 11:17 UTC, leafty commented on client/src/features/sessionsV2/sessionsV2.api.ts
> +      },
Why do you override the `query`? It should be correctly generated.

2024-12-12 11:18 UTC, leafty commented on client/src/features/sessionsV2/sessionsV2.api.ts
> +      },
Oh I see it is not generated. Well, all the renku 2.0 should be generated.

2024-12-12 12:08 UTC, leafty approved these changes
Should be OK to merge now. Good work.

2024-12-12 13:10 UTC, leafty requested changes
Actually, should be good to go once the footer cards are fixed.

2024-12-13 09:30 UTC, leafty approved these changes

2024-12-13 09:44 UTC, leafty commented on client/src/features/dashboardV2/DashboardV2.module.scss
> +  a:hover svg {
Small detail, but this would be nice:

```suggestion
  a:hover svg, a:focus svg {
```

Reference: https://webaim.org/techniques/hypertext/link_text#hover

2024-12-16 08:50 UTC, leafty commented on client/src/features/dashboardV2/DashboardV2.tsx
> -        {totalSessions > 0 && (
Did you intend to remove this?

2024-12-16 08:50 UTC, leafty approved these changes

2024-12-16 14:32 UTC, merged