feat: configure disk storage for Renku 2.0 sessions
SwissDataScienceCenter/renku-ui pull request #3463
Opened 2024-12-23 09:08 UTC by leafty

Closes #3451.

/deploy #notest renku-data-services=leafty/add-disk-size-session-envs

2025-01-06 14:08 UTC, andre-code requested changes
The session with the custom disk size work as expected, however I noticed a few things that could be improved:

- The disk size option isn’t visible until you change the resource class selector. It would be better if it was always visible when a resource class is selected. It only happens when the form is use for first time.
<img width="777" alt="Screenshot 2025-01-06 at 15 05 06" src="https://github.com/user-attachments/assets/78acf431-fbc2-4cb8-84ba-c9d1742e839b" />


- If the disk size exceeds the available limit, the input shows an error, but the error message isn’t displayed. We should make sure the error message is shown when this happens.
<img width="783" alt="Screenshot 2025-01-06 at 14 50 07" src="https://github.com/user-attachments/assets/d2e7012c-c2e4-453d-a4d2-110037a6b9cd" />


- When trying to delete the current value with the keyboard, the toggle gets triggered instead, so it’s not possible to delete the value. This needs to be fixed so users can delete the value without triggering the toggle.
![change disk](https://github.com/user-attachments/assets/d9b119c5-f630-4325-940a-cd9ac5386cc3)


Also, I’m curious—why add the toggle to show the input instead of just keeping the input always visible? It could make the experience smoother for the user.

2025-01-06 14:35 UTC, leafty commented
> Also, I’m curious—why add the toggle to show the input instead of just keeping the input always visible? It could make the experience smoother for the user.

The question is: how to handle the difference between keeping the value unset (and thus using the default value from the resource class) and setting the value equal to the default for the resource class?

2025-01-07 09:10 UTC, lorenzo-cavazzi commented
After thinking about this, I wonder if we need to distinguish between default and manually set.
Once the session is started, it doesn't matter if the value was manually set or taken from the default. I agree with Andrea that leaving the slider always visible simplifies the UX.

2025-01-07 09:14 UTC, leafty commented
> After thinking about this, I wonder if we need to distinguish between default and manually set.

Yes, because the default value can be changed by an admin, while a value specifically set here will only be changed by the project members.

2025-01-07 09:33 UTC, lorenzo-cavazzi commented
> Yes, because the default value can be changed by an admin, while a value specifically set here will only be changed by the project members.

True, but would that make any difference to users with running sessions? Even if an admin changes the default, the running sessions won't be affected immediately. And we don't want to accidentally resize the disk while patching as well.
It seems safer (and easier) to use the default for the first input and not automatically modify that as long as the session lives

2025-01-07 09:44 UTC, leafty commented
Also, storing the value when not touched by users would prevent admins from "upgrading" the session classes. Right now, if an admin upgrades the default storage to be 4GB instead of 1GB, then all users without a value set would benefit from the upgrade. With your solution, no user would get the automatic upgrade to session storage.

2025-01-07 09:52 UTC, lorenzo-cavazzi commented
I totally agree with this:

> I think it would be good to merge a way to configure disk storage instead of insisting upon a better way to configure storage (you're free to patch it afterwards).

I might have lost some bits here and there; I thought my suggestions implied _less_ work, not more. And I'm afraid of the possible negative consequences of downsizing. Anyway, let's try to merge the changes and, if needed, we can adjust details later

2025-01-07 09:54 UTC, leafty commented
> And I'm afraid of the possible negative consequences of downsizing.

Why? This cannot affect any existing session.

2025-01-13 20:22 UTC, andre-code approved these changes
The code looks great and works as expected. It's intuitive, and the error messages are clear and helpful. Great job!

2025-01-14 08:32 UTC, merged