feat(datasets): new fields to dataset creation
SwissDataScienceCenter/renku-ui pull request #965
Opened 2020-06-21 20:52 UTC by vfried

Closes #790 

Added the title and creators field

![image](https://user-images.githubusercontent.com/42647877/85234959-88c0c580-b411-11ea-90c3-06e2e007fd45.png)

TODO:
- Shall we check if an email is an email with regex? --> The browser already checks this
- We need to fetch the short_name for the edit or make a temporary dataset model until i can get this from the KG since i am not getting this info ATM, do not merge until this is solved!!!

2020-10-13 12:59 UTC, lorenzo-cavazzi requested changes
Wow, this PR makes adding and editing datasets from the UI a smooth experience! Very well done!

I tried to test it thoroughly and I spotted a couple of details to be polished.
* The keywords contain a json object instead of the string value (see screenshot 1).
* The "Dataset files" card occasionally shows `Error fetching dataset files: internal error`, even if the API fetching the files seems to contain the proper values (see screenshot 1).
* I tried to edit an existing dataset (https://virginiatest.dev.renku.ch/projects/lorenzo.cavazzi.tech/test-datasets/datasets/sarscov2_detection_dog/) and I get a blank page with this error `(creator.email is null -- InputValidator.js@31)`
Not sure if only old projects can have authors without an email or if it's still possible (maybe from the cli?) but I would either handle this case or disable the edit button for projects not migrated to the latest version.
* The "Dataset" tab occasionally shows an error when trying to load the dataset page directly in the browser. The error seems to come from the core service (see screenshot 2) but there is no error logged in the core pods (I checked the pod and the 4 containers).
(e.g. https://virginiatest.dev.renku.ch/projects/lorenzo.cavazzi.tech/test-datasets/datasets/sarscov2_detection_dog/).
I believe this should be forwarded to the renku-core team, but since I managed to reproduce it only when loading the page directly and not when navigating to the dataset, I thought maybe some information is missing when invoking the API.

![Screenshot_20201013_142634](https://user-images.githubusercontent.com/43481553/95863473-8984bb00-0d64-11eb-94dd-5ecc601f38c5.png)

![Screenshot_20201013_143530](https://user-images.githubusercontent.com/43481553/95863503-91dcf600-0d64-11eb-9605-0542c39d4a30.png)

2020-10-16 16:57 UTC, vfried commented
Thanks for your review...
- The keywords issue is a problem that comes from the backend (provably something was imported wrongly). This @value that you see actually comes as a string from the core service. 
I see that in general this works well...
Imported dataset:
https://virginiatest.dev.renku.ch/projects/virginiafriedrich/more-dataset-testing/datasets/bip4covid19_impact_metr_17/
Local dataset:
https://virginiatest.dev.renku.ch/projects/virginiafriedrich/what-is-going-on/datasets/test-dataset-creation-all-fields/
(this are just examples) 

- Dataset Files card error ---> i think it's fixed but i couldn't find a reliable way of reproducing the error

- Creator email editing problem fixed ---> this has nothing to do with the migrations, regarding migrations i don't know if we want to not allow migrations, it could happen that two versions that are different don't affect dataset creation/editing and if they do they will get a message from the backend.

- As you said, this is a problem with the core service, i think it doesn't happen so much on the more sable releases but we should make sure that this is not constantly happening.

2020-10-19 13:41 UTC, lorenzo-cavazzi commented
I tried it again and I still get errors.
It's pretty easy to replicate by re-loading this dataset a couple of times in a row https://virginiatest.dev.renku.ch/projects/lorenzo.cavazzi.tech/test-datasets/datasets/sarscov2_detection_dog/

* The most promintent error is this one, apperently coming from the service, specifically from `GET /datasets.list` returning an error with code `32603` (pinging @jsam for some help with the debug). Trying to reload the page linked above a few times in a row within a short timespan should trigger it. I can't find any error in the core pods logs but it's easy to reproduce.
![Screenshot_20201019_151653](https://user-images.githubusercontent.com/43481553/96457078-a36c4500-121f-11eb-8232-8a68aa4fde99.png)

* The other one is the `Error fetching dataset files: internal error`. This seems to be a UI error since the API response seems fine. I initially thought it happens sporadically, but I believe it's more complicated. I can't replicate it when the user is not the project's owner, but it happens _almost_ always when the user is the owner of the project. You can try by visiting the link above (should see the files) and then forking the project. This time, there should be an error (if not, try refreshing the page or going back to the list and again to the dataset details).
The first screen shows the (apparently valid) response from the service. The second shows the difference between the dataset view for project owner (on the right) and a third user (on the left)
![Screenshot_20201019_151620](https://user-images.githubusercontent.com/43481553/96458389-29d55680-1221-11eb-876a-14ace592e1ce.png)

![Screenshot_20201019_152145](https://user-images.githubusercontent.com/43481553/96458405-2fcb3780-1221-11eb-8422-ab1e8d1c435c.png)

2020-10-19 13:42 UTC, lorenzo-cavazzi commented
I forgot to mention that trying to browse the same dataset on dev works well with any user, so both points seem to be a regression
https://dev.renku.ch/projects/lorenzo.cavazzi.tech/test-datasets/datasets/sarscov2_detection_dog/

2020-10-20 16:49 UTC, vfried commented
I just fixed the datset files error, it's in a separate commit, a tiny mistake was causing a recall of the useEffect (this is a one line commit btw).

2020-10-20 16:58 UTC, jsam commented
@lorenzo-cavazzi @vfried Thanks for reporting the problem! However, I'm not sure if the problem is in the service itself. The version @vfried is using in this deployment is exactly the same to the one which is provisioned to the dev environment and things seems to be working fine there. I've manage to reproduce it successfully the first time I tried but since I did not find anything which could be problematic per say. Sadly, the core was provisioned without the `SENTRY_DSN` so any exception which was caught with internal error report, its stacktrace was lost. I asked @vfried to put the same sentry dsn value so if we get this error again it should be visible in the sentry (for now), which might help us troubleshoot this issue. However, change of environment variable triggered re-provisioning of the core containers and now the issue went away completely and I cannot reproduce it anymore. 

Let's try to use the deployment a bit and see if we can reproduce the behavior and catch the little bugger on the sentry.

:rocket:

2020-10-21 12:31 UTC, lorenzo-cavazzi commented
Thank you @jsam for helping with this! And great to hear that it was just a temporary problem :smile:  One minor comment: would it make sense to log the errors also in the pod logs to simplify debugging and be coherent with the other renku components?

2020-10-21 12:45 UTC, lorenzo-cavazzi requested changes
Great improvement for the Dataset UX! Very nice work! :raised_hands: 
I have just a minor change request before merging this PR (see inline comment).

Here are 2 points we could improve in a follow-up issue:
1. I've noticed there are no dataset related tests. It would be great to add unit tests for the functions in `DatasetFunctions.js` and for the rendering of the main components.
2. I think there are still a few cases when there are duplicate calls to the APIs. It would be great to double-check when this is still happening (e.g. when clicking on the "modify" button, the `datasets.files` endpoint is called 3 times. Furthermore, I am not sure if it's necessary to invoke again the `datasets` and `status` endpoints but I may very well be wrong on this)
![Screenshot_20201021_143717](https://user-images.githubusercontent.com/43481553/96720995-ce839f80-13ab-11eb-9826-825f6d32731b.png)

2020-10-21 12:45 UTC, lorenzo-cavazzi commented on src/api-client/dataset.js
> +        let body = edit ?
The 2 objects you are assigning to `body` seem to be the same. Is that correct? Should we remove the ternary operator?

2020-10-21 12:53 UTC, vfried commented on src/api-client/dataset.js
> +        let body = edit ?
Thanks for the review, you are right about the unit tests, I will create issues for that and for the duplicated call... I thought i solved it yesterday but maybe there is something I didn't catch that makes the page load twice/repeat calls.

Regarding the body thing, you are right... it's the same, it wasn't but with the latest changes, it became the same object

2020-10-21 15:07 UTC, lorenzo-cavazzi commented on src/api-client/dataset.js
> +        let body = edit ?
:+1:

2020-10-21 15:07 UTC, lorenzo-cavazzi approved these changes

2020-10-21 15:08 UTC, merged